### PR TITLE
DS-2571 Fix jumping to value in descending browse

### PR DESCRIPTION
**Pull request by aschweer**

### CODE REVIEW

**Comment by aschweer** [comment]
https://jira.duraspace.org/browse/DS-2571

**Comment by seesmith** [comment]
+1 tested in Vagrant-DSpace for XMLUI and JSPUI

**Comment by kshepherd** [comment]
All tests for descending "browse by title" and "browse by issue date" successful in XMLUI and JSPUI
So that covers the item browse..
However, "browse by author" still suffers the problem -- a single "z" author won't appear in the current page after jumping to "z", but appears on the previous page.

If this PR was intended just to fix item browsing and not author browsing (I saw some references to DS-2534 as a different bug in the JIRA comments), then +1. If not, then is it too tricky to fix the author browse issue at the same time?

**Comment by aschweer** [comment]
Thanks @kshepherd -- given that I didn't even remember that I'd made this PR, I'm not sure I'm qualified to comment on how easy it would be to fix the author browse (and presumably subject and other 2-level browse options)... I'll have a quick look, it may just be a matter of adding the same one line in another spot in the same file.

**Comment by hardyoyo** [comment]
My testing results are the same as above: works for title and issue date browse (combined with decending sort) in both JSPUI and XMLUI. Author browse + descending sort is still a bit "funky" however, this fix is still an improvement, and is worth merging now. +1

**Comment by tdonohue** [comment]
+1 Tested and fixes Title/Date browse (with decending sort).

As mentioned by others, Author and Subject Browse (with decending sort) still don't work quite right. But, this PR fixes 2 of the 4 descending jump-to problems.

**Pull request merged**
