### PR TITLE
Duplicate Detection ported from DSpace CRIS 7

### PR DESCRIPTION
**Pull request by kshepherd**
This pull request ports the Duplicate Detection framework from DSpace CRIS 7 into DSpace.

*Attribution: Ported from DSpace-CRIS and extended by The Library Code with support of Technische Universität Berlin*

Angular PR: https://github.com/DSpace/dspace-angular/pull/1732
REST Contract PR: [Link](https://github.com/DSpace/RestContract/pull/198)

**To test**
- Make sure both the dspace-angular and DSpace PRs are applied
- Enable the ‘dedup’ event consumer in dspace.cfg and add the ‘detect-duplicate’ step to a submission process in item-submission.xml
- For best results, configure autosave on the dc.title field and any others you’re planning to test (eg. dc.title, dc.identifier.doi, dc.identifier.isbn or so on). This means that whenever a change is saved to dc.title, the duplicate detection section will update with a new list of potential matches
- Submit an item to a collection with the detect-duplicate step enabled. Enter some text in the title so that it matches an existing item in the archive (current user must have READ rights) and tab out of the field to force a save (see autosave recommendation -- if not using, complete a section eg file upload or licence grant). A potential duplicate should appear at the detect-duplicate section.
- Change the title to something completely different and tab out again. The duplicate should disappear.
- Change the text so that it is off by *one* character (more specifically, off by 1 levenshtein distance) and tab out again. The duplicate should reappear. Eg. Sample vs S_mple.
- Change the text so that it is still similar but off by more than 1 eg. Sample vs Sam__e. The duplicate should disappear again (note: max distance is configurable but default is 1)
- With one more more duplicates showing, register a decision using the buttons provided. Note that these don't do much currently - they allow a decision to be recorded where the submitter acknowledges a duplicate but still wishes to submit, and also allows the submitter or reviewer to get rid of false positives.

Tests can be repeated as a workflow reviewer/editor. Decisions made by submitters are able to be overridden / rejected duplicates can be seen by reviewers. This is configured true by default.

I appreciate this is a large change with a lot of parts, so please contact me in this Github thread or on Slack for any testing assistance needed.

**Notes for PR reviewers**
- There is a new ‘dedup’ table in the database, this should be added by flyway
- There is a new ‘dedup’ Solr core
- The ‘dedup’ consumer is not in the default event consumers by default, so it’ll need to be added for practical testing
- The fuzzy search signature is commented out of the deduplication.xml spring config by default, so uncomment that to test fuzzy matches (the default MD5 signatures for exact metadata matches still work)

**Notes for 4Science devs (regarding changes from CRIS)**
- SearchDeduplication was renamed to DeduplicationPluginService as that seemed more fitting to what it actually does
- tmpMapFilter, tmpFilter, other similar names of maps and lists were renamed to suit their purpose (eg. signatureSearchFilters)
- A lot of unused methods, variables, classes were stripped out during the port to keep code lean and easier to review. If some were partial implementations of future work, we can bring them in with a subsequent PR

As I’ve added an authorization check (configurable, enabled by default) so that the user needs read access to each item in the potential matches list, I manually disabled it for some integration tests and leave it for others, and explicitly test it in a new integration test

I’ve added javadoc and most is pretty straightforward but please correct me if I misunderstood terms such as ‘fake', ‘reader’

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR modifies the REST API, I've linked to the REST Contract page [here](https://github.com/DSpace/RestContract/pull/198)

### CODE REVIEW

**Comment by kshepherd** [comment]
No idea why `workflowDuplicationWithSameDoiButDifferentCommunityTest` is failing in this CI, but works fine on my local environment.

**Comment by kshepherd** [comment]
For some reason, ITs that pass on the exact same code in my local install are failing in Github's CI.

I don't have any untracked configs lying around that I see... 

```mvn -DskipIntegrationTests=false -Denforcer.skip=true -Dcheckstyle.skip=true -Dlicense.skip=true -Dxml.skip=true -Dfailsafe.rerunFailingTestsCount=2 clean install -DfailIfNoTests=false -Dit.test=org.dspace.app.rest.SubmissionDeduplicationRestIT#\*```

```[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.dspace.app.rest.SubmissionDeduplicationRestIT
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 61.941 s - in org.dspace.app.rest.SubmissionDeduplicationRestIT
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
```

**Comment by tdonohue** [comment]
@kshepherd : Good to see you got tests passing now!  Could you make sure to also resolve the LGTM issues (except the warning on MD5, which can be ignored as we aren't using it for encryption)? LGTM is warning that there's [some obvious bugs in the code](https://github.com/DSpace/DSpace/pull/8415#issuecomment-1296378134).

**Comment by kshepherd** [comment]
@tdonohue I've fixed the LGTM errors as best I can see, except for the alert about a weak signature using MD5 digest -- this is using MD5 hash just for duplicate detection in Solr and not for any security purpose. If possible I'd prefer to leave this one as is -- is there a way to suppress the alert? I can look into SHA or some other digest if really necessary

**Comment by mwoodiupui** [comment]
We have ignorable warnings about MD5 all over the code.  It really would be good to find a way to mark them ignorable.  MD5 is quite adequate for checksumming or generating unique identifiers -- as far as I know it is only significantly weak in the face of *deliberate* attempts to create collisions.  https://en.wikipedia.org/wiki/MD5

**Comment by tdonohue** [comment]
@kshepherd : As [I noted above](https://github.com/DSpace/DSpace/pull/8415#issuecomment-1297208504), the MD5 warning can be ignored as we aren't using MD5 for any sort of encryption.  We'll be switching soon from LGTM.com (which retires at the end of the year) to GitHub Code Scanning (see #8548 )... and after that switch we can look at whether there's a way to disable MD5 warnings more easily.

**Comment by benbosman** [comment]
Thanks @kshepherd for this work.

I'm not assigned as a reviewer, but took a quick look at this functionality, and had some questions:
* Is it correct that you have to go through all potential duplicates during the submission, and click on duplicate/not-duplicate for all individually?
* Is there any documentation on how the configuration of the matching system works? It was unclear to me how it works based on the Spring configuration and the JavaDocs
* In DetectDuplicateAddPatchOperation, how do you verify that the decision type is real (not a regular user claiming to be an admin
* I also think that the new `ItemUtils` class has an unused method. If it is planned to be used, it could really use some JavaDocs, as it was also unclear to me what it does

I didn't check everything in detail (e.g. for completeness of JavaDocs, security, bugs, …), but the just the overall concepts

**Comment by kshepherd** [comment]
Hi @benbosman 

>     * Is it correct that you have to go through all potential duplicates during the submission, and click on duplicate/not-duplicate for all individually?

No, no action is required. If the user is annoyed at seeing the list and wants to explicitly mark them as not duplicate or as 'known duplicate' (with a note), they can. But it isn't required.
I can see the potential for improving UX here. As it is, I wanted to take a direct port from DSpace CRIS 7.
 
>     * Is there any documentation on how the configuration of the matching system works? It was unclear to me how it works based on the Spring configuration and the JavaDocs

Good point about docs, the CRIS 5/6 versions are not that relevant and there are no v7 docs yet on the wiki. To give you a basic idea: the 'signatures' are hashes of one or more bits of data that work well for quick and accurate duplicate detection. I'll add something to the wiki shortly.

>     * In DetectDuplicateAddPatchOperation, how do you verify that the decision type is real (not a regular user claiming to be an admin

Good catch, I think that checking and authorizing ADMIN and WORKFLOW decision types at the time of processing the add patch op would be a necessary addition, I'll double check with the original author

>     * I also think that the new `ItemUtils` class has an unused method. If it is planned to be used, it could really use some JavaDocs, as it was also unclear to me what it does

Yes good catch, I removed it. As part of the port, a lot of incomplete code was stripped but this method slipped by.

> I didn't check everything in detail (e.g. for completeness of JavaDocs, security, bugs, …), but the just the overall concepts

Thanks for the feedback!

**Comment by kshepherd** [comment]
@benbosman my draft wiki documentation is at https://wiki.lyrasis.org/pages/viewpage.action?spaceKey=~kshepherd&title=Duplicate+Detection (requires you to be logged in as its on my personal space)
I can add further technical details, too, but does that cover the questions you would have about how the matching and spring config works?

**Comment by pnbecker** [comment]
We are willing to follow this up if it is clear who and when it is being reviewed. We rebased and fixed this PR several times. We would do this one more time if there is a concrete plan how this is being reviewed. We will not rebase again and again until it is clear who and when this will be reviewed.

**Comment by tdonohue** [comment]
Per decision in DSpace Steering (and as announced in last DSpace DevMtg), I'm moving this (and related tickets) to the 8.0 board.  Steering has limited 7.6 to only features which provide "feature parity" with 6.x.  Even though this will move to the 8.0 board, our goal is to move all existing pre-8.0 features forward as soon as 7.6 development is finishing.

**Comment by tdonohue** [comment]
@pnbecker and @kshepherd : If you plan to work on finishing the Duplicate Detection work for 8.0, this would be a good time to get the PRs all updated for review.  Our 8.0 schedule can be found at https://wiki.lyrasis.org/display/DSPACE/DSpace+Release+8.0+Status#DSpaceRelease8.0Status-ReleaseTimeline

As @pnbecker is aware, this Duplicate Detection work was prioritized by DSpace Steering for inclusion in 8.0 because it was unable to get into the 7.x releases.  So, this gives me the ability to flag it as `high priority` if we can get these PRs updated. https://wiki.lyrasis.org/display/DSPACE/DSpace+Release+8.0+Status#DSpaceRelease8.0Status-Prioritiesfor8.0

Please let us know if you feel this can be updated for 8.0.

**Comment by pnbecker** [comment]
We took a new simpler approach. Closkng this in favor for #9265

**Pull request closed without merging**
