### PR TITLE
DS-2614: Ignore custom resource policies for unfinished items

### PR DESCRIPTION
**Pull request by pnbecker**

### CODE REVIEW

**Comment by tdonohue** [comment]
+1. I just ran a quick test, and it looks to work as advertised. I've added more info in a comment on the ticket.

**Comment by kshepherd** [comment]
I'm having a bit of trouble testing this one - maybe I was foolish to checkout the PR and test that case first? It works as advertised, but when switching back to master or any old branch, rebuilding+redeploying, and trying new submissions, etc., I can't seem to reproduce the old bad behaviour using the test Tim described in DS-2614 JIRA comments. Am I doing something wrong?

**Comment by tdonohue** [comment]
@kshepherd - are you sure nothing was "cached"? If you were only testing XMLUI, it's possible you were hitting the Cocoon cache.  As noted in the ticket, I was able to reproduce this behavior on "master" with any in-progress submission.

**Comment by kshepherd** [comment]
@tdonohue yep mea culpa, wasn't caching, it was a more fundamental, err, "user error"
I can confirm that I can view a bitstream with lifted embargo in various "in progress" submissions as unauthenticated user with master, and that this PR fixes the issue (restricted resource 404).
Tested in DSpace-Vagrant with XMLUI and EmbargoUploadStep.

+1, tested successfully

**Comment by tdonohue** [comment]
Has +2 Committer votes/tests. Merging & cherry-picking to dspace-5_x.

**Pull request merged**
