### PR TITLE
DS-3016 upgrade dependencies before 6.0 release (2)

### PR DESCRIPTION
**Pull request by helix84**
https://jira.duraspace.org/browse/DS-3025

Supersedes #1260. Only upgrades dependencies which don't cause build failures.

### CODE REVIEW

**Comment by helix84** [comment]
Passes smoke test - browsing, viewing, searching in XMLUI and JSPUI, couple of endpoints in REST and in OAI.

**Comment by pnbecker** [comment]
+1 by inspection. Travis tells us, that it is building and helix84 tested it. I think it is important to merge before testathon!

**Comment by hardyoyo** [comment]
+1 by inspection

**Comment by helix84** [comment]
Discussed in today's DevMtg.

**Pull request merged**
