### PR TITLE
[DS-4020] fix statistics logging issue in DSpace 5.9

### PR DESCRIPTION
**Pull request by terrywbrady**
https://jira.duraspace.org/browse/DS-4020

See Jira ticket for testing suggestions

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 Obvious fix. See all other usages of `ConfigurationManager.getProperty()` in `SolrLogger` for reference.  They all use two params when loading up `usage-statistics` configs.

**Comment by tdonohue** [comment]
As a sidenote, in case others are interested, this does *not* need porting to 6.x (or master), as the behavior of how configurations are loaded was changed significantly in 6.x (as we know).  So, in 6.x, this is a single param, e.g. https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/statistics/SolrLoggerServiceImpl.java#L166

So, my suspicion is this bug was caused by an accident in backporting to 5.x (i.e. assuming the same config behavior in 5.x as in 6.x)

**Comment by terrywbrady** [comment]
Tested locally in a plain DSpace instance and confirmed the logging of VIEW records.

**Review by tomdesair — APPROVED** [review]
This seems to be a duplicate of https://github.com/DSpace/DSpace/pull/2177 (ticket https://jira.duraspace.org/browse/DS-3986). 

But since both PR's do the same thing, both changes look OK and we can close both tickets.

**Pull request merged**
