### PR TITLE
DS-3281 - Submisisions made through REST API (POST/item method) use workflow

### PR DESCRIPTION
**Pull request by arvoConsultores**
https://jira.duraspace.org/browse/DS-3281

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 Looks correct to me.

As a sidenote, this should also be ported to `dspace-6_x` and `master` branches. Those likely will require a new PR, as the various `*Manager` classes used here are now `*Service` classes

**Review by mwoodiupui — APPROVED** [review]
+1 by inspection.

**Comment by pnbecker** [comment]
@tdonohue mentioned that indexing is triggered by the workflow process. With this in mind I'm +1 by inspection.

**Comment by MW3000** [comment]
I know too little about the codebase to review the code, but I tested the functionality for the earlier pull-request [https://github.com/DSpace/DSpace/pull/1657](https://github.com/DSpace/DSpace/pull/1657) on 5.X and it had the intended effect.

I tried this code on our current 6.X DSpace, where it did not compile. But @tdonohue mentioned already, that 6.X would require another pull request.

**Comment by kshepherd** [comment]
looks good, but I'm aware that it's basically the same implementation as #1657, so @tdonohue, did your note on #1657 about forcing everything through workflow still apply here, or is that not as much of a problem as initially thought?

**Comment by tdonohue** [comment]
@kshepherd : I'm withdrawing my comment on #1657 about forcing everything through workflow. On second thought, I think that's appropriate behavior, as otherwise we are bypassing workflows enforced elsewhere (e.g. in UIs, SWORD, etc).  So, I'm in favor of this implementation, but it would need to also be implemented for `dspace-6_x` branch.

**Pull request merged**
