### PR TITLE
[DS-2777] Fix startup issues with oai, sword & swordv2

### PR DESCRIPTION
**Pull request by KevinVdV**
Ensure that the DSpace configuration manager is started up before the DSpace kernel in the webapps.

### CODE REVIEW

**Comment by tdonohue** [comment]
On my end, this doesn't seem to be a complete fix. While the webapps now seem to "load" (and get past the initial errors), all three throw immediate errors when accessed from a browser.

The two SWORD webapps both refuse to return a "servicedocument" (from `/sword/servicedocument`) throwing this error:
```
org.swordapp.server.SwordError: Unable to recognise URL as a valid service document: http://localhost:8081/swordv2/servicedocument
	at org.dspace.sword2.SwordUrlManager.extractDSpaceObject(SwordUrlManager.java:323)
	at org.dspace.sword2.ServiceDocumentManagerDSpace.getServiceDocument(ServiceDocumentManagerDSpace.java:169)
	at org.dspace.sword2.ServiceDocumentManagerDSpace.getServiceDocument(ServiceDocumentManagerDSpace.java:74)
	at org.swordapp.server.ServiceDocumentAPI.get(ServiceDocumentAPI.java:56)
	at org.swordapp.server.servlets.ServiceDocumentServletDefault.doGet(ServiceDocumentServletDefault.java:32)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        ...
```

The OAI webapp throws a `BeanCreationException` error which seems to lead back to this exception:
```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.dspace.handle.service.HandleService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency.
```

**Comment by tdonohue** [comment]
Argh. The SWORD errors are my own fault, so disregard my earlier complaint. My "dspace.baseUrl" setting had the wrong port configured, and the SWORD webapp was attempting to validate against the wrong port.  After correcting the misconfigured port, SWORDv1 and v2 both work.

Still digging into OAI-PMH issues.

**Comment by tdonohue** [comment]
:+1: to this PR overall, as I think its fixes are necessary.  However, even with this PR applied, the OAI-PMH interface still doesn't function. It seems like OAI is unable to "find/load" most (all?) beans/services in the dspace-api itself. The first API-level dependency it attempts to inject is the HandleService bean, and it throws this exception:
```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.dspace.handle.service.HandleService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency.
```
I played around with this a little today, but it wasn't immediately obvious where the problem is... though I did notice that OAI seems to completely ignore DSpace Services (and essentially creates its own beans/services). An example is in how it creates its own [`DSpaceConfigurationService`](https://github.com/DSpace/DSpace/blob/master/dspace-oai/src/main/java/org/dspace/xoai/services/impl/config/DSpaceConfigurationService.java) which has nothing to do with the DSpaceConfigurationService from dspace-services.

All this said, I suspect this is the first time we've tried to actually *use* DSpace Services within OAI, and it's not quite setup correctly.  I hope to investigate a bit further on Monday, unless someone else figures this out first.

**Comment by KevinVdV** [comment]
It appears that the OAI uses its own way to manage spring beans:
https://github.com/DSpace/DSpace/blob/master/dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java#L327
https://github.com/DSpace/DSpace/blob/master/dspace-oai/src/main/java/org/dspace/xoai/app/BasicConfiguration.java

So this leaves us with 2 options:
1) We remove the custom spring configuration from the OAI & hopefully this isn't to hard.
2) We change the OAI code to use the factories to retrieve the beans (the factories auto use the DSpace kernel)

**Comment by tdonohue** [comment]
Aha, good eye @KevinVdV. That was what I was overlooking on Friday.  I think your first option sounds preferable (as long as it isn't overly difficult, like you said). That'd mean OAI would act similar to all other webapps (which is what we want).

**Comment by tdonohue** [comment]
I'm going to merge this particular PR. It's definitely *part* of the solution (and it fixes the most annoying part -- that these three webapps don't even start up). I'll update the ticket with what is left to be resolved.

**Pull request merged**
