### PR TITLE
Fix dependencies docker image build

### PR DESCRIPTION
**Pull request by ghost**
## Description
Fix docker dependencies image build. The app directory requires to be owned by dspace user.

```
#10 5.843 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.2.0:single (default) on project dspace-parent: Failed to create assembly: Error creating assembly archive testEnvironment: Problem creating output file for zip /app/target, /app/target/dspace-parent-7.2-SNAPSHOT-testEnvironment.zip (No such file or directory) -> [Help 1]
```

## Instructions for Reviewers

List of changes in this PR:
* add `RUN chown -Rv dspace: /app`

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

```
docker build -f Dockerfile.dependencies --no-cache -t dspace-dependencies .
```

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by tdonohue** [comment]
@wwelling : I'm strangely not able to reproduce this Docker image build error.  Here's what I tried running, based on what's in [our README](https://github.com/DSpace/DSpace/tree/main/dspace/src/main/docker#dockerfiledependencies) (and ensuring I'm using `--no-cache` like you are):

`docker build -t dspace/dspace-dependencies:dspace-7_x --no-cache -f Dockerfile.dependencies .`

It builds fine for me *without* your PR.  While I don't think this PR is detrimental (it's obviously a tiny permission change), I'm just having trouble reproducing the original problem.  Could you try this build again on `main` just to see if it's working for you now...maybe something got messed up temporarily on your machine while you were doing other Docker work yesterday?

**Comment by wwelling** [comment]
@tdonohue thanks for testing. I am however still able to reproduce. Not sure what could be the cause.

```
C:\Users\william_welling\Development\DSpace>git log
commit 7fda074543abddb1408935d50cbb4d2c4d5aec0e (HEAD -> main, upstream/main, origin/main, origin/HEAD)
Merge: ae6f795f2 6bedbf09a
Author: Tim Donohue <tim.donohue@lyrasis.org>
Date:   Thu Nov 11 16:16:24 2021 -0600

    Merge pull request #7994 from mwoodiupui/7988

    Ensure that a mapped Item is exported only once.
```

```
C:\Users\william_welling\Development\DSpace>docker -v
Docker version 20.10.10, build b485636
```

```
C:\Users\william_welling\Development\DSpace>docker build -t dspace/dspace-dependencies:dspace-7_x --no-cache -f Dockerfile.dependencies .
[+] Building 23.8s (10/11)
...
#10 13.99 [INFO] DSpace Services Framework :: API and Implementation  SKIPPED
...
#10 13.99 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.2.0:single (default) on project dspace-parent: Failed to create assembly: Error creating assembly archive testEnvironment: Problem creating output file for zip /app/target, /app/target/dspace-parent-7.2-SNAPSHOT-testEnvironment.zip (No such file or directory) -> [Help 1]
```

**Comment by tdonohue** [comment]
@wwelling : Very odd, as I've got the exact same version of Docker, etc. Not sure what could be different here, but it definitely sounds like this bug at least effects some people.

Ok, in that case, I'll test this PR with the assumption that it's fixing a bug that may not be reproducible everywhere.  Overall, as I said, the change seems reasonable & harmless.  So, if it works on my end as well, we can just move this forward.

**Comment by tdonohue** [comment]
@wwelling : We've just fixed the failing ITs on `main` in #8038. So, if you can rebase this on `main`, tests should now succeed.

**Comment by wwelling** [comment]
@tdonohue is a merge with main branch okay? I think a squash and merge will clean up the commit onto main.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @wwelling !  This looks good to me now, and I just tested these changes on my end..and it works same as before.  So, I'll go ahead and get this merged.

**Pull request merged**
