### PR TITLE
DS-1955 embargo reason length

### PR DESCRIPTION
**Pull request by KevinVdV**
https://jira.duraspace.org/browse/DS-1955

### CODE REVIEW

**Comment by KevinVdV** [comment]
Replacement pull request for: https://github.com/DSpace/DSpace/pull/602

**Comment by helix84** [comment]
+1 This looks good as an alternative to limiting the input field length. There may still be browser and server limits to max length of an input field or a POST request, respectively, but it may not be worth worrying about that at application level.

**Comment by KevinVdV** [comment]
@helix84 The same limit of input field length is also affected for the metadata during submission, so I wouldn't worry about it.

**Comment by tdonohue** [comment]
This looks to need rebasing on latest "master" as it's failing all Unit Tests in Travis.  While there are no merge conflicts, it seems like something may be wrong with the Flyway DB migrations? (Either that, or it could be hitting old issues as the branch was created from an old version of master)

**Comment by KevinVdV** [comment]
@tdonohue Rebased on latest master & I fixed the unit test problem.

**Comment by tdonohue** [comment]
+1 looks good to me. Merging for 6.0 as it's at +2.

**Pull request merged**
