### PR TITLE
DS-4034 Remove diacritics when indexing and browsing content 

### PR DESCRIPTION
**Pull request by PabloDeAlbu**
Added StripDiacritics filter to the list of filters at OrderFormatText, in order to remove diacritic characters when indexing content. Also remove accents in DAO query at BrowseEngine in order when quering to Solr.

[DS-4034](https://jira.duraspace.org/browse/DS-4034)

### CODE REVIEW

**Review by kshepherd — APPROVED** [review]
+1 quick win, improves both search and browse, and browse first-letters sorting. i've tested this locally.
thanks @pablobuenaposada !
We should port this to master, as well

**Comment by marsaoua** [comment]
+1 Works fine!

**Comment by kshepherd** [comment]
closing and reopening to force travis rebulid

**Comment by J4bbi** [comment]
There's another PR that I've just merged,  #2276 .

The PRs are similar but have differences.

I've just discovered this one. @kshepherd and @alanorth  , help!

**Comment by J4bbi** [comment]
This is really a duplicate of #2276. Therefore closing.
Thanks for the PR nonetheless @PabloDeAlbu

**Pull request closed without merging**
