### PR TITLE
Return headers for HEAD request

### LINKED ISSUE #9247: Unexpected response headers for bitstream content HTTP HEAD request
**Describe the bug**
A HTTP HEAD request to a bitstreams content does not return expected headers.

**To Reproduce**
1. Make HEAD request to bitstream content endpoint.
2. See if the Content-Type header is provided as to expect what the GET request will return.

**Expected behavior**
The HTTP HEAD request to an item's bitstream content endpoint should provide response headers to inform what the HTTP GET request will return in the body. 

**Related work**
N/A

### PR DESCRIPTION
**Pull request by tamu-sad-iii**
## References
Fixes #9247 

## Description
Remove logical branch from `HTTPHeadersInitializer.initialiseHeaders` that returns `null` and another logical branch in `BitstreamRestController.retrieve` endpoint handler that returns `ResponseEntity` with headers and no response body.

## Instructions for Reviewers
Issue HTTP HEAD request to API bitstream content endpoint and confirm the anticipated response headers inform what the GET request will return in the response body. i.e. `Content-Type` matches bitstream.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
Thanks @wwtamu. I tested this on DSpace 7.6.1 by uploading a PDF to an item's ORIGINAL bundle.

Before the patch I saw the following relevant headers for a HEAD request:

```console
$ curl -I 'localhost:8080/server/api/core/bitstreams/c0fa95ff-87c4-418b-a481-5fb4af71be3a/content'
...
Content-Type: application/json;charset=UTF-8
Content-Length: 760398
Date: Wed, 10 Jan 2024 08:07:45 GMT
```

The `Content-Type` is wrong as you noticed, but the `Content-Length` is correct. After the patch I see:

```console
$ curl -I 'localhost:8080/server/api/core/bitstreams/c0fa95ff-87c4-418b-a481-5fb4af71be3a/content'
...
Content-Type: application/pdf;charset=UTF-8
Content-Length: 0
Date: Wed, 10 Jan 2024 08:13:45 GMT
```

Now the `Content-Type` is correct, but the `Content-Length` is 0. Would it be possible to address that?

**Comment by wwelling** [comment]
@alanorth I'll check it out.

**Comment by wwelling** [comment]
Thanks @alanorth for the review. I have pushed a commit to add the `Content-Length` header for a HTTP HEAD request and an update to an integration test. I am assuming Spring is deriving the `Cntent-Type` from the body added to the `ResponseEntity`. However, the request scoped singleton `HttpServletResponse` may be modified elsewhere. Which this and the `HTTPHeadersInitializer` helper class both modifying headers and response makes me a bit uneasy and certainly difficult to know where the response changes are occurring.

Additionally, I have discovered that the integration tests for the bitstream content endpoint appears to be asserting that the HTTP HEAD and GET requests are being counted the same for Solr statistics. Do you know if the statistics are differentiating between an actual download?

**Comment by wwelling** [comment]
Was reading the specifications regarding HTTP HEAD requests. I like the cache benefits stated [here](https://www.rfc-editor.org/rfc/rfc2616#section-9.4).

A later [standard](https://www.rfc-editor.org/rfc/rfc9110.html#name-head) mentions '...Such a response to GET might contain [Content-Length](https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length) and [Vary](https://www.rfc-editor.org/rfc/rfc9110.html#field.vary) fields, for example, that are not generated within a HEAD response...'.

Haven't been able to distill the latter down to determine if there is any difference.

**Comment by alanorth** [comment]
Haven't tried the updated patch yet, but found your comments interesting. By my reading of the two RFCs I think it's OK to include the `Content-Length` here.

> The server SHOULD send the same header fields in response to a HEAD request as it would have sent if the request method had been GET. However, a server MAY omit header fields for which a value is determined only _while generating the content_.

I think this part is more about dynamic pages or content that is generated upon request. In our case the content already exists and we know the size, so we can send it. I did some HEAD requests for other stuff on some other servers and found the `Content-Length` being sent.

> Additionally, I have discovered that the integration tests for the bitstream content endpoint appears to be asserting that the HTTP HEAD and GET requests are being counted the same for Solr statistics. Do you know if the statistics are differentiating between an actual download?

Yes, in the past I wondered this as well. I just found [my notes from 2019](https://alanorth.github.io/cgspace-notes/2019-04/#2019-04-07) where I confirmed that yes, HEAD requests on bitstreams are counted in Solr statistics (in DSpace 5 at least).

**Comment by alanorth** [comment]
Thanks @wwelling. I've tested the new patch and it works as advertised. The `Content-Length` header in the HEAD response matches the expected size of the file on disk.

This is passing all tests and I'm ready to merge it. It is a welcome fix. The fact that HEAD requests are counted as statistics events is a topic for another discussion (perhaps was intentional?).

**Review by alanorth — APPROVED** [review]

**Pull request merged**
