### PR TITLE
[DS-3458]5x Allow Shard Process to Append to an existing repo

### PR DESCRIPTION
**Pull request by terrywbrady**
https://jira.duraspace.org/browse/DS-3458

This pull request contains the contents of https://github.com/DSpace/DSpace/pull/1623/files.  It is recommended that you install that PR first.

The context for this PR and a suggested test plan is documented here: https://wiki.duraspace.org/display/~terrywbrady/Statistics+Import+Export+Issues

### CODE REVIEW

**Review by kshepherd — APPROVED** [review]
All tests passed.
Detailed notes/results at https://wiki.duraspace.org/pages/viewpage.action?pageId=79794259#Solrstatisticsimport/export/shardissuetesting(PR-1623,PR-1625)-Resultsoverview

**Comment by terrywbrady** [comment]
@mwoodiupui , this is a portion of the DS-3457 fix since part of that issue was not applicable to 5x.

**Comment by terrywbrady** [comment]
Will re-create

**Comment by terrywbrady** [comment]
Replaced by https://github.com/DSpace/DSpace/pull/1643

**Pull request closed without merging**
