### PR TITLE
DS-3422 Remove XMLUI and JSPUI from the official distribution

### PR DESCRIPTION
**Pull request by abollini**
Removed all the references to the JSPUI and XMLUI.
Installation process succesful tested.
Maintenance of the XMLUI and JSPUI should occur in the 6_x branch and merged forward in the master to get in fix to the API, services and other components

### CODE REVIEW

**Comment by hardyoyo** [comment]
Tested in Vagrant-DSpace, this compiles and deploys cleanly (and quickly!), and the REST-API comes up and behaves as expected. +1

**Review by hardyoyo — APPROVED** [review]
Tested in Vagrant-DSpace, this compiles and deploys cleanly (and quickly!), and the REST-API comes up and behaves as expected. +1

**Comment by abollini** [comment]
I have updated the pull request to resolve a conflict that was introduced by some recent commit. I suggest to merge this PR asap. The new rest7 branch is build upon this PR

**Comment by tdonohue** [comment]
I'm completely in favor of this PR. However, I wonder if we should first "export" the current "master" codebase (and history of changes) for XMLUI to a "DSpace/dspace-xmlui" project, and JSPUI to a "DSpace/dspace-jspui" project?

That would follow the model of what we did with LNI...we removed it from the codebase (and stopped supporting it). But, we made it available as a separate GitHub project in case others wanted to maintain it or fork it for future maintenance.  See https://github.com/DSpace/dspace-lni

**Comment by helix84** [comment]
@tdonohue++

**Comment by tdonohue** [comment]
Closing this PR, as it was replaced by an updated version in #1648 (now merged)

**Pull request closed without merging**
