### PR TITLE
DS-2880: additional javadocs docs and renames for clarity

### PR DESCRIPTION
**Pull request by rradillen**
https://jira.duraspace.org/browse/DS-2880
Currently still a work in progress.

### CODE REVIEW

**Comment by tdonohue** [comment]
Thanks @rradillen and @jonas-atmire!  Let us know when this is ready for review and merge. It's looking good so far (at a glance).  For now, I'll flag this for 6.0 and mark as "work in progress"

**Comment by tdonohue** [comment]
@rradillen and @jonas-atmire: This PR now looks to include some code changes?  We'd need to get the description of it updated, if it's now more than just Javadocs.

To be clear, code refactoring is OK, but it'd need to be described in this PR.

**Comment by rradillen** [comment]
I changed some names of classes to more acurately reflect their purpose. I.e. make them more self documenting.

**Comment by tdonohue** [comment]
@rradillen : any updates on this work? We're striving to get 6.0 out the door before OR16, and time is getting short.

Also, as noted in the related DS-2880 ticket comments, as of yet, we cannot seem to get PubMed integration working in the pre-6.0 codebase.

**Comment by jonas-atmire** [comment]
Restructured the packages to have a better overview of functionality and minimise orphan classes.
Updated the documentation accordingly
I've retested this PR rebased on the latest master to verify it still works.
To correctly retrieve the actual records (+fixing errors while retrieving a handlebars file), the latest config update pull request (https://github.com/DSpace/DSpace/pull/1370) is required though. Since this is a small quick win change, I don't think it would be any problem to merge it.

The latest (non-javadoc) documentation can be found here.
https://wiki.duraspace.org/display/DSDOC6x/2016+Framework+for+live+import+from+external+sources

**Comment by rradillen** [comment]
We've finished the changes we wanted to make.
Summary:
- Added javadoc to all packages, methods and classes in org.dspace.importer.external
- Restructured the package tree to be a little more sensible.
- Renamed classes to be more descriptive of their function.
- Updated the README.md and ported those changes to https://wiki.duraspace.org/display/DSDOC6x/2016+Framework+for+live+import+from+external+sources 

Note that #1370 should be merged first and this one should be rebased on the then master. (In reverse rebasing that will be a nightmare).

**Comment by tdonohue** [comment]
Closing this PR in favor of #1462 (which is a merger of all the commits in this PR along with some of them from #1370).

**Pull request closed without merging**
