### PR TITLE
DS-2299 useProxies and X-Forwarded-FOR

### PR DESCRIPTION
**Pull request by rradillen**
Make the useProxies param easier to configure and log a warning if X-Forwarded-For is not detected.
Note that it logs every time this is detected. I though it may be a good idea to turn the annoyance factor up as this is a very common error.

### CODE REVIEW

**Comment by pnbecker** [comment]
@rradillen This PR needs to be rebased.

**Comment by rradillen** [comment]
I managed to recreate the message. What I don't know is how to have the second part: make it easier to configure useProxies. My solution back then was to put it in build.properties and put a variable in dspace.cfg. I reckon this approach isn't valid anymore. @tdonohue please advise.

**Comment by tdonohue** [comment]
@rradillen : I'm not sure you need to do anything to make useProxies easier to configure.  In DSpace 6, it can be easily overridden by simply specifying a new value in `local.cfg`.

Essentially, the new model of configuration is to have the *default* setting in `dspace.cfg` (or one of the `config/modules/*.cfg` files), and then users can easily override the default setting by copying it into their `local.cfg` if necessary.

**Review by tdonohue — APPROVED** [review]
Looks obvious and helpful. @mwoodiupui and I reviewed and approved in backlog hour today. Merging

**Comment by tdonohue** [comment]
Also cherry-picked this PR to the `dspace-6_x` maintenance branch

**Pull request merged**
