### PR TITLE
Update Postgres Docker scripts to build/tag image automatically

### PR DESCRIPTION
**Pull request by tdonohue**
## Description
Our custom PostgreSQL images for DSpace (which install/setup pgcrypto) are the only major images which are NOT built/tagged automatically on every commit.

This PR updates those images to be built alongside all others, to help ensure we are always have the latest Postgres fixes in the latest image.

Changes the tagging logic on [DockerHub](https://hub.docker.com/r/dspace/dspace-postgres-pgcrypto/tags):
* `dspace-postgres-pgcrypto` - Will be tagged `dspace-7_x` (for latest) or `dspace-7.6` (per release) just like other DSpace images.
    * Previously this was just tagged `latest` and that tag was updated on each push.
* `dspace-postgres-pgcrypto-curl` - Will be tagged in the same manner, but with `-loadsql` suffix (e.g. `dspace-7_x-loadsql`, `dspace-7.6-loadsql`, etc).
    * Previously this was always tagged `loadsql` and that tag was updated on each push.

Other major changes:
* **PostgreSQL image has been upgraded from v11 to v13.**  The official PostgreSQL v11 image is no longer being actively maintained (it throw errors when running `apt-get update`). Instructions for how to upgrade your local PostgreSQL data were added to `./dspace/src/main/docker-compose/README.md` (see section titled "Upgrading PostgreSQL in Docker").

## Instructions for Reviewers
* Verify GitHub Action now successfully builds `dspace-postgres-pgcrypto` and `dspace-postgres-pgcrypto-loadsql` using the "Checks" tag on this PR
* Checkout PR
* Build new Postgres image locally: `docker-compose -f docker-compose.yml -f docker-compose-cli.yml build`
* Deploy locally and verify it works: `docker-compose -p d7 up -d`

**TEMPORARILY flagged as a work-in-progress.  Needs further testing & updates to README.**

### CODE REVIEW

**Comment by tdonohue** [comment]
@mark-cooper : Wanted to make you aware of this PR to update the Postgres Docker scripts.  I had forgotten they were *not* auto-updating, which is a major concern for any "production-like" scenario (including the new demo site). So, this PR is making sure the Postgres images are auto-updating like all other images.

I'm still testing & documenting this change (in the README).  But, wanted to bring this to your attention as we'll want to ensure these changes "work" for the new demo site (I don't anticipate any issues, but you might want to give it a quick look).

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Comment by hardyoyo** [comment]
Tested locally, seems to work as advertised:

```
docker-compose -p d7 -f docker-compose-cli.yml run --rm dspace-cli database test

Attempting to connect to database
Connected successfully!

Database Type: postgres
Database URL: jdbc:postgresql://dspacedb:5432/dspace
Database Schema: public
Database Username: dspace
Database Software: PostgreSQL version 13.10 (Debian 13.10-1.pgdg110+1)
Database Driver: PostgreSQL JDBC Driver version 42.4.3
PostgreSQL 'pgcrypto' extension installed/up-to-date? true (version=1.3)
FlywayDB Version: 8.4.4
```

**Review by hardyoyo — APPROVED** [review]
This all looks good, and works in my local test. 👍

**Pull request merged**
