### PR TITLE
[DS-4508] Update JQuery, JQueryUI and other JS dependencies

### PR DESCRIPTION
**Pull request by kshepherd**
JIRA: https://jira.lyrasis.org/browse/DS-4508
Fixes #7842

UI updates for stable and secure versions of jquery, jqueryui, prototype.js

This includes work by @lap82 for JSPUI, originally attached as a patch to the JIRA ticket while it was non-public. The patch comes from DSpace-CRIS updates which have been tested extensively.

I have made minimal updates to XMLUI to bring Mirage 1 and 2 themes up to date, and fixed some bugs introduced with popups in authority choice popups. I have also included the previous 1.8.15 jquery UI CSS in the new CSS so as to give priority to any customisations made in the past.

Other XMLUI themes have not been updated - I will discuss and either push further changes or open a separate PR (or we will choose to leave them) - the idea is to avoid too much restyling. Perhaps an advisory notice to help users update their own themes with the new jquery UI will be sufficient.

### CODE REVIEW

**Comment by nwoodward** [comment]
@lap82 this PR looks really good. Can you update the Bootstrap glyphicon files to match the new version? I see 404 logs in the console because at least one of those files is missing. I also see 404s for jQuery UI Redmond theme images files that are missing, so I think those files should be updated to match the new jQuery UI version.

**Comment by J4bbi** [comment]
Fetched the PR and tested in Mirage2. Everything seemed to work well, not sure how to test this properly as I don't understand fully how bower/grunt are aggregating the js into a final theme.js.

Created a community, collection and submitted an item. Added metadata. No errors in console.

What's a good way to test?

**Comment by kshepherd** [comment]
@J4bbi thanks - the main things i've been focusing on for testing are things like form controls and responsiveness, anywhere where i think a version change *might* impact on some jqueryui css or jquery js handling, keeping an eye out for console errors that didn't appear before, etc. It is looking ok for me too.
Grunt does combine everything in the `js/` folder into a single `theme.js`. There is a comment in the docs about building in dev mode to keep them separate but I don't think I've ever gotten that to work properly for me:
> Use the mirage2_dev maven profile, or run Grunt with the dev task to build the theme in development mode

Note: I do need to amend the authorship on @lap82 's commit but when I do so I won't change anything else, just authorship

**Comment by J4bbi** [comment]
@kshepherd, I just tested again in JSPUI there's  a 404

GET http://localhost:8080/jspui/static/css/fonts/glyphicons-halflings-regular.woff2 net::ERR_ABORTED 404

I tested with Orcid authority control enabled in XMLUI and everything was okay

I think we should merge. I would like to get this one in asap.

It's high time these dependencies be updated. If there are bugs discovered that's an eventuality we will respond to if it occurs.

**Comment by kshepherd** [comment]
@J4bbi thanks, sounds good, if you can add an approving review then merge that'd be great.
(as the PR owner, I can't review and shouldn't really merge my own work)

**Review by J4bbi — APPROVED** [review]

**Pull request merged**
