### PR TITLE
[DS-3202] PMH Responder returns 500 Internal Error if item is in no Community or no Collection

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://jira.duraspace.org/browse/DS-3853
This is running in production and the instance now satisfies the openarchives.org validator.

### CODE REVIEW

**Comment by mwoodiupui** [comment]
Oops!  This was already fixed in master by #1401 and seems to be present in branches dspace-6_x and master (will be DSpace 7).  I'm rewording this PR to attach it to DS-3202 and closing DS-3853.

**Review by tdonohue — APPROVED** [review]
👍 Code looks good to me. This is an obvious, minor refactor to add in `if (null != [obj])` sorts of checks.

**Review by terrywbrady — APPROVED** [review]
+1 Tested

**Comment by kshepherd** [comment]
merging! thanks @mwoodiupui

**Pull request merged**
