### PR TITLE
Rename flyway migration scripts for relation versioning according to our convention

### PR DESCRIPTION
**Pull request by abollini**
## References
* Related to https://github.com/DSpace/DSpace/pull/8265

## Description
The upgrade of the demo instance fails due to out of order sequence of the flyway migration. The scripts added in the noted PR were named incorrectly (7.2 instead than 7.3).

## Instructions for Reviewers
Migrate a DSpace stable DB to the latest main and verify that all the migration steps (flyway) are performed correctly

## Checklist
- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [N/A] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [N/A] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [N/A] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [N/A] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [N/A] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by tdonohue** [comment]
@abollini : This seems reasonable, and seems like the same sort of fix we had to apply in #8354.

However, it looks like you also changed the *date* embedded in the SQL file name?  So, It seems the filename changed from 
`V7.2_2022.02.28__add_last_version_status_column_to_relationship_table.sql` to 
`V7.3_2022.06.20__add_last_version_status_column_to_relationship_table.sql`.

While this is OK, it will likely mean that you are going to hit the same problem when we merge #8266 (as that PR contains SQL scripts with a date of prior to 2022.06.20).  Does that mean @LucaGiamminonni needs to rename the scripts in that PR as well?

We may also want to consider potentially updating the demo backend to run `./dspace database migrate ignored` to avoid this issue in the future.  I'm a bit concerned about us having to always rename SQL files right before merger.

All this said, I do agree that the SQL file in this case should be renamed to start with `V7.3` since it relates to 7.3.  I'm just commenting on the change of date as well -- as modifying the date of every SQL seems like a something we don't want to need to do every time we merge a database change.

**Comment by abollini** [comment]
hi @tdonohue  you are right, it was not required to change the date embedded in the file name... I have changed it just because it was looking odd to me as it was back in February. Feel free to discard this PR and make a new one with only the version renaming

**Comment by abollini** [comment]
we can of course add a ` ./dspace database migrate ignored` step to the automatic deployment procedure of the demo instance but I would prefer not as in this way we can spot errors like these that could have a serious impact on users installing DSpace for the first time (as flyway script running in unexpected order can eventually fails).

You can merge this and the https://github.com/DSpace/DSpace/pull/8266 without further changes as I will be around to restore the demo after the deployment

**Review by tdonohue — APPROVED** [review]
👍 Overall, I approve of this as it makes sense to rename to `V7.3` since this is added in 7.3 (not 7.2).  The date change is unnecessary but it's harmless.

I'll wait to merge this until tomorrow as it will likely crash the demo site.

ONCE MERGED we need to send this warning to all developers:

---
**WARNING: For any developers who previously ran the (renamed) `V7.2_2022.02.28__add_last_version_status_column_to_relationship_table.sql` migration**

This PR may result in your DSpace throwing a "Flyway migration error" as that migration has be renamed to `V7.3_2022.06.20__add_last_version_status_column_to_relationship_table.sql`.

How to fix the migration error (if you encounter it):
1. First run `./dspace database repair`  (This will cause the old migration to be flagged as deleted)
2. Second, in your database, remove the "latest_version_status" column from the "relationship" table, e.g. `ALTER TABLE relationship DROP COLUMN latest_version_status;`  (NOTE: This will delete all existing data in that column, if any)
3. Finally, run the new migration (recreating this column): `./dspace database migrate`

(NOTE: This WILL NOT IMPACT anyone upgrading between 7.2 and 7.3, as this migration was not a part of 7.2.  It will only impact developers who are working on pre-7.3 who have run the `V7.2_2022.02.28__add_last_version_status_column_to_relationship_table.sql` script.)

**Comment by tdonohue** [comment]
Merging with +1 approval.

**Pull request merged**
