### PR TITLE
Bugfix to usage report rest permission evaluator plugin

### PR DESCRIPTION
**Pull request by benbosman**
## Description
The UsageReportRestPermissionEvaluatorPlugin returns true if a null object is used regardless of the type of request.
This has been solved here.

## Instructions for Reviewers
This can be tested using a generic `PreAuthorize` with the first argument in `hasPermission` set to null

Most of the changes are spacing, due to the surrounding `if` block

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by tdonohue** [comment]
@benbosman : Quick question...is there any way to add a test to verify this code change?  It sounds like you've found endpoints where, if you pass in `null` for the object, they return *true* instead of *false*?  If that's the case, maybe we can add a simple IT which just verifies (for one sample endpoint) that a null object now results in a permissions failure.

(At a glance the code changes make some sense...I'm just trying to protect against making similar mistakes in the future by adding a test to prove that a null object is handled as expected.)

**Comment by benbosman** [comment]
We don't have a current use case for this, but a scenario can be in `CommunityRestRepository`:
Replace
```
@PreAuthorize("hasAuthority('ADMIN')")
    protected CommunityRest createAndReturn(Context context) throws AuthorizeException {
```

With
```
@PreAuthorize("hasPermission(null, 'COMMUNITY', 'ADD')")
    protected CommunityRest createAndReturn(Context context) throws AuthorizeException {
```

If you'd want to implement a permission to check this, it would be impossible because the `UsageReportRestPermissionEvaluatorPlugin` claims you're authorized

Writing an IT for that may be possible by creating a test repository for this. It would expand the scope of this quite a bit (instead of just surrounding with an `if`, it would create quite some test code)

**Comment by tdonohue** [comment]
@benbosman : Good point that an automated test might be harder to achieve here. For now, let's see if we can move this forward as-is... I admit, I need to take a closer look at the code changes myself

**Review by tdonohue — APPROVED** [review]
👍 Looks correct. I realized this same sort of `if` logic is in other EvaluatorPlugins, so this makes sense.  Thanks for finding this @benbosman and @YanaDePauw !

**Pull request merged**
