### PR TITLE
Improve IPv6 support

### LINKED ISSUE #3094: Poor support for IPv6
**Describe the bug**
`org.dspace.statistics.util.DnsLookup` explicitly does not handle IPv6 addresses.  This was filling up the log with error messages and throwing `NullPointerException`s when recording access events.

`org.dspace.statistics.util.IPTable` also explicitly does not handle IPv6 addresses.  It was throwing `IPFormatException`s when an IPv6 address was added or checked.

All of this was obscuring the cause of a problem with logging in from a dual-stacked host (which is a separate issue).

**To Reproduce**
1. Ensure that `jwt.login.token.include.ip = true`
2. Log in via IPv6.

**Expected behavior**
IPv6 addresses are accepted without problems.

### PR DESCRIPTION
**Pull request by mwoodiupui**
## References
* Fixes #3094

## Description
Uses IPv6-aware JRE class instead of home-grown IPv4-only class to resolve addresses to names.  Treats IPv6 addresses as valid non-matches, not format errors.

## Instructions for Reviewers

List of changes in this PR:
* Resove IPv6 addresses to names properly, by using InetAddress.
* Avoid logging `NullPointerException`s for logged-out sessions by testing the current-EPerson reference for nullity before asking for its name.
* Work around problem with testing for allowed proxies, by detecting IPv6 addresses and treating them as non-matching instead of throwing an exception.  We should extend IPTable to handle IPv6 addresses as it does IPv4 addresses, but this change solves the immediate problem.

Test by logging on over an IPv6 connection.  This should no longer log NPEs or format errors, and should fail (if at all) further down the code path.  (Login may fail if the authentication token is bound to the client's address with `jwt.login.token.include.ip = true`.  This is a separate issue)

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by abollini — COMMENTED** [review]
thank @mwoodiupui changes look good by code inspection but I would like to have a test in place to demonstrate that IPv6 generate issue with the current codebase that are solved with these changes. Is this something that you can add easily? otherwise I can check if I'm able to help on that in the next weeks

**Comment by tdonohue** [comment]
@mwoodiupui : I agree with @abollini that it might be nice to add in some Tests to verify this is working as expected.  The code also looks good to me overall.

In terms of writing Tests...in my opinion either Unit Tests or ITs are fine here.  Unit Tests could probably sit in the dspace-api alongside this new code.  For ITs though, it might be easier to implement them in dspace-server-webapp, as then you could easily mock requests from different IP addresses (here's one example of [mocking an IP](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthenticationRestControllerIT.java#L574)).  In any case, either Unit Tests or ITs are fine to me here...it'd just be good to have some form of tests to help validate the new code.

**Review by tdonohue — APPROVED** [review]
👍 The code here looks good to me.  I don't have an easy way to test this out, but it's passing all current tests & the new `IPTableTest` class looks good.  Thanks @mwoodiupui !

**Review by abollini — APPROVED** [review]
hi @mwoodiupui thanks for the additional test, it looks ready to merge to me.

**Pull request merged**
