### PR TITLE
Add indexes to expedite migration

### PR DESCRIPTION
**Pull request by terrywbrady**
This change allowed my migration to complete.

https://jira.duraspace.org/browse/DS-2798

### CODE REVIEW

**Comment by mwoodiupui** [comment]
+1 by inspection.

**Comment by terrywbrady** [comment]
Update the PR per the Jira conversation about other legacy id columns.

**Comment by terrywbrady** [comment]
I am attempting to re-run this on my test server through the migration process.  That process runs the full script as a single transaction.  I am seeing some warnings in the postgres log file.  I will update this PR with what I learn.

**Comment by helix84** [comment]
Ran it on a small DB upgrade, looks good:

DB1 without indexes:
2015-10-14 18:29:06,060 INFO  org.flywaydb.core.internal.command.DbMigrate @ Current version of schema "public": 3.0
2015-10-14 18:29:06,060 WARN  org.flywaydb.core.internal.command.DbMigrate @ outOfOrder mode is active. Migration of schema "public" may not be reproducible.
2015-10-14 18:29:06,061 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 4.0 - Upgrade to DSpace 4.x schema
2015-10-14 18:29:06,638 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 5.0.2014.08.08 - DS-1945 Helpdesk Request a Copy
2015-10-14 18:29:06,810 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 5.0.2014.09.25 - DS 1582 Metadata For All Objects drop constraint
2015-10-14 18:29:06,889 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 5.0.2014.09.26 - DS-1582 Metadata For All Objects
2015-10-14 18:29:25,133 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 6.0.2015.03.06 - DS 2701 Dso Uuid Migration
2015-10-14 18:29:25,234 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 6.0.2015.03.07 - DS-2701 Hibernate migration
2015-10-14 18:34:35,190 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 6.0.2015.08.31 - DS 2701 Hibernate Workflow Migration
2015-10-14 18:34:35,241 INFO  org.flywaydb.core.internal.command.DbMigrate @ Successfully applied 7 migrations to schema "public" (execution time 05:29.188s).

DB1 with indexes:
2015-10-14 18:09:19,265 INFO  org.flywaydb.core.internal.command.DbMigrate @ Current version of schema "public": 3.0
2015-10-14 18:09:19,267 WARN  org.flywaydb.core.internal.command.DbMigrate @ outOfOrder mode is active. Migration of schema "public" may not be reproducible.
2015-10-14 18:09:19,269 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 4.0 - Upgrade to DSpace 4.x schema
2015-10-14 18:09:19,710 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 5.0.2014.08.08 - DS-1945 Helpdesk Request a Copy
2015-10-14 18:09:19,801 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 5.0.2014.09.25 - DS 1582 Metadata For All Objects drop constraint
2015-10-14 18:09:19,827 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 5.0.2014.09.26 - DS-1582 Metadata For All Objects
2015-10-14 18:09:38,553 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 6.0.2015.03.06 - DS 2701 Dso Uuid Migration
2015-10-14 18:09:39,731 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 6.0.2015.03.07 - DS-2701 Hibernate migration
2015-10-14 18:11:28,344 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 6.0.2015.08.31 - DS 2701 Hibernate Workflow Migration
2015-10-14 18:11:28,418 INFO  org.flywaydb.core.internal.command.DbMigrate @ Successfully applied 7 migrations to schema "public" (execution time 02:09.164s).

I'm now trying it on a moderately big one. Will also attempt to profile where it takes so long.

**Comment by terrywbrady** [comment]
I was able to complete the migration on a large repo.  (250,000 items).  I noted system performance issues that I encountered in the jira ticket.

**Comment by helix84** [comment]
:+1: Huge improvement. Here are my tests on a larger database (35k items).

DB2 without indexes:
```
2015-10-14 18:42:11,789 INFO  org.flywaydb.core.internal.command.DbValidate @ Validated 18 migrations (execution time 00:00.069s)
2015-10-14 18:42:11,882 INFO  org.flywaydb.core.internal.command.DbMigrate @ Current version of schema "public": 5.0.2014.09.26
2015-10-14 18:42:11,882 WARN  org.flywaydb.core.internal.command.DbMigrate @ outOfOrder mode is active. Migration of schema "public" may not be reproducible.
2015-10-14 18:42:11,883 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 6.0.2015.03.06 - DS 2701 Dso Uuid Migration
2015-10-14 18:42:12,032 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 6.0.2015.03.07 - DS-2701 Hibernate migration
2015-10-15 08:51:27,972 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 6.0.2015.08.31 - DS 2701 Hibernate Workflow Migration
2015-10-15 08:51:29,259 INFO  org.flywaydb.core.internal.command.DbMigrate @ Successfully applied 3 migrations to schema "public" (execution time 849:17.391s).
```

DB2 with indexes:
```
2015-10-15 09:06:10,462 INFO  org.flywaydb.core.internal.command.DbMigrate @ Current version of schema "public": 5.0.2014.09.26
2015-10-15 09:06:10,463 WARN  org.flywaydb.core.internal.command.DbMigrate @ outOfOrder mode is active. Migration of schema "public" may not be reproducible.
2015-10-15 09:06:10,463 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 6.0.2015.03.06 - DS 2701 Dso Uuid Migration
2015-10-15 09:06:10,646 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 6.0.2015.03.07 - DS-2701 Hibernate migration
2015-10-15 09:21:42,022 INFO  org.flywaydb.core.internal.command.DbMigrate @ Migrating schema "public" to version 6.0.2015.08.31 - DS 2701 Hibernate Workflow Migration
2015-10-15 09:21:42,291 INFO  org.flywaydb.core.internal.command.DbMigrate @ Successfully applied 3 migrations to schema "public" (execution time 15:31.841s).
```

I also profiled migration with indexes and these are the slowest queries:
```
5m41s	
UPDATE metadatavalue SET dspace_object_id = ( SELECT item.uuid FROM item WHERE metadatavalue.resource_id = item.item_id AND metadatavalue.resource_type_id = 2 ) WHERE metadatavalue.resource_type_id = 2;
4m33s	
DELETE FROM collection2item WHERE ctid NOT IN ( SELECT max ( ctid ) FROM collection2item GROUP BY collection_id, item_id );
2m17s	
UPDATE metadatavalue SET dspace_object_id = ( SELECT bitstream.uuid FROM bitstream WHERE metadatavalue.resource_id = bitstream.bitstream_id AND metadatavalue.resource_type_id = 0 ) WHERE metadatavalue.resource_type_id = 0;
```

I wasn't able to speed them up further.

**Comment by helix84** [comment]
Actually, I suggest using this one instead. Just please test whether it's really equivalent.

```
DELETE FROM collection2item a USING (
      SELECT MIN(ctid) as ctid, collection_id,item_id
        FROM collection2item 
        GROUP BY collection_id,item_id HAVING COUNT(*) > 1
      ) b
WHERE a.collection_id = b.collection_id
AND a.item_id = b.item_id
AND a.ctid <> b.ctid;
```

**Comment by tdonohue** [comment]
Regarding the "slow" UPDATE queries, I wonder if converting them to UPDATE...FROM syntax would be any faster: http://www.postgresql.org/docs/9.1/static/sql-update.html

For example:
```sql
UPDATE metadatavalue SET dspace_object_id = item.uuid FROM item WHERE  metadatavalue.resource_id = item.item_id AND metadatavalue.resource_type_id = 2;
```

AND

```sql
UPDATE metadatavalue SET dspace_object_id = bitstream.uuid FROM bitstream WHERE metadatavalue.resource_id = bitstream.bitstream_id AND metadatavalue.resource_type_id = 0;
```
Many of the other UPDATE queries in the same SQL migration use this UPDATE..FROM syntax. I'm not sure why these ones do not, so I wonder if converting them would speed things up as well.

**Comment by helix84** [comment]
Note for further investigation - since we're using UUIDv4 (random), it's worth investigating how batch operations (like this migration) may be affected by size of the available entropy pool.

In Linux this can be watched here:
cat /proc/sys/kernel/random/entropy_avail

I wouldn't expect this to affect regular operation, just batch operations.

**Comment by helix84** [comment]
According to @tdonohue's suggestion, I changed all 7 "UPDATE metadatavalue" queries to UPDATE...FROM syntax. Any difference in speed was under measurement error:

DB2 with indexes:
14m46s average of 3 runs, std. dev. 42 (15:31.841s, 14:37.245s, 14:09.591s)

DB2 with indexes, UPDATE...FROM:
14m58s average of 3 runs, std. dev. 108 (12:54.191s, 15:54.742s, 16:06.560s)

So no need to change those.

It does make sense to change the "DELETE FROM collection2item" to what I suggested (orders of magnitude faster).

**Comment by helix84** [comment]
Calling gen_random_uuid() doesn't seem to have noticable effect on linux entropy pool.

```sql
CREATE OR REPLACE FUNCTION my_loop() RETURNS void AS $$
BEGIN
  FOR i IN 1..1000000 LOOP
    PERFORM gen_random_uuid();
  END LOOP;
END;
$$ LANGUAGE plpgsql;

SELECT my_loop();
```

```
while true; do sleep 1; cat /proc/sys/kernel/random/entropy_avail; done
```

**Comment by mwoodiupui** [comment]
Prefix those SQL statements with ANALYZE EXPLAIN to see what the
PostgreSQL query planner thinks of them.

-- 
Mark H. Wood
Lead Technology Analyst

University Library
Indiana University - Purdue University Indianapolis
755 W. Michigan Street
Indianapolis, IN 46202
317-274-0749
www.ulib.iupui.edu

**Comment by helix84** [comment]
@terrywbrady: Please, add [this query](https://github.com/DSpace/DSpace/pull/1101#issuecomment-148340405) to the PR and we can merge unless you have objections:

**Comment by terrywbrady** [comment]
@helix84, I pushed out the change you recommended (untested).  I see 12 additional queries using the same SQL format.  I will do another commit to make those match the format.

**Comment by helix84** [comment]
@terrywbrady No, that was not the change that matters. These don't have any impact on performance, the one with "HAVING COUNT(*) > 1" does.

**Comment by helix84** [comment]
I'd revert the last two commits (git reset --hard HEAD~2 and force-push to GitHub). I haven't tested the correctness of this change to UPDATE (although it most likely works), just tested its performance.

**Comment by terrywbrady** [comment]
@helix84 , sorry for the confusion on that.  I believe that I have reset as you recommended.

**Comment by helix84** [comment]
Perfect. Merging.

**Comment by helix84** [comment]
Actually one more tiny change, please don't delete the comment above the query in the last commit. Thanks.

**Pull request merged**
