### PR TITLE
DS-3427: Update DataCite crosswalk to version 4.0

### LINKED ISSUE #6781: [DS-3427] DIM2DataCite crosswalk update to version 4.0
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3427">[DS-3427]</a> created by cjuergen</i>
<p>In September 2016 the <a href="http://doi.org/10.5438/0012" class="external-link" target="_blank" rel="nofollow noopener">DataCite Schema 4.0</a> has been published.<br/>
The major changes are:</p>
<ul>
	<li>Changing resourceTypeGeneral from optional to mandatory</li>
	<li>Addition of a new property: FundingReference, with subproperties funderName, funderIdentifier, awardNumber, awardURI and awardTitle. Deprecation of contributorType “funder”</li>
	<li>Addition of new optional subproperties for creatorName and contributorName: familyName and givenName</li>
	<li>Addition of a new relatedIdentifierType option “IGSN”</li>
	<li>Addition of a new subproperty for GeoLocation “geoLocationPolygon”, and changing the definition of the existing GeoLocation subproperties (geoLocationPoint and geoLocationBox)</li>
</ul>

<p>DSpace 5.x uses the version 2.2.<br/>
DSpace 6.0 uses the version 3.1</p>

<p>The schema should be updated with the next release.</p>

### PR DESCRIPTION
**Pull request by PhilipVis**
Updated the DataCite crosswalk to be compliant with DataCite Schema 4.0.

- updated version numbers
- resourceTypeGeneral is now always included
- added property FundingReference which will contain the value of DSpace metadata field dc.description.sponsorship

Jira ticket: https://jira.duraspace.org/browse/DS-3427
Fixes #6781

### CODE REVIEW

**Review by kshepherd — APPROVED** [review]
+1 quick win, tested successfully just now, registering new DOIs for items using my test Datacite account. thanks @PhilipVis !

**Comment by nwoodward** [comment]
This would be a great thing to add to 6.4 since the current crosswalk is really old. Have you made any updates since opening this PR for the 4.x minor releases?

**Comment by kshepherd** [comment]
closing and reopening to force new Travis CI build

**Comment by lap82** [comment]
@PhilipVis thank you for the update of Datacite Crosswalk. Please can you change also the default value for https://github.com/DSpace/DSpace/blob/594d6978504a7d6fe2f0730173af2a63359d8a8a/dspace-api/src/main/java/org/dspace/identifier/doi/DataCiteConnector.java#L947 
It's a minor changes. Maybe you could remove this default configuration from the code at all and use simply the configurationService.getProperty(CFG_NAMESPACE) without default.

**Comment by J4bbi** [comment]
Thanks for the PR @PhilipVis

This is great. Like @nwoodward I am just wondering if we should review the opportunity to look at the minor releases, there's currently 4.3.

See: https://schema.datacite.org/

**Comment by tdonohue** [comment]
@PhilipVis : Any chance you could do minor cleanup here in preparation for 6.4?  It looks like one change was requested in this comment: https://github.com/DSpace/DSpace/pull/2321#issuecomment-621685347

This also should get a port for `main` so that we can apply this to 7.x

**Pull request closed without merging**
