### PR TITLE
dspace: capture publisher from CrossRef live import

### PR DESCRIPTION
**Pull request by alanorth**
## Description
Publisher is a [required field on CrossRef](https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md) so we can always rely on capturing this information when doing a live import.

* Requires: https://github.com/DSpace/dspace-angular/pull/2272

## Instructions for Reviewers
This pull request adds publisher to the list of metadata harvested from CrossRef. To test this pull request you should try starting a new submission using CrossRef as the live import source and seeing that publisher is added to the list of metadata captured.

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@alanorth : Just an FYI... this PR appears to have a very minor IT failure.  Looks like there's a metadata field counter in an IT and you need to increment it by one.

**Comment by alanorth** [comment]
@tdonohue ah yeah. Just fixed the checkstyle issue, let me look into the integration test failure.

**Comment by alanorth** [comment]
@francescopioscognamiglio since you are working on other issues in the live import subsystem, you could review this. Thanks. (There is a new UI string required in the frontend but it is only cosmetic).

**Comment by francescopioscognamiglio** [comment]
@alanorth yes, of course. I can review this work. You can mark me as reviewer, thank you.

**Comment by alanorth** [comment]
@francescopioscognamiglio It seems I can only mark you as a reviewer if you're a member of the DSpace group. No matter, you can test it and leave feedback here. That's also useful.

**Comment by francescopioscognamiglio** [comment]
@alanorth check again, as I am now a member of the DSpace 7 Dev group. Please let me know, thanks!

**Comment by alanorth** [comment]
Hi @francescopioscognamiglio, you can test the code and comment here without being a "reviewer". ;)

But yes, I see your name in the reviewer field now.

**Review by francescopioscognamiglio — APPROVED** [review]
Hi @alanorth, I reviewed your work and it seems good to me.
I tested a CrossRef import of this resource https://api.crossref.org/works/10.1629/22161 using the DOI `10.1629/22161` and it now populates the dc.publisher metadata.
I attached a video demonstrating this:
[screencast-localhost_4000-2023.06.05-12_08_58.webm](https://github.com/DSpace/DSpace/assets/36161521/d702ca0f-d5c9-4112-90bb-b515a1ff929f)

PS: Since I cannot merge it directly, I am waiting for someone to do so :laughing:

**Comment by alanorth** [comment]
Thanks for the thorough feedback, @francescopioscognamiglio. The video is very helpful to verify it is working.

I have just rebased my branch on top of DSpace main, and will merge it myself once the tests finish running (just in case). Cheers!

**Pull request merged**
