### PR TITLE
DS-4473: Configurable whitelist for Access-Control-Allow-Origin, add support for Access-Control-Allow-Credentials

### PR DESCRIPTION
**Pull request by tdonohue**
## References
* https://jira.lyrasis.org/browse/DS-4473
* Loosely related to https://github.com/DSpace/dspace-angular/issues/641 (withCredentials issues in Angular UI)
* May also be related to https://github.com/DSpace/dspace-angular/issues/289 (Needs testing to verify if the problem is fixed by this PR)

## Description
1. This is a small improvement to our `ApplicationConfig` to ensure the existing `rest.cors.allowed-origins` both (1) works properly for Apache Commons Config (which treats comma-separated values as an array, and (2) defaults to the value of `dspace.ui.url` if unspecified.
2. It updates `rest.cfg` to set `rest.cors.allowed-origins=${dspace.ui.url}` by default.
3. Adds a new `rest.cors.allow-credentials` setting to `rest.cfg` and sets to `true` by default. This adds support for the `Access-Control-Allow-Credentials` CORS Header.

## Instructions for Reviewers
* This should be tested with the Edit Item Bitstreams UI to see if it solves the CORS error noted here: https://github.com/DSpace/dspace-angular/pull/577#issuecomment-607685503
* This should ideally be tested with Shibboleth to see if the `rest.cors.allowed-origins` configuration can replace the special Apache configuration instructions listed here: https://wiki.lyrasis.org/display/DSPACE/DSpace+7+Shibboleth+Configuration#DSpace7ShibbolethConfiguration-SeparateRESTandAngularhostname

### CODE REVIEW

**Comment by benbosman** [comment]
@tdonohue I've read through your code changes, and when comparing it with https://wiki.lyrasis.org/display/DSPACE/DSpace+7+Shibboleth+Configuration#DSpace7ShibbolethConfiguration-SeparateRESTandAngularhostname I noticed there are rules in here that are not present in https://github.com/DSpace/DSpace/blob/master/dspace-server-webapp/src/main/java/org/dspace/app/rest/Application.java#L132
If all the documented rules are required (I never tested using less of the rules), The Application.java would need to be extended as well.

It would also be useful to make this set of rules more configurable. The headers seem to be important for e.g. Shibboleth, but also for other features. It's perhaps something to make configurable as well.

I will also try to get my Shibboleth test installation operational again to test the setup without the Apache changes

**Comment by benbosman** [comment]
@tdonohue I've been able to get my Shibboleth test box working again

This solution is indeed not sufficient yet to get Shibboleth working

You can see the difference using e.g.
```
curl -D - 'https://dspace7-test.atmire.com/server/api/authn/status' -H 'Accept: application/json' -H 'Content-Type: application/json; charset=utf-8'   -H 'Origin: http://localhost:3000'
```

It results in:
```
Access to XMLHttpRequest at 'https://dspace7-test.atmire.com/server/api/authn/status' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

The edit bitstream seems to work correctly though, but it doesn't need those additional headers

**Comment by benbosman** [comment]
@tdonohue I've been able to get my Shibboleth test box working again

This solution is indeed not sufficient yet to get Shibboleth working

You can see the difference using e.g.
```
curl -D - 'https://dspace7-test.atmire.com/server/api/authn/status' -H 'Accept: application/json' -H 'Content-Type: application/json; charset=utf-8'   -H 'Origin: http://localhost:3000'
```

It results in:
```
Access to XMLHttpRequest at 'https://dspace7-test.atmire.com/server/api/authn/status' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

The edit bitstream seems to work correctly though, but it doesn't need those additional headers

**Comment by tdonohue** [comment]
@benbosman : I've rebased this on the latest `master` and retested it.  I'm not able to reproduce the `curl` issues you noted after I update the `rest.cors.allow-origins` configuration appropriately.

For example, with default settings (which is `rest.cors.allowed-origins = ${dspace.ui.url}` and `dspace.ui.url=http://localhost:3000`), this command works for me (no CORS errors):
```
curl -D - 'http://localhost:8080/server/api/authn/status' -H 'Accept: application/json' -H 'Content-Type: application/json; charset=utf-8' -H 'Origin: http://localhost:3000'
```
But any other `Origin` that I pass in will fail with a "Invalid CORS request" error.

If I change the allowed-origins settings to have additional origins like this: `rest.cors.allowed-origins = ${dspace.ui.url}, http://www.google.com`, then the same `curl` command also works with `Origin: http://www.google.com` *or* `Origin: http://localhost:3030`.

So, I think this PR is doing exactly what it is supposed to do.  However, I'm not sure whether it solves all the issues behind the Shibboleth CORS problems (it might not and I unfortunately don't have a Shibboleth instance to test this on). But, I think it at least adds the capability to have a whitelist of allowed `Origin` values (which was the main goal of this PR).

Does this make sense?  Or am I missing something that still isn't working correctly?

**Comment by benbosman** [comment]
I've tested the latest version, and it still doesn't support Shibboleth or exposing the list of login methods.
The curl request does not respond with `Access-Control-Allow-Credentials:true` which is required for Shibboleth

In order to use this for Shibboleth authentication , the Access-Control-Allow-Credentials header has to be set to true.
A configurable list of exposed headers would be the most flexible solution.

You can even see this without using Shibboleth in your net panel, the /server/api/authn/status request fails due to this CORS policy

**Comment by tdonohue** [comment]
@benbosman : Thanks for the additional testing & explanation. I didn't realize the issue was the lack of the "Access-Control-Allow-Credentials" header.  I've just pushed up a new commit to add support for a configurable "Access-Control-Allow-Credentials" header (and it now defaults to "true").

I'll also update the PR description as this was not part of the original goal of the PR, but it was simple enough to add in.

Please give this another try/review. Thanks!

**Review by benbosman — APPROVED** [review]
I've verified this again, and the /server/api/authn/status can now respond correctly.
I assumed it was broken due to this branch, but it seems this has never worked, that may explain the confusion

Shibboleth won't work yet without Apache changes with this PR, but that can be handled in a separate PR. It would require an additional exposed header.
It would be a good next improvement to make the allowed headers and exposed headers configurable

**Comment by tdonohue** [comment]
Merging, as we decided this was one approval in today's meeting.

**Pull request merged**
