### PR TITLE
[TLC-387] When retrieving S3 bitstream, strip -R from internal ID if bitstream is registered

### PR DESCRIPTION
**Pull request by kshepherd**
## Description
This small PR implements the same "strip -R internal ID prefix from bitstream" functionality to the S3BitStoreService that is already in use by DSBitStoreService, for the `get` and `about` methods.

I haven't changed `put` (possible case: replacement?) as that hasn't come up in my own testing yet.

This probably needs including in some tests as the fact that S3 couldn't deal with registered bitstreams has gone unnoticed for a long time.

Still working on test instructions - the CLI import tool might be OK but Integration Tests are probably the clearest way forward.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 @kshepherd :  This all looks reasonable.  I'll admit, I don't have a way to test this out, but I've verified that the logic in this PR matches the same logic seen in DSBitStoreService with regards to this `-R` flag: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/storage/bitstore/DSBitStoreService.java

So, I think this looks good, provided that you've tested it and verified it's working for you??  (I'd just prefer to know whether this has been verified via testing)

UPDATE: I also agree that it might be nice to at least add some basic tests to `S3BitStoreServiceTest.java`.  That just provides unit tests (using mocks), but I don't think integration tests would be very easy to achieve here.  See https://github.com/DSpace/DSpace/blob/main/dspace-api/src/test/java/org/dspace/storage/bitstore/S3BitStoreServiceTest.java

**Comment by kshepherd** [comment]
> So, I think this looks good, provided that you've tested it and verified it's working for you?? (I'd just prefer to know whether this has been verified via testing)

Hi Tim, yes, I've been able to successfully register S3 bitstreams that were uploaded outside of DSpace. I've looked to try and find any other impact of this flag and additional places that it needs handling, but didn't find much.

**Comment by tdonohue** [comment]
@kshepherd : Would you be able to add a basic test or two into our existing `S3BitStoreServiceTest.java` to verify the new behavior?  I think tests should be pretty easy to add for this, but if you disagree let me know.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @kshepherd !  The new tests look good and verify that this is working as expected.

**Pull request merged**
