### PR TITLE
Fix for dc.date.available does not take into account embargoes

### LINKED ISSUE #6583: [DS-3228] dc.date.available and dc.date.accessioned only differ when using old Embargo system
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3228">[DS-3228]</a> created by tdonohue</i>
<p>This ticket is based on this thread on dspace-tech:<br/>
<a href="https://groups.google.com/d/msg/dspace-tech/k7qCSJVhRrU/lk8Ze_7OOwAJ" class="external-link" target="_blank" rel="nofollow noopener">https://groups.google.com/d/msg/dspace-tech/k7qCSJVhRrU/lk8Ze_7OOwAJ</a></p>

<p>The <tt>dc.date.accessioned</tt> and <tt>dc.date.available</tt> metadata fields are always set to the same time (within a millisecond), except for one specific scenario:</p>

<ol>
	<li>The old (pre-3.x) <a href="https://wiki.duraspace.org/display/DSDOC5x/Embargo" class="external-link" target="_blank" rel="nofollow noopener">embargo system</a> is used</li>
	<li>AND, an old style embargo is set on the Item.</li>
</ol>

<p>See the code in <tt>InstallItemServiceImpl.populateMetadata()</tt>: <a href="https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/content/InstallItemServiceImpl.java#L137" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/content/InstallItemServiceImpl.java#L137</a></p>

<p>This specific scenario is less and less likely for more recent releases of DSpace, and seems to go against the need for two metadata fields.</p>

<p>Likely, <tt>dc.date.available</tt> should be set to a different value in other scenarios as well. For example, when an Item is undergoing an approval process, <tt>dc.date.available</tt> likely should be set to the date/time when that approval is completed, while <tt>dc.date.accessioned</tt> should be set to the date/time when that approval was begun.</p>

### LINKED ISSUE #9071: Install item: populateMetadata is not populating dc.date.available correctly
**Describe the bug**
Upon item archival the populateMetadata method is called to populate various relevant metadata fields such as dc.date.accessioned and dc.date.available.

Currently the population of dc.date.available does not take into account current embargoes on the bitstreams of the item, and still relies on the old embargo setting functionality where embargo dates where stored in the dcterms.embargo.liftdate metadata.

This is currently causing for embargoes to be ignored at archival time when setting dc.date.available and for it to always match that of dc.date.accessioned.

**Related work**
Link to any related tickets or PRs here.
I would like to work on a PR for this once the issue is confirmed and propose to use the work on this other PR #8926 to extract the embargoDate using the AccessStatus information.

### PR DESCRIPTION
**Pull request by amgciadev**
Remove setting dc.date.available

## References
* Fixes #9071
* Fixes #6583 

## Description
It is proposed to remove setting this field (dc.date.available) upon item archival. Embargo dates can be exposed via the API and the UI using the current accessStatus information as proposed in the issue description

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [X] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@amgciadev : Just a quick note... this is failing a few Integration Tests because we seem to have a few which *count* the number of Item metadata fields, and now we have one less field.   (These ITs likely shouldn't be counting fields, but that's a separate issue.  If you wanted to fix the failures you could just decrease the expected counts by one.)

**Comment by pnbecker** [comment]
I'm in favor for this code change, but I would propose to put it into DSpace 8.0 and not into any minor versions of 7.6. I also would ask that this change is mentioned in the Release Notes.

We often get questions about the different date fields that DSpace uses. And dc.date.available is the hardest one to explain. I expect that some people are using it and expecting it to be set automatically. We should advise those people to use dc.date.accessioned instead or use the embargo helper. But this is a change in the expected behavior of DSpace and not a bugfix. Therefore, I think this would fit better into DSpace 8.0 as into any minor release of DSpace 7.

@tdonohue already pointed out the failing tests. I haven't tested the PR, I just reviewed the code.

**Comment by tdonohue** [comment]
Based on discussion in today's meeting, I agree with @pnbecker  (and @J4bbi in the meeting) that we should move this to the 8.0 release.  It *is possible* that some sites are using this `dc.date.available` field in custom code, and are depending on it to be auto-populated with some date.   

Therefore, as @pnbecker notes above, we should clearly document its removal & tell everyone to use `dc.date.accessioned` instead (because in 7.x both `dc.date.accessioned` and `dc.date.available` will contain the same date).  That would imply it should be done in the 8.0 release, so that institutions can be warned about this potentially breaking change.

**Comment by pnbecker** [comment]
@amgciadev If you want to get this into DSpace 7, I would use the embargo helper and set it to the value it gives back. That would fix the originally reported bug and would be a proper bugfix, that could be included in a minor release.

**Comment by amgciadev** [comment]
Hi both, thanks both! @pnbecker that is exactly what I had in mind originally - our initial 7.6 customisation had it implemented in this way, but I think @tdonohue mentioned the concern that that metadata field could potentially end up not up-to-date if the embargo changes later on. Although, the current functionality does not account for embargo changes does it? So we could use the same argument there. I am actually happy to implement the changes in the way that @pnbecker suggest so that it gets into 7 plus it will also ensure that the date is set correctly upon archival, based on the embargo placed at that point and stop using the obsolete embargo setter functionality. What are your thoughts?

**Comment by pnbecker** [comment]
@amgciadev @tdonohue is right, sorry I forgot about this. We could add an Event that is pushed over DSpace's event mechanism whenever a resource policy is changed and add a consumer to update this field. But that is much more work. But that would probably be the perfect solution.

**Comment by tdonohue** [comment]
@amgciadev and @pnbecker : I don't think it will be easy to ever get the `dc.date.available` field to accurately hold the embargo date. I'd honestly question whether the effort is worth it, as I don't see a real (long term) benefit to having that field automatically "sync" to the embargo information kept in ResourcePolicies.

I think the best approach is to remove the field from being set, as it no longer serves a purpose.  But, I agree that seems more like a change that should occur in a major release.

**Comment by tdonohue** [comment]
Closing & reopening to trigger GitHub CI to run again.  Apologies for the noise, but trying to see why this PR was failing tests & whether it was a random failure.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@amgciadev : Sorry it's taken so long to get back to this.  Our concentration has been on new features & I'm just now finding a little time to test some bug fixes.

First off, the **good news is that this works**. I've verified the `dc.date.available` metadata field is no longer added to newly submitted Items.  Code looks good too.

However, there is still on IT that is failing.  It looks like the problem is on this line where the count needs to be decreased from 23 to 22:
https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/RelationshipRestRepositoryIT.java#L1042

Once that is fixed, I'm hopeful all the ITs will pass.  At that point we can merge this immediately.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @amgciadev !  This looks good now & it works as described.  Merging immediately for 8.0

(NOTE for all: Based on discussions/comments above, this will *not* be backported to 7.x)

**Comment by tdonohue** [comment]
Flagging this as `needs documentation` simply because this change deserves a mention in our eventual 8.0 Release Notes.

**Comment by tdonohue** [comment]
Removing "needs documentation" as this has been documented as a "Breaking Change" in 8.0 release notes: https://wiki.lyrasis.org/display/DSDOC8x/Release+Notes#ReleaseNotes-BreakingChanges

**Pull request merged**
