### PR TITLE
[DS-3246] Improve cleanup in recyclable components

### PR DESCRIPTION
**Pull request by aschweer**
https://jira.duraspace.org/browse/DS-3246

Same as #1437 , but for 5.x

### CODE REVIEW

**Comment by aschweer** [comment]
This has been live in production in several of "my" IRRs for months.

**Comment by hardyoyo** [comment]
Testing in our staging repository now, seems to work fine, no complaints. Memory usage (monitored with Yourkit) does look more tame than stock DSpace. +1

**Comment by tdonohue** [comment]
+1 via code review. Same code changes as #1437 , but for the 5.x codebase.

**Comment by tdonohue** [comment]
Approved during backlog hour today, and already at +2. Merging

**Pull request merged**
