### PR TITLE
[Docker] Use fully qualified image names & allow for other registries to be used

### LINKED ISSUE #8348: Use fully qualified image name for containers on Docker Hub
**Describe the bug**
Docker is not the only container runtime and docker.io is not the only container registry. We should use fully qualified image names for containers hosted on Docker Hub so we are not ambiguous when running on other container runtimes.

**To Reproduce**
1. Try to pull a container without a fully qualified name while using Podman.
2. Get an error.

```console
$ podman pull dspace/dspace:dspace-7_x                                                                                   
Error: short-name "dspace/dspace:dspace-7_x" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
```

**Expected behavior**
Using the fully-qualified registry name we can pull successfully:

```console
$ podman pull docker.io/dspace/dspace:dspace-7_x
Trying to pull docker.io/dspace/dspace:dspace-7_x...
Getting image source signatures
Copying blob 1334d60df9a8 skipped: already exists
Copying blob bf168a674899 skipped: already exists
Copying blob 6d5c91c4cd86 skipped: already exists
Copying blob e604223835cc skipped: already exists
Copying blob 16c2728dcd90 skipped: already exists
Copying blob 3bbce73846a1 skipped: already exists
Copying blob 58e753cca0c7 skipped: already exists
Copying blob 05288798d23d skipped: already exists
Copying blob e756f3fdd6a3 skipped: already exists
Copying blob 6f5861255518 done
Copying blob 5e20d165240e skipped: already exists
Copying blob 933d053ab028 done
Copying config 8b91fb3510 done
Writing manifest to image destination
Storing signatures
8b91fb35109f04260f4300798436f3e841fe47bb4f3d590ca626c53a2e73dc9c
```

**Related work**
See similar issue in dspace-angular: https://github.com/DSpace/dspace-angular/issues/1686

### PR DESCRIPTION
**Pull request by tdonohue**
## References
* Fixes #8348 
* Replaces #8349

## Description

The primary purpose of this PR is to allow for DSpace images to be referenced in other Docker registries via a new `DOCKER_REGISTRY` parameter/variable.  This allows sites to more easily customize these images and store their custom images in a different registry (e.g. GitHub's `ghcr.io` or any other Docker registry).  By default, `docker.io` is used.

While adding this improvement, I also made the following enhancements to our Dockerfiles in general:
* Cleaned up old/outdated `ENV` syntax

## Instructions for Reviewers
* Ensure all tests pass, as this will validate that `docker.io` is used by default (i.e. no change in default behavior)
* Optionally, use the new `DOCKER_REGISTRY` parameter to pull images from a different registry.  However, this would require first pushing images to a different registry, so it's not easy to test.
    * For example, this should pull and build DSpace images stored in `ghcr.io`:
       ```
       docker compose -f docker-compose.yml -f docker-compose-cli.yml pull --build-arg DOCKER_REGISTRY=ghcr.io
       docker compose -f docker-compose.yml -f docker-compose-cli.yml build --build-arg DOCKER_REGISTRY=ghcr.io
       ```
     * The above commands would work for **Committers** if they authenticate with `ghcr.io` first (e.g. `docker login ghcr.io -u [username] -p [password]`).  This is because, I tested this PR myself by pushing (private) images to `ghcr.io` at https://github.com/orgs/DSpace/packages
     * The above commands will NOT work for non-Committers as they will not have access to the private images at `ghcr.io`

### CODE REVIEW

**Comment by tdonohue** [comment]
@alanorth : You may be interested in this PR because it replaces / builds from your old PR #8349   (That said, this is not a high priority PR to merge immediately, but just something I've found useful myself.)

**Comment by alanorth** [comment]
@tdonohue ah, yes. For those of us who use containers but not Docker (Podman!) this is nice. Can't assume every un-prefixed image must live on docker.io. Cheers!

**Comment by tdonohue** [comment]
Merging, as this PR is necessary to solve #10092 .  As noted in today's Developers Meeting, I'm working on refactoring our GitHub Actions to **build** our Docker images via GitHub's Container Registry (ghcr.io), and then perform a simple copy over to DockerHub.  For more information, see https://github.com/DSpace/DSpace/issues/10092#issuecomment-2540032006

(If anyone notices issues in this PR *after merger*, then I'll gladly clean them up later.  This is only being merged immediately as it's necessary to solve the larger problem of our reliance on DockerHub)

**Comment by tdonohue** [comment]
Manually ported to 8.x and 7.x in #10114 and #10115 respectively

**Pull request merged**
