### PR TITLE
Align Java code with new Code Style

### PR DESCRIPTION
**Pull request by tdonohue**
This PR aligns our Java code (on `master` only) with the new Code Style rules detailed in #1895.

(NOTE: It is built off a shared branch based on the #1895 branch, so it does include the commits also in #1895)

This PR only changes the following:
* code alignment (e.g. alignment of brackets/braces)
* line wrapping (all lines of code now <=120 chars)
* whitespace (e.g. no trailing spaces, no tabs)
* occasionally, comments may need minor modification as well to align with code style 
* occasionally, add `private`, empty default constructors for Utility classes (per this rule: http://checkstyle.sourceforge.net/config_design.html#HideUtilityClassConstructor)
* occasionally, add in missing `default` clause to `switch` statements (per new code style)
* occasionally, split up multiple variable declarations in a single line to multiple lines (per new code style)

**No code changes/refactoring are made in this PR (only exceptions are minor fixes noted above)**

Please note the majority of the code fixes in this PR are being automated via IntelliJ IDEA bulk "Reformat Code" tools. For details of the process, please see: https://wiki.duraspace.org/pages/viewpage.action?pageId=90967266#CodeStyleGuide(WIP)-Fixingthecodebase

**STATUS:** Each module will be cleaned/fixed in a separate commit. As modules are considered "fixed", they will be added to the below list:

- [x] dspace (*no changes needed*)
- [x] dspace-spring-rest  (See https://github.com/DSpace/DSpace/pull/1952/commits/c5cd807f913551ed7604b4b89bb41663634509f)
- [x] dspace-oai (See https://github.com/DSpace/DSpace/pull/1952/commits/df6328120928c2df83c83504eeb4384292d98744)
- [x] dspace-rdf (See https://github.com/DSpace/DSpace/pull/1952/commits/baa22380ed8428d2b759d38ed93970d0d9dadbeb)
- [x] dspace-rest (See https://github.com/DSpace/DSpace/pull/1952/commits/425ed01af5fc3c1f12602065bad0b424cb9b9f33)
- [x] dspace-services (See https://github.com/DSpace/DSpace/pull/1952/commits/02f6da902072988b65e93ce15aa2097a7503bdee)
- [x] dspace-solr (See https://github.com/DSpace/DSpace/pull/1952/commits/654f9d22604b0b3c9fb59e7a7a61cdb28ec09909)
- [x] dspace-sword (See https://github.com/DSpace/DSpace/pull/1952/commits/fdbfa24393d1fd493a49c8b38847dd2fae32facc)
- [x] dspace-swordv2 (See https://github.com/DSpace/DSpace/pull/1952/commits/8110062655d15320b05b53fc42824d545fa24782)
- [x] dspace-api (See https://github.com/DSpace/DSpace/pull/1952/commits/714024226418dd074c2a85a38f951e3f30adf052)
- [x] dspace-parent (i.e. Root directory files) - No changes needed
- [x] enable checkstyle validation on all builds

### CODE REVIEW

**Comment by tdonohue** [comment]
After completing all of the above, I just realized that I neglected to fix our test source code (`/src/test/java`), as `maven-checkstyle-plugin` excludes that directory by default.  However, as this PR is already massive, I'd recommend merging this as-is, and fixing tests in a separate PR.

So, this PR should be considered "complete" (once Travis finishes approving one last time) and is read for review/merger.

**Comment by pnbecker** [comment]
👍

**Review by kshepherd — APPROVED** [review]
looks good to me (as much as one can look through so many lines!) and builds fine

**Comment by abollini** [comment]
I'm fine with merging that as soon as the recent introduced conflicts are solved. Thanks to take care of that @tdonohue

**Comment by tdonohue** [comment]
I've just finished rebasing this PR on the latest `master` code.  Will wait for Travis CI approval/verification before proceeding.

**Comment by tdonohue** [comment]
Approved in DSpace 7 meeting today. Merging.

**Pull request merged**
