### PR TITLE
[DS-3903] Resolve Jaskson Dependency Issues in 6x REST API

### PR DESCRIPTION
**Pull request by terrywbrady**
https://jira.duraspace.org/browse/DS-3903

### CODE REVIEW

**Review by mwoodiupui — APPROVED** [review]
This all looks good to me.  +1 by inspection.

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me too

**Comment by mwoodiupui** [comment]
Be on the lookout for other version changes around Jackson, when porting to another branch.

**Comment by mwoodiupui** [comment]
Some remaining Snyk issues may be addressed by #2032.

**Pull request merged**
