### PR TITLE
Common Extendend Regex Parser

### LINKED ISSUE #8563: Common Extendend Regex format for submission-forms
As of now it will be impossible to define a common regex tag value that has flags usable for both `REST` and `angular` projects.
Moreover, using regex with the form `/{regex}/` will be invalid for `REST`.
It will be nice to use a common format / parser to analyze, parse and correctly create the `regex`.
Because we are currently showing the mismatched pattern inside the wrongly filled field in the `angular` project, it will be useful to use the standard regex format with flags: `/{regex}/{flags}` inside the `input-forms.xml` definition files. In this way the user will have a quickly understandable pattern (standard with flags) for check and adjust the configuration also using some famous online tools.

**To Reproduce**
Insert some regex with flags `/{regex}/{flags}` inside `input-forms` definition file, or insert a regex with `/` as delimiter: `/{regex}/`. This could led to wrong / unexpected behaviors.

**Expected behavior**
We should use the extended definition for regex, that will support all of these cases:
* `/{regex}/{flags}`
* `/{regex}/`
* `{regex}`

In this way we could easily parse and compute the right pattern with or without flags, and also check that the regex field contains a valid pattern.

### PR DESCRIPTION
**Pull request by vins01-4science**
## References
* Fixes #8563 
* Requires DSpace/dspace-angular#1976

## Description
Parses the submission-forms and checks for a valid regex that could have flags declared in this way: `/{regex}/{flags}`.

## Instructions for Reviewers
Without the Frontend part you can test it by inserting some `regex` inside the `<regex>` tag of the submission form and try to save it with a valid / invalid value.

List of changes in this PR:
* New utility class for regex parsing and generation;
* New method inside DCInput to correctly retrieve the regex pattern.

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by tdonohue** [comment]
@vins01-4science : Could you please rebase this PR on the latest `main`?  It's showing Integration tests failures, but I believe those were the same ones we recently fixed in #8597 .  So, if you rebase, those failures should hopefully go away.  Thanks!

**Comment by vins01-4science** [comment]
> @vins01-4science : Could you please rebase this PR on the latest `main`? It's showing Integration tests failures, but I believe those were the same ones we recently fixed in #8597 . So, if you rebase, those failures should hopefully go away. Thanks!

@tdonohue : I've just updated the branch.
Thank you too!

**Review by tdonohue — COMMENTED** [review]
@vins01-4science :  Tested this today with the frontend.  I tried using the new flags (from ECMAScript format), and they appear to be working.  I also tried an invalid Regex, which logged a `WARN` and disabled any checks on that field.

My only comments are that the new utility class could use more tests (see inline comment below).  Your basic tests look good, but I think more tests would help to prove that this is working as expected to handle ECMAScript regex format.

So, overall I'm a +1, but I think this needs some minor code cleanup. Thanks!

**Comment by vins01-4science** [comment]
@tdonohue: I pushed some code refactoring with also java doc improvements.
Added also new tests as you requested.

Hope that's all good now :smile: !

Thank you!

**Review by tdonohue — APPROVED** [review]
👍 Thanks @vins01-4science !  The new tests look good. I tested this again manually too, and it's still working well.

So, +1 to this backend PR.  I still have a very minor suggestion though for more code comments on your frontend PR at https://github.com/DSpace/dspace-angular/pull/1976   Once better code comments are added to the frontend PR, I think that's ready to merge as well.

**Pull request merged**
