### PR TITLE
Prevent NPE during indexing if bitstream is null

### LINKED ISSUE #8954: Discovery re-indexing - NPE if bitstream is null
**Describe the bug**
When triggering a full reindexing an NPE is thrown if there are issues with bitstreams in the TEXT bundle when performing a discovery reindexing
**To Reproduce**
The instances that were causing this issue for us cases when somehow the bitstream sequence order was off for bitstreams within bundles. E.g. bitstream_order column had incorrect sequences. This was causing for the NPE error to be thrown here:

https://github.com/DSpace/DSpace/blob/4771ebe87388576b2a17f1af043b478eba70d587/dspace-api/src/main/java/org/dspace/discovery/FullTextContentStreams.java#L84 

**Expected behavior**
An error like this could be better reported in the logs, and it shouldn't cause for the whole reindexing process to stop.

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by amgciadev**
Fix NPE if bitstream is null

## References
* Fixes #8954

## Description
Add better logging and avoids NPE if bitstream is null

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
I've tested this on DSpace 7.6 by doing a full Discovery re-index. The process works fine for me.

I don't see any messages about null bitstreams in my `dspace.log` during indexing. I guess I don't have any null bitstreams? Or maybe because I don't have debug logging enabled?

**Comment by amgciadev** [comment]
@alanorth it could be that you don't have any of those bitstreams - we encountered this issue because we had a number of bitstreams with an incorrect order sequence in the DB, and somehow this was causing for them to hit the null exception

**Comment by alanorth** [comment]
@amgciadev as far as I can see we don't have any null bitstreams and this pull request doesn't cause any side effects for us, so I am +1.

**Review by alanorth — APPROVED** [review]

**Review by tdonohue — APPROVED** [review]
👍 Code seems reasonable to me.  It's just safety checks to ensure no NPEs can occur when a bitstream is null.  Thanks @amgciadev !

**Comment by tdonohue** [comment]
Manually ported this to `dspace-7_x` in #8997.  The automatic port didn't work. (I suspect because this PR had a merge commit within it)

**Pull request merged**
