### PR TITLE
[DS-2701] dspace-oai

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://jira.duraspace.org/browse/DS-2701

Much of the sheer size of this PR comes from a few sources:
- adding or augmenting javadoc in dspace-api to record my developing understanding of the changes there;
- removing the database-style search implementation;
- liberally accepting hints from my IDE, where they made sense and made the code better or more readable.
- moving non-database classes out of org.dspace.xoai.services.impl.database (emptying that package) into org.dspace.xoai.services.impl.

### CODE REVIEW

**Comment by tdonohue** [comment]
Pinging @KevinVdV as this PR is also "ready for initial review". If you just haven't gotten to it, yet, no worries. I just saw you were reviewing and merging other UI-level refactors today.

**Comment by KevinVdV** [comment]
@mwoodiupui @tdonohue I will perform a quick review in the days to come. Today my focus was the removal of the BundleBitstream object (https://github.com/DSpace/DSpace/pull/1035), since it had to be refactored & tested.

**Comment by mwoodiupui** [comment]
When you have time, I'm curious to know whether my assigning the PR to @KevinVdV produced a message to you that was understandable as a request for review.  I've never been assigned a PR, so I don't know what happens.  Is this a useful method?

**Comment by KevinVdV** [comment]
@mwoodiupui I got a nice notification in my mail box (with your name as the sender):

Assigned #1024 to @KevinVdV.

So it wa pretty clear to me & very useful.

**Comment by KevinVdV** [comment]
@mwoodiupui I took a quick look around & things are looking very good, but I do see a lot of "buildDatabaseQuery" methods still lying around.
Best to remove all of these to avoid confusion (& this code isn't used anyway). Once these get removed I think it would be best to merge it (I will do the rebase on the removal of the BundleBitstream object in that pull request).

**Comment by helix84** [comment]
Hi, sorry if I missed some conversation, but why are you removing the DB backend from OAI?

**Comment by tdonohue** [comment]
@helix84: The OAI-PMH DB backend is incompatible with Hibernate.  See https://wiki.duraspace.org/display/DSPACE/DSpace+Service+based+api#DSpaceServicebasedapi-Redundantfeaturesthathavebeenremoved

**Comment by mwoodiupui** [comment]
@KevinVdV well caught!  I've cleaned out a lot more database references.

**Comment by KevinVdV** [comment]
@mwoodiupui Went over everything a second time & could find no flaws, merging.

**Pull request merged**
