### PR TITLE
Add support for Java / JDK 17 (latest LTS release)

### PR DESCRIPTION
**Pull request by tdonohue**
## Description
Recently on the [dspace-community list it was noted that DSpace 7 doesn't compile with JDK 17](https://groups.google.com/g/dspace-community/c/MZmu3FnZCuA/m/W9PsyXc_BAAJ) (latest [LTS release](https://www.oracle.com/java/technologies/java-se-support-roadmap.html)). 

This PR fixes those compilation issues by updating the following:
* Upgrades us to latest version of `errorprone` which is compatible with JDK 17
    * Also some minor code fixes to resolve new errorprone errors reported after this upgrade. See 52a8edc7d62fb5ef8a2186144573338c73d02277
* Upgrades us to more recent version of `mockito-inline` to ensure it is also compatible with JDK 17
* ~~Updates our CI build/test process to run our tests BOTH for JDK 11 and JDK 17  (_Optionally, we could remove this as needed, but I added it to prove that the tests work for both JDK 11 and 17._)~~ Reverted this, we still only run tests for JDK11 at this time, however kept the CI build process changes to allow us to support multiple JDKs easily, if we desired to in the future
* Updates Dockerfiles to support either JDK11 (default) or JDK17.  To run JDK17 with Docker images, you must pass this build arg: `docker-compose -f docker-compose.yml -f docker-compose-cli.yml build --build-arg JDK_VERSION=17`

~~**I have NOT fully tested all functionality with JDK 17 at this time.**  This PR simply ensures everything compiles and passes all tests.~~ UPDATE: I've been testing this locally and have not seen any issues so far.

However, since all tests pass (including integration tests), this implies that DSpace 7 _likely should work with JDK 17_ (but additional testing/verification should be done before we add JDK 17 to our list of supported Java versions.

### CODE REVIEW

**Comment by tdonohue** [comment]
NOTE TO REVIEWERS:  Because this PR *renames/changes* the CI build process, it won't ever build the older "required" tests (meaning this PR will never get the green checkmark).  However, you can see that all the new tests succeed for both Java 11 and Java 17 here: https://github.com/DSpace/DSpace/actions/runs/1668711004

**Review by hardyoyo — APPROVED** [review]
👍

**Comment by tdonohue** [comment]
I've been testing the backend with JDK 17 over the past few days, and so far, I've not had any issues running this PR + openJDK 17 + Tomcat 9. It's all working the same as JDK11.  

So, this small PR seems to add support for JDK 17 to DSpace 7.x

**Comment by tdonohue** [comment]
In today's meeting, @abollini pointed out that we may want to consider only building on *one version* of Java (even if we support multiple), because GitHub actions has a free tier limit of 2,000 build minutes per month: https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions  Building on both JDK 11 and JDK17 will double the amount of minutes we are using per month, which could send us near that limit.

So, I'll refactor the CI changes in this PR to only build on JDK 11 again... then we can merge this and updated documentation that JDK 17 also works.

**Review by hardyoyo — APPROVED** [review]
This all looks good 👍

**Comment by tdonohue** [comment]
I just rebased this on latest main, just as a final verification that these tests all still pass (they should).  Once this passes CI, I'll merge immediately with +1 approval.

**Pull request merged**
