### PR TITLE
DS-2315: export Simple Archive Format without bitstreams

### PR DESCRIPTION
**Pull request by kohts**
https://jira.duraspace.org/browse/DS-2315

### CODE REVIEW

**Comment by mwoodiupui** [comment]
+1, code looks correct and and passes tests.

**Comment by kohts** [comment]
Refactored patch to be compatible with new service-based api (DS-2701), please remove "merge conflict" tag.

**Comment by kohts** [comment]
I'm going to clean this up, please do not merge yet

**Comment by kohts** [comment]
Done the clean up, please remove "work in progress".

**Comment by kohts** [comment]
Broke this PR, closing and creating a new, clean one.

**Comment by kohts** [comment]
New clean PR instead of this one: https://github.com/DSpace/DSpace/pull/1210

**Pull request closed without merging**
