### PR TITLE
DS-4115: Fix rb-inotify version

### PR DESCRIPTION
**Pull request by arvoConsultores**
https://jira.duraspace.org/browse/DS-4115

### CODE REVIEW

**Comment by tantz001** [comment]
Note, this fixes the same problem in v5.10.

**Comment by arvoConsultores** [comment]
It fail because travis make the -Dmirage2.deps.included=false compilation. 
Some Ruby expert can make a more elegant patch?

**Comment by hardyoyo** [comment]
I have changed the .travis.yml config for my fork of DSpace, see https://github.com/UCLALibrary/DSpace/pull/145, to set -Dmirage2.deps.included=true this allowed me to merge my PR and will allow me to deploy my code to production. So... it works for me. It may not be the best solution for DSpace, though. I thought I'd mention it.

**Comment by terrywbrady** [comment]
@arvoConsultores I added a commit that might help this PR pass the travis tests.  I do not know much about ruby, so this is a test.

**Comment by terrywbrady** [comment]
This might resolve the issue: https://github.com/DSpace/DSpace/pull/2309

**Comment by tdonohue** [comment]
This PR is no longer needed and has been replaced by two PRs:

* #2309 which updated the version of SASS being used by Travis CI builds (which build Mirage2 using `mirage2.deps.included=false` and Ruby 2.4.x)
* #2315 which updated the version of JRuby and SASS being used by our Maven build process when `mirage2.deps.included=true`

With these two PRs in place, pinning the version of `rb-inotify` is not necessary.  However, if you build Mirage 2 using `mirage2.deps.included=false` then you MUST have Ruby 2.2.x or above installed (or JRuby 9.1.x.x which is compatible with Ruby 2.3.x)

In any case, thanks @arvoConsultores for reporting this issue and helping provide a temporary fix (for anyone immediately impacted).

**Pull request closed without merging**
