### PR TITLE
[DS-3217] trying the suggestion from LuizClaudioSantos

### PR DESCRIPTION
**Pull request by hardyoyo**
use Calendar and not Date

### CODE REVIEW

**Comment by hardyoyo** [comment]
https://jira.duraspace.org/browse/DS-3217

**Comment by hardyoyo** [comment]
Tested in Vagrant-DSpace, I set the time in the VM to 23:01:

sudo date --set 23:01:00

and then re-ran the test:

mvn test

Everything passed.

**Comment by hardyoyo** [comment]
false positive, I need to re-test. It seems that [Virtualbox re-sets the time](http://askubuntu.com/questions/35566/how-do-i-manually-set-the-system-time-in-virtualbox#180358)

Here's how I set the time on my Virtuabox VM:
sudo service vboxadd-service stop && sudo date --set 23:01:00

**Comment by hardyoyo** [comment]
A different test is failing now, perhaps due to a similar reason:
`
testInstallItem_todayAsIssuedDate(org.dspace.content.InstallItemTest)  Time elapsed: 0.075 sec  <<< FAILURE!
java.lang.AssertionError: 
testInstallItem_todayAsIssuedDate 0
Expected: "2016-06-28"
     but: was "2016-06-29"
	at org.dspace.content.InstallItemTest.testInstallItem_todayAsIssuedDate(InstallItemTest.java:260)

testRestoreItem_todayAsIssuedDate(org.dspace.content.InstallItemTest)  Time elapsed: 0.063 sec  <<< FAILURE!
java.lang.AssertionError: 
testRestoreItem_todayAsIssuedDate 0
Expected: "2016-06-28"
     but: was "2016-06-29"
	at org.dspace.content.InstallItemTest.testRestoreItem_todayAsIssuedDate(InstallItemTest.java:310)
`

**Comment by LuizClaudioSantos** [comment]
Hi @hardyoyo,
    How are you running the test I ran "mvn test -Dmaven.test.skip=false" and I didn't get a test fail at all.
Best
Luiz

**Comment by helix84** [comment]
IIRC, it was due to timezone difference (probably normal vs. DST or GMT vs. CET). Hardy, what are your timezone settings?

**Comment by hardyoyo** [comment]
I have tests turned on all the time in my maven settings file.

On Jun 28, 2016 3:53 PM, Luiz Claudio França dos Santos <notifications@github.com> wrote:

Hi @hardyoyo<https://github.com/hardyoyo>,
How are you running the test I ran "mvn test -Dmaven.test.skip=false" and I didn't get a test fail at all.
Best
Luiz

**Comment by LuizClaudioSantos** [comment]
Yes, you are right, run the test all the time is the correct thing to do, but what I would like to know is if you and I are running the same maven command to test, because I ran it and I didn't get any fail.

**Comment by hardyoyo** [comment]
well... the tests run all the time whenever you activate the profile in maven settings, so it doesn't really matter if you turn them on via the command line. However, I am re-checking now. Yep, I still get a failure, after running the following:

sudo service vboxadd-service stop && sudo date --set 23:01:00 #set the time to 23UTC to trigger the error
date #confirm the time is set
mvn test -Dmaven.test.skip=false

two more test failures:

Failed tests: 
  InstallItemTest.testInstallItem_todayAsIssuedDate:260 testInstallItem_todayAsIssuedDate 0
Expected: "2016-06-29"
     but: was "2016-06-30"
  InstallItemTest.testRestoreItem_todayAsIssuedDate:310 testRestoreItem_todayAsIssuedDate 0
Expected: "2016-06-29"
     but: was "2016-06-30"

Probably similar to the first test failure (which seems to be fixed by this PR)... so... this PR does fix the test specified, but it doesn't fix the build.

**Comment by hardyoyo** [comment]
replaced by #1449

**Pull request closed without merging**
