### PR TITLE
DS-1689 Spatial Indexing and Querying

### PR DESCRIPTION
**Pull request by bbkopsas**
This request implements the following:
1. Introduces a new input-type "location" for submitting an item's bounding box using a map.
   An example is commented at input-forms.xml
2. Enables Spatial Indexing and quering in Lucene. The user has to specify the spatial metadata field in config.cfg following by ":location" flag
3. Enables Spatial Indexing and quering in Solr. For that reason a new spatial field Type was added in solr schema. The user has to specify the spatial metadata field in discovery.xml. 

Also, there is an implementation in XMLUI for mirage theme.

For making visible the map it needs to export OpenLayers 2.12 API (http://openlayers.org/download/) in xmlui/static/js folder and comment out "display:none" command in style.css at line 1405.

Also jts-1.8.jar must be present at lib folders

### CODE REVIEW

**Comment by tdonohue** [comment]
Closing as outdated/obsolete (no activity in several years and large numbers of merge conflicts). Please resubmit if you are interested in helping move this forward. Thanks!

**Comment by eneshukic** [comment]
Does this code works with DSpace 6.x (Mirage 2)?  If yes, what are current valid commits? Thanks

**Comment by tdonohue** [comment]
@eneshukic : No, this code was initially built for DSpace 4 or 5, and it was never updated for DSpace 6.  So, while the code in this PR likely would work for DSpace 5, it would not work as-is for DSpace 6.

**Comment by eneshukic** [comment]
@tdonohue Thanks for the quick reply.  I guess I will have to implement something similar for DSpace 6 as I have some additional requirements (define a circle, etc). This would be a good starting point.

**Pull request closed without merging**
