### PR TITLE
DS-2623: Add different file descriptions for multiple files after upload

### PR DESCRIPTION
**Pull request by pnbecker**
https://jira.duraspace.org/browse/DS-2623

Resumable.js makes it possible to upload multiple files at once. This PR
adds a description field for every uploaded file so multiple
descriptions can be added if multiple files were uploaded using the
resumable upload in JSPUI.

### CODE REVIEW

**Comment by pnbecker** [comment]
I updated this PR today to get support for multiple descriptions into the UploadWithEmbargoStep as well.

**Comment by olli-gold** [comment]
Thank you, Pascal!

I have tested the PR locally here and it works for me.

**Comment by nteike** [comment]
Pascal, thanks for fixing this. I have tested the PR and everything worked well.

**Comment by pnbecker** [comment]
Resolved the merge conflict today.

To test this PR: Upload files in JSPUI using HTML5 (enabled by default, you recognize it if you can upload files by drag & drop), add a description per files in the table that is created during the upload of the files, click next, see your file descriptions, end submission of the file an take a look for the file descriptions in item view.

**Comment by pnbecker** [comment]
While testing this PR I discovered DS-2833 and created #1123 as separate PR. Both PR are ready to get tested and merged.

**Comment by helix84** [comment]
+1, verified

**Pull request merged**
