### PR TITLE
[DS-3515] REST 7 Pagination for items and bitstreams

### PR DESCRIPTION
**Pull request by terrywbrady**
https://jira.duraspace.org/browse/DS-3515

For review purposes, pay particular attention to the changes in dspace-api.

This PR was built upon the branch for https://github.com/DSpace/DSpace/pull/1661, so that code is also included.  That PR contains support for the ItemRest class.

### CODE REVIEW

**Review by abollini — COMMENTED** [review]
The code looks fine, my only concern is about starting to make improvement to the DSpace-API since we are still in the feature branch. This could result in a more complex merge of rest7 in the master or duplication of effort is someone needs these improvements in the master to solve other issues....

we need to fix asap the build issue of the rest7 branch so to move the development to the master

**Comment by abollini** [comment]
during the today dspace7 hangout call we have agreed to postpone changes to the DSpace-API until the rest7 work will be merged in the master.
We are committed to solve the build / dependencies issue to move on with the merge within 2-3 weeks
https://jira.duraspace.org/browse/DS-3482

**Comment by tdonohue** [comment]
@terrywbrady : when you get the chance, can you *rebase* this on top of the latest code in `rest7`?  @mwoodiupui just fixed all the Travis test failures in `rest7` in #1675.  So, all other PRs against `rest7` should be updated so that Travis can (re)verify them.

**Comment by terrywbrady** [comment]
@abollini , @tdonohue , PR rebased.

**Comment by abollini** [comment]
tested now on top of the current rest7 branch. Merging now as I expect to merge the rest7 branch in the master in the next hour too (see #1679)

**Pull request merged**
