### PR TITLE
Per format pseudo streaming DS-1942

### PR DESCRIPTION
**Pull request by jsnshrmn**
https://jira.duraspace.org/browse/DS-1942

This is a work in progress.  I'm looking for feedback from the folks interested in real streaming to make sure I'm dovetailing nicely with what they want.  I've got a basic XMLUI implementation done.  This adds a new db column for the BitstreamFormatRegistry table.  I've handled the postgres setup, but not oracle.

### CODE REVIEW

**Comment by amandafrench** [comment]
I know that @keithgilbertson built something similar for us locally: perhaps he can help ...

**Comment by jsnshrmn** [comment]
I'm currently knee deep in an islandora project, so my immediate need to touch dspace is low right now. If someone else can agree to write the tiny oracle piece or if it's okay to only do this on postgres, I'll bring this up to speed with master since it's a few months old. Otherwise, we mark should mark it as abandoned/cancelled.

**Comment by helix84** [comment]
DSpace commiters are currently in the middle of a large refactoring that changes how DB queries are made, so there will be no separate queries for Postgres and Oracle (for DSpace 6 release). Because of this, there is a soft freeze on the master branch. Please, check out these docs, the relevant branch and any PRs against it to see how DB queries will work from now on. Thanks.

https://wiki.duraspace.org/display/DSPACE/DSpace+Service+based+api

https://github.com/DSpace/DSpace/tree/DS-2701-service-api

**Comment by helix84** [comment]
Perhaps @kshepherd would be interested in bringing this work forward?

**Comment by jsnshrmn** [comment]
Thanks for the info, Ivan. I'll check out those docs.

**Comment by tdonohue** [comment]
Closing as outdated/obsolete (significant merge conflicts). Please resubmit if you are interested in helping move this forward. Thanks!

**Pull request closed without merging**
