### PR TITLE
[DS-3397] Fix error when getting bitstream policies in REST API

### PR DESCRIPTION
**Pull request by SophiaGoldberg**
Fixes https://jira.duraspace.org/browse/DS-3397
Added null checks for EPerson and Group

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 Looks good. Small, obvious bug fix. Thanks!

**Review by mwoodiupui — APPROVED** [review]
+1 by inspection.

**Comment by mwoodiupui** [comment]
Looks well, but should this be against master or 6_x?

**Comment by tdonohue** [comment]
Created a 6.x version of this PR at #1799

**Pull request merged**
