### PR TITLE
DS-3315: update node dependencies

### PR DESCRIPTION
**Pull request by artlowel**
https://jira.duraspace.org/browse/DS-3315

A few remarks:
- This only updates the dependencies described in the issue as producing warnings: the node dependencies. These are the build tools, not the libraries used in the theme (jquery, handlebars, etc.). They are specified in bower.json. Updating those to the latest versions has more consequences as it will most likely require us to rewrite parts of the javascript code due to breaking changes. It will likely also affect the list of supported browsers, as the newer versions of those libs are likely to drop support for older Internet Explorer versions for example. Doing so may be worth considering, but it warrants a separate issue in my opinion.
- Using these newer node tools, also requires a node version >= 6. That means people that have installed the dependencies locally will likely need to upgrade their node version when upgrading to DSpace 6. If they used nvm, as we suggested in the docs, it won't be hard, but it is still something to keep in mind.
- I've tested this PR on node 6.5.0, npm 3.10.8 on OS X El Capitan, both dev and prod builds, and builds with and without preinstalled dependencies work using that combination of tools/platform. It is recommended that this is tested on a few more platforms before it is merged. _Especially on windows_!

### CODE REVIEW

**Comment by hardyoyo** [comment]
Compiled on Windows 10, without preinstalled dependencies, and everything works without any warnings or errors. Will try again after I install the full Mirage2 stack and report back. Looks good so far.

**Comment by hardyoyo** [comment]
I've tested pr1515 on Windows, without pre-installed dependencies. I can confirm it compiles correctly. I have not been able to manually install the dependencies to test that version of the build, I've given it about 30 minutes, which is all the time I have today. +1 based on the fact that the slightly more-complicated with dependencies build works correctly.

**Review by hardyoyo — COMMENTED** [review]
I've tested pr1515 on Windows, without pre-installed dependencies. I can confirm it compiles correctly. I have not been able to manually install the dependencies to test that version of the build, I've given it about 30 minutes, which is all the time I have today. +1 based on the fact that the slightly more-complicated with dependencies build works correctly.

**Comment by tdonohue** [comment]
@artlowel : This PR should probably also update our Travis CI config to install the new required version of node. https://github.com/DSpace/DSpace/blob/master/.travis.yml#L11   

I'm surprised Travis didn't complain during the build/test, but we should ensure it's running the expected version of node (and all other necessary dependencies)

**Comment by tdonohue** [comment]
Just tested this on Windows 10 myself, and it's NOT fully working yet.

While the build succeeds, Mirage 2 does **not** build properly and throws errors (the fact that it reports success despite errors is already a know issue: https://jira.duraspace.org/browse/DS-2458)

The errors seem to occur in the node installation process, as node cannot be downloaded (404) and never ends up being installed. Here's the errors I'm seeing:
```
[INFO] ------ (Mirage2) com.github.eirslett:frontend-maven-plugin:0.0.23:install-node-and-npm
[INFO] Installing node version v6.5.0
[INFO] No proxy was configured, downloading directly
[ERROR] MojoFailureException:
org.apache.maven.plugin.MojoFailureException: Could not download Node.js from: http://nodejs.org/dist/v6.5.0/x64/node.exe: Got error code 404 from the server.

... (After this there are several errors stating "Failed to run task" because "node" cannot be found)...

[INFO] ------ (Mirage2) de.saumya.mojo:gem-maven-plugin:1.0.6:exec
[WARNING] Compass can't find any Sass files to compile.
[WARNING] Is your compass configuration correct?.
[WARNING] If you're trying to start a new project, you have left off the directory argument.
[WARNING] Run "compass -h" to get help.
[ERROR] PluginManagerException:
org.apache.maven.plugin.PluginExecutionException: Execution null of goal de.saumya.mojo:gem-maven-plugin:1.0.6:exec failed: Java returned: 1
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at com.soebes.maven.plugins.iterator.ExecutorMojo.executeMojo(ExecutorMojo.java:302)
        at com.soebes.maven.plugins.iterator.ExecutorMojo.execute(ExecutorMojo.java:235)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: Java returned: 1
        at org.apache.tools.ant.taskdefs.Java.execute(Java.java:87)
        at de.saumya.mojo.ruby.script.AntLauncher.doExecute(AntLauncher.java:107)
        at de.saumya.mojo.ruby.script.AntLauncher.executeIn(AntLauncher.java:141)
        at de.saumya.mojo.ruby.script.Script.executeIn(Script.java:108)
        at de.saumya.mojo.gem.ExecMojo.executeWithGems(ExecMojo.java:106)
        at de.saumya.mojo.gem.AbstractGemMojo.executeJRuby(AbstractGemMojo.java:469)
        at de.saumya.mojo.jruby.AbstractJRubyMojo.execute(AbstractJRubyMojo.java:298)
        at de.saumya.mojo.gem.AbstractGemMojo.execute(AbstractGemMojo.java:222)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 24 more
```

**Comment by artlowel** [comment]
I've updated the versions in the travis build. I also updated to the latest version of the maven node plugin. That should fix the 404 according to [this issue](https://github.com/eirslett/frontend-maven-plugin/issues/451). @tdonohue Can you verify that it works for you now?

**Review by tdonohue — APPROVED** [review]
@artlowel - I've retested this on Windows 10. The build process (`-Dmirage.on=true`) now works and the Mirage2 theme displays properly in Tomcat 8.

+1 This works on Windows and the code changes look good to me.

**Comment by pnbecker** [comment]
I deleted my .npm directory, run mvn clean package -U -Dmirage2.on=true and was not able to spot any errors.
+1 => merging.

**Pull request merged**
