### PR TITLE
[Port dspace-7_x] Fix for DSpace#9667: Request-a-copy link generation for base URLs that have sub-paths

### PR DESCRIPTION
**Pull request by tdonohue**
Manual port of #9668 by @kshepherd to `dspace-7_x`

### CODE REVIEW

**Comment by tdonohue** [comment]
@kshepherd : It appears this isn't possible to easily backport to 7.x?  The new `RequestItemRepositoryIT` tests are all failing on 7.x.  Any ideas?

If you figure out a better way to port this, we can close this PR in favor of any you create.  I had just assumed this was an easy port.

**Comment by kshepherd** [comment]
@tdonohue the problem was with the NAME -> PLURAL_NAME change in the REST path registration, so it wasn't able to get the bean for that repository properly.

Now running into the `VersioningWithRelationshipsIT` failure which seems unrelated and is that annoying "handle / identifier reuse" issue - I'm not getting it locally, I'll keep trying to re-run here
(if you have any other ideas please let me know)

**Comment by tdonohue** [comment]
@kshepherd : Yes, it appears that **all recent PRs** are failing with this odd `VersioningWithRelationshipsIT` failure:
```
javax.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session : [org.dspace.content.MetadataValue#882]
```

It's unclear to me what has broken this test on `main`, but it seems to be consistent in behavior (at least in GitHub CI).  It appears to have started recently, but with no clear cause (as recent PRs don't touch this area of the code).  I'll have to try to find time to dig into this tomorrow or Monday, as it's unclear to me why this test would suddenly fail.

**Comment by tdonohue** [comment]
I've rebased this on latest `dspace-7_x` now that the `dspace-7_x` IT failures should be fixed (by #9812 ).  Assuming the tests all succeed, I'll merge this backport immediately

**Pull request merged**
