### PR TITLE
Authority controll - Suggest option is not working on JSPUI

### LINKED ISSUE #7594: [DS-4254] Authority control - "Suggest" type is not working
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4254">[DS-4254]</a> created by marcio.gurgel</i>
<p>The rendering type "suggest" for the authority plugin is not working on DSpace 6.3.</p>

<p>There's is an string concatenation error when the call to </p>

<p>"DSpaceSetupAutocomplete" is built (edit-metadata.jsp) . </p>

<p>This concatenation problem results the following invalid HTML:</p>

<p></p>

<p>(notice that "collection" attribute became invalid)</p>

<p> </p>

### PR DESCRIPTION
**Pull request by mrgurgel**
Code to fix the following issue:
https://jira.duraspace.org/browse/DS-4254
Fixes #7594

### CODE REVIEW

**Comment by mrgurgel** [comment]
Issue here:
https://jira.duraspace.org/browse/DS-4254

**Review by kshepherd — APPROVED** [review]
+1 by code review - this ensures UUIDs are concatenated properly (the previous version assumed the legacy integer collection IDs)

**Comment by tdonohue** [comment]
I resolved the merge conflict.

**Comment by toniprieto** [comment]
@tdonohue I think that the "merge conflict" was because another merged PR has already resolved the issue.
This merged PR ( #2918) has the same modification to add simple quotes to the collection parameter:

https://github.com/DSpace/DSpace/pull/2918/commits/423af4ca981a9c3fd850fd1609f7ed9dfbe0f000#diff-758a4253c8a9b9756e56c80a541358b456d780f7f3ba65a02eb37362d918c983R192

I haven't tested it but I think that the issue should be already resolved in current dspace-6_x branch.

**Comment by tdonohue** [comment]
@toniprieto : Thanks for the follow-up. Yes, it appears your analysis is correct & I also see those fixes already applied to `dspace-6.x` here:  https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-jspui/src/main/webapp/submit/edit-metadata.jsp#L192-L193

 Therefore, I'm closing this PR as already fixed.  Thanks!

**Pull request closed without merging**
