### PR TITLE
DS-2629: ExcelFilter

### PR DESCRIPTION
**Pull request by edgo914**
Addition to filter-media for Excel file text extraction

### CODE REVIEW

**Comment by tdonohue** [comment]
Hi @edgo914 , thanks for the PR!  It looks reasonable, at a glance.  Per our normal policies, I've added a new JIRA ticket to describe this PR: https://jira.duraspace.org/browse/DS-2629

One other note, I'd encourage you to also add the necessary `dspace.cfg` configurations to enable this new ExcelFilter by default, as it seems like it'd be useful to turn on by default whenever `./dspace filter-media` is run

**Comment by edgo914** [comment]
Added default config settings for ExcelFilter to dspace/config/dspace.cfg

**Comment by edgo914** [comment]
Note to whoever at DSpace will document this feature:
The latest pdf manual I have for DSpace lists the plain xls "Microsoft Excel" file within the section
"Default Bitstream Format Registry", but it does not contain an entry for "Microsoft Excel XML"
file type "xlsx". The underlying code has it right but the docs don't yet reflect that.

**Comment by tdonohue** [comment]
Looks good @edgo914 , thanks again!

Regarding documentation, DSpace is entirely developed and documented via community contributions. DSpace is not an organization, and while DuraSpace (the organization I work for) helps to steward DSpace software, we don't have documentation experts or developers on staff (other than myself). Literally, the software and documentation is managed by a distributed team of volunteer developers (often with support of the institutions they work at).

So, if you have any documentation you feel should be added/changed, there are two options

  1. Add documentation details to the ticket itself (as a comment or as an attachment): https://jira.duraspace.org/browse/DS-2629
  2. OR, I can give you access to modify the documentation directly. It's all managed in a Wiki (which is access restricted by default to avoid spam). Here are the current docs for DSpace 5: https://wiki.duraspace.org/display/DSDOC5x/

But, beyond that, I've scheduled this for review for possible inclusion in 6.0 (coming later this year). So, we're just waiting on a volunteer tester to help verify everything works, and then we'll get it merged in, etc.

**Comment by edgo914** [comment]
Documentation added as comment to:

https://jira.duraspace.org/browse/DS-2629

**Comment by tdonohue** [comment]
Unfortunately, this PR has been accidentally "messed up" as it now includes an unrelated commit (a REST API bug fix). 

I already emailed @edgo914 about it, recommending he create a new PR against a non-"master" branch (e.g. a branch called "DS-2629"), per our recommendations here:
https://wiki.duraspace.org/display/DSPACE/Development+with+Git#DevelopmentwithGit-Creating&UpdatingPullRequests

Unfortunately, we won't be able to merge this PR as it includes unrelated changes. Sorry, each change needs a separate review & we need to track them in separate tickets (as they are unrelated).

@edgo914,  if you have any issues creating a new PR, please do let us know by adding comments here. Thanks for your contributions!  Don't worry, everyone makes these sorts of mistakes early on (self included)...as it's not always clear that a PR 'tracks' your source branch, and so you'll accidentally change the PR if you add new commits to that branch.

**Comment by edgo914** [comment]
I created a new PR:

https://github.com/DSpace/DSpace/pull/989

**Comment by tdonohue** [comment]
Closing this PR in favor of #989

**Pull request closed without merging**
