### PR TITLE
[DS-4425] Indexing Performance is very slow since refactor. ITs take twice as long

### PR DESCRIPTION
**Pull request by KevinVdV**
JIRA: https://jira.lyrasis.org/browse/DS-4425

This PR will fix the performance issues raised with the rework of the IndexableObject. The problem was located in the IndexEventConsumer. 

The previous behavior for when a workflow item passed the consumer:
* it would add the item from that workflow item to the "to-index-list" of objects to be indexed.
* It then passed this single object to discovery service
* This discovery method would resolve the object into the related objects (item, workflow item, pooled task, ...)
* the discovery method would trigger a single commit at the end commit

What my code changed:
* instead of adding the single object the code would add all the related objects to the "to-index-list", so for a workflow item this would be: item, workflow item, pooled task, ...
* it would then pass these objects one by one to the discovery service doing a single commit for each of them. This would lead to X number of additional commits to the solr which was slowing the whole thing down.

What we did to fix it:
* All the objects are still added to the "to-index-list"
* We still pass each object to the discovery service but do not trigger a commit at the end
* We trigger a single commit at the end of the consumer when we are done looping over all the objects

The fix here has the initial benefit if multiple items are deposited at a single context.commit that there will now only be one commit instead of a single commit for every item. So the general performance of DSpace should also be better.

Ps: The timing for the travis could still be a bit longer then it was before the IndexableObject merge, but this is because the API tests have increased from 815 to 833

### CODE REVIEW

**Comment by mwoodiupui** [comment]
I like the approach.

In addition it made me think once again that later we may wish to re-examine our Solr commit strategies throughout the code.  The Solr maintainers hold that one should be biased in favor of relying on auto-commit rather than explicit commits in most cases.  A shorter auto-commit interval (seconds, not minutes) together with a reasonable limit on uncommitted work would keep the system lively and still do a good job of aggregating commitment.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @KevinVdV for tracking this one down.  The problem & the resolution here make sense to me and the code is straightforward. Travis also shows the build to be significantly faster than current `master` (by 15-20mins)

(As a sidenote, I agree with @mwoodiupui 's comments above. Ideally we'll find some time in the future to reexamine how we are interacting with Solr and perhaps move more towards the recommended auto-commit approach. However, that is *not* necessary for this PR nor for DSpace 7 release, and this PR solves the main issue of committing to frequently.)

**Comment by tdonohue** [comment]
Merging this PR as it has approval by @mwoodiupui and I, and it also helps to unblock other PRs which are bumping up against the Travis build time limit.  Thanks again @KevinVdV

**Review by mwoodiupui — APPROVED** [review]
+1 by inspection

**Pull request merged**
