### PR TITLE
DS-2608: Improve collections and communities metadata in XMLUI discovery results

### PR DESCRIPTION
**Pull request by nicolasschwab**
https://jira.duraspace.org/browse/DS-2608
When discovery returns collections and communities it will generates every metadata the collection/community has. 
I also have merged the three renders: item,collection,community into one generic render

### CODE REVIEW

**Comment by tdonohue** [comment]
Thanks @nicolasschwab!

The change sounds reasonable. There's a lot of code moving around here, so we'll need to find a tester on our end to verify things, but it seems promising.

**Comment by nicolasschwab** [comment]
Hi Tim, i have done a successfully rebase, so the merge conflict is solved

**Comment by tdonohue** [comment]
The code looks reasonable to me, passes a code review. This is just waiting on a tester (or two) to verify that the refactored code works the same as the old code.

**Comment by helix84** [comment]
Could we rename genericRender() -> renderDSO()? I feel like I wouldn't know what it's about if I randomly encountered the former.

**Comment by nicolasschwab** [comment]
Hi @helix84,
We can rename it, there is no problem. I would be making a new commit with you as the author.
Cheers

**Comment by hardyoyo** [comment]
Compiles and deploys in Vagrant-DSpace, XMLUI works as expected. I still need to verify that a new metadata field for a collection or community DSO makes its way to the DRI.

**Comment by hardyoyo** [comment]
I have to admit, I can't seem to find a quick way to add a metadata field to a collection or community. As I said before, it does look like the refactoring was successful, so, +1 just based on that.

**Comment by hardyoyo** [comment]
Here's a quick and dirty way to add a subject to a collection DSO (I ran the psql client in my Vagrant-DSpace environment): insert into metadatavalue (metadata_field_id, text_value, text_lang, place, confidence, dspace_object_id) values (63, 'Stuff', 'en_US', 1, -1, '95f833e1-6727-43b4-b8fe-6552cb5a6aef');

**Comment by hardyoyo** [comment]
I have to admit defeat, I've added a new metadatavalue for a collection DSO, have refreshed the Discovery index, and I still can't see any sign of the metadata in the DRI of the collection page. Am I just misunderstanding this patch? I'm looking for suggestions on how to test.

**Comment by nicolasschwab** [comment]
Hi @hardyoyo, thanks for your time and testing the PR.
I've tested my PR again by adding a new metadatavalue for a collection DSO, re-index solr core, and discovery results reflects the new metadata as expected. 
If you are expecting to get the new metadatavalue in collection DSO page, please note this is not what I am trying to achieve. My PR only extends metadata for discovery results, so it has no influence in the collection DSO page. 
Nevertheless I can confirm that the new metadatavalue does not appear in collection DSO' mets.xml. I think this is wrong and that it might be a bug in mets.xml generator.
In addition I've also fixed a little bug in my code, when checking for communities with no parents.
Please let me know if I misunderstood you. 
Cheers

**Comment by hardyoyo** [comment]
Hi, I'd love some advice on how to test this, if you can spare the time. Thanks!

**Comment by nicolasschwab** [comment]
Hi, to test you can:
1-insert a new metadata in the metadatavalue table for a given collection named x with handle h.
2-re-index discovery (./dspace index-dicovery -bos)
3-search for x in discovery and check the collection appears among the results
4-check the dri of discovery result page look for the new metadata in /document/body/div/div/list/list[n="comm-coll-result-list"]/list[n="123456789/h:collection"].

Please let me know for any inconvenient
Cheers

**Comment by hardyoyo** [comment]
Hi, I've tried following your suggestion, running the following SQL in the psql client in Vagrant-DSpace:

insert into metadatavalue (metadata_field_id, text_value, text_lang, place, confidence, dspace_object_id) values (63, 'Dolor', 'en_US', 1, -1, '95f833e1-6727-43b4-b8fe-6552cb5a6aef');

That's a new "subject" of "Dolor" for the collection that matches the UUID 95f833e1-6727-43b4-b8fe-6552cb5a6aef. I then run bin/dspace index-discovery -bos, and search for "Dolor" but I don't see a collection in my search results.

**Comment by nicolasschwab** [comment]
Hi,
In order to find your collection between discovery results you should search for the collection's name. Looking for its subject won't work (at least in a default discovery configuration). 
For example, I have a collection named "Artículos y presentaciones en Congresos" so the discovery search URL is http://digital.cic.gba.gob.ar/discover?scope=%2F&query=Art%C3%ADculos+y+presentaciones+en+Congresos&submit=Go
If you look at discovery results page's DRI you will find some elements about the new metadata. In my case, I' ve added a subject with value "Something". See http://digital.cic.gba.gob.ar/discover?scope=%2F&query=Art%C3%ADculos+y+presentaciones+en+Congresos&submit=Go&XML 
```xml
<list id="aspect.discovery.SimpleSearch.list.123456789/263:collection" n="123456789/263:collection">
      <list id="aspect.discovery.SimpleSearch.list.123456789/263:dc.subject.other" n="123456789/263:dc.subject.other">
              <item>Something</item>
       </list>
       ...
</list>
```
Regards

**Comment by hardyoyo** [comment]
Aha, there they are, thanks!

<list id="aspect.discovery.SimpleSearch.list.10673/2:dc.subject" n="10673/2:dc.subject"><item>Stuff</item></list><list id="aspect.discovery.SimpleSearch.list.10673/2:dc.subject" n="10673/2:dc.subject"><item>Stuff</item></list><list id="aspect.discovery.SimpleSearch.list.10673/2:dc.subject" n="10673/2:dc.subject"><item>Dolor</item></list>

+1 working as advertised, it will be cool to see what we can do with this capability.

**Comment by nicolasschwab** [comment]
Hi,
After analyzing this PR and reading Hardyoyo comments, we've realized that some things would be improved and corrected. Up to this point, this PR allows any metadata for communities and collections in discovery, but it should allow any metadata for any kind of DSO. 
 
To do this I propose to create a renderDSO template method with generic behavior for all DSO, and let renderItem,renderCollection and renderCommunity methods for specific behavior for each type of DSO. 
This micro-refactoring will support the inclusion of other DSOs among discovery results, something not used right now but very probable in near future. For example, search index could have indexed also bundles and bitstreams.
 
I've created a new branch in https://github.com/sedici/DSpace/tree/refactoring-proposal-DS-2608 so you can see the new code and compare against this PR changeset.  Let me know if you agree with these new changes so I add them in this PR.

I apologize for this double proposal but I think this new changeset is more simple, concise, and generic.

Regards

**Comment by tdonohue** [comment]
@nicolasschwab : I'd recommend updating this PR, or closing it in favor of your new version/branch (and creating a new PR). That'd likely simplify our testing on our end, etc.

**Comment by nicolasschwab** [comment]
Hi, 
Following Tims suggestion I've created a new PR https://github.com/DSpace/DSpace/pull/1353 and will close this PR.
Regards

**Pull request closed without merging**
