### PR TITLE
DS-3095: Remove Sonatype's oss-parent from our parent POM

### PR DESCRIPTION
**Pull request by tdonohue**
This is an initial PR for
https://jira.duraspace.org/browse/DS-3095

_NOTE: This PR will not work for Java 8 because of [DS-3154](https://jira.duraspace.org/browse/DS-3154)._

This is a MAJOR refactor / rework of our Parent POM (including fixing all alignment). A few key notes:
- Follows Sonatype recommendations at http://central.sonatype.org/pages/apache-maven.html
- When using a local Maven `settings.xml`, you now need to specify a username/password for a `ossrh` server (which is the recommended name from Sonatype). This is different from our current Release Procedure which shows a sample `settings.xml` using username/password combos for `sonatype-nexus-*` servers. See https://wiki.duraspace.org/display/DSPACE/Release+Procedure#ReleaseProcedure-UpdateMavensettings.xml
- Enhanced comments in this Parent POM and fixed alignment of tags (which is why the diff is so large)
- Fixed all mailing list links (still pointed at SourceForge lists)
- Removed outdated list of contributors / developers. That is managed on our Wiki anyways.

Overall, this _should_ work for Java 7 (untested). However, I'm working on also fixing DS-3154 so that this will work for Java 8 as well.

### CODE REVIEW

**Comment by tdonohue** [comment]
@pnbecker : would you be interested in testing this with Java 7 (since you rediscovered this issue during the RC1 release)? As noted above, I think this should work fine for Java 7 releases. But, it doesn't provide the full fix for Java 8 (as the bigger problem there is JavaDocs issues).

**Comment by pnbecker** [comment]
@tdonohue I ran without any problems the following commands:
```
mvn install -Dmirage2.on=true
mvn clean verify -Dthird.party.licenses=tru
git checkout .
mvn release:prepare -DdryRun=true
mvn release:perform -DdryRun=true
```
Then I noticed that I'm currently using Java 8 as I made a dist upgrade after releasing 6.0-rc1. I have several servers still runing java 7 and will rerun the tests there now, but I don't expect any problems.

**Comment by pnbecker** [comment]
@tdonohue except the verify step I ran the three other steps without any problems using Java 7. Doing so I noticed, that I wasn't ask about my GPG key passphrase when I tested with Java 8 and that the Java 7 run took significant longer then my tests with Java 8 (nevertheless both tests were running on different hardware).

So with Java 7 all seems to be fine, with Java 8 it would be worth investigating why maven didn't try to sign the packages.

**Comment by tdonohue** [comment]
Thanks @pnbecker!  To me, that sounds like a good, basic verification test. As noted via IRC yesterday, the only way to fully test this is to do a real release (RC2 or similar). 

I think this sounds like it's working enough to merge. If we run into further issues with the next release, I'd gladly help debug them.

**Comment by pnbecker** [comment]
@tdonohue @mwoodiupui and I discussed this today in #dspace and decided to merge this as it is.

**Pull request merged**
