### PR TITLE
[DS-3246] Improve cleanup in recyclable components

### PR DESCRIPTION
**Pull request by aschweer**
https://jira.duraspace.org/browse/DS-3246

### CODE REVIEW

**Comment by hardyoyo** [comment]
I'll test this this week, I like memory fixes!

**Comment by hardyoyo** [comment]
+1 tested on Vagrant-DSpace, everything is still working, and the XMLUI memory utilization (viewed using Psi Probe) does seem better. I'm glad to hear this is doing well in production, and I'm overjoyed to see a related PR for 5x, I'll test that next.

**Comment by tdonohue** [comment]
+1 via code review. All the code changes make good sense and are obviously cleanup tasks or avoidance of NPEs.

**Comment by tdonohue** [comment]
Approved during backlog hour today, and already at +2. Merging.

**Pull request merged**
