### PR TITLE
DS-3858 add HttpRequestRetryHandler to DataCiteCon

### PR DESCRIPTION
**Pull request by ssolim**
https://jira.duraspace.org/browse/DS-3858

### CODE REVIEW

**Review by pnbecker — CHANGES_REQUESTED** [review]
Hi @ssolim,

thank you for the Pull-Request. DataCite's test systems has some problems today, which make it hard to test this PR. So I tested it against the production system using the test Prefix 10.5072 (this was not possible in earlier versions of DSpace, but works since DSpace 6).

I like your changes as they make the DataCiteConnector a bit more reliable. Unfortunately the way we construct the DefaultHttpClient is deprecated. I added some more changes and will create a PR against you feature branch. Please consider them.

Could you please also squash your two commits into one? Your second commit misses the issue number (DS-3858) and there is no need for two commits here.

Thanks for pulling our attention to this and helping out with code!

**Comment by pnbecker** [comment]
@ssolim Sorry, I'm unable to create a PR against your repository as github doesn't see it as official fork of DSpace. Could you please cherry-pick my latest commit from [here](https://github.com/the-library-code/DSpace/tree/DS-3858)?

**Review by pnbecker — APPROVED** [review]

**Comment by pnbecker** [comment]
The changes I requested were fulfilled. +1
I tested this code quite well, would be great if it could be included into 6.3 and cherry-picked to master. @terrywbrady, @kshepherd could you please give it another short review?

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me. Haven't tested, but the code looks correct.

**Pull request merged**
