### PR TITLE
[DS-2951] Honour proxy setting when looking up CC licence

### PR DESCRIPTION
**Pull request by aschweer**

### CODE REVIEW

**Comment by aschweer** [comment]
Re-based version of #1217

**Comment by aschweer** [comment]
Actually, I'm not sure this is needed any longer -- CreativeCommonsServiceImpl also sets the proxy host / port system properties.

**Comment by pnbecker** [comment]
@aschweer I'm afraid we broke this PR by merging #1526. Can you please rebase it?

**Comment by aschweer** [comment]
Rebased on master but not tested

**Review by tdonohue — CHANGES_REQUESTED** [review]
I lean towards closing this ticket, as I don't think it is needed.

As @aschweer notes, the proxy is already being set in the `CreativeCommonsServiceImpl` class: https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/license/CreativeCommonsServiceImpl.java#L100

As that class is the one contacting the CC API, it seems the more appropriate place for the Proxy to be used. I don't see why we need it duplicated into `CCLookup`

**Comment by tdonohue** [comment]
Closing this PR for reasons mentioned above. If the existing proxy settings aren't working, we should create a new PR to fix the code in CreativeCommonsSerivceImpl: https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/license/CreativeCommonsServiceImpl.java#L100

**Pull request closed without merging**
