### PR TITLE
Configurable workflow: Enable workflow item deletion without publishing it (DS-3926)

### PR DESCRIPTION
**Pull request by santit96**
The whole issue is described here:
https://jira.duraspace.org/browse/DS-3926

### CODE REVIEW

**Comment by J4bbi** [comment]
Closing and opening to restart tests

**Comment by J4bbi** [comment]
@santit96, it's been a while since you submitted, but a belated thanks for the pr

I am having some difficulty actually testing the functionality described, I haven't used the workflow process very much

could you explain how to use the described feature in this PR?

**Comment by J4bbi** [comment]
Thanks @santit96 

I don't know why but I don't get that option, I am pretty sure I have done everything correctly, I am building your branch with the two commits and using docker-compose.

image

these are the only, and standard options I get.

Is it possible this branch is missing a commit?

**Comment by J4bbi** [comment]
@santit96  should there perhaps be something in either

https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-xmlui/src/main/resources/aspects/Workflow/workflow.js

or

https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-xmlui/src/main/resources/aspects/XMLWorkflow/xmlworkflow.js

?

**Comment by J4bbi** [comment]
Or possibly, rather

https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/workflow/PerformTaskStep.java

**Comment by santit96** [comment]
@J4bbi I'm pretty sure that i have pushed all the commits, but i made this PR long ago so i'll check just in case!

**Comment by J4bbi** [comment]
@santit96, can you also confirm if this PR is intended for configurable xmlworkflow or the basic workflow?

see: https://wiki.lyrasis.org/display/DSDOC6x/Configurable+Workflow

**Comment by santit96** [comment]
It is for configurable xmlworkflow

**Comment by santit96** [comment]
I checked the feature again with the branch of this PR (also checked that i have the same commits this PR has), and everything works fine for me. I seems to me that there is a permissions issue. Perhaps the problem is that the the group assigned to WF2 Accept/Reject/Edit Metadata Step does not have DELETE permissions over the items, you can try giving DELETE permissions over the collection to that particular admin.

**Comment by tdonohue** [comment]
@santit96 and @J4bbi :  I'd recommend this PR be updated to go against `main` and DSpace 7.x.  It looks, to me, like it's adding a new feature to Configurable Workflow (the ability to delete a workflowitem while it's in workflow) and XMLUI.  Since this feature doesn't exist in DSpace 7.0, adding it into 6.x this late is potentially problematic unless it's also added to 7.x.

Therefore, I'd like to ask that you consider adding this into 7.x instead of 6.x.  In the 7.0 platform, it is possible for Administrators in the system to delete any item in Workflow (which would solve the DS-3926 ticket in a different manner).  But, I don't believe it's possible yet for reviewers to delete items currently in workflow.

**Pull request closed without merging**
