### PR TITLE
DS-4006: Embed membership groups on EPerson REST object

### PR DESCRIPTION
**Pull request by tomdesair**
This is a fix for https://jira.duraspace.org/browse/DS-4006. This also relates to https://github.com/DSpace/dspace-angular/issues/292.

This is still work in-progress as there still seem to be some issues with the link values. But some early testing can already be done.

### CODE REVIEW

**Comment by tomdesair** [comment]
The relations section looks good after all. So this is ready for review and testing.

**Review by tdonohue — APPROVED** [review]
👍 The number of actual code changes is rather small here, and there's a good number of new/updated ITs.

Before merging though, I think this could use a test from someone on the Angular team (fyi @artlowel), to ensure it helps resolve (or get closer to resolving) the issues that were also reported in https://github.com/DSpace/dspace-angular/issues/292

**Comment by LotteHofstede** [comment]
I tested your PR with our current master to see if DSpace/dspace-angular#292 has been resolved. Unfortunately there's still an issue with parsing the `Groups`. Not just `EPersons` have embedded `Groups`, but `Groups` themselves also have embedded `Groups`. These last ones are not part of the `_links` section of `Groups` yet, which results in the same issues in the frontend as before.

**Comment by tomdesair** [comment]
Hi @LotteHofstede, I've added specifc checks that test your requirement, see [the changes in GroupMatcher](https://github.com/DSpace/DSpace/pull/2216/commits/0961c5040d6af3908dd03f5095ce8865ff2109a5#diff-4dc40eef9f76ea4d7d33c02e9c6b939f)

It seems that your issue is fixed now. Can you please retest to see if this fixes the problems you encountered on the Angular side?

**Comment by tomdesair** [comment]
Hi @LotteHofstede, did you already have some time to look at this?

**Comment by LotteHofstede** [comment]
Hey @tomdesair
I had tested your changes against the UI last month, but because I ran into some issues forgot about it. After testing it a second time, I found out the remaining issue lies in the Angular frontend, not in your PR.
@tdonohue, I will create a PR with some small fixes on the Angular side to make sure users can log in properly when this PR is merged. I would suggest to merge both PRs simultaneously to make sure everything still works as expected.

**Review by paulo-graca — APPROVED** [review]
This PR is a dependency for https://github.com/DSpace/dspace-angular/pull/385. I did some testing and the code looks good to me. Thank you @tomdesair !

**Review by tdonohue — APPROVED** [review]
Code looks good to me. Did some light testing with this and https://github.com/DSpace/dspace-angular/pull/385 together, and they seem to work great. Merging both, as this means they are both at +2

**Pull request merged**
