### PR TITLE
Fix PATCH of resource policy end date when start date is null

### LINKED ISSUE #8239: The replace of the end date of a resource policy fails if the start date is null
Patching a resource policy to replace the end date fails if the start date is not set.
To verify this incorrect behavior you can:

- log in as administrator
- go to the page of an item and open the edit/authorizations section
- try to modify a resource policy replacing (not just adding) an end date when the start date is not present
- the system reports that the operation was successful but an error 500 occurs

**Expected behavior**
The end date must be updated even if the start date is not set.

### PR DESCRIPTION
**Pull request by tdonohue**
## References
* Fixes #8239

## Description
Fixes a tiny, obvious typo which causes the issue described in #8239.  Code should check if **StartDate** is not null before validating with StartDate.

### CODE REVIEW

**Comment by tdonohue** [comment]
@LucaGiamminonni : Assigning you as a reviewer to this small PR as you reported the bug.

**Review by LucaGiamminonni — APPROVED** [review]
Hi @tdonohue, the modification seems ok to me. Wouldn't it be worth adding a test?

**Comment by tdonohue** [comment]
@LucaGiamminonni : Good for pointing out the test here.  After more closely looking at `ResourcePolicyRestRepositoryIT`, I discovered that, while we test replacing the *start date*, we were missing a test for replacing the *end date*.  I've added that test just now in https://github.com/DSpace/DSpace/pull/8240/commits/527f5eea2af41f7979202309c8388213a9773ac8 (and also fixed some typos in test method names).

I've verified this newly added test *fails* on `main`, throwing a 500 exception, just like in #8239.  But, the tiny fix to `ResourcePolicyUtils` fixes that exception.

Even though you've approved this, could you take a glance at the new test & make sure it all looks good?

**Comment by tdonohue** [comment]
@LucaGiamminonni : Good for pointing out the test here.  After more closely looking at `ResourcePolicyRestRepositoryIT`, I discovered that, while we test replacing the *start date*, we were missing a test for replacing the *end date*.  I've added that test just now in https://github.com/DSpace/DSpace/pull/8240/commits/527f5eea2af41f7979202309c8388213a9773ac8 (and also fixed some typos in test method names).

I've verified this newly added test *fails* on `main`, throwing a 500 exception, just like in #8239.  But, the tiny fix to `ResourcePolicyUtils` fixes that exception.

Even though you've approved this, could you take a glance at the new test & make sure it all looks good?

**Review by LucaGiamminonni — APPROVED** [review]
Hi @tdonohue, it's all ok for me, thanks.

**Comment by tdonohue** [comment]
Merging with +1, as this was flagged for 1 approval.

**Pull request merged**
