### PR TITLE
DS-4587: update spider user agent file for more accurate Solr usage statistics

### LINKED ISSUE #7920: [DS-4587] DSpace's built-in list of spider/robot user agents is old
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4587">[DS-4587]</a> created by aorth</i>
<p>DSpace's built-in spider user agents file has not been updated since 2015. This file contains regular expressions matching user agents of common spider (non-human) clients. When a usage event (item view, download, search, etc) is received from one of these clients Solr does not log a statistics hit, which improves the accuracy of the usage statistics.</p>

<p>The <a href="https://github.com/atmire/COUNTER-Robots" class="external-link" target="_blank" rel="nofollow noopener">COUNTER-Robots</a> project maintains a large, up-to-date list of spider user agents curated by a community of website admins. DSpace can use their list without modification (we have been using it in production on our site for years already).</p>

### PR DESCRIPTION
**Pull request by alanorth**
This updates the included spider user agent file to the latest from the COUNTER-Robots project. DSpace's own copy is over five years old and is missing a bunch of new patterns, which greatly decreases the accuracy of the Solr usage statistics.

A similarly trivial change could be made in 4.x and probably 7.x.

See: https://jira.lyrasis.org/browse/DS-4587
See: https://github.com/atmire/COUNTER-Robots/releases/tag/2021-07-05

### CODE REVIEW

**Review by J4bbi — APPROVED** [review]
After a slack conversation I quickly eyeballed this PR and approved.

**Review by J4bbi — COMMENTED** [review]
Failing test

**Comment by alanorth** [comment]
@J4bbi hmm, that's unfortunate. The test is incorrect because it is using the literal string `Firefox` as a user agent, which has never, ever been used by the Firefox browser. So this test matches the following pattern in the updated bot list:

```console
^firefox$
```
I filed [an issue (DS-4588)](https://jira.lyrasis.org/browse/DS-4588) for the test and now I will make a pull request to fix it.

**Comment by J4bbi** [comment]
Closing and reopening to ensure tests pass

**Comment by tdonohue** [comment]
@alanorth or @J4bbi : Could this be ported to `main` for 7.x?  It appears it was only applied to 6.x but this config also exists in 7.x

**Comment by tdonohue** [comment]
@alanorth : If you have the time/willingness, I'd prefer it if you just create a PR to port these features to `main`.  No new ticket is needed.  Feel free to assign me as the reviewer, as these sorts of ports can be quickly reviewed & merged -- primarily you just need to make sure it aligns with the DSpace 7+ code styles & doesn't end up breaking any existing tests.  (For both of these PRs you are talking about, I don't think it'll be a problem at all)

**Comment by alanorth** [comment]
@tdonohue ported this to `main` for DSpace 7.1: https://github.com/DSpace/DSpace/pull/7931. Cheers!

**Pull request merged**
