### PR TITLE
DS-2547: Adds a label to access restricted bitstreams in JSPUI.

### PR DESCRIPTION
**Pull request by pnbecker**
https://jira.duraspace.org/browse/DS-2547

This feature is configurable (using configuration property webui.itemdisplay.label.restricted.bitstreams).

### CODE REVIEW

**Comment by pnbecker** [comment]
This PR seems to be bigger than it is, caused by a change of indentation.

**Comment by pnbecker** [comment]
I enhanced and rebased this PR today.

**Comment by pnbecker** [comment]
Ready for review again.

**Comment by pnbecker** [comment]
rebased to resolve merge conflict.

**Comment by helix84** [comment]
+1, tested (shows label for restricted, doesn't show it for accessible bitstreams)

**Comment by tdonohue** [comment]
Code looks reasonable to me. I think this looks ready to go. +1

**Pull request merged**
