### PR TITLE
Browse by Controlled Vocabulary (hierarchicalBrowse)

### PR DESCRIPTION
**Pull request by MarieVerdonck**
## References
* Related to contract PR: https://github.com/DSpace/RestContract/pull/225
* Related Angular PR: https://github.com/DSpace/dspace-angular/pull/2215

## Description
Includes controlled vocabularies in the browse endpoints.

## Instructions for Reviewers
`/api/discover/browses/srsc` => contains a hierarchical browse for srsc vocabulary (includes link to vocabulary, metadata fields for which vocabulary is configured in input forms & facet which indexes these metadata fields)
**ToDo**: include in `/api/discover/browses`

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ ] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@MarieVerdonck and @benbosman : Is this in a reviewable state yet (it is still in "Draft" status, but not sure if that's accidental)?  Our review deadline is this coming Friday (May 25), so we need this PR and the REST Contract PR (https://github.com/DSpace/RestContract/pull/225) to be in a reviewable state as soon as possible so that we can get reviewers working on them this week.  Thanks.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@MarieVerdonck : Overall this works & looks good.  However, I find it odd that the new `browseType: hierarchicalBrowse` returns `_links` which are invalid for it's type.  For instance, I see this when I go to `/server/api/discover/browses/srsc`

invalid-links

It seems like, for each type of browse, we should **only return valid _links** (ideally for all `browseType` values.. i.e. if easy to do, we should make sure the list & flat types also only return valid links).  There's no reason to send the client (i.e. our UI) links that will never work.  As documented in the REST Contract PR, `/srsc/items` and `/srsc/entries` are invalid for `hierarchicalBrowse`.  And if I click on either in the Hal browser, I get a `400 Bad Request` error.

**UPDATE:** Because of these invalid `_links`, I'm also noticing that a number of errors appear in the Chrome DevTools Console when using the new UI PR (https://github.com/DSpace/dspace-angular/pull/2215/) as it appears the UI is trying to "follow" the invalid links.

* For instance, when using "Browse by Author" (or Browse by Subject) from the UI, I see this 500 error in the DevTools Console:
  ```
  GET http://localhost:8080/server/api/discover/browses/author/items?sort=default,ASC&page=0&size=20&embed=thumbnail 500
  ```
    * The reason is that the "author" browse is a `valueList` and a `valueList` doesn't support `/items`.  So, `/author/items` is invalid, but the UI still tries to use it. This same error occurs for "subject" browse as it's another `valueList`.
* Similarly, when using "Browse by Title" from the UI, I see this 500 error:
  ```
  GET http://localhost:8080/server/api/discover/browses/title/entries?sort=default,ASC&page=0&size=20 500
  ```
    * The reason is that the "title" browse is a `flatBrowse` and a `flatBrowse` doesn't support `/entries`.  So, `/title/entries` is invalid, but the UI still tries to use it.  This same error occurs for "dateissued" browse as it's another `flatBrowse`.

Beyond that, the code here looks good overall & it appears to work (based on initial testing with the frontend PR).  It'd just be good to ensure our REST response is always sending valid `_links`.

**Comment by benbosman** [comment]
@tdonohue I'm not sure if my feedback in https://github.com/DSpace/RestContract/pull/225/commits/0cd0ea04991f3c546175b97ea1d8f6210927f119 was clear
The links section has always included links which are not valid, depending on the type. There's always only one link that's functional
That design has not been altered

**Comment by tdonohue** [comment]
Per discussion in today's DevMtg, I'm moving the design flaw that I reported to a separate ticket.  It is an existing design flaw in this area of the REST API.  I'd love to see it fixed, as it results in unnecessary, failing requests from the UI to the REST API... but it's not unique to this PR, so we'll treat it as a separate issue.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @MarieVerdonck and @benbosman .  Re-tested today with the frontend PR.  This is working as designed.  Code looks good too.  

It looks ready to merge as soon as the minor issues reported in the frontend PR are resolved (the remaining issues appear to be in the UI code though)

**Pull request merged**
