### PR TITLE
CitationPage curation task mess the bitstream policies

### PR DESCRIPTION
**Pull request by abollini**
https://jira.lyrasis.org/browse/DS-4415
Fixes #7753

### CODE REVIEW

**Review by nwoodward — CHANGES_REQUESTED** [review]
Some cosmetic changes, but I've tested and it works as described.

**Comment by tdonohue** [comment]
@abollini : This looks to minimally need minor cleanup if it should still be considered for 6.4.  We could also consider just resubmitting this to `main` instead... it seems like a worthwhile fix to get into 7.x at the minimum.

**Comment by abollini** [comment]
hi @tdonohue  I have done the cleanups requested by @mwoodiupui

**Comment by tdonohue** [comment]
@abollini : I'd recommend moving this PR to 7.x (`main`).  I don't have anyone available to help test additional PRs for 6.4 at this time (unless someone steps forward quickly).  The 6.4 release is nearly "wrapped up" and we aren't really looking to add more PRs to the list to merge.

**Pull request closed without merging**
