### PR TITLE
[DS-3775] Hibernate session bug when submitting item with Versioning enabled

### PR DESCRIPTION
**Pull request by jsavell**
https://jira.duraspace.org/browse/DS-3775

### CODE REVIEW

**Review by tomdesair — CHANGES_REQUESTED** [review]
Thanks for the PR @jsavell! This week we encountered a similar issues but in another part of the code.

The root cause of the problem seems to be the `HandleUtil.obtainHandle` method that retrieves an internally cached version of a DSO. This DSO is potentially detached if a commit happened before.

Do you agree that it would be better to move the `context.reloadEntity(dso)` call to the `return` statement in `HandleUtil.obtainHandle` method? That would fix this issue also in other places.

**Comment by jsavell** [comment]
That sounds great.

I'm on vacation right now, but will update the PR within a few days.

**Comment by jsavell** [comment]
@tomdesair The reloadEntity call has been moved to HandleUtil as requested.

**Review by tomdesair — APPROVED** [review]

**Comment by tomdesair** [comment]
Thanks @jsavell ! That will also prevent future issues with the `HandleUtil.obtainHandle` method.

**Review by tdonohue — APPROVED** [review]
👍 Haven't tested, but this fix seems quite in line with other `reloadEntity()` fixes applied in 6.1 and 6.2.  So, the code looks good to me.

**Review by terrywbrady — APPROVED** [review]
Tested locally and verified the fix.  @jsavell , thanks for the good instructions for re-creating the issue.

**Pull request merged**
