### PR TITLE
Multiple import source (e.g. DOI -> Crossref, DataCite)

### LINKED ISSUE #8674: Combine multiple import sources (Crossref + DataCite -> DOI)
**Is your feature request related to a problem? Please describe.**
Users generally don't know which source (DataCite or Crossref) to use for DOIs. Similar concerns apply to ISBNs (#8673).

(Sorry if we've missed a more obvious way of doing this...)

**Describe the solution you'd like**
It would be nice if we could enter a DOI and retrieve results from all potentially relevant sources.

**Describe alternatives or workarounds you've considered**
* asking the user to try both providers: not workable for more than two or three sources/identifier
* querying all sources (rather than the relevant ones): false positives, DoS

**Additional context**
* we have some code for the DOI case, but (as usual) it needs work

### PR DESCRIPTION
**Pull request by philipprumpf**
This is what the University of Bamberg uses (https://fis.uni-bamberg.de) to look up DOIs specified by the user for import in both the Crossref registry and the DataCite registry, in parallel. Other institutions have expressed an interest in it (@pnbecker) so it's probably best put here. No specific tests yet.

This source can be specified just once, replacing the Crossref and DataCite sources by a single entry.

Code mostly by @johannastaudinger.

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #8674
* Related to DSpace/RestContract#`pr-number`  (if a corresponding REST Contract PR exists)

## Description
Adds a new external source which can be configured to query multiple existing sources simultaneously, returning results from either.

## Instructions for Reviewers
This is currently in draft state: no specific tests yet.

List of changes in this PR:
* the main code: `MultipleParallelImportMetadataSourceServiceImpl.java`
* configuration examples for the DOI use case

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ ] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@philipprumpf : Thanks! Pulling this over to the 8.0 board for more eyes, as it's definitely a new feature.  Could you please add some steps on how to manually verify this is working?  I'm assuming maybe importing via DOI suddenly searches two locations?  

If it's easier to show via screenshots, that's good too.  I know it's likely that our testers/reviewers will need more info on how the behavior changes with this PR installed.

**Comment by pnbecker** [comment]
@philipprumpf is this related to #8674?

**Comment by philipprumpf** [comment]
Screenshots from https://github.com/philipprumpf/DSpace/tree/pr-9132 , which is this PR + #9203 .

How this is supposed to work is that a new import source shows up which is currently unlabelled but should probably be labelled "DOI" in practice:

image

Entering a Crossref DOI yields a result:

image

Entering a DataCite DOI yields a result:

image

Nonsense yields no results:

image

This is in contrast to the individual Crossref / DataCite sources, which return results only for their respective DOIs.

**Review by tdonohue — COMMENTED** [review]
@philipprumpf : Thanks for sharing this!  I gave it a review/test today.  Overall, it appears to work well.  DOIs resolve properly and appear to be querying both services.  I can also search by keyterms as well (e.g. typing "Science" works too).

This definitely seems to be an improvement overall for a generic DOI search where you don't know which service to use.

It also can be useful for keyterm searches...but I found that in this scenario it appears that you'll always find *everything from* CrossRef **first** then everything from DataCite (because CrossRef is listed first in the config).  So, these keyword searches are no longer ordered by relevance necessarily.  That might be the best we can do though, but I wanted to point it out.

One minor improvement is that we need to add a translation for the `submission.import-external.source.multiple` key (and any other similar keys), e.g.
missing-key

Ideally, we'd name this something like "DOI".  However, that might require not using the identifier `multiple`, as that's not specific enough.

Overall, this is great work.  I'm basically a +1 to this.  But, I suspect we need to update the configuration to allow for multiple configurations of `MultipleImportService`, each with it's own identifier...and this one should be specific to DOIs.

**Review by kshepherd — APPROVED** [review]
Thanks @philipprumpf  for this PR and sorry for my late review (a bit of confusion over two similarly named PRs!)
 
I am +1 pending the i18n label added. I agree that DOI searches tend to be the most consistent and accurate across all sources (even though some support keywords as noted by @tdonohue ) so giving that hint in the label is a good idea.

Note, searching for a full DOI URL doesn't give very good results compared to just the identifier string -- however, since this contribution does not concern itself with how each provider handles the queries and simply passes the query onto them, I think that is feedback for future improvements to the individual (DataCite, Crossref, etc) providers, not this PR.

**Comment by philipprumpf** [comment]
> Thanks @philipprumpf for this PR and sorry for my late review (a bit of confusion over two similarly named PRs!)
> 
> I am +1 pending the i18n label added. I agree that DOI searches tend to be the most consistent and accurate across all sources (even though some support keywords as noted by @tdonohue ) so giving that hint in the label is a good idea.
> 
> Note, searching for a full DOI URL doesn't give very good results compared to just the identifier string -- however, since this contribution does not concern itself with how each provider handles the queries and simply passes the query onto them, I think that is feedback for future improvements to the individual (DataCite, Crossref, etc) providers, not this PR.

Thank you @kshepherd and @tdonohue . I've got a local branch addressing Tim's comments, but had a hard time merging it yesterday. I'll have another go today.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @philipprumpf and @johannastaudinger !  This looks good to me now.  I re-tested it with the small PR for the frontend https://github.com/DSpace/dspace-angular/pull/2820

Merging immediately.  But, I'm also going to temporarily add the `needs documentation` flag until we can add basic docs about this new "DOI" external source to https://wiki.lyrasis.org/pages/viewpage.action?pageId=315720684

**Pull request merged**
