### PR TITLE
IIIF manifest and canvas cache eviction is asynchronous and could led to unexpected responses

### LINKED ISSUE #8243: IIIF manifest and canvas cache eviction is asynchronous and could led to unexpected responses
**Describe the bug**
While testing parallel builds on same machine (Bitbucket instance) we experienced systematic failures of following tests:
- IIIFControllerIT.findOneWithCacheEvictionAfterBitstreamUpdate
- IIIFControllerIT.findOneWithCacheEvictionAfterItemUpdate 

We suppose this can be done to an asynchronous cache eviction and invalitation. 

**To Reproduce**
1. configure a parallel execution of unit-tests and integration-tests builds on same machine (i.e. a bitbucket Pipeline)
2. run parallel builds

**Expected behavior**
Test passing

**Related work**
We (4Science) can look into this in order to have synchronous cache eviction, in 1 or 2 hours.
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by corrad82-4s**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #8243

## Description
Short summary of changes (1-2 sentences).
Used cache eviction or invalidation methods which guarantee synchronous execution.

List of changes in this PR:
* dspace-api/src/main/java/org/dspace/iiif/consumer/CanvasCacheEvictService.java evictSingleValue method uses evictIfPresent method for eviction
* dspace-api/src/main/java/org/dspace/iiif/consumer/ManifestsCacheEvictService.java evictSingleValue method uses evictIfPresent method for eviction
* dspace-api/src/main/java/org/dspace/iiif/consumer/ManifestsCacheEvictService.java evictAllCacheValues method uses invalidate method for eviction

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

The only evidence of impact of reported problem emerged during parallel builds on same machine. It is possible to run in parallel two or more builds and check that IIIFControllerIT.findOneWithCacheEvictionAfterBitstreamUpdate and IIIFControllerIT.findOneWithCacheEvictionAfterItemUpdate are not failing anymore.

## Checklist

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by tdonohue** [comment]
@mspalti : Would you be willing to give this a quick code review/test, as you wrote much of this IIIF code?

**Comment by mspalti** [comment]
@tdonohue,  sure,  I'm happy to review this.  I'll get to it soon.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @corrad82-4s .  The code here looks good to me. I gave it some light testing and noticed no behavior changes... but unfortunately, I'm not setup to try to reproduce the initial bug.

@mspalti : Just a reminder it'd be good to get your feedback here as you are most familiar with this code and might be able to immediately tell if these small changes could have ill effects.

**Review by mspalti — APPROVED** [review]
The changes here look good to me. The synchronous methods makes sense if they solve the build problem and the result should be the same either way. My quick tests verified that the cache eviction works as expected when I update item and bitstream metadata. Thanks for tracking this one down and fixing it!

**Pull request merged**
