### PR TITLE
Submission forms migration script

### LINKED ISSUE #2818: DS-4046: Provide a script to automatically migrate input-forms.xml to submission-forms.xml
This is a duplicate of [DS-4046](https://jira.lyrasis.org/browse/DS-4046)

Estimate from release plan: 22 hours
Expressing interest: none

Currently, estimate assumes we need to do this migration via Java code (Generate a submission form where each inputform step is mapped to a single panel. It includes also the generation of a new item-submissions where the single panel are listed).  However, we might be able to cut the effort in half if we can simply use an XSLT transformation (as both files are XML)

### PR DESCRIPTION
**Pull request by Raf-atmire**
## References
* Fixes https://github.com/DSpace/DSpace/issues/2818

## Description
This PR introduces a script that will parse `input-forms.xml` and `item-submission.xml` from DSpace <7 versions into the `submission-forms.xml` and `item-submission.xml` standard for DSpace 7.
This script can be called by using `submission-forms-migrate -s {path-to-config-dir}/item-submission.xml -f {path-to-config-dir}/input-forms.xml`
with the `path-to-config-dir` leading to the config dir for the DSpace <7 instance that you're looking to migrate.
The migrated xml files will be present in the DSpace's install dir in the config folder

## Instructions for Reviewers

List of changes in this PR:
* introduced a script to automatically migrate the old submission xml files to the new ones

How to test this PR:
* Setup this branch
* Call the script using {dspace.dir}/dspace submission-forms-migrate -s {path-to-config-dir}/item-submission.xml -f {path-to-config-dir}/input-forms.xml
* Verify that the new submission xml files are present in the {dspace.dir}/config directory

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@Raf-atmire : I gave this a try today, and ran into immediate problems.  My assumption was that I would be able to do the following:
1. Copy an old `input-forms.xml` and `item-submission.xml` from DSpace 6.x into my DSpace 7 config installation folder `[dspace]/config/`.  So, I literally just grabbed these two older files from this GitHub branch: https://github.com/DSpace/DSpace/tree/dspace-6_x/dspace/config
2. Run the script as you describe.
    ```
    cd [dspace]/bin/
    ./dspace submission-forms-migrate -s ../config/item-submission.xml -f ../config/input-forms.xml
    ```
3. However, I get errors immediately:
    ```
    The script has started
    Transforming ../config/input-forms.xml with xsl: /dspace/config/migration/submission-forms.xsl to output: /dspace/config/submission-forms.xml 
    (Location of error unknown)java.io.FileNotFoundException: /dspace/config/input-forms.dtd (No such file or directory)
    Transforming ../config/item-submission.xml with xsl: /dspace/config/migration/item-submissions.xsl to output: /dspace/config/item-submission.xml
    SystemId Unknown; Line #-1; Column #-1; Premature end of file.
    The script has completed
    ```
    
From what I can tell, it *looks like* the problem is that I copied these old files into my DSpace 7 config directory (which is what I expect most people will try to do), instead of pointing this script at an old DSpace 6 config folder (which is less likely, as you must require everyone to install DSpace 7 alongside DSpace 6).  Since I copied these two files over into DSpace 7, their old DTDs from DSpace 6 *do not exist* and cause issues when you attempt to validate the XMLs.

Is there a way we can turn off the DTD validation during this migration?  I haven't had a chance to look into it yet myself, but I'd hope it'd be possible.

Additionally, I notice this `submission-forms-migrate` is ALSO available from the Admin UI under the Processes UI (http://localhost:4000/processes/).  I think we should change this script to be CLI **only**, as I'm worried we'll see strange errors if the Submission configuration is changed while the REST API and Angular UI are running.  Ideally, it seems like this script should be a part of the Upgrade Procedure and therefore need only be run via CLI.

**Comment by mwoodiupui** [comment]
An alternative:  pack copies of the old DTDs into the dspace-api JAR as resources and fetch them from there.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@Raf-atmire and @MarieVerdonck : I've retested this today, and while it's slightly better, it's still not fully working based on the process I [described above](https://github.com/DSpace/DSpace/pull/3076#pullrequestreview-553852079).

If I do these steps exactly, I end up with an empty `item-submission.xml` (though the `input-forms.xml` -> `submission-forms.xml` transformation appears to work):
1. Copy an old `input-forms.xml` and `item-submission.xml` from DSpace 6.x into my DSpace 7 config installation folder `[dspace]/config/`.  So, I literally just grabbed these two older files from this GitHub branch: https://github.com/DSpace/DSpace/tree/dspace-6_x/dspace/config
2. Run the script as you describe.
    ```
    cd [dspace]/bin/
    ./dspace submission-forms-migrate -s ../config/item-submission.xml -f ../config/input-forms.xml
    ```
3. Here's the new output:
    ```
    The script has started
    Transforming ../config/input-forms.xml with xsl: /dspace/config/migration/submission-forms.xsl to output: /dspace/config/submission-forms.xml
    Transforming ../config/item-submission.xml with xsl: /dspace/config/migration/item-submissions.xsl to output: /dspace/config/item-submission.xml
    SystemId Unknown; Line #-1; Column #-1; Premature end of file.
    The script has completed
    ```

I believe the issue is that the DSpace 7.x `item-submission.dtd` is still being loaded by the DSpace 6.x `item-submission.xml` when I attempt to transform it.  This results in the `Premature end of file` error, and the empty result.  So, I believe the new approach you've taken here to create "dummy" DTDs isn't sufficient in this scenario, since there's two different versions of the `item-submission.dtd`...and by default the DSpace 7.x one will be used.

I've also tried this slightly different process (to attempt to avoid the above error). But, unfortunately, it still fails in a different manner:
1. Create a new (temporary) empty folder in your DSpace 7 instance.  For example `[dspace]/config/temp/`
2. Copy your DSpace 6 configs into that temp folder
3. Then, run the script against the configs in that temp folder
    ```
    cd [dspace]/bin/
    ./dspace submission-forms-migrate -s ../config/temp/item-submission.xml -f ../config/temp/input-forms.xml
    ```
4. In this scenario, I get a slightly different error:
    ```
    The script has started
    Transforming ../config/temp/input-forms.xml with xsl: /dspace/config/migration/submission-forms.xsl to output: /dspace/config/submission-forms.xml
    Transforming ../config/temp/item-submission.xml with xsl: /dspace/config/migration/item-submissions.xsl to output: /dspace/config/item-submission.xml
    file:/dspace/config/migration/item-submissions.xsl; Line #11; Column #74; Can not load requested doc: /dspace/config/config/temp/input-forms.xml (No such file or directory)
    The script has completed
    ```
    
Am I misunderstanding how this script is supposed to work?  I just cannot seem to get it to work.  Have you been able to get it to work locally?

I also admit that, when this script fails, it does so **destructively**.  It overwrites the default DSpace 7 `submission-forms.xml` and `item-submissions.xml` files with whatever the output file (even if that output is empty).  So, you are stuck either having the re-download the DSpace 7 configs, or trying again with your DSpace 6 ones.  It makes me wonder if we should be writing the output to a temporary file, which the admin can then verify before copying it over the DSpace 7 config (or moving individual sections over into the default DSpace 7 config).

**Comment by Raf-atmire** [comment]
@tdonohue Thank you for the feedback. I was able to reproduce the first error that you describe, however I'm currently unsure of how to approach this. Indeed if we're putting those DSpace 6 files in the config folder together with the DSpace 7 dtd files, it'll go wrong. Do you have a suggestion on how to implement a clean fix for this?
The second issue, with using a temp folder, is something I cannot reproduce locally. The script works as intended for me when the files aren't put directly into the config folder where the other .dtd files reside.

**Comment by tdonohue** [comment]
@Raf-atmire : Could you share with me your step-by-step process where this works properly? Strangely, I still cannot get it to work from a temp directory...and I'm not sure how my process differs from yours.  Again, my process is simply:

1. Create a new (temporary) empty folder in your DSpace 7 instance.  For example `[dspace]/config/temp/`
2. Copy your DSpace 6 configs into that  `[dspace]/config/temp/` folder  (There are no DTDs in that folder, just the two config files)
3. Then, run the script against the configs in that temp folder
    ```
    cd [dspace]/bin/
    ./dspace submission-forms-migrate -s ../config/temp/item-submission.xml -f ../config/temp/input-forms.xml
    ```
4. In this scenario, I still get this error (Notice the error seems to be that the new migration xslt `item-submissions.xsl` is unable to find the `input-forms.xml` as it seems to be looking in the wrong directory)
    ```
    The script has started
    Transforming ../config/temp/input-forms.xml with xsl: /dspace/config/migration/submission-forms.xsl to output: /dspace/config/submission-forms.xml
    Transforming ../config/temp/item-submission.xml with xsl: /dspace/config/migration/item-submissions.xsl to output: /dspace/config/item-submission.xml
    file:/dspace/config/migration/item-submissions.xsl; Line #11; Column #74; Can not load requested doc: /dspace/config/config/temp/input-forms.xml (No such file or directory)
    The script has completed
    ```

In terms of recommendations... if we can get the `temp` directory option working properly, we could simply document that as the necessary procedure (and recommend *against* copying your DSpace 6 configs directly into the `[dspace]/config` folder for DSpace 7).  However, if we go with that process, I'd recommend we AVOID always overwriting the existing/default DSpace 7 `submission-forms.xml` and `item-submission.xml` files... instead, this migration script should perhaps write it's output into temp files named `submission-forms.xml.migrated` and `item-submission.xml.migrated`.  Then the final step would be for the administrator to verify the migration looks good & copy them over the default configs manually.

**Comment by Raf-atmire** [comment]
@tdonohue I followed the exact same workflow as you and when using the relative paths, we did indeed come across the same error as you did. @MarieVerdonck pushed a commit that should resolve that issue. Could you check again when you get the time please? Thanks! She's also ensured that the `.migrated` gets added after the name and that it doesn't destructively overwrite.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@Raf-atmire and @MarieVerdonck : Thanks for your hard work on this! The bugs I was seeing are now fixed.  So, it's now successfully migrating the two configs to the corresponding `*.migrated` file.

However, I've found that the resulting `item-submission.xml.migrated` is not entirely "valid".  If I simply copy it over as-is to `[dspace]/config/item-submission.xml` and restart Tomcat, I end up with an error in the logs that says..

```
09-Feb-2021 22:01:25.145 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start:
dspace        |         org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/server]]
...
...
Caused by: org.dspace.app.util.SubmissionConfigReaderException: Error creating Item Submission Configuration: org.dspace.app.util.SubmissionConfigReaderException: step-definition section has no steps! A step with id='collection' is required in 'item-submission.xml'!
```

Notice that last line.  It looks like we *must* have a step of `id='collection'`... Looking closer at the `item-submission.xml.migrated`... I do see this:
```
<step-definitions>
   <step id="collection">
```

However, if I compare that to the default `item-submission.xml`, I see that the tag is supposed to be named `step-definition`, i.e.
```
<step-definitions>
   <step-definition id="collection">
```

You may recall, that this tag changed names in your other PR #3081 ... So, it looks like those changes need to be applied to this script as well.  Once that change is made, I suspect (fingers crossed) this might be ready to merge -- though I'd want to do one last tests of installing the output files to make sure they are "valid". Thanks!

**Comment by MarieVerdonck** [comment]
@tdonohue Rebased on latest master and applied changes so resulting xml matches changes from #3081. 
Did a test to launch a DSpace7 instance with the new item-submission.xml & submission-forms.xml and didn’t encounter any errors.

**Review by tdonohue — APPROVED** [review]
👍 Looks great now! I gave it one last test and everything works.  Thanks @Raf-atmire and @MarieVerdonck again!

I'll also wrote these instructions into the Upgrade docs for 7.x (see step 9b): https://wiki.lyrasis.org/display/DSDOC7x/Upgrading+DSpace#UpgradingDSpace-UpgradeSteps

**Pull request merged**
