### PR TITLE
DS-1028 - CAS and SAML implementation

### PR DESCRIPTION
**Pull request by tboinski**
CAS Authentication with optional SAML attribute values dicovery for DSpace 5_x.

The first patch was formerly implemented by Kaboré Wendin-Malegdé Patrick at JIRA (https://jira.duraspace.org/browse/DS-1028) and further user kgunn at JIRA did some arrangements to make it work with DSpace 1.8.2 and CAS 3.1.x. Finally nkneumann updated it to work with DSpace 3.1 (nkneumann@53e02e1).

This patch extends the work done by nkneumann by fixing it for DSpace 4_x and 5_x and allowing usage of SAML to get user attributes.

### CODE REVIEW

**Comment by helix84** [comment]
Hi, this is just a reminder of what I already asked about review. Please, also prepare a documentation on the wiki to be included along with docs for the existing plugins: https://wiki.duraspace.org/display/DSDOC5x/Authentication+Plugins

**Comment by tboinski** [comment]
Hi,

I posted info about the plugin in varius places where people were 
looking for such functionality. However so far I did not get any 
feedback (positive ore negative).

As for the documentation I assume I should edit the provided wiki? I'll 
do it during this week.

W dniu 21.01.2015 o 14:14, helix84 pisze:
> Hi, this is just a reminder of what I already asked about review.
> Please, also prepare a documentation on the wiki to be included along
> with docs for the existing plugins:
> https://wiki.duraspace.org/display/DSDOC5x/Authentication+Plugins
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DSpace/DSpace/pull/804#issuecomment-70834300>.
>


-- 
Pozdrowienia
Tomasz Boiński
http://tboinski.eti.pg.gda.pl
http://gplus.to/tboinski

**Comment by helix84** [comment]
It's probably best to contact the previous developers and known users directly, at least in a fairly niche use case like this.

Yes, please put it on the wiki, then it will be easy to move it to the official documentation space once this is merged. Existing documentation is now a requirement for inclusion. Thanks.

**Comment by tboinski** [comment]
Hi again,

This is probably a stupid question but should I create a new page for 
the documentation? I don't see any other edit/draft etc. option.

W dniu 21.01.2015 o 14:27, helix84 pisze:
> It's probably best to contact the previous developers and known users
> directly, at least in a fairly niche use case like this.
>
> Yes, please put it on the wiki, then it will be easy to move it to the
> official documentation space once this is merged. Existing documentation
> is now a requirement for inclusion. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DSpace/DSpace/pull/804#issuecomment-70835987>.
>


-- 
Pozdrowienia
Tomasz Boiński
http://tboinski.eti.pg.gda.pl
http://gplus.to/tboinski

**Comment by helix84** [comment]
Yes, please, create a new page in the DSPACE space. It will be then easy to move the page or copy the text to the DSDOC6x space when ready.

**Comment by bram-atmire** [comment]
Here's a template you can copy and use for this purpose:

https://wiki.duraspace.org/display/DSDOC/New+Contribution+Template

**Comment by tboinski** [comment]
The documentation is on this page:

https://wiki.duraspace.org/display/DSPACE/CAS+and+SAML+Authentication

W dniu 26.01.2015 o 15:37, Bram Luyten pisze:
> Here's a template you can copy and use for this purpose:
>
> https://wiki.duraspace.org/display/DSDOC/New+Contribution+Template
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DSpace/DSpace/pull/804#issuecomment-71469420>.
>


-- 
Pozdrowienia
Tomasz Boiński
http://tboinski.eti.pg.gda.pl
http://gplus.to/tboinski

**Comment by sazli** [comment]
Hi,

I am testing this on Jasig CAS 4.0.1 (with SAML disabled) and got 'Error: Document Not Found' upon redirection, after successful login on CAS server. dspace logs follows,

2015-03-09 04:40:08,894 INFO  org.dspace.browse.BrowseEngine @ anonymous:session_id=5268A715BBA6CA726B2D57728A351BAC:ip_addr=42.0.29.248:browse_mini:
2015-03-09 04:40:08,908 INFO  org.dspace.app.webui.discovery.DiscoverUtility @ facets for scope, null: 3
2015-03-09 04:40:11,989 INFO  org.dspace.authenticate.CASAuthentication @ anonymous:session_id=5268A715BBA6CA726B2D57728A351BAC:ip_addr=42.0.29.248:login: ticket\colon; null
2015-03-09 04:40:11,989 INFO  org.dspace.authenticate.CASAuthentication @ anonymous:session_id=5268A715BBA6CA726B2D57728A351BAC:ip_addr=42.0.29.248:login:service\colon; http\colon;//dspace.pulasan.my/mydspace
2015-03-09 04:40:11,989 INFO  org.dspace.authenticate.CASAuthentication @ CAS server and service:  https://weblogin.pulasan.my/cas/login

Thanks.

**Comment by tboinski** [comment]
Ok, so as far as I understand the login process works ok, but the return 
address is somehow broken?


Can you send me the full url that is generated after clicking Single 
Sign-On CAS Authentication?

And what url is shown in address bar after login in? Can you grab a 
screen with page not found error?

You can send reply directly to my email tobo@eti.pg.gda.pl


W dniu 09.03.2015 o 09:46, Syahrul Sazli Shaharir pisze:
> Hi,
>
> I am testing this on Jasig CAS 4.0.1 (with SAML disabled) and got
> 'Error: Document Not Found' upon redirection, after successful login on
> CAS server. dspace logs follows,
>
> 2015-03-09 04:40:08,894 INFO org.dspace.browse.BrowseEngine @
> anonymous:session_id=5268A715BBA6CA726B2D57728A351BAC:ip_addr=42.0.29.248:browse_mini:
> 2015-03-09 04:40:08,908 INFO
> org.dspace.app.webui.discovery.DiscoverUtility @ facets for scope, null: 3
> 2015-03-09 04:40:11,989 INFO org.dspace.authenticate.CASAuthentication @
> anonymous:session_id=5268A715BBA6CA726B2D57728A351BAC:ip_addr=42.0.29.248:login:
> ticket\colon; null
> 2015-03-09 04:40:11,989 INFO org.dspace.authenticate.CASAuthentication @
> anonymous:session_id=5268A715BBA6CA726B2D57728A351BAC:ip_addr=42.0.29.248:login:service\colon;
> http\colon;//dspace.pulasan.my/mydspace
> 2015-03-09 04:40:11,989 INFO org.dspace.authenticate.CASAuthentication @
> CAS server and service: https://weblogin.pulasan.my/cas/login
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DSpace/DSpace/pull/804#issuecomment-77817432>.
>


-- 
Pozdrowienia
Tomasz Boiński
http://tboinski.eti.pg.gda.pl
http://gplus.to/tboinski

**Comment by guilhermeportela** [comment]
Does it work with JSPUI?

**Comment by tboinski** [comment]
The backend class should be good for any UI, however the frontend (link 
display, EPerson management etc. would require some transfer for i to 
work in jspui.


-- 
Pozdrowienia
Tomasz Boiński
http://tboinski.eti.pg.gda.pl
http://gplus.to/tboinski

**Comment by akinom** [comment]
For  org.jasig.cas.client.validation used in CASAuthentication.java I needed to add 
```
        <dependency>
            <groupId>org.jasig.cas</groupId>
            <artifactId>cas-client-core</artifactId>
            <version>3.1</version>
         </dependency>
```
to dspace-api/pom.xml 

I made the CAS logout conditional on the availability of the #cas.logout.url config setting

**Comment by huyDlcorp** [comment]
we integrated Dpace 5.2 with CAS 3.5.2 but i got an error: 
2016-05-25 10:50:25,589 ERROR org.dspace.authenticate.CASAuthentication @ org.jasig.cas.client.util.CommonUtils.assertNotNull(CommonUtils.java:73)
2016-05-25 10:50:25,589 INFO  org.dspace.app.xmlui.utils.AuthenticationUtil @ anonymous:session_id=7B904BAE5368664B804C2ED8AF3DE5AB:ip_addr=192.168.1.52:failed_login:email=null, realm=null, result=5

pls. give an advice  to resolve it.
Tks.

**Comment by tboinski** [comment]
Hi,

you would have to provide more info, what client (xmlui or jspui) you 
are using, what is exactly happening, probably a wider log also would be 
nice.

W dniu 25.05.2016 o 06:04, huyDlcorp pisze:
> we integrated Dpace 5.2 with CAS 3.5.2 but i got an error:
> 2016-05-25 10:50:25,589 ERROR org.dspace.authenticate.CASAuthentication
> @ org.jasig.cas.client.util.CommonUtils.assertNotNull(CommonUtils.java:73)
> 2016-05-25 10:50:25,589 INFO
> org.dspace.app.xmlui.utils.AuthenticationUtil @
> anonymous:session_id=7B904BAE5368664B804C2ED8AF3DE5AB:ip_addr=192.168.1.52:failed_login:email=null,
> realm=null, result=5
>
> pls. give an advice to resolve it.
> Tks.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/DSpace/DSpace/pull/804#issuecomment-221467847>
>

-- 
Pozdrowienia
Tomasz Boiński
http://tboinski.eti.pg.gda.pl
http://gplus.to/tboinski

**Comment by huyDlcorp** [comment]
Tks for your response! 

I was simply success CAS authentication with xmlui, i fixed my error by adding hosts to point cas client to my cas server and every worked well. But i did not know to how to add more filed of user at LDAP (CAS server)  like Last_name, first_name and telephone when assign new user from cas to dspace? 

And Could you help me to deploy for JSPUI CAS Authentication?

Tks.

**Comment by tboinski** [comment]
Thr fields are read using saml library, you would probably need to check EPerson class and implement the support for needed info and define tgem in config file.

As far as jspui goes I didnot have time to implement cas callback function (the endpoint that the cas server sends response) and as such my patch will not work with jspui.

Dnia 30 maja 2016 07:15:54 CEST, huyDlcorp <notifications@github.com> napisał(a):
>Tks for your response! 
>
>I was simply success CAS authentication with xmlui, i fixed my error by
>adding hosts to point cas client to my cas server and every worked
>well. But i did not know to how to add more filed of user at LDAP (CAS
>server)  like Last_name, first_name and telephone when assign new user
>from cas to dspace? 
>
>And Could you help me to deploy for JSPUI CAS Authentication?
>
>Tks.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/DSpace/DSpace/pull/804#issuecomment-222412979

-- 
Pozdrawiam
Tomasz Boiński

**Comment by tdonohue** [comment]
Closing as this PR must be recreated on `dspace-6_x` branch. XMLUI has been removed from `master`. See this mailing list notice: https://groups.google.com/d/msg/dspace-devel/aEFqSn46ryM/iPRr_IMLCwAJ

However, there are parts of this PR which simply add a new Authentication Plugin to the API. If this PR was refactored to ONLY include the API changes, we could reopen it for consideration on `master`

**Comment by Clamsik** [comment]
Does cas client Java 3.1.x versione support SAML? 
I have to federate It with ms Azure

**Pull request closed without merging**
