### PR TITLE
DS-2616: correcting xpath for dc:format in oai_dc.xsl

### PR DESCRIPTION
**Pull request by kosarko**
Regarding DS-2616. 
https://jira.duraspace.org/browse/DS-2616

If the intention was to have the format from all bitstreams, including those in LICENSE and other bundles, this should be enough. If it was intended just for ORIGINAL bundle the xpath needs to be modified further.

### CODE REVIEW

**Comment by tdonohue** [comment]
Thanks for the PR @kosarko 

As I just commented in the ticket, my "guess" is that it should be intended to ONLY include bitstreams from the ORIGINAL bundle.

I cannot think of any use cases for returning the formats of files in the LICENSE, THUMBNAIL, TEXT (and other) bundles via the <dc:format> field in OAI-PMH. So, I suspect we'll want to modify this PR slightly to only include bitstreams in the ORIGINAL bundle.

**Comment by kosarko** [comment]
@tdonohue modified the xpath to only include bitstreams from ORIGINAL bundel

**Comment by tdonohue** [comment]
Thanks, @kosarko! At a glance, this looks good. 

Just needs a volunteer to run a quick test of the new xpath.

**Comment by kshepherd** [comment]
I've tested this PR, works well.
I'm in support of this fix generally but withholding an actual vote pending outcome of discussion on JIRA ticket and any further thoughts I might have ;)

**Comment by tdonohue** [comment]
In order to accept this for 6.0, we'd need this PR to be recreated against the "master" branch.

**Pull request closed without merging**
