### PR TITLE
DS-3769 Set the right hibernate property of …

### PR DESCRIPTION
**Pull request by marsaoua**
... org.dspace.eperson.Subscription: ePerson instead of eperson.id

### CODE REVIEW

**Comment by pnbecker** [comment]
+1
Full disclosure / Reminder: @marsaoua is a colleague of mine. This should be reviewed by another DSpace committer.

**Review by terrywbrady — APPROVED** [review]
The code change looks good.  I tested this locally and the issue described is resolved.  

Note: We do not run the email subscription process and my test server has email disabled, so I was unable to fully verify the subscription process.  -

**Review by kshepherd — APPROVED** [review]
+1 test successful as advertised (lastModified error from another issue notwithstanding)

**Comment by kshepherd** [comment]
Merging this along with #1890 , thanks @marsaoua !

**Pull request merged**
