### PR TITLE
Add SAF import via remote URL

### LINKED ISSUE #1913: SAF import via URL
Angular part for https://github.com/DSpace/DSpace/issues/8536

The Angular import page should allow to input an URL other than drag&drop the file.

4Science can work on that, estimation is 4 hrs

### LINKED ISSUE #8536: Import a SAF from URL
In version 5-6 there was also an option to import a remote SAF, this is convenient when you are going to restore from a remote storage or deal with large file.
This seems to be overlooked in the tier3

Screenshot from 2022-10-19 16-42-25

4Science can work on that, estimation is 6hrs

### PR DESCRIPTION
**Pull request by francescopioscognamiglio**
## References
Fixes #8536
Fixes https://github.com/DSpace/dspace-angular/issues/1913
Corresponding frontend PR: https://github.com/DSpace/dspace-angular/pull/2212

## Description
Added the import of a remote SAF via the `--url` option.

## Instructions for Reviewers

List of changes in this PR:
* new `--url`  option in `import` script to specify the URL of the remote SAF
* changes in dspace-api/src/main/java/org/dspace/app/itemimport/ItemImport.java to retrieve the remote SAF

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@francescopioscognamiglio : The IT errors here were on `main` and have been fixed in #8746.  If you rebase on `main` they should go away.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@francescopioscognamiglio : I finally got to testing this today... and I cannot get it to work from either the commandline or the User Interface.

When I try to run this from the commandline, I get this error:
```
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --url
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
        at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:407)
        at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:384)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:239)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at org.dspace.scripts.DSpaceRunnable.parse(DSpaceRunnable.java:85)
        at org.dspace.scripts.DSpaceRunnable.initialize(DSpaceRunnable.java:75)
        at org.dspace.app.launcher.ScriptLauncher.executeScript(ScriptLauncher.java:148)
        at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:131)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:98)
```

I believe the reason for this error is that you didn't add the new `--url` param to the `ItemImportCLIScriptConfiguration`.  So, it's not allowed on the commandline.

When I attempt to test this from the User Interface, I see the `--url` option, but I cannot paste a URL in there.. instead, it tells me to select a local file:

import

So, it appears that either a User Interface PR is needed, or some other change to allow the `--url` option to display a textbox in the UI.

**Comment by francescopioscognamiglio** [comment]
Hi @tdonohue, thanks for your feedback! I fixed both the import via UI and the import via CLI to use the `--url` param correctly.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@francescopioscognamiglio : Thanks for the updates!  It's **closer**, but not fully working.  The good news is that I **can** get it to run successfully from the User Interface.

However, the bad news is that I cannot get it to work from the command-line.  I'm trying to run this from commandline:
```
./dspace import --add --collection c90eeab3-f124-480c-94b1-153eed3321d4 --url [full-https-url-to-SAF-zip-file] -m ./mapfile.out -e dspacedemo+admin@gmail.com
```

The results are that the script returns a validation error:
```
The script has started
A source directory containing items must be set (run with -h flag for details)
java.lang.UnsupportedOperationException: A source directory containing items must be set
        at org.dspace.app.itemimport.ItemImportCLI.validate(ItemImportCLI.java:71)
        at org.dspace.app.itemimport.ItemImport.internalRun(ItemImport.java:162)
        at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:104)
        at org.dspace.app.launcher.ScriptLauncher.executeScript(ScriptLauncher.java:149)
        at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:131)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:98)
```

So, from the command-line, it appears the script is *requiring* the `--source` param.  But, from the UI, it works fine with just the new `--url` param.  Obviously, the user should either use `--source` or use `--url`, but not both.

**Comment by francescopioscognamiglio** [comment]
Hi @tdonohue, I fixed the issue so now you can run the script from the command-line.
So, from the command-line, using the `--url` param the `--source` is no lorged needed.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @francescopioscognamiglio !  This is now working completely for me.

**Pull request merged**
