### PR TITLE
DS-2895: Backport to DSpace 4

### PR DESCRIPTION
**Pull request by pnbecker**
https://jira.duraspace.org/browse/DS-2895

### CODE REVIEW

**Comment by pnbecker** [comment]
I backported it and made all tests run. I didn't test it manually (yet).

**Comment by mwoodiupui** [comment]
It doesn't let another user see the submission, but I get this:  
2016-10-06 16:40:53,194 ERROR org.dspace.app.webui.servlet.SubmissionController @ Error loading step class'org.dspace.submit.step.SkipInitialQuestionsStep': java.lang.NullPointerException
        at org.dspace.submit.step.SkipInitialQuestionsStep.doProcessing(SkipInitialQuestionsStep.java:52)

**Comment by mwoodiupui** [comment]
More testing:  I logged in as admin, **saved an unfinished submission**, logged out, logged in as unprivileged, and tried 'http://localhost:8080/DS-2895/jspui/submit?resume=2'.  Again I got "Internal System Error", but the error was:

2016-10-07 14:10:40,467 ERROR org.dspace.app.webui.servlet.SubmissionController @ Error loading step class'org.dspace.submit.step.SkipInitialQuestionsStep': org.dspace.authorize.AuthorizeException: Authorization denied for action WRITE on ITEM:2 by user 3
        at org.dspace.authorize.AuthorizeManager.authorizeAction(AuthorizeManager.java:181)
        at org.dspace.authorize.AuthorizeManager.authorizeAction(AuthorizeManager.java:100)
        at org.dspace.content.Item.update(Item.java:1547)

"Authorization denied" sounds right, but it should be caught and explained instead of spewing Internal System Error.

**Comment by abollini** [comment]
I'm going to merge the PR as is. It fixes the bug, I have created a ticket for the bug noted by Mark (https://jira.duraspace.org/browse/DS-3357 ) and also proposed a fix only for 6.0.

The latest bug doesn't need to be fixed in previous version as it doesn't have any security implication and also it will be odd to have the fix in place for 4.7 and not for 5.6.

**Pull request merged**
