### PR TITLE
Adding/removing relationships in the submission form does not update the view automatically

### LINKED ISSUE #1671: Adding relationships through submission doesn't update view automatically
**Describe the bug**
When adding (or removing) a relationship to an item in submission, the view (list displayed under the field's input) doesn't update automatically. The relationship is correctly added/removed to/from the item, but isn't visible until a page reload.

**To Reproduce**
* Start a submission for an item in a collection that contains a relationship input (as of writing this, the "People 2" collection contains a relationship input for "Publications" on [Demo](https://demo7.dspace.org/))
* Click the lookup for that field and select an item
* The item isn't visible under the input
Screenshot 2022-06-01 at 15 58 08
* Reload the page
* The item is visible under the input
Screenshot 2022-06-01 at 15 58 33
* Click the delete button next to the related item
* Nothing seems to happen (although a request is sent to the REST API)
* Reload the page
* The related item under the input is gone

**Expected behavior**
The relationships should display under the inputs after adding/removing them without requiring a page reload.

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes DSpace/dspace-angular#1671
* Related to DSpace/dspace-angular#2252

## Description
When the backend returns the submission form after an update, it will not only return all the current values but also create the `relation.*` metadata fields for all the relation fields (who don't have a `<linked-metadata-field>`) because otherwise when they don have an explicit field linked to them (using `<linked-metadata-field>`) the data is not sent back to the frontend

## Instructions for Reviewers
By default the when the form is loaded for the first time the item metadata is used to populate the form data. This [includes virtual metadata](https://github.com/DSpace/DSpace/blob/d99fb55df19c244576e795f1ecc182b4a559bea3/dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/ItemConverter.java#L75) (so relationships).

When the form is updated, the submission form object is retrieved, and the metadata is [added](https://github.com/DSpace/DSpace/blob/e0534a5d966a225fbb5142e5b1e0638dfc63a3e5/dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/DescribeStep.java#L97-L98) by the `DescribeStep`. This did not include virtual metadata. I’ve added it for the case when there is no linked metadata field to a relationship field.

The easiest way to test this PR is to use the linked angular PR and follow the steps on how to test it.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alexandrevryghem** [comment]
While testing this PR I also found out that the "read-only" for the `<scope>` tag is not working [like it should](https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-Structureofthe%3Cstep-definition%3Etag). When "read-only" is specified you can still edit the fields in he UI and even save them

**Review by tdonohue — COMMENTED** [review]
@alexandrevryghem :  Just wanted to comment here and note that the code looks good.  It appears to (mostly) work.  But, I'm holding back on approving it officially until this bug in the UI is solved: https://github.com/DSpace/dspace-angular/pull/2252#pullrequestreview-1466014952

So, no updates are required to this PR unless they are needed to solve that bug.  Looks good overall.

**Comment by atarix83** [comment]
@alexandrevryghem @tdonohue 

I've verified the problem with read-only fields exists with every input type. However we've already fixed on DSpace-CRIS and we can port the fix quickly

**Comment by atarix83** [comment]
@tdonohue 

we can open it

**Comment by atarix83** [comment]
@tdonohue  @alexandrevryghem 

here the PR for the read-only issue
https://github.com/DSpace/dspace-angular/pull/2297

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem .  This looks good and the code makes sense. Works with the frontend PR

**Pull request merged**
