### PR TITLE
DS-4121: Refactor Entities ITs

### PR DESCRIPTION
**Pull request by benbosman**
https://jira.duraspace.org/browse/DS-4121
Refactoring the ITs to use the new cleanup method.

The changes have been re-created because they caused problems with the latest master merge

This replaces https://github.com/DSpace/DSpace/pull/2353

### CODE REVIEW

**Comment by tdonohue** [comment]
@tomdesair : If you have time, I'd appreciate a quick review from you on this, especially since you had very useful feedback for the original PR #2353 (which this replaces).  If you won't have time in the near future, let us know and I'll find someone else to help review. Thanks!

**Review by tdonohue — APPROVED** [review]
👍 This looks like what I expected.  New Builders exist, and all `@Ignore` tests have been reenabled.  Also much fewer changes/tweaks then the previous PR. Thanks @benbosman !

**Review by paulo-graca — APPROVED** [review]
👍

**Comment by tdonohue** [comment]
Merging, as this is at +2.  Remember, this is will also get an additional review in PR #2376  (as this PR is simply committing to that PR#2376's branch).

**Pull request merged**
