### PR TITLE
DS-2374 authority indexing matching metadata by value

### PR DESCRIPTION
**Pull request by antoine-atmire**
https://jira.duraspace.org/browse/DS-2374

### CODE REVIEW

**Comment by KevinVdV** [comment]
+1

**Comment by helix84** [comment]
I tested the PR by deleting the authority index ([dspace]/solr/authority/data), deploying b50efa6a5a047a41f763424a8acb5ce047d94bed and running the index-authority script. Unfortunately, it exibits the same behaviour as before - for the author I tested, the same number of documents were created in the authority index as the number of items shown in the browse index for that author. What could have gone wrong?

**Comment by KevinVdV** [comment]
@helix84 If you want to test with an existing Database you will also need to clear the authority column in the metadatavalue table. If certain metadata values already have authority keys these keys will be used every time. (We don't want to be throwing away data)

**Comment by helix84** [comment]
@KevinVdV Thanks, that was indeed the "problem" and it also explains whether and how these new generated authority IDs are persisted.

+1, tested

**Pull request merged**
