### PR TITLE
[DS-3694] Clean up EHCache configuration mess (Port to 6x)

### PR DESCRIPTION
**Pull request by terrywbrady**
https://jira.duraspace.org/browse/DS-3694

This is not yet tested, it has been created to facilitate testing

### CODE REVIEW

**Review by kshepherd — APPROVED** [review]
+1 new commits reviewed, build+tested, and tested with item uploads, views, collection adds/views, works fine

**Comment by kshepherd** [comment]
merging this with just one +1 as its a port and has already been reviewed/tested for master

**Comment by minurmin** [comment]
The change omits following lines in assembly.xml:
```<!-- Exclude Mirage2, as it is copied into the XMLUI WAR when enabled -->
<excludes>
     <exclude>org.dspace.modules:xmlui-mirage2:war:*</exclude>
</excludes>
```
I'm not sure whether these are needed anymore with DSpace 6, but at least they seem to be unrelated to the EHCache fix. The change seems to be originated in DSpace 7 -specific DS-3422 Remove XMLUI and JSPUI from the official distribution.

**Comment by kshepherd** [comment]
well spotted, @minurmin, i think we actually do want to keep this exclusion in dspace6
@terrywbrady , it looks like this omission will cause an unnecessary mirage2 war to be copied in during assembly (as noted, it's copied into xmlui war, doesn't need its own)... was this change intentional? maybe an artefact introduced during port from master branch?

**Comment by terrywbrady** [comment]
@kshepherd , @minurmin , that was not intentional.  I must have picked up another artifact from testing.  Sorry for the confusion.

**Comment by kshepherd** [comment]
@minurmin , @terrywbrady , i've opened #2043 to add the exclusion back in

**Comment by minurmin** [comment]
@terrywbrady , I just noticed another issue. This commit sets diskStore path to java.io.tmpdir/DSpaceHibernateCache in hibernate-ehcache-config.xml, even though this directory was omitted a few months ago in DS-3710, and seems to be "java.io.tmpdir" in master branch as well. Perhaps the config conflict-related fix #1860 should be applied to 6x branch again?

**Comment by tdonohue** [comment]
@minurmin is correct. This PR seems to have accidentally reverted #1860 on 6.x.  I'll correct this in a PR shortly.

**Pull request merged**
