### PR TITLE
Replace new uses of Log4J v1 with v2.  Ban v1 artifacts.  #3190.

### LINKED ISSUE #3190: New uses of Log4J v1 are appearing
Since we converted from Log4J v1 to v2, some new code has been importing v1 packages again.  This leaves us with confusing dependencies, and if it works, it does so in a roundabout and wasteful fashion.

**To Reproduce**
1. Build DSpace
2. See v1 JARs in various `**target/**/lib/` directories.

**Expected behavior**
Only Log4J v2 artifacts should be included in the build.

### PR DESCRIPTION
**Pull request by mwoodiupui**
## References
* Fixes #3190

## Description
All imports of Log4J v1 classes switched to v2.  v1 banned.

## Instructions for Reviewers
List of changes in this PR:
* Uses of `org.apache.log4j.*` classes moved to `org.apache.logging.log4j.*`.
* `maven-enforcer-plugin` configured to ban all versions of `log4j:log4j`.

With the patch, you should find no Log4J v1 JARs in any target `lib/` directories.

Introducing an import of e.g. `org.apache.log4j.Logger` should cause the build to fail.  Most likely the compiler will complain that the class does not exist.  The compiler message should show you the file and line to be fixed.

Introducing a dependency that depends on `log4j:log4j` should cause `maven-enforcer-plugin` to fail the build and complain of a forbidden dependency.  You'll need to use `maven dependency:tree` to find the offender and add an `<exclusion>` in the relevant POM.  See `apache-jena-libs` in `dspace-api/pom.xml` for an example.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@mwoodiupui : Just wanted to note that this looks good/correct to  me.  **However**, it appears this is dependent on #3189 . Currently (on latest `main`), this PR builds properly, but the REST API fails to start with this error:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dspace.app.itemimport.BTEBatchImportService' defined in file [/dspace/config/spring/api/bte.xml]: Cannot resolve reference to bean 'bibTeXDataLoader' while setting bean property 'dataLoaders' with key
[TypedStringValue: value [bibtex], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bibTeXDataLoader': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [gr.ekt.bteio.loaders.BibTeXDataLoader] from ClassLoader [ParallelWebappClassLoader
```

Since the BTE files that error references are being removed from our codebase in #3189, we probably should just review & merge that PR first. That'll allow you to quickly rebase this & it **should** work at that point.

So, in the meantime, I'll put effort into getting #3189 moved along quickly to unblock this PR.

**Comment by tdonohue** [comment]
@mwoodiupui : If you can rebase this on the latest `main`, this is now unblocked as #3189 was just merged.  Once this PR is updated, I can give it another review & test and see if we can merge it quickly.  Thanks!

**Comment by mwoodiupui** [comment]
@tdonohue done!

**Review by tdonohue — CHANGES_REQUESTED** [review]
@mwoodiupui : This is looking good overall. But, when I start up the OAI-PMH interface (which is on by default), I'm seeing this error...
```
07-Apr-2021 19:17:44.546 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start:
dspace        |         org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/server]]
dspace        |                 at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
dspace        |                 at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
dspace        |                 at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
dspace        |                 at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
dspace        |                 at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
dspace        |                 at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
dspace        |                 at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1858)
dspace        |                 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
dspace        |                 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
dspace        |                 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
dspace        |                 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
dspace        |                 at java.base/java.lang.Thread.run(Thread.java:834)
dspace        |         Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'DSpaceOAIDataProvider': Unsatisfied dependency expressed through field 'cacheService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xoaiCacheService' defined in class path resource [org/dspace/xoai/app/BasicConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.dspace.xoai.services.api.cache.XOAICacheService]: Factory method 'xoaiCacheService' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/log4j/LogManager
```

It looks (to me) like log4j v1 is still (trying to be) used by XOAI.  We may need to look closer at how to avoid this...not sure yet if this means a new release of XOAI (https://github.com/DSpace/xoai/), or if we can just exclude it via our Maven POM.

**Comment by mwoodiupui** [comment]
It appears that XOAI needs `log4j-1.2-api` (which supplies that class) and `dspace-server` doesn't depend on it.

**Review by tdonohue — APPROVED** [review]
👍 I've retested this today & it's now working.  Code looks good too. Thanks @mwoodiupui !

**Pull request merged**
