### PR TITLE
DS-3582

### PR DESCRIPTION
**Pull request by pnbecker**
https://jira.duraspace.org/browse/DS-3582

### CODE REVIEW

**Review by hardyoyo — APPROVED** [review]
+1 obviously correct

**Comment by pnbecker** [comment]
We just encountered that we'll need more JSPs fixed. => Marking this work in progress.

**Comment by pnbecker** [comment]
In the same commit that remove the `context.abort()` call, three more JSPs were changed. This PR no fixes all of them.

**Comment by pnbecker** [comment]
We discussed exactly this approach yesterday in slack. The resulting code change is obvious. I'll merge it without another review.

**Pull request merged**
