### PR TITLE
Performance improvement for pagination

### PR DESCRIPTION
**Pull request by mspalti**
## Description
Modifies the REST converter for paginated objects to improve performance, especially for items with many bitstreams. E.g. for an item with 350 bitstreams in the `ORIGINAL` bundle the initial SSR response time in my tests dropped from 7 seconds to 2 seconds. 

The reason for the performance gain is that instead of converting all model objects to rest objects only necessary objects are converted. In my test example, that meant that only 5 objects were converted rather of the full 350. When rendering items this adds to the performance improvement in https://github.com/DSpace/dspace-angular/pull/2065 and I notice a similar performance benefit when the mirador component checks for the number of bitstreams (over 3 secs to under 300ms).

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

List of changes in this PR:
* The ConverterService only converts objects needed for pagination 
* A new utility method is added to return a list of objects based on the pagination requirement

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@mspalti : Nice find, this does sound like a potentially major performance improvement.  Added to 7.6 board & we'll find some volunteer reviewers.

**Comment by mspalti** [comment]
This also speeds up the Item bitstreams edit panel when the item has lots of files.  So far that's the only other place where I've seen a benefit but there might be others.

**Review by abollini — APPROVED** [review]
Changes look good, thanks you. Current automatic tests should be enough imho to keep us safe

**Comment by tdonohue** [comment]
@DSquareTechnologies: In today's dev mtg you briefly mentioned seeing performance issues for Items with many Bitstreams.  I wanted to alert you to this PR (I'm currently testing it today) as it may improve performance in that area.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @mspalti !  This is a great improvement.  Code looks good, and it's good to see tests all still succeed. I gave this some light testing on my end as well by doing various interactions with the Item & Edit Item UI.  I'm not seeing any issues.

**Comment by DSquareTechnologies** [comment]
Thanks Tim! I have forwarded this to team. Will get back in a day or two 
if they can test on volume I shared.

Narendra

**Comment by tdonohue** [comment]
@DSquareTechnologies : as of a few minutes ago, this PR was merged to `main` as it's working well for me.  So, your team can always just test the latest `main` (of both the frontend & backend) to see if the performance is improved there.  If it still isn't great, feel free to log a ticket with the exact behavior you are seeing (and ideally, if possible, steps which others can use to reproduce it)

**Comment by DSquareTechnologies** [comment]
Noted. Thanks
________________________________

**Pull request merged**
