### PR TITLE
[DS-3849] REST API items resource returns items in non-deterministic order (master port)

### PR DESCRIPTION
**Pull request by PhilipVis**
This PR updates the ItemDAOImpl class to make sure all item lists returned by this class will now be in a deterministic order.

Jira Issue: https://jira.duraspace.org/browse/DS-3849

Fixes #7196

### CODE REVIEW

**Comment by tdonohue** [comment]
@PhilipVis : Just an FYI, it looks like this port to `master` is failing a few tests in `ItemTest`.  Failures start here in Travis logs: https://travis-ci.org/DSpace/DSpace/builds/584044986#L3734

**Comment by PhilipVis** [comment]
@tdonohue Thanks for notifying me on the failing tests. I had mistakenly edited method countArchivedByCollectionExcludingOwning instead of findArchivedByCollectionExcludingOwning. I have now fixed this, but unfortunately some tests are still failing. I'm not sure yet what the cause is now.

**Comment by PhilipVis** [comment]
I have updated the failing test so that it will check the items ordered by UUID instead of title. Unfortunately this still results in the test failing in Travis, while on my local machine this did result in the test succeeding. Is there something else I need to do to?

**Comment by tdonohue** [comment]
@PhilipVis : sorry for the late reply. But, if Travis is failing, even though your local machine succeeds, then there must be some flaw in the test or the code itself.  The flaw is not immediately evident to me either, but maybe your local machine has something different that Travis does *not*?  Even differences in dependency version or operating system can sometimes result in different or unexpected behaviors. Travis is reporting that it is running Oracle Java 8, Maven 3.5.2 on Ubuntu Linux (those versions are reported near the top of the Travis logs).

I should also notice that (very occasionally) I've seen issues arise where the *order in which Integration Tests run* affects the output. This is usually encountered when one Integration Test fails to clean up after itself, and it then (unexpected) data from that test carries over into the next Integration Test. It's possible this is also the cause.

For what it's worth, I've also tried running these tests on my machine (Oracle JDK 8, Maven 3.3.9, Windows 10) using `mvn clean install -Dmaven.test.skip=false -DskipITs=false` and I'm seeing the **same integration test failure** that is reported in Travis CI.  (It is worth noting though that all unit tests succeed...it's just a failure in the `findAllWithPaginationTest` integration test)

**Comment by kshepherd** [comment]
it looks as though the failure is in expecting Public Item 2 but seeing Public Item 3. do the tests need some tweaking?

**Comment by tdonohue** [comment]
@PhilipVis : This appears to still need updating for our `main` branch. It looks like it was already applied to 6.x (in #2501)...so, it'd be a shame if this same fix doesn't appear in 7.x.

**Pull request closed without merging**
