### PR TITLE
Dockerfile.test and docker-compose: expose port 8000, set JDWP java opts

### PR DESCRIPTION
**Pull request by kshepherd**
This allows a remote JVM debugger to be connected to port 8000 on the
dspace docker container (test environment).

This may need a documentation note to warn against running the supplied docker-compose / Dockerfile.test config in production or on any unsecured network -- already a good warning but made more important now that the JVM can be exposed to a debugger for reading memory.

## To review

Rebuild and start the test docker services with `docker-compose -p ${projectName} ...` (`build`, `up -d`) where project name is eg. d7 or whatever you prefer to use for v7 docker testing environment.

Attach a debugger to a remote JVM using **localhost:8000** as the address. Here's a screenshot from my IDE as an example:
Screenshot from 2022-05-25 10-45-15

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR doesn't modify any actual DSpace code or maven projects, just docker configuration

### CODE REVIEW

**Comment by kshepherd** [comment]
I've realised this breaks the DSpace launcher inside the docker container as it wants to use JAVA_OPTS but the debug line will cause it to exit with a "port in use" error. So there is probably a better environment variable to use like CATALINA_OPTS that won't interfere with other java usage. I'll update the PR soon.

**Comment by tdonohue** [comment]
Feel free to let me know when this is next in a reviewable state.  For now, I'm moving this into our "on hold" column as this sounds like it's not yet ready for any sort of review.

**Comment by kshepherd** [comment]
No problem, it should be ready but I realise it is not a priority.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @kshepherd.  Finally got back to testing this and this change works perfectly for me.  I can debug the REST API in my IntelliJ using..
* Run -> Debug
* Edit Configuration
* '+' -> Remote JVM Debug
* I then see the screenshot you show above, and aligned my settings with your, especially using port 8000
* Once I click "Debug", I see it connects to port 8000, and I'm able to set breakpoints in my IDE and step through the code.

I can see how this will be really useful for those of us who use Docker heavily.  Thanks!

**Pull request merged**
