### PR TITLE
Protecting against possibly missing values supplied by Orcid and logg…

### PR DESCRIPTION
**Pull request by J4bbi**
Replaces #2194

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
Thanks @J4bbi ! This looks good to me, and improves on #2194

**Review by tdonohue — CHANGES_REQUESTED** [review]
@J4bbi : After approving this, I've realized it failed tests.  So, it looks like this needs more work.  Maybe the method needs to remain `static`?

**Comment by J4bbi** [comment]
a bit hasty of me, this should work fine

**Review by tdonohue — APPROVED** [review]
👍 Looks good now, thanks!

**Comment by tdonohue** [comment]
Merging with one approval.  This does NOT need to be ported to `main` as we're now using ORCIDv3 on main (and this fix is for the ORCIDv2 integration)

**Pull request merged**
