### PR TITLE
https://github.com/DSpace/dspace-angular/issues/1306 - Implemented ne…

### PR DESCRIPTION
**Pull request by DanGastardelli**
https://github.com/DSpace/dspace-angular/issues/1306 - Implemented new metadata in the dspace schema to store thumbnail descriptions of collections and communities

## References
https://github.com/DSpace/dspace-angular/issues/1306
This change was targeted at https://github.com/DSpace/dspace-angular/issues/1306 which now allows storing in a "dspace" schema metadata a detailed description of collection and community logo thumbnail images (also recognized by screen readers). This change is linked to another made in the frontend with the same ticket name.

## Description
The "dspace.thumbnail.description" metadata was added to be able to store thumbnail descriptions

## Instructions for reviewers
Use a new database and use the "dspace database migrate" command in the "bin" folder of the installed DSpace or perform a new installation of DSpace with this change applied.

List of changes in this PR:
*The "dspace.thumbnail.description" was created for the schema "dspace" in the file "dspace/config/registries/dspace-types.xml"

**Include guidance on how to test or review your PR.**

When installing DSpace, simply check whether the "dspace.thumbnail.description" metadata was created correctly on the DSpace metadata registration page, in the "dspace" schema.

### CODE REVIEW

**Comment by kanasznagyzoltan** [comment]
We have tested but for us the dspace.thumbnail.description metadata does not show up in the metadata registry page.

Checked out the PR branch.
Started backend with the docker compose up -d command
Entered the dspace container with the docker exec -it dspace /bin/bash command

Ran the /dspace/bin/dspace database migrate command

image

Connected frontend and backend
Checked the Registries → Metadata page, opened the dspace schema, but the new type does not appear there

image

To me it looks like he new type does not get created with the migration process. Please let me know if I did something wrong during my testing.

**Comment by DanGastardelli** [comment]
@kanasznagyzoltan I redid the test with an empty bank and the metadata was installed correctly. I suggest you retrace your steps, something may have been left behind. If it still doesn't work, you can follow this step in the official DSpace documentation to manually update the metadata (https://wiki.lyrasis.org/display/DSDOC8x/Upgrading+DSpace#UpgradingDSpace-ManuallyupdatingtheMetadataRegistries).

**Comment by kanasznagyzoltan** [comment]
@DanGastardelli 
I have tested using a blank postgres db and now there is the new metadata element in the list:

**Comment by DanGastardelli** [comment]
> @DanGastardelli Eu testei usando um banco de dados postgres em branco e agora há o novo elemento de metadados na lista:
> 
> imagem
> 
> No meu caso anterior, eu tinha um banco de dados existente e a migração do banco de dados ./dspace talvez não tenha executado todas as migrações relacionadas ao xml. ( https://wiki.lyrasis.org/display/DSDOC8x/Upgrading+DSpace#UpgradingDSpace-ManuallyupdatingtheMetadataRegistries )

I'm glad you made it!

**Pull request closed without merging**
