### PR TITLE
DS-3719: Trying to fetch unqualified metadata fields via REST fails

### PR DESCRIPTION
**Pull request by philip-muench**
This small fix allows one to fetch unqualified metadata fields from the registry via REST. Example for the error:
- https://demo.dspace.org/rest/registries/schema/dc/metadata-fields/title fails.
- https://demo.dspace.org/rest/registries/schema/dc/metadata-fields/title/alternative works.

### CODE REVIEW

**Comment by philip-muench** [comment]
This affects all versions since at least 6.0, therefore this should be cherry-picked for dspace-6_x. I don't know if it also affects 5.x or older versions.

**Review by hardyoyo — APPROVED** [review]
A tiny change, obviously correct. +1

**Comment by tdonohue** [comment]
Please rebase this PR against the latest `master` branch.  The `master` branch now requires adherence to our new Java Code Style documented at: https://wiki.duraspace.org/display/DSPACE/Code+Style+Guide

If you have any questions, feel free to ask in this PR or on our Slack: https://wiki.duraspace.org/display/DSPACE/Slack

**Comment by terrywbrady** [comment]
@philip-muench , thank you for submitting this fix. 

Please see the note on this PR regarding the rebase.

Also, it would be helpful to create a new PR against the dspace-6_x branch that contains this same fix.

(Otherwise, I recommend that we re-direct this fix to the dspace-6_x branch.  Since demo.dspace.org is referenced in the notes, I assume that was the original intent.)

**Comment by philip-muench** [comment]
Merged it and opened up a PR for 6.x : PR 2004

**Comment by philip-muench** [comment]
Closing this PR due to commit spam trying to meet style requirements. Reopened as PR 2007.

**Pull request closed without merging**
