### PR TITLE
Add migration to fix metadatavalue.place

### LINKED ISSUE #7997: Metadata value place is not updated when migrating from DSpace 5.10
#### Describe the bug

After migrating a database from DSpace 5.10 to 6.x or 7.x, the `metadatavalue.place` of existing MDVs still starts from 1 instead of 0.

This can cause unexpected behaviour e.g. when editing metadata in the frontend:

* Editing the MDV `N` edits MDV `N+1` instead and "fixes" some MDV's `place` as they get overwritten
* Editing the _last_ MDV fails ~ `422: Unprocessable or invalid entity` 

#### To Reproduce

1. Deploy a clean DSpace ~ [dspace-5.10](https://github.com/DSpace/DSpace/tree/dspace-5.10)

2. Add a few Items with multiple values for some MDFs

3. Dump the resulting database

4. Deploy a clean DSpace ~ `main` with the same database and run ignored migrations

   ```
   ./dspace database migrate ignored
   ```

6. Compare the migrated database to the original 5.10 database
   * `metadatavalue.place` will still start from 1 instead of 0

#### Expected behavior

The `place` of existing MDVs should be updated when migrating to DSpace 6+

#### Proposed solution

Add a new migration:

```sql
UPDATE metadatavalue AS mdv
SET place = mdv.place - minplace
FROM (
  SELECT dspace_object_id, metadata_field_id, MIN(place) AS minplace
  FROM metadatavalue
  GROUP BY dspace_object_id, metadata_field_id
) AS mp
WHERE mdv.dspace_object_id = mp.dspace_object_id
  AND mdv.metadata_field_id = mp.metadata_field_id
  AND minplace > 0;
```

* We've tested this with

  * a "test database" with a few MDVs
  * some production databases which has the same issue.

* Also covers cases where `place` starts at values >1; we've encountered a few of these during testing

* Things to note:

  * Time will be a concern for large databases:
     * ~700k MDVs → ~20 seconds
     * ~15M MDVs → ~20 minutes

  * Because we're performing a lot of `UPDATE`s, the database can swell quite a bit during/after the migration because _Postgres keeps both values_.

    We can address this by [adding a `VACUUM`](https://www.postgresql.org/docs/9.0/routine-vacuuming.html).

### PR DESCRIPTION
**Pull request by ybnd**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #7997

## Description
Add a SQL migration to fix `metadata.place` after migrating from DSpace 5.x

## Reviewing
1. Follow the steps "to reproduce" from the issue linked above 
    * `metadatavalue.place` should start from 1 (this is the bug)
2. Update the test instance ~ this PR & run migrations
    * `metadatavalue.place` should start now start from 0

## TODO
* [x] Port to Oracle & H2

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by ybnd** [comment]
No clue what's up with that IT failure though...
`RelationshipTypeRestControllerIT#findAllEntityTypes` finds 8 entity types instead of 7, somehow, nothing enitity-related was changed

**Comment by tdonohue** [comment]
@ybnd : There was an IT failure on `main` as you noted. It's been fixed in #8026 which was just merged. So, if you rebase this PR on the latest `main` code, then you should no longer see that random IT failure.

**Review by tdonohue — COMMENTED** [review]
@ybnd : I've verified the initial bug by spinning up an old 5.10 database in Docker (using https://github.com/DSpace-Labs/DSpace-Docker-Images) and seeing that this query returns all `1` values:
```
SELECT resource_id, metadata_field_id, MIN(place) AS minplace
       FROM metadatavalue
       GROUP BY resource_id, metadata_field_id;
```

So, it does appear that, at some point in the history of DSpace, some code was inserting 1 as the first value instead of 0.

I've also verified that a fresh 7.x database with new content has all zeros.  While, an upgraded database may have a mixture of 1s and 0s.

So, it appears that currently, in 7.x, metadata values are inserted with a minimum place of 0.  It's **unclear to me when this was fixed, or even what fixed it.**

Finally, I've verified that your migration fixes the issue if 1s and 0s are intermixed.  My hope is that this migration may not run for *too long* for most sites...as not every metadata field may have a minplace value of 1, depending on when/where this bad behavior was fixed in DSpace.

Overall, I think this PR makes sense.  However, I cannot move it forward or approve it without a similar migration for H2 and Oracle at this time.

**Comment by MarieVerdonck** [comment]
> It's **unclear to me when this was fixed, or even what fixed it.**

Looks like:

- The place was set to start at 0 in DS6 [here](https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/content/DSpaceObjectServiceImpl.java#L579-L580). 
- Whilst in DS5 the place was set [here](https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace-api/src/main/java/org/dspace/content/DSpaceObject.java#L253) which was set to so `placeNum[dcIdx]=placeNum[0]`. Above that this `placeNum` gets populated starting at [1] [here](https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace-api/src/main/java/org/dspace/content/DSpaceObject.java#L94-L115) (the `current++` is before putting it in the `placeNum`)

**Comment by ybnd** [comment]
Would be best for someone to double check these, since I'm not well versed in H2/Oracle at all.
Tested on a copy of the `metadatavalues` table ~ the toy example DB from #7997

**Review by paulo-graca — APPROVED** [review]
I've tested this migration from a DSpace5 version. This migration comes is last:

```
| Versioned | 7.0.2021.02.08 | tilted rels                                         | SQL      |                     | Pending        |
| Versioned | 7.0.2021.03.18 | Move entity type to dspace schema                   | SQL      |                     | Pending        |
| Versioned | 7.0.2021.09.24 | Move entity type from item template to collection   | SQL      |                     | Pending        |
| Versioned | 7.0.2021.10.04 | alter collection table drop workflow stem columns   | SQL      |                     | Pending        |
| Versioned | 7.1.2021.10.18 | Fix MDV place after migrating from DSpace 5         | SQL      |                     | Pending        |
+-----------+----------------+-----------------------------------------------------+----------+---------------------+----------------+
```
and after migrating:
`/dspace/bin/dspace database migrate`

and managed to successfully migrate:
```
| Versioned | 7.0.2021.09.24 | Move entity type from item template to collection   | SQL      | 2021-12-03 16:46:58 | Success        |
| Versioned | 7.0.2021.10.04 | alter collection table drop workflow stem columns   | SQL      | 2021-12-03 16:46:58 | Success        |
| Versioned | 7.1.2021.10.18 | Fix MDV place after migrating from DSpace 5         | SQL      | 2021-12-03 16:46:58 | Success        |
+-----------+----------------+-----------------------------------------------------+----------+---------------------+----------------+
```
and I confirm I now have places starting at 0.
image

**Review by tdonohue — APPROVED** [review]
👍 Tested on Postgres, and it's working for me as well.  The H2 version is auto-tested in our GitHub Action CI process, and looks reasonable.  The Oracle version looks like valid syntax to me as well, though I don't have an Oracle test instance (and I cannot claim to be an Oracle expert).

**Pull request merged**
