### PR TITLE
DS-4232 Norwegian Science Index 

### PR DESCRIPTION
**Pull request by gregorgabriel**
The Norwegian Science Index is tody juat available in norwegian. Here is n english translation to use in input-forms.xml. (To use the input-forms in norwegien use a input-forms_no.xml together with nsi_no.xml)

### CODE REVIEW

**Comment by AlexanderS** [comment]
@gregorgabriel Can you maybe clean up the history of this pull request, so that it only contain the commits it should contain? (You can use f.e. `git rebase` or `git rebase -i` to remove commits you do not want to have here and then do a "force push".)

**Comment by gregorgabriel** [comment]
> @gregorgabriel Can you maybe clean up the history of this pull request, so that it only contain the commits it should contain? (You can use f.e. `git rebase` or `git rebase -i` to remove commits you do not want to have here and then do a "force push".)

No, sorry, I gave it a try with "git rebase -i" and "git push --force" but it made it worth.

**Comment by AlexanderS** [comment]
@gregorgabriel Okay, I have created #2417 with a clean history.

**Comment by tdonohue** [comment]
Closing. Replaced by #2417

**Pull request closed without merging**
