### PR TITLE
Add endpoints for Item/Bitstream thumbnails

### LINKED ISSUE #3286: Thumbnail resolution should happen on the rest side
**Is your feature request related to a problem? Please describe.**

Finding the correct thumbnail for an item or a bitstream is every slow at the moment, because it is done client side. The UI has to download the entire thumbnail bundle, ignoring pagination, to compare filenames with bitstreams in the ORIGINAL bundle and find a match.

We've never had much issues with this because we've never used DSpace 7 in a situation where we had a lot of items with a lot of bitstreams and thumbnails. If you do the performance becomes very poor in situations where you need to resolve multiple thumbnails quickly, e.g. the search result grid view.

**Describe the solution you'd like**

I propose we add an optional thumbnail link to bitstreams. If a bitstream is in the ORIGINAL bundle, rest should check if there's a matching thumbnail. If there is, add a `thumbnail` link to the links section of the ORIGINAL bitstream, with the self link to the THUMBNAIL bitstream (or to a new `/bitstreams/:uuid/thumbnail` alias if that's preferable)

Items should get a thumbnail link as well, for the default thumbnail that should be used for that item (best to check dspace 6 for the exact logic to determine which one that is, because as it stands the UI just picks the first one it finds). We should get that both for items retrieved directly, as well as discovery results.

For performance it would be probably good if this would happen using a projection: by default the links aren't added, but if you ask for the thumbnail projection they are. However I don't think we've used projections that way before, so if this adds a significant amount of extra effort we can drop that requirement for now.

### PR DESCRIPTION
**Pull request by ybnd**
## References

* Fixes #3286
* Related to [REST Contract - Bitstreams - Main Thumbnail]( https://github.com/DSpace/RestContract/blob/main/bitstreams.md#main-thumbnail)
* Related to [REST Contract - Items - Main Thumbnail](https://github.com/DSpace/RestContract/blob/main/items.md#main-thumbnail)

## Description

Implement thumbnail endpoints for Bitstream` and Items

* `/api/core/bitstreams/<:uuid>/thumbnail`
* `/api/core/items/<:uuid>/thumbnail`

## Instructions for Reviewers

List of changes in this PR:

* New method `BitstreamService#getThumbnail`
  * Looks up a matching thumbnail in the "sibling THUMBNAIL Bundles" of the Bundles the  Bitstream is included in
  * `<name>.<ext>` → thumbnail name `<name>.<ext>.jpg`
* `BitstreamThumbnailLinkRepository`
  * Exposes `BitstreamService#getThumbnail` at `/api/core/bitstreams/<:uuid>/thumbnail`
* `ItemThumbnailLinkRepository`
  * Exposes `ItemService#getThumbnail` at `/api/core/items/<:uuid>/thumbnail`

**Reviewing:**

1. Select (or create) an Item with some Bitstreams and corresponding thumbnail Bitstreams
2. Open the Item in the HAL browser
   * [ ] should contain a link `thumbnail`
   * [ ] it should link to the thumbnail of the primary Bitstream (if specified)
   * [ ] otherwise, it should link to the thumbnail of the first Bitstream in the ORIGINAL Bundle
3. Open the Item's ORIGINAL Bitstream(s) in the HAL browser
   * [ ] should contain a link `thumbnail`
   * [ ] it should link to the Bitstream's thumbnail

## Checklist

_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by tdonohue** [comment]
Also assign for review to @corrad82

**Comment by tdonohue** [comment]
@ybnd : As #3301 was just merged, this PR will need to be rebased on `main` in order to run the newly updated CI build process.

**Review by LucaGiamminonni — APPROVED** [review]
Thanks @ybnd , for me the changes are ok and can be merged

**Comment by corrad82-4s** [comment]
As already stated by my colleague @LucaGiamminonni , I approve this changes as well, thank you

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me as well @ybnd.  I tested it with the corresponding Angular PR (https://github.com/DSpace/dspace-angular/pull/1261) and found no obvious bugs. Also did some light testing from the HAL Browser. Thanks!

**Pull request merged**
