### PR TITLE
Add a configuration key to disable hierarchical browse indexes

### LINKED ISSUE #8947: Hierarchical browse indexes to create should be configurable
The hierarchical browse indexes are automatically generated based on the controlled vocabularies used in the submission forms and there is currently no option to disable them without removing from submission forms.

It may happen that you have defined a vocabulary in the submission form for which you do not want to create a browse index. There should be an option to configure which hierarchical browse index should be created.

### PR DESCRIPTION
**Pull request by toniprieto**
## References
* Fixes #8947 

## Description

This PR adds a new configuration key to be able to disable the creation of hierarchical browse indexes by vocabulary name.

If instead of excluding vocabularies to be created it is better to configure which ones to create specifically, let me know, I can change the logic of the configuration key.

## Instructions for Reviewers

Uncomment the configuration key and check that the srsc browse index is not generated.

If this is accepted, the documentation should be modified to add this new configuration key: https://wiki.lyrasis.org/display/DSDOC7x/Configuration+Reference#ConfigurationReference-HierarchicalBrowseIndexes

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
@toniprieto thank you, this is exactly what I was hoping for. We use a handful of controlled vocabularies, but don't necessarily want them to be automatically wired up as browse indexes. Your patch works well to disable unwanted browses.

> If instead of excluding vocabularies to be created it is better to configure which ones to create specifically, let me know, I can change the logic of the configuration key.

Yes, good question. Whether we want to use opt in or opt out logic, we need to improve the documentation on the wiki and in `dspace.cfg` so that people understand what's going on. I will let @tdonohue give his opinion. For me it was a surprise to see the browse indexes created automatically (with broken i18n string keys, etc).

**Comment by mwoodiupui** [comment]
Just to muddy the waters a bit more:  one could make e.g. `browseable=true|false` an attribute of the vocabulary itself.  That is:  set this in `config/controlled-vocabularies/*`.  That would probably want a redesign of the schema (which seems peculiar anyway) since this attribute only makes sense on the outermost `node`.

Or it could be an attribute of the entry field.  That would permit indexing in some forms or not others, which may make this proposal nonsensical.  It might require a larger overhaul of the indexing code.

Either one of these probably belongs in 8_x rather than 7_x (if it belongs anywhere).

I bring these up because they seem to bring the indexing decision closer to the description of that which is indexed, IMHO a good thing.  The current indexing configuration is already rather ugly and fragile.

**Comment by tdonohue** [comment]
I've flagged this as a bug & pulled it over to 7.6.x as I see there's a lot of concerns about this feature being "on by default" in Slack and on mailing lists (e.g. https://groups.google.com/g/dspace-tech/c/WN4imyGcoaI).   So, I'm considering this to be a bug as there's no way to turn it off.  The changes in this PR are also quite minor in nature and seem backwards compatible with 7.6

**Comment by pilasou** [comment]
@tdonohue +1 I agree. The impossibility to disable this feature should be considered a bug. I have tested the PR (thanks @toniprieto) and it worked as described. If the dspace.cfg lign is uncommented, the hierarchical browse is disabled.
srsc-disable

If the dspace.cfg lign is commented (# sign at the beginning of the line), the hierarchical browse is enabled.
srsc-enable

**Comment by BrandonKowalski** [comment]
@toniprieto thanks for the fix our instance needed this fix.

Just as a heads up, I noticed when applying this patch that the `By Subject Category` still appears for authenticated admin users, even with `srsc` disabled in the config.

Is this intended functionality for the admin users? We were under the impression that this re-added option would disable this feature unilaterally.

**Comment by toniprieto** [comment]
Hi @BrandonKowalski , 

No, it shouldn't appear for authenticated admin users.  I just tested it and it worked like this, it did not create the index for admins. I don't know why it creates it in your tests.

**Comment by BrandonKowalski** [comment]
@toniprieto DOH! Didn't reindex after patching. Sorry for crying wolf.

Appreciate the fix! Thanks again!

**Review by tdonohue — APPROVED** [review]
👍 Thanks @toniprieto !  This works well and looks good to me.  I did however push up a very small additional comment to the `dspace.cfg` changes.  I found this only works if you *reboot* Tomcat after changing this config (because these indexes are cached alongside the submission forms).  I don't think there's any easy way around it, but wanted to make sure it's noted in dspace.cfg.

**Comment by tdonohue** [comment]
I've added the docs for this new option to https://wiki.lyrasis.org/display/DSDOC7x/Configuration+Reference#ConfigurationReference-HierarchicalBrowseIndexes

**Pull request merged**
