### PR TITLE
(Work in Progress) Tiny PR to investigate broken ITs in recent PRs

### PR DESCRIPTION
**Pull request by tdonohue**
## Description
Several recent PRs to DSpace/DSpace all seem to be failing with the same IT failures:
```
Error:  Failures: 
Error:    EntityTypeRestRepositoryIT.getAllEntityTypeEndpoint:55 JSON path "$.page.totalElements"
Expected: is <8>
     but: was <7>
Error:    EntityTypeRestRepositoryIT.getAllEntityTypeEndpointWithPaging:83 JSON path "$.page.totalElements"
Expected: is <8>
     but: was <7>
Error:  Errors: 
Error:    EntityTypeRestRepositoryIT.findAllPaginationTest:142 » NullPointer
```
(These IT failures seem related to changes made in #8026, which worked 2 weeks ago, but now seem to be causing problems)

This failure strangely is not appearing on `main` (at least not in the [most recent build](https://github.com/DSpace/DSpace/actions/workflows/build.yml?query=branch%3Amain)) & I've not been able to reproduce it locally either. So, I'm trying this tiny PR to see if it triggers the same IT failure.

**Currently, this PR contains just a tiny, cosmetic change to the README to remove outdated information.**  If I find a way to reliably reproduce the IT failures, I'll enhance this PR to try to fix them

### CODE REVIEW

**Comment by tdonohue** [comment]
I've verified that our ITs **are definitely** failing on `main` now, when they succeeded just 8 days ago.

It appears that recently GItHub updated the virtual environment / linux version in the last few days.
* Old version (where tests worked)
  ```
  Environment: ubuntu-20.04
  Version: 20211108.1
  ```
* New version (where tests are failing)
  ```
  Environment: ubuntu-20.04
  Version: 20211114.1
  ```

It appears that this minor change has _changed the order in which our ITs run_.   The order of the ITs now is completely different (almost no simularities) to the old ordering
* Old order (where tests worked): https://github.com/DSpace/DSpace/runs/4183654863?check_suite_focus=true#step:5:999
* New order (where tests fail): https://github.com/DSpace/DSpace/runs/4269204593?check_suite_focus=true#step:5:999

It also appears that these newly failing tests are somehow fragile...in that the order in which the tests run is impacting their behavior.  Previously, the `EntityTypeRestRepositoryIT` ran very *early* in the list of ITs (and it succeeded).  Now, it runs very *late* in the list of ITs (and it fails).  _I've not yet determined why it's behavior changes based on where it runs in the IT list_

I've run out of time today to dig deeper, so this will need to wait for Monday.

**Comment by mwoodiupui** [comment]
failsafe's default `runOrder` is `filesystem`, so somewhat stable but unpredictable.  This is good:  it tends to reveal order-dependencies sooner or later.  If we want them sooner, we might use `random` instead.

If we can come up with some good "do this not that" rules for writing truly independent tests, that would be a good thing.  I often feel that I don't fully understand the potential sources of interference among tests.

**Comment by LucaGiamminonni** [comment]
Hi @tdonohue, I think the problem is that the destroy method of the InitializeEntitiesIT test deletes all the entity types present in the db, including the none type. So if it is executed before EntityTypeRestRepositoryIT then the type none is no longer present and some tests fail.

**Comment by tdonohue** [comment]
@LucaGiamminonni : Good catch! Yes, that'd do it. I haven't had a chance to dig into this yet, but that definitely sounds like the problem.  Did you want to create a small PR to fix that, or would you rather I did? (I might find time later today)

**Comment by LucaGiamminonni** [comment]
@tdonohue yes i can create a PR to solve this problem. I think modifying the destroy method to not delete the none entity type should work.

**Comment by tdonohue** [comment]
Closing, replaced by #8038

**Pull request closed without merging**
