### PR TITLE
DS-3729: Set the Bitstream deletion flag in the database

### PR DESCRIPTION
**Pull request by marsaoua**
https://jira.duraspace.org/browse/DS-3729

Needs to be cherry-picked to master too.

### CODE REVIEW

**Review by pnbecker — APPROVED** [review]
~~+1 This PR comes from my colleague, so other committers should review that.~~
Travis is complaining, obviously something is still wrong here. We'll take a close look. -> marked as work in progress.

**Comment by pnbecker** [comment]
@tomdesair You were right about the order of cleaning a bitstream's bundle and deleting it. Nevertheless there was a bug related to this. We added a code comment that should help understand the bug and our change.

I'm +1, but as noted before: it comes from my colleague, so I would appreciate more reviews.

**Comment by tomdesair** [comment]
+1

Makes sense and validated by Travis that the delete (in the unit tests) still works.

We shouldn't forget to port this to master.

**Review by hardyoyo — APPROVED** [review]
+1 by review, looks fine and passes tests

**Comment by pnbecker** [comment]
@hardyoyo thank you for merging. Did you cherry-picked this to master too or shall I?

**Comment by kshepherd** [comment]
apparently this is already ported to master, removing label

**Pull request merged**
