### PR TITLE
[DS-995] Upgrade XSLT processor to support XSLT 2/3

### LINKED ISSUE #4367: [DS-995] support XSLT 2.0 in XMLUI
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-995">[DS-995]</a> created by helix84</i>
<p>This issue is to track work needed to make XMLUI support XSL 2.0 (using Saxon).</p>

<p>Details why it was created are here:<br/>
<a href="http://dspace.2283337.n4.nabble.com/Why-does-DSpace-use-XSLT-1-0-td3750179.html" class="external-link" target="_blank" rel="nofollow noopener">http://dspace.2283337.n4.nabble.com/Why-does-DSpace-use-XSLT-1-0-td3750179.html</a></p>

### PR DESCRIPTION
**Pull request by J4bbi**
Fixes #4367 
Work-in-progress

This PR switches from the obsolete Xalan XSLT processor to the Saxon-HE 9.9.1-5 processor which is licensed under MPL 2.0 license. (http://www.saxonica.com/documentation/#!conditions)

For DSpace 6 everything works to the best of my knowledge for all the XMLUI themes (even the obsolete ones).

Reasons for changing to Saxon
 - Saxon is actively developed and has a user community
 - XSLT 2.0 supports date/time types, strong typing, string functions (replace, regular expressions), custom functions, and more.

See also:
https://stackoverflow.com/questions/16455276/saxon-9-xslt-transformer-vs-xalan-2-7
https://stackoverflow.com/questions/9387396/upgrading-xslt-1-0-to-xslt-2-0/9392424
https://support.adeptia.com/hc/en-us/articles/207874733-XALAN-vs-SAXON-Performance-Results
http://saxon-xslt-and-xquery-processor.13853.n7.nabble.com/Saxon-vs-Xalan-td9851.html

Some of the functionality under XSLT 1.0 like, shortenString has be done using XSLT 2.0+. Saxon-HE doesn't allow integrating Java classes unless calling the processor is done via Java as well (see: https://www.saxonica.com/html/documentation/extensibility/integratedfunctions/).

The ConfigurationManager class which is called under the namespace confman has been supplemented by embedding the variables in the DRI. This approach of embedding the variables in the XML for the Saxon to consume directly is, in my opinion, a better way than calling Java classes via Saxon. This also frees up the cluttered XSL namespace.

Mark Wood's done impressive work in #2624 whereby he's wrapped calling the Saxon processor into a Java class at a level where I admit I don't fully understand the mechanics at play. A definite advantage to Mark's approach is the flexibility allowed in being able to access a Java class, this is likely only required in heavily customised cases.

### CODE REVIEW

**Comment by mwoodiupui** [comment]
We can define our own functions in the `confman` prefix.  I have tested this much.

But we need to (somehow) provide the TransformerFactory that Cocoon will use.  I think we can wrap SaxonTransformerFactory in a class that configures it with our custom functions, and declare it as `transformer-factory` in cocoon.xconf.  I have *not* tested this.

**Comment by J4bbi** [comment]
> We can define our own functions in the `confman` prefix. See https://github.com/mwoodiupui/confman-demo
> 
> We'd need to wrap the Saxon TransformerFactory instead of using it directly, so that we can configure it.

@mwoodiupui , that's certainly one way to go. I talked to @kshepherd about another possibility which is to embed the config values needed in the dri, for instance in pagemeta. what do you think?

**Comment by mwoodiupui** [comment]
That's certainly another way to go.  There are, I think, 23 distinct configuration names referenced in stock DSpace XSL.  We'd probably want to make a configurable list.

**Comment by mwoodiupui** [comment]
shortenString() is also used in the original Mirage theme, and this causes:

> net.sf.saxon.trans.XPathException: Cannot find a 3-argument function named Q{http://www.dspace.org/xmlns/dspace}shortenString()
> context:/file:///home/mwood/dspaces/DS-995/webapps/xmlui/themes/Mirage/lib/xsl/aspect/artifactbrowser/collection-list.xsl - 68:0
The definition will need to be copied, or better yet moved to a more central location.

**Comment by J4bbi** [comment]
> That's certainly another way to go. There are, I think, 23 distinct configuration names referenced in stock DSpace XSL. We'd probably want to make a configurable list.

Yes. I guess. I'm leaning toward embedding these configurables into the DRI. But I don't have a strong opinion.

The only thing that might complicate things is that the variables have to load dynamically, as in it has to be reloadable like the config itself.

**Comment by J4bbi** [comment]
> shortenString() is also used in the original Mirage theme, and this causes:
> 
> > net.sf.saxon.trans.XPathException: Cannot find a 3-argument function named Q{[http://www.dspace.org/xmlns/dspace}shortenString()](http://www.dspace.org/xmlns/dspace%7DshortenString())
> > context:/file:///home/mwood/dspaces/DS-995/webapps/xmlui/themes/Mirage/lib/xsl/aspect/artifactbrowser/collection-list.xsl - 68:0
> > The definition will need to be copied, or better yet moved to a more central location.
Yes. I hadn't really looked at Mirage. Is there an XSL of shared resources between Mirage and Mirage2?

**Comment by J4bbi** [comment]
The following two templates are not catching the head and item-view toggles and therefore they get rendered on the item-view page.

https://github.com/DSpace/DSpace/blob/2975cdbe7b7745271b130f55fe254f7e4195c895/dspace-xmlui-mirage2/src/main/webapp/xsl/aspect/artifactbrowser/item-view.xsl#L496-L503

**Comment by tdonohue** [comment]
I'd recommend we close this as "won't fix".  This looks like a significant change, and we need to keep 6.x to bug fixes only.  If anyone disagrees, let me know

**Comment by J4bbi** [comment]
Agreed

**Pull request closed without merging**
