### PR TITLE
DS-4327 Configurable workflow: Provenance metadata lacking submitter details

### LINKED ISSUE #7667: [DS-4327] Configurable workflow: Provenance metadata lacking submitter details
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4327">[DS-4327]</a> created by bram</i>
<p>To reproduce this:</p>
<ol>
	<li>Ensure you have configurable workflow active, and not the legacy workflow</li>
	<li>Submit an item to a collection that doesn't have any workflow steps enabled. Submission should appear in recent submissions immediately after the original submission.</li>
	<li>As admin, look at the dc.description.provenance metadata field</li>
</ol>

<p>You will see something like:</p>

<p><span class="image-wrap" style=""></span></p>

<p>While you are also expecting details about the submitter in there.</p>

<p>In contrast, when a workflow step IS active, there IS an entry that references the original submitter:</p>

<p><span class="image-wrap" style=""></span></p>

<p>This is an important issue for repositories with many different submitters, and where workflow steps are turned off. Without a fix for this, it is not possible for admins to see which items were submitted by which EPeople.</p>

<p> </p>

### PR DESCRIPTION
**Pull request by jonas-atmire**
The DSpace 6 version fix for the issue mentioned here:
https://jira.duraspace.org/browse/DS-4327

Fixes #7667

The recordStart method has been changed to also allow a null 'action'. When no actual workflow steps are enabled, this provenance is now also created, where previously, this was skipped.

### CODE REVIEW

**Review by kshepherd — APPROVED** [review]
+1 looks good to me, untested

**Comment by kshepherd** [comment]
doing the "close and reopen" tick to kick off the new travis CI build

**Review by nwoodward — APPROVED** [review]
:+1: Tested and confirmed this works. New items had two dc.description.provenance entries: one for "Made available in DSpace..." and one for "Submitted by...".

**Comment by tdonohue** [comment]
@jonas-atmire : Could you please port this to `main` as well?  It looks like it's ready to go for 6.4...but we obviously need to ensure this fix makes it back to 7.x

**Pull request closed without merging**
