### PR TITLE
DS-4428 missing parameter exception

### PR DESCRIPTION
**Pull request by Micheleboychuk**
As by https://jira.lyrasis.org/browse/DS-4428
 - added separate exception handler to manage the report for missing required parameters in all REST API v7 endpoints
- fixed unit test that should return 400 BAD REQUEST

**Question**: should we return 400 also when the parameter is supplied but fails to be converted, i.e when a QueryMethodParameterConversionException?

### CODE REVIEW

**Comment by abollini** [comment]
I have reviewed once again the definition of 400 and 422. The definition of 422 is

> The 422 (Unprocessable Entity) status code means the server
   understands the content type of the request entity (hence a
   415(Unsupported Media Type) status code is inappropriate), and the
   syntax of the request entity is correct (thus a 400 (Bad Request)
   status code is inappropriate) but was unable to process the contained
   instructions.  For example, this error condition may occur if an XML
   request body contains well-formed (i.e., syntactically correct), but
   semantically erroneous, XML instructions.

according to that I guess that if we get a json file when we expect an xml we should return a 400, getting a String when we expect an Integer is imho the same, so 400 is also the appropriate return code for QueryMethodParameterConversionException.
@tdonohue @benbosman do you agree?

**Comment by tdonohue** [comment]
@abollini  & @benbosman :  I'm starting to wonder if we should be using 422 *at all*.   On closer look, the 422 status code was introduced for WebDAV in this RFC: https://tools.ietf.org/html/rfc4918

It seems like we really should be using 400 everywhere, unless we ever find a situation where a request actually is valid but semantically incorrect (which seems very unlikely for DSpace -- I cannot think of a scenario where this would be true).  So, I'm starting to wonder if we should remove 422 from the REST API entirely and replace it with 400 requests.   

(That all said, I don't mind if we move this PR forward as-is and do further cleanup in other followup PRs)

**Comment by abollini** [comment]
I copy here some additional comments that were exchanged on slack

@abollini 

> 422 is appropriate when there is a semantic issue with the request. For instance a valid patch to withdrawn an item, if the item is a workspace should return 422

@cwilper 

> That particular case seems more like a 409 conflict -- the request can't be honored due to the state of the target resource. As a data point, I see that aws s3 rest api uses  400 and 409 quite a lot to indicate various interesting "semantic" request issues...but not 422. https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Comment by abollini** [comment]
For this specific PR @Micheleboychuk  I recommend to update also the handling of `QueryMethodParameterConversionException` to return 400 instead than 422.

I have created a separate ticket https://jira.lyrasis.org/browse/DS-4435 to consider the use of `409` for some scenario as well. Keep in mind that more specific / different (but obviously meaningful) codes we will be able to return more information we will provide to the client to handle (or debug) the issue

**Review by tdonohue — APPROVED** [review]
👍 The code here looks good to me, and it has tests to prove that it works.  Thanks @Micheleboychuk & @abollini !

**Comment by tdonohue** [comment]
Merging, as this was flagged for one approval by the DSpace 7 team.  Thanks again @Micheleboychuk and @abollini for your hard work here!

**Pull request merged**
