### PR TITLE
Remove unused `useProxies` to avoid NPE when debugging

### PR DESCRIPTION
**Pull request by mwoodiupui**
## Description
Remove unused field that causes NPE when debugging.

## Instructions for Reviewers
List of changes in this PR:
* Tidy up the code and comments.
* Remove "useProxies" which is only touched in one debug logging statement, and NPEs because it is never set.

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@mwoodiupui : I think this might be a duplicate of #8781 ?

**Comment by mwoodiupui** [comment]
*sigh* It is.

**Comment by tdonohue** [comment]
@mwoodiupui : If you'd rather review #8781 , we can move it forward quickly.  It's one of those small fixes that I simply haven't found time to test out...but it looks "right".

**Comment by mwoodiupui** [comment]
Duplicate of earlier PR.

**Pull request closed without merging**
