### PR TITLE
Alteration to index-discovery script to only (re-)index specific type of IndexableObject

### PR DESCRIPTION
**Pull request by MarieVerdonck**
## Description
Alteration to index-discovery script to only (re-)index specific type of IndexableObject

## Instructions for Reviewers
- With `-t` option, help output logs options of types of `IndexableObject` with indexing factory
- Not compatible with `-b` option since this clears entire index first (& expect to rebuild it in its entirety) 
- Compatible with `-f` to force reindex specific type of `IndexableObject`

Test option `-t`
- Clear solr search core
- Run `ds index-discovery -t MetadataField` => Verify all metadata fields are indexed
- Also testable with: `ClaimedTask, Collection, Community, Item, PoolTask, XmlWorkflowItem, WorkspaceItem`

With `-f` option:
- Alter config so more things are indexed on an Item, eg virtual metadata for an item with relationship
- Run `ds index-discovery -f -t Item` => Verify the changes are indexed & only the Item docs are reindexed

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@MarieVerdonck : Thanks for this!  This is very useful...and I was able to verify it works from the Processes UI as well.   **However**, I noticed there's no validation for the `--type` option.  I can pass in `--type NOTVALID` and the index-discovery script will still run:
```
/dspace/bin# ./dspace index-discovery -t NOTVALID
The script has started
Updating Index
Done with indexing
The script has completed
```

Could we add some basic validation for this new option?  It seems like it should throw an error if the passed in type doesn't match one of the IndexObjectFactory options.

Beyond that, I'm +1 this PR.  It just needs validation for the new param.

**Comment by MarieVerdonck** [comment]
@tdonohue : Added validation for the type option value, with list of allowed types.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @MarieVerdonck !  This looks good now and works well.

Merging immediately.  But, I'm also flagging as "needs documentation" as we should update the indexing script docs for DSpace 8 in https://wiki.lyrasis.org/display/DSDOC8x/Discovery#Discovery-DiscoverySolrIndexMaintenance   If you have a chance to add this new param to those docs, I'd appreciate it.

**Comment by tdonohue** [comment]
Removing "needs documentation" flag as docs exist at https://wiki.lyrasis.org/display/DSDOC8x/Discovery#Discovery-DiscoverySolrIndexMaintenance

**Pull request merged**
