### PR TITLE
DS-4211: Set Item iterator to emptyIterator() so that it's never null (6.x)

### PR DESCRIPTION
**Pull request by nwoodward**
Fixes https://jira.duraspace.org/browse/DS-4211

### CODE REVIEW

**Comment by mwoodiupui** [comment]
This looks like it will work.  But would it not be better to instead initialize `result` to `Collections.emptyIterator<Item>()` rather than `null`?  Then `addItemsToResult()` will *always* return an `Iterator<Item>` and no null check is necessary here or elsewhere.

It might be even better to change the `Iterator` to a `List<Item>`, add `Item`s to it in the normal way, and return the value of its `#iterator()` method.

**Comment by nwoodward** [comment]
Yeah, an empty iterator would be better. I assume you're talking about the Collections from commons-collections? I don't see an emtpyIterator class that takes a type in version 3.2.2, so I thought I'd ask.

**Comment by mwoodiupui** [comment]
No, I'm talking about java.util.Collections.emptyIterator().

**Comment by nwoodward** [comment]
How does it look now?

**Review by kshepherd — APPROVED** [review]
+1 looks like an easy win, thanks @nwoodward !

**Review by mwoodiupui — APPROVED** [review]
+1 by inspection.  Yes, that should work.

**Pull request merged**
