### PR TITLE
Disable the copy request for specific DSpace objects

### LINKED ISSUE #8290: Configuring Request a copy on a per collection basis
In DSpace, requesting copy can only be set for the entire repository (https://wiki.lyrasis.org/display/DSDOC7x/Request+a+Copy).  

The objective is to allow to configure the request copy feature for the entire repository (current DSpace behavior) or on a per collection basis using configuration parameters.  

This possibility would allow a more flexible way to manage access to document under embargo. The 2 use cases below tend to emphasis some benefits:  

- Use case 1: each collection in the repository is a publication type (Book, Book Chapter, Article, Research Reports).  Depending on the collection, it may be tricky, in a legal point of view, to offer to obtain a copy of the entire document under embargo (ex: Books, reports). 
- Use case 2 : each collection is a unit of the institution (Research Center, etc.) and is managed by the unit. For each collection, the unit can decide to activate request a copy or not. 

This development will add or change configuration parmeters as they already exist in DSpace. It is not planned to add Angular UI pages for it.

### PR DESCRIPTION
**Pull request by nibou230**
## References
* Fixes #8290

## Description
Added the possibility to disable the copy request feature based on a new configuration `request.item.restricted`. This configuration is enumerating the GUID of DSpace objects for which the feature should be disabled.

## Instructions for Reviewers
Add the new configuration in the file `local.cfg` with at least one valid GUID of DSpace object where you don't want the copy feature to be enabled.

```
# List (comma-separated) of DSpace object UUID (communities, collections, items, others)
# for which the request-copy feature must be disabled.
# request.item.restricted = item-uuid-1, \
#                           item-uuid-2, \
#                           item-uuid-3
```

List of changes in this PR:
* Added a configuration example in the file `dspace.cfg`.
* Implemented the restriction functionality in the class `RequestCopyFeature` by looking at the GUID for the object itself, but also for the GUID of every parent in the hierarchy.
* Added some tests in the class `RequestCopyFeatureIT` to cover some use cases.

**If the copy request feature is disabled using this new configuration, for anonymous users, clicking on a copy request link will show the login page. If the user is logged in, it will show a 403 forbidden access.**

## Checklist
- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by tdonohue** [comment]
Moving this to the 7.4 release as we won't be able to test/approve in time for 7.3.

**Review by abollini — CHANGES_REQUESTED** [review]
thanks @nibou230 for your contribution.
I have a suggestion that would imho improve a lot the usability of this feature. You could use a metadata, I suggest the dspace schema something like `dspace.requestcopy.disabled`, that when set to `true` will act exactly as the uuid in the configuration file as by your proposal.
This metadata can be set easily via the UI for Item and Bitstream (during the submission) but in all case can be set also for community and collection via REST API. A gui can came later. @tdonohue  can you provide a feedback on this idea as well?

That said, you need to modify also the authorization check on the `org.dspace.app.rest.repository.RequestItemRepository` otherwise a smart user can still trigger the flow manually via REST API. To do that you will need to create your own implementation of `org.dspace.app.rest.security.RestObjectPermissionEvaluatorPlugin` and set an authorization annotation like that in the Rest Repository
```
@PreAuthorize("hasPermission(#id, 'REQUESTITEM', 'ADD')")
``` 
where `REQUESTITEM` will be used in your evaluator plugin implementation.

**Comment by mwoodiupui** [comment]
I agree with the suggestion by @abollini that metadata is a better place to keep this information.  Clearly it is a property of the individual object rather than of the DSpace instance as a whole.  It makes good sense to minimize the "logical distance" between the setting and its subject.

Also:  storing it in metadata makes it easily accessible to a community or collection administrator, who might not have ready access to the instance's configuration files.  This is just the sort of thing that we should be devolving to those most interested in managing it.

**Comment by tdonohue** [comment]
@nibou230 : Based on the feedback of @abollini and @mwoodiupui , it does seem like there's a strong favoritism for the approach of configuring this via metadata.  As @abollini notes, that doesn't mean that a UI screen is required. But, it does mean we'd want to clearly document the metadata field that should be added to disable copy request.  

I just realized this discussion has become a repeat of one already had in the ticket #8290, where we had a (very brief) discussion of metadata vs config approaches... unfortunately, at the time no other developers were able to provide feedback (as we were in the midst of finishing up 7.3 so all new PRs were set aside).  

@nibou230 : Let us know if you'd like help updating this PR based on the feedback... I see in the ticket you mentioned that you may not have time to change this feature into metadata-based. If that's the case, I could look for other volunteers to take this forward (and we can make sure you are still credited with the initial feature).

**Comment by nibou230** [comment]
Hi @tdonohue, @abollini, @mwoodiupui,

Thanks for the feedback! As you mentionned, we already took position in late may on how we implemented this fonctionnality and favor global config over metadata. We also explained why it makes more sense to us to proceed this way (see: https://github.com/DSpace/DSpace/issues/8290#issuecomment-1141400587)

Unfortunately, we miss time to invest and convert this PR to use metadata instead of global configurations. It would be much appreciated to have someonelse that can help going forward to do so.

@abollini also mentionned that it is possible to trigger the copy request process via the REST API and it's a good point! I probably will take a look at this part and add an authorization check to prevent this behavior.

**Comment by tdonohue** [comment]
Closing this PR as there was general agreement that we'd highly prefer an approach which uses metadata instead of hardcoded configs.  That said, obviously others are welcome to adopt this PR as needed.

**Pull request closed without merging**
