### PR TITLE
[DS-4200] IPMatcher: Fix netmask conversion

### PR DESCRIPTION
**Pull request by AlexanderS**
The old netmask conversion code (from prefix length to a bitmask) did not work for a 128 prefix.

https://jira.duraspace.org/browse/DS-4200

_(I will backport this fix to dspace-6_x and dspace-5_x once merged into master.)_

### CODE REVIEW

**Comment by tdonohue** [comment]
@AlexanderS : Could we add new Unit Tests that show the improved behavior?  I.e. a test that failed previously but now will succeed?  This class already has existing tests in https://github.com/DSpace/DSpace/blob/master/dspace-api/src/test/java/org/dspace/authenticate/IPMatcherTest.java

I have no objections to the code changes in this PR, but they are definitely not obvious.  It's good to see old tests pass, but it'd be better to have new tests that prove this bug is fixed.

**Comment by AlexanderS** [comment]
@tdonohue Sure, I will add a test.

**Comment by AlexanderS** [comment]
@tdonohue New test was added.

**Review by tdonohue — APPROVED** [review]
Thanks! 👍 Looks good to me now that it has a test to prove.

**Comment by tdonohue** [comment]
I just closed & reopened this PR to trigger a current Travis rebuild.  If it succeeds, I think this should be merged, as it's an obvious fix to me, and the LGTM bot noted it fixes an array out of bounds exception.

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me.  Travis approves, as does LGTM bot.  Merging this as it seems like an obvious fix & includes tests.

**Pull request merged**
