### PR TITLE
Patch Add entire array with virtual values does not work

### LINKED ISSUE #3214: Patch Add entire array with virtual values does not work
**Describe the bug**
When we try to execute a patch add request of a metadata with multi values in presence of _at least one virtual value_, an exception is thrown and 500 error returned.

**To Reproduce**
The easiest way to reproduce is testing by running the work of the https://github.com/DSpace/dspace-angular/pull/1025.

1. Start a submission in [this collection ](http://localhost:4000/submit?collection=dd1240ae-d7dd-405c-bdc3-d6c960609433) on the api7.dspace.org backend
2. Add a virtual value to the author field through the lookup feature.
3. Add a second value (plain value)
repeatable1
4. Click on Save
repeatable2

**Expected behavior**
The patch operation should be successful.

**Related work**
This is related to https://github.com/DSpace/dspace-angular/pull/1025

### PR DESCRIPTION
**Pull request by alemarte**
## References
* Fixes https://github.com/DSpace/DSpace/issues/3214

## Description
The Patch ADD Operation of an array of values now support the presence of pre-existent virtual metadata. 
Virtual metadata related to existent relations can be now moved or deleted through this API. 

## Instructions for Reviewers
List of changes in this PR:
* The [replaceValue](https://github.com/4Science/DSpace/blob/047c2850ce069b759f00db0067e3296709717c5a/dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/factory/impl/ItemMetadataValueAddPatchOperation.java#L133) method of ItemMetadataValueAddPatchOperation takes into account the presence of virtual metadata that are preserved (and repositioned when needed, updating the relationship's leftPlace/rightPlace as happen for example during a simple move operation). In this way we can preserve also the previous relationship's ids.
* Plain metadata instead are cleared and recreated as before, with a slightly different requirement, the possibility to force the place field. To do this an extra [addMetadata](https://github.com/4Science/DSpace/blob/047c2850ce069b759f00db0067e3296709717c5a/dspace-api/src/main/java/org/dspace/content/service/DSpaceObjectService.java#L390) method has been added which takes a place argument too. The standard implementation wasn't correct because the place was computed counting all the existent relationships, but they could have been moved just after the processed value, so the place were not correct.

Integration tests:
1) [patchAddAllAuthorsOnTraditionalPageTest](https://github.com/DSpace/DSpace/blob/047c2850ce069b759f00db0067e3296709717c5a/dspace-server-webapp/src/test/java/org/dspace/app/rest/PatchMetadataIT.java#L1177)
In this case we test that virtual metadata can be deleted/moved to different positions, mixed with plain metadata values.

2) [patchAddAllAuthorsOnTraditionalPageNotExistentRelationTest](https://github.com/DSpace/DSpace/blob/047c2850ce069b759f00db0067e3296709717c5a/dspace-server-webapp/src/test/java/org/dspace/app/rest/PatchMetadataIT.java#L1199)
With this test we try to provide an authority of type "virtual::id" that does not exist. So we get a 422 error.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ ] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by benbosman — CHANGES_REQUESTED** [review]
I did an initial test with the latest main, and discovered the following issues:
* Deleting a related entity no longer works correctly. It displays the entity as still related until you refresh the page: https://www.dropbox.com/s/3659knfp6l8pqt7/Schermopname%202021-04-08%20om%2013.18.11.mov?dl=0
* If you don't save prior to adding a relationship, the relationships are broken https://www.dropbox.com/s/zpv4svo9o58dknv/Schermopname%202021-04-08%20om%2013.24.58.mov?dl=0

I didn't perform any further reviews

**Comment by alemarte** [comment]
@benbosman thanks for your review!

> I did an initial test with the latest main, and discovered the following issues:
> 
> * Deleting a related entity no longer works correctly. It displays the entity as still related until you refresh the page: https://www.dropbox.com/s/3659knfp6l8pqt7/Schermopname%202021-04-08%20om%2013.18.11.mov?dl=0

This is an old behaviour, as I remember it was present even before merging https://github.com/DSpace/dspace-angular/pull/960
Unfortunately those selected items are completely detached from the form state and they are not kept in sync (until as you noticed a full page refresh occurs).

> * If you don't save prior to adding a relationship, the relationships are broken https://www.dropbox.com/s/zpv4svo9o58dknv/Schermopname%202021-04-08%20om%2013.24.58.mov?dl=0
> 

This should not happen since every time the lookup modal is opened there is an automatic submission save. I'll give it a quick look.

Apart from possible problems Angular side which has a very complicated state management, I'd appreciate to know if at least Rest side the responses and modification are consistent and act as expected.

**Comment by alemarte** [comment]
@benbosman I've given a look at the second point and I've found a couple of bugs angular side. 

I've opened https://github.com/DSpace/dspace-angular/issues/1091 for it.

**Review by benbosman — CHANGES_REQUESTED** [review]
Thanks @alemarte 

I've reviewed your code in detail now, and I only noticed one thing:
You've added the new solution to perform patch add on an entire array, but only created one IT to verify that works, where the IT only uses plain metadata

Can you add ITs similar to patchAddAllAuthorsOnTraditionalPageTest:
* Proving this also works when a few objects are a virtual metadata field
* Proving this also works when all object are a virtual metadata field

I will check the Angular PR out as well

**Comment by benbosman** [comment]
I've been testing this branch in combination with https://github.com/DSpace/dspace-angular/pull/1092, but can't tell for sure whether it's an Angular or REST issue.

But I did notice all non-Publication submissions are broken when I try to use them
I've tested the Person and Journal Issue submission. I did want to test them because they use a submission field which is a relationship not linked to plain text metadata
The Person has a lookup for a Publication. The Journal Issue has a lookup for a Journal Volume
When adding the relationship, the UI doesn't display it
When refreshing the page, only part of the page loads: https://www.dropbox.com/s/avzrgbdi0ah8cws/Schermafbeelding%202021-04-09%20om%2015.39.34.png?dl=0

**Comment by alemarte** [comment]
@benbosman thanks for your feedback.

> Thanks @alemarte
> 
> I've reviewed your code in detail now, and I only noticed one thing:
> You've added the new solution to perform patch add on an entire array, but only created one IT to verify that works, where the IT only uses plain metadata
> 
> Can you add ITs similar to patchAddAllAuthorsOnTraditionalPageTest:
> 
> * Proving this also works when a few objects are a virtual metadata field
> * Proving this also works when all object are a virtual metadata field
> 
> I will check the Angular PR out as well

[patchAddAllAuthorsOnTraditionalPageTest](https://github.com/DSpace/DSpace/blob/047c2850ce069b759f00db0067e3296709717c5a/dspace-server-webapp/src/test/java/org/dspace/app/rest/PatchMetadataIT.java#L1177) already covers the case with several mixed values (plain and virtual). It should ensure that all work properly.


> I've been testing this branch in combination with [DSpace/dspace-angular#1092](https://github.com/DSpace/dspace-angular/pull/1092), but can't tell for sure whether it's an Angular or REST issue.
> 
> But I did notice all non-Publication submissions are broken when I try to use them
> I've tested the Person and Journal Issue submission. I did want to test them because they use a submission field which is a relationship not linked to plain text metadata
> The Person has a lookup for a Publication. The Journal Issue has a lookup for a Journal Volume
> When adding the relationship, the UI doesn't display it
> When refreshing the page, only part of the page loads: https://www.dropbox.com/s/avzrgbdi0ah8cws/Schermafbeelding%202021-04-09%20om%2015.39.34.png?dl=0

This seems to be an Angular issue. We tried to reproduce it but we haven't found a suitable configuration on the demo. From what we have seen it seems that the [configurations you mentioned](https://github.com/DSpace/DSpace/blob/10bfce55856914af7a3d339adb57b44c65b900c2/dspace/config/submission-forms.xml#L248) don't have a virtual metadata related to the submission.
Is this configuration correct? If true how it should be handled in the context of the submission without a related virtual metadata?

@tdonohue 

In our opinion this PR covers and solves the problems described in the https://github.com/DSpace/DSpace/issues/3214. 

If there are other problems related to relations managing they should be tackled by dedicated tickets. 

We should remember that a refactoring work is already planned for version 7.1 anyway. Here the references https://github.com/DSpace/DSpace/issues/2953 https://github.com/DSpace/dspace-angular/issues/858

**Comment by tdonohue** [comment]
@alemarte and @benbosman :  I've done some testing of this alongside the frontend PR (https://github.com/DSpace/dspace-angular/pull/1092) and with this updated configuration in place (https://github.com/DSpace/DSpace/pull/3232).

Overall, the basics seem to work.  I agree with @alemarte that the scope of this PR should not include issues with adding Relationships (I'm also seeing issues there, but I don't believe they are related to this PR -- I admit, I haven't been able to debug them fully yet, but they seem to already exist on `main`).  I **have** been able to add other Entity types, as long as I use the updated configuration in #3232 -- so, I think this is a configuration problem on the demo site.

I'll do some more testing on Monday, but I wanted to note that the overall direction here seems fine.  However, I do think we still have some bugs in the Entity submission process around creating **new relationships** (especially by importing from ORCID or similar, where you create a new Person object based on an ORCID and attempt to link to a Publication).  But, at least as of now, I think those are unrelated to this PR.

**Review by benbosman — CHANGES_REQUESTED** [review]
Thanks for clarifying https://github.com/DSpace/DSpace/blob/047c2850ce069b759f00db0067e3296709717c5a/dspace-server-webapp/src/test/java/org/dspace/app/rest/PatchMetadataIT.java#L1177 did indeed add the necessary IT. I missed it included virtual authors.

This PR in combination with https://github.com/DSpace/dspace-angular/pull/1092 sadly still doesn't fix the bugs introduced in https://github.com/DSpace/dspace-angular/pull/1025

I've tested it with Tim's configuration and database from https://github.com/DSpace/DSpace/pull/3232, but the submission of a Person entity, and relating it to a Publication entity, keeps failing

**Review by benbosman — APPROVED** [review]
Based on my testing, the issues are all in the Angular part, so I'm approving this REST PR

**Review by tdonohue — APPROVED** [review]
👍 I've tested this today and I agree with @benbosman that this all appears to work.  There are still frontend bugs, but I believe this fixes issues on the backend.  Therefore, I'm going to merge this in order to help with testing the frontend with a common backend

**Pull request merged**
