### PR TITLE
[DS-3616] Fix nested vocabulary search (#1770)

### PR DESCRIPTION
**Pull request by edusperoni**
https://jira.duraspace.org/browse/DS-3616

### CODE REVIEW

**Comment by edusperoni** [comment]
Huh? Travis failed for some reason. Doesn't seem to be related to this PR, though.

**Comment by tdonohue** [comment]
@edusperoni : we have a few unit tests on our `master` branch that have been flakey as of late...namely some in `ItemTest`, and a few Integration Tests that sometimes run slower than we expect (and if they are too slow, that results in an Integration Test failure).

In any case, I've restarted your Travis PR build and it worked the second time around.

**Comment by nix1947** [comment]
Hello everyone, I was testing dspace with custom forms. I got this error on  `bitstore.xml` file. Here is the error log.
```
test_database:
     [java] 2017-06-13 14:15:12,577 WARN  org.springframework.context.support.ClassPathXmlApplicationContext @ Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'localStore' defined in file [/dspace/config/spring/api/bitstore.xml]: Could not resolve placeholder 'assetstore.dir' in string value "${assetstore.dir}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'assetstore.dir' in string value "${assetstore.dir}"
     [java] 2017-06-13 14:15:12,579 ERROR org.dspace.servicemanager.DSpaceServiceManager @ Failed to startup the DSpace Service Manager: failure starting up spring service manager: Invalid bean definition with name 'localStore' defined in file [/dspace/config/spring/api/bitstore.xml]: Could not resolve placeholder 'assetstore.dir' in string value "${assetstore.dir}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'assetstore.dir' in string value "${assetstore.dir}"
     [java] java.lang.IllegalStateException: failure starting up spring service manager: Invalid bean definition with name 'localStore' defined in file [/dspace/config/spring/api/bitstore.xml]: Could not resolve placeholder 'assetstore.dir' in string value "${assetstore.dir}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'assetstore.dir' in string value "${assetstore.dir}"
     [java] 	at org.dspace.servicemanager.DSpaceServiceManager.startup(DSpaceServiceManager.java:215)
     [java] 	at org.dspace.servicemanager.DSpaceKernelImpl.start(DSpaceKernelImpl.java:153)
     [java] 	at org.dspace.servicemanager.DSpaceKernelImpl.start(DSpaceKernelImpl.java:128)
     [java] 	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:49)
```

**Comment by edusperoni** [comment]
Testing this over a long period of time I ran into a problem. Since it matches any children, when I imported some records iareactually imported with the wrong authority (since it found one with a similar name before the exact match).

The solution I wrote feel a bit hacky:

Given the example

AAA::BBB::CCC

This PR would returns results like:

AAA::BBBA:CCC
AAA::DDD:BBB:CCCA
AAA::BBB::CCC

As you can see, the exact match is lower on the list. If you're importing a record, it would select AAA:BBBA:CCC as the authority value.

So instead of doing matching every node with the xpath //contains(aaa)//contains(bbb)//contains(ccc), I opted to write:

1. If the search has no delimiter (single node), search the entire tree. (this is the current behavior)
2. If it has more than one node
    2.1. Match the first node exactly, anywhere on the tree.
    2.2. Any node in the middle should be matched exactly and be a direct child of the previous node
    2.3. The last node is a startswith (or contains) match
    2.4. This would never match the node's children, so there's an OR operation to match the children aswell


I feel like this is better. For one, it will only print the exact node you're searching for and all of it's children.
The search/suggest would also work, since you start typing AAA and will keep following the structure. The startswith in the end guarantees it will not get confused with other direct child nodes. The "OR" operator in the end will get the nested nodes, which helps the search.

I'd like some feedback on this, so I can add it to the PR

**Comment by kshepherd** [comment]
hi @edusperoni  I've merged #1770 but this master version results in conflicts now (due to subsequent changes in the target file I guess). Could you try and resolve these in your branch/PR and commit up so we can merge this into master? Cheers

**Comment by tdonohue** [comment]
Closing as this PR was rebased & merged in #2147

**Pull request closed without merging**
