### PR TITLE
DS-3522 Ensure Submission Policies are removed in XMLWorkflow

### PR DESCRIPTION
**Pull request by aprilherron**
See JIRA: https://jira.duraspace.org/browse/DS-3522

### CODE REVIEW

**Comment by terrywbrady** [comment]
+1, code looks sensible.  I do not know xml workflow well

**Comment by abollini** [comment]
+1 for me as well

**Review by lap82 — APPROVED** [review]
I ends with the same modification in other PR marked as duplicate. So, my +1

**Comment by tdonohue** [comment]
Closing as this fix was already applied to 6.x (#1779) and main (#2146).   5.x is in security fix only mode.

**Pull request closed without merging**
