### PR TITLE
DS-2262 Checking if the context is valid before aborting it + Context refactor

### PR DESCRIPTION
**Pull request by joao-de-melo**
This PR only fixes the first issue of the list.

### CODE REVIEW

**Comment by lyncodev** [comment]
Core changes to Context class:

- lowering the log level
- abort() & complete() cleanup identical

**Comment by robintaylor** [comment]
Hi, just a daft question - if the error messages generated in Context indicate that we have called complete() or abort() when we shouldn't have, then should we not be fixing the calling code rather than suppressing the error messages? 

Other than that the code is just a tidy up rather than adding new functionality so shouldn't cause a problem. Having said that, Context is the most important class in the code so this change should definitely get released to the demo server and tested before any final release.

Cheers.

**Comment by lyncodev** [comment]
That's a good point. I realised that:

- isValid is called always before context.abort()/context.complete() on the client code. Leading to a enormous amount of code duplication, which is a slightly little bit unperformant (as we are also calling isValid internally). So, you will always see this:

     if(context!=null && context.isValid())
                context.abort();

So, I think we benefit to just ignore the message, as there is no benefit on having the client code checking this all the time.

**Comment by robintaylor** [comment]
Sounds like you have given this a lot more thought than I did in my brief check. My only comment would be that at this time I think we should only be committing critical fixes in order to get 5.0 released. This fix might be better waiting for 5.1. Having said that, if others disagree, please feel free to press the Merge button.

Cheers, Robin.

**Comment by lyncodev** [comment]
Well, the refactor is not affecting anything else other than the logging level downgrade. So, no functionality is affected.

I wonder the benefit of having that INFO level logging entry. If there is any value in it, probably, we should close this PR. If there is a great value in it and client must verify the context validity before aborting/completing, probably we should throw an exception forcing the clients to behave themselves.

**Comment by tdonohue** [comment]
The INFO logging was added as part of PR#626 (fixes DS-2125 where an NPE would be called if a Context was aborted/completed twice). See more in the comments of that PR.

I'm not against switching it to "debug()" if others prefer that.

**Comment by tdonohue** [comment]
Closing as outdated / obsolete. This has changed drastically in latest master with Service API refactor (https://jira.duraspace.org/browse/DS-2701)

**Pull request closed without merging**
