### PR TITLE
Update of DataCite crosswalk to metadata schema 4.5

### LINKED ISSUE #9291: Update DataCite Metadata Schema to new version 4, as version 3 will be deprecated on January 1, 2025
> DataCite Metadata Schema 3 (3.0 and 3.1) will be deprecated on January 1, 2025.

At the moment DSpace uses version 3.1 in `DIM2DataCite.xsl` for registering DOIs with DataCite. We probably should update to a newer schema version. There seem to be only two breaking changes:

> Schema 4 introduced two breaking changes:
>The resourceType property was changed from optional to mandatory. This property has resourceTypeGeneral as a mandatory attribute.
>The contributorType "Funder" was deprecated. This concept was replaced with the FundingReference property.

As we already set `resourceType` with `resourceTypeGeneral` and do not use `Funder`, those seem no problem for DSpace.
We can probably get away with just updating the `resource` element to:

`<resource xmlns="http://datacite.org/schema/kernel-4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">`

We might update our mapping for `resourceTypeGeneral` as the new schema allows a more granular vocabulary.

DataCite documentation on [Updating from Schema 3 to Schema 4](https://support.datacite.org/docs/updating-from-schema-3-to-schema-4)

### PR DESCRIPTION
**Pull request by yannickpaulsen**
Sponsored by The Library Code.

## References
* Fixes #9291 

## Description
This updates the metadata DSpace sends to DataCite to DataCite's schema 4.5. The schema version 3, that DSpace currently uses will be abandoned by the end of 2024.

## Instructions for Reviewers
https://wiki.lyrasis.org/display/~pbecker/DOI+support+using+DataCite contains credentials for a DataCite test account and explain how to test DOI registration with DSpace.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

# To discuss
The DataCite schema defines some mandatory fields. One of them is a resource type. We would suggest to either make dc.type a required field in DSpace by default or to add to the documentation, that people should use dc.type if they use DataCite. As safe-fail solution, we set the resource type to "Other" if dc.type is not set.

### CODE REVIEW

**Comment by amgciadev** [comment]
It's good that I have caught this one, as we were also working on similar work for one of our new DSpace instances. Happy to help reviewing/contributing to this one.

**Comment by MW3000** [comment]
Ok. the above was not the right way to test this. I found a way to get to the actual xml created by `DataCiteXMLCreator.java`:

`dspace dsrun org.dspace.identifier.DataCiteXMLCreator <handle>`

And the result looks much better! I will test the changes again now.

**Comment by amgciadev** [comment]
@MW3000 my understanding from @pnbecker comments in #9291 is that their team is working on an updated version that in addition to being compliant with schema 4.5, it will also incorporate enhanced mappings (I am assuming that this means that mappings to ORCID id metadata, related identifiers, etc. will also be included).

@YPaulsen-TLC thanks a lot for working on this one. May I ask: would you be able to consider expanding your changes to resourceTypeGeneral, so that all types available (https://schema.datacite.org/meta/kernel-4.5/include/datacite-resourceType-v4.xsd) are incorporated in addition to those that DSpace uses? Repositories may choose to use those if available.

**Review by MW3000 — APPROVED** [review]
I reviewed the XSLT (IntelliJ finds some problems, but there are no new problems introduced, they all existed before), reviewed the output by checking the result of 
`dspace dsrun org.dspace.identifier.DataCiteXMLCreator <handle>` and I successfully tested registering DOIs with the new crosswalk with our DataCite test account.

**Comment by MW3000** [comment]
Thank you for this hint, @amgciadev. That's very useful.

> I find this way of testing Datacite metadata useful: DSpace has the following command that will generate the datacite xml metadata based on a handle:
> 
> `[dspace-home]/bin/dspace dsrun org.dspace.content.crosswalk.XSLTDisseminationCrosswalk DataCite <handle> <output-file>`

**Comment by pnbecker** [comment]
@tdonohue this is +1 by @MW3000 now. Can I merge this as soon as the proposed changes from @amgciadev are resolved? Shall we ask @mwoodiupui if he can give it another review?

**Comment by pnbecker** [comment]
@MW3000 thank you for the review!

**Comment by amgciadev** [comment]
@pnbecker thanks a lot for clarifying - I also got initially confused as I didn't know Y. Paulsen works with you. Your comment re resourceType is fair enough, so agree with keeping this PR as is.

Re enhancing the crosswalks, relatedIdentifiers or even funding information, perhaps one for the future. I was thinking on a similar approach to what openaire crosswalks do by making use of default dspace entities (virtual metadata) to enrich the metadata that is sent (people identifiers, funding information is also sent). But in this instance, makes perfect sense to provide support to ensure compliance with 4.5 using the basic available info.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @YPaulsen-TLC .  Code looks reasonable to me.  I haven't tested it, but several others have. So, merging this immediately.

**Pull request merged**
