### PR TITLE
DS 2557 xmlui curation ux

### PR DESCRIPTION
**Pull request by aschweer**

### CODE REVIEW

**Comment by aschweer** [comment]
https://jira.duraspace.org/browse/DS-2557

**Comment by tdonohue** [comment]
This needs rebasing on the latest master, because of merge conflicts

**Comment by aschweer** [comment]
Rebased but not re-tested

**Comment by tdonohue** [comment]
@aschweer : unfortunately, it seems this needs another rebase.

**Comment by aschweer** [comment]
Thanks @tdonohue. Rebased again but not re-tested. I hope it's ok that I cleaned up the code quite a bit; I can take that last commit out if people prefer.

**Comment by tdonohue** [comment]
Thanks @aschweer!

@hardyoyo, this is now ready for testing (as I know you were interested in this at yesterday's meeting).

**Comment by hardyoyo** [comment]
+1 by inspection, haven't yet been able to test (sorry)

**Comment by peterdietz** [comment]
+1 by reading through code. Unfortunately this needs to be rebased, yet again. Once you rebase, feel free to merge this into master.

**Comment by mwoodiupui** [comment]
Discussed in \#dspace today.

**Comment by aschweer** [comment]
Thanks folks, will rebase and merge soon.

**Comment by hardyoyo** [comment]
I checked this out in Vagrant-DSpace, and rebased it on master, resolved one minor conflict, deployed it and tested: works fine, is a good improvement to the curation task user experience. +1

**Comment by tdonohue** [comment]
Any chance we can get this rebased? Looks like it has enough votes to get in.  If @aschweer doesn't have time, I'm sure someone else could create a new branch from this & generate a new PR

**Comment by aschweer** [comment]
Rebased and given a very quick test - I hope this isn't too late for DSpace 6.0!

**Comment by tdonohue** [comment]
I've flagged this as a possible "quick win" for DSpace 6, as it looks to be primarily better descriptions / error messages on the existing curation task UI page.  I think this just needs a quick test/verification, as the code looks good to me.

**Comment by tdonohue** [comment]
Closing as this PR must be recreated on `dspace-6_x` branch. XMLUI has been removed from `master`. See this mailing list notice: https://groups.google.com/d/msg/dspace-devel/aEFqSn46ryM/iPRr_IMLCwAJ

**Pull request closed without merging**
