### PR TITLE
[HIGH PRIORITY] Fix ConcurrentModificationException in getPermissionFilteredMetadata()

### PR DESCRIPTION
**Pull request by tdonohue**
## References
* Fixes bug described here: https://jira.lyrasis.org/browse/DS-4487
* Related to #2719 (where the bug was accidentally introduced)

## Description
Fixes ConcurrentModificationException by ensuring that the List of metadata in `getPermissionFilteredMetadata()` is not modified while looping through its values.

See Ticket for how to reproduce this bug easily on the `/api/core/collections` endpoint.

### CODE REVIEW

**Review by abollini — COMMENTED** [review]
I would try to work in the opposite direction, instead than identify which metadata needs to be hidden and remove them at the end we can just create the actual list of metadata to return.
As we hit an issue on the official demo we should also include an IT to reproduce the problem and proof that the fix solve it. I will check if someone in my team can help on that

**Comment by Micheleboychuk** [comment]
I'm working on that

**Comment by Micheleboychuk** [comment]
here my alternative PR: https://github.com/DSpace/DSpace/pull/2750

**Comment by tdonohue** [comment]
Closing, as this was replaced by #2750

**Pull request closed without merging**
