### PR TITLE
[DS-3611] added missing quotes to choice-authority-control.xsl

### PR DESCRIPTION
**Pull request by hardyoyo**
https://jira.duraspace.org/browse/DS-3611

### CODE REVIEW

**Comment by tdonohue** [comment]
@hardyoyo : this looks to be very similar in nature to #1741, although the fixes are slightly different. You may want to review that other PR to see if it resolves this issue, or if you feel both fixes are appropriate.

**Comment by hardyoyo** [comment]
@tdonohue: indeed, this portion of #1741 

https://github.com/edusperoni/DSpace/blob/63ba6e93eac10639ec466367955a3f8690e82bab/dspace-xmlui-mirage2/src/main/webapp/xsl/aspect/general/choice-authority-control.xsl#L325-L327

looks identical to my proposed fix here. I'd be OK with closing this PR in favor of that one, I will test whether it does what it says.

**Comment by tdonohue** [comment]
@hardyoyo : Sounds good. I'd recommend verifying/validating #1741 then (and we can move to merge it quickly). Once you've had a chance to test/verify #1741, then yes, let's close this PR in favor of that one.

**Comment by edusperoni** [comment]
I believe both fixes are needed. My PR (#1741) fixes the autocomplete bug. This PR seems to affect the Lookup Button (template addLookupButtonAuthor).

I add this fix to #1741 if needed.

**Comment by hardyoyo** [comment]
@edusperoni no modification of your PR should be required, both #1764 and #1741 add in the same missing single quotes, and do so in the same way. I'm testing #1741 now, and I will give it a +1 if it works. I'd prefer a more feature-complete fix to this issue, so I'll close #1764 in favor of #1741 if it does work.

**Comment by hardyoyo** [comment]
Closing this in favor of #1741, since it fixes more broken things than #1764.

**Pull request closed without merging**
