### PR TITLE
[DS-3057] Enable enforce versions to prevent dependency issues

### PR DESCRIPTION
**Pull request by KevinVdV**
https://jira.duraspace.org/browse/DS-3057

This pull request will prevent potential bugs sneaking in due to conflicting versions..

### CODE REVIEW

**Comment by KevinVdV** [comment]
Marked as in progress because not all dependencies have been fixed yet.

**Comment by tdonohue** [comment]
Clarification..this PR actually "works", but it is showing we have dependency conflicts (which is why Travis CI is failing).  To get this merged, we need someone to help us dig into those dependency conflicts and add exclusions to POMs as needed, etc.

**Comment by KevinVdV** [comment]
All dependency conflicts should be resolved, rebased on latest master. Clean package works, in order to test just add a conflicting dependency version to a pom.xml & the build will fail.

**Comment by hardyoyo** [comment]
+1 by inspection

**Pull request merged**
