### PR TITLE
DS-2441 Add a bitstream column to item/browse list

### PR DESCRIPTION
**Pull request by pastleo**
https://jira.duraspace.org/browse/DS-2441

In the IR of our university, not all items have file (full text like pdf or we call 全文) , just some of them.
We want a function to show if there is a file in the item at the list view so I write (or maybe hack) some code into the core of dspace.  
My code may not be great, but at least this will work.  
If someone want this function too, they can add 'bitstream' to `webui.itemlist.columns` like line 1845 in `dspace.cfg` and the full version (with the file name and its link) can be enabled by `webui.browse.bitstream.showfull = true` on line 994 in `dspace.cfg`

### CODE REVIEW

**Comment by helix84** [comment]
1) Thank you for your contribution. Please, fix the compile error. https://travis-ci.org/DSpace/DSpace/builds/49433221
Then either push a new commit to this branch or replace the branch (using push with the --force parameter).

2) We keep track of issues in our Jira and all pull requests muse be accompanied by an issue. I created one here: https://jira.duraspace.org/browse/DS-2441

3) Please note that we now require at least basic documentation for new features. You could use this template as a start: https://wiki.duraspace.org/display/DSDOC/New+Contribution+Template

4) If you plan to submit multiple pull requests, it's possible to do so if you push your work to separate branches in your GitHub fork, e.g. NCHUIR:feature-1 and NCHUIR:feature-2 instead of NCHUIR:master.

**Comment by kstamatis** [comment]
This feature is already available in DSpace 5.0. Read more here: https://wiki.duraspace.org/display/DSDOC5x/Configuration+Reference#ConfigurationReference-JSPUI:Peritemvisualindicatorsforbrowseandsearchresults

**Comment by helix84** [comment]
There is new functionality in DSpace 5 JSPUI that sounds like a superset of what you're trying to implement here. Could you please look at it (links below), try it, and write whether you're trying to implement something different or whether you could use that existing functionality instead? Thanks.

https://jira.duraspace.org/browse/DS-2162
https://wiki.duraspace.org/display/DSDOC5x/Configuration+Reference#ConfigurationReference-JSPUI:Peritemvisualindicatorsforbrowseandsearchresults

**Comment by chgu82837** [comment]
First, sorry for the compile error. I directly apply our changes on `4.1.2 CRIS` into your code...  
After reading the doc, I think [the functionality you mentioned](https://wiki.duraspace.org/display/DSDOC5x/Configuration+Reference#ConfigurationReference-JSPUI:Peritemvisualindicatorsforbrowseandsearchresults) is exactly what we want, sorry again for not searching in current version first. I will close this pull request  
The only concern I have is if the performance might be a little bit affected by the each-item-query. Maybe we can add something like `ItemMarkingDataPrepare` interface to obtain the data for `getItemMarkingInfo` first? Or I just think too much? Thanks

**Pull request closed without merging**
