### PR TITLE
New ImageMagick-based media filter to generate video thumbnails

### PR DESCRIPTION
**Pull request by abelgomez**
## Description
This PR provides a simple filter, based on the existing ImageMagick filter, to automatically create thumbnails for MP4 videos. In order to generate the thumbnail, ImageMagick only needs to modify how the input file of the conversion is specified:

* First, we specify the VIDEO _format specifier_ before the full path of the input file (see https://imagemagick.org/script/formats.php#supported). VIDEO supports, APNG, AVI, MP4, and WEBM, among other video formats.
* Second, we specify between brackets the frame we want to use as the thumbnail after the full path of the input file. We use 100, to avoid black thumbnails if the video starts with a a fade-in effect.

## Instructions for Reviewers

The changes are minimal: 

* A new `ImageMagickVideoThumbnailFilter` class, based on `ImageMagickImageThumbnailFilter` and also overriding the `getThumbnailFile` method from the `ImageMagickThumbnailFilter`abstract class.
* The corresponding configuration options un `dspace.cfg`. The filter is disabled by default, as other ImageMagick-based filters are.

The filter may be enabled as any other ImageMagick-based filters. The only additional pre-requisite is also installing `ffmpeg`, since ImageMagick relies on it. 

## Checklist

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods. -> **No new methods have been added, the code only overrides existing methods.**
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide). -> **No tests are affected, and previous ImageMagick filters didn't have specific tests so that has been left as it was.**
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation. -> **No new libraries have been included.**
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change. -> **No endpoints have been modified.**
- [X] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@alanorth : I wanted to ping you on this PR in case you would be interested in helping review/test it.  I know you've worked frequently on improving these ImageMagick media filters.

**Comment by alanorth** [comment]
@tdonohue yes I saw this and also thought it was right up my alley. I'll try to take a look soon.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @abelgomez .  The code looks good, and it works.  It would be nice to perhaps, eventually make it more configurable (e.g. the FRAME_NUMBER).  But, it's a good enough start.

For other testers, to enable this requires the following:
* Install ImageMagick & ffmpeg (new requirement).  See also https://wiki.lyrasis.org/display/DSDOC7x/ImageMagick+Media+Filters
* Upload an MP4
* Enable the new filter, e.g.
   ```
   filter.plugins = Text Extractor
   filter.plugins = ImageMagick Image Thumbnail
   filter.plugins = ImageMagick Video Thumbnail
   ```
* Run filter-media on the Item which has the MP4.  Verify a thumbnail is created.

Overall, I think this is good enough to merge as-is.  We can always improve it in the future.

**Comment by tdonohue** [comment]
Merging for 7.6.  I added some basic docs on this new feature to https://wiki.lyrasis.org/display/DSDOC7x/ImageMagick+Media+Filters

**Comment by abelgomez** [comment]
Great!

In my experience, the default values in ImageMagick (see https://github.com/DSpace/DSpace/blob/4d4899cc3a562a3b5dd1d229713392608885c117/dspace/config/dspace.cfg#L462) may be insufficient to generate some thumbnails.

Probably it's a good idea to also include some indications about that in https://wiki.lyrasis.org/display/DSDOC7x/ImageMagick+Media+Filters#ImageMagickMediaFilters-PossibleErrors/Issues

If you agree, just let me know. I can prepare some paragraphs with the verbatim errors that may be thrown. In such a case, please tell me how to proceed.

**Comment by tdonohue** [comment]
@abelgomez : If you are able & willing to enhance the documentation, we'd welcome that!  You can either prepare the documentation and link or include it in a comment here... or you can setup a free wiki account (see yellow note here: https://wiki.lyrasis.org/) and send me your email/account id.  Then I can give you access to modify the documentation directly (don't worry, there's a few of us who review any modifications to official docs, so we can double check your work).

**Comment by abelgomez** [comment]
Hi @tdonohue , I already have an account in the lyrasis wiki with the e-mail abgolla@gmail.com.

Hopefully, I'll be able to work on the "Possible Errors/Issues" in one week or two. In any case, I'll put my best effort to prepare it before the release of Dspace 7.6.

**Comment by tdonohue** [comment]
@abelgomez : I've given you access to edit the DSpace documentation area of the wiki.  So, you should now be able to edit this page: https://wiki.lyrasis.org/display/DSDOC7x/ImageMagick+Media+Filters#ImageMagickMediaFilters-PossibleErrors/Issues

As a sidenote, the 7.6 release is planned to be announce on Monday (June 26) or Tues (27).  That said, if these docs are not updated by then, it's OK to simply update them when you get the chance.

**Comment by abelgomez** [comment]
Ops! I didn't think the release was so close! Well, then I've given priority to update the documentation...
Please, find my contributions at:

https://wiki.lyrasis.org/display/DSDOC7x/ImageMagick+Media+Filters#ImageMagickMediaFilters-%22convert-im6.q16:cacheresourcesexhausted%22errors

BTW, I formatted the ERROR details in my contribution as in the previous subsection, i.e.:

```
ERROR filtering, skipping bitstream:
        Item Handle: 1234/5678
        Bundle Name: ORIGINAL
        File Size: 146761357
        Checksum: 735ceb1b6b249afc84a5bb1b87ae0c02 (MD5)
        Asset Store: 0
```
But to be fair, I get all the details of the errorsin a single line...:

```
ERROR filtering, skipping bitstream:
        Item Handle: 1234/5678    Bundle Name: ORIGINAL   File Size: 1076302954   Checksum: 5976df9801f99aac8f8c776e958cb372 (MD5)        Asset Store: 0

```

Not sure if that's expected, it's a bug, or what, but didn't want to be inconsistent with the existing documentation.

**Comment by tdonohue** [comment]
Thanks! That all looks good enough for now.  We appreciate the documentation improvements!

**Pull request merged**
