### PR TITLE
[DS-3311] Fix healthcheck

### PR DESCRIPTION
**Pull request by isido**
https://jira.duraspace.org/browse/DS-3311

These trivial fixes should fix sending the healthcheck-emails. There is still a NPE and IllegalArgumentException to be fixed.

I tested only with actual mail server disabled.

### CODE REVIEW

**Comment by isido** [comment]
I added second commit to fix the NPE. It was caused by trying to access deprecated Lucene ``search.dir``-property. I also added a check for null pointer. I don't know if that is necessary, since the properties accessed are hard-coded, and if those are not found, it's programming error and should ideally be caught in the compile time. Perhaps message should be changed to something like "ALERT. PROGRAMMING ERROR"...

**Comment by isido** [comment]
I made minimal modifications to the embargo check. The check name now shows that it is for pre-3.0 embargo functionality (docs should also be updated). I also added a note which is shown when exception is thrown.

I  considered also adding a flag to enable the embargo check, which would be disabled by default (as was discussed on the #dspace 2016-09-20). After looking at the code I didn't want to start implementing that feature, since the checks are dynamically specified in a configuration file. To disable single check, I would have had to rely either on the check name or the check order, both which can be changed by the user. A proper way of fixing this would have been perhaps implemeting a list of available checks and enabled checks. I didn't want to do any intrusive changes this close to 6.0 release, so the fix is end result is minimal modification.

**Review by tdonohue — APPROVED** [review]
+1 I've tested this and it fixes the issues with running `./dspace healthcheck -e [email]` on current master

**Comment by abollini** [comment]
+1 by code inspection

**Comment by tdonohue** [comment]
Approved in today's DevMtg. Merging

**Comment by pnbecker** [comment]
@isido thanks for that fix!
I created a follow-up PR to change the default configuration: #1540.

**Pull request merged**
