### PR TITLE
DS-4201 Do not pass starts_with if browsing an item index.

### PR DESCRIPTION
**Pull request by J4bbi**
Fixes [DS-4192](https://jira.duraspace.org/browse/DS-4192).

### CODE REVIEW

**Comment by terrywbrady** [comment]
I tested this PR to see if it could also resolve https://jira.duraspace.org/browse/DS-4208.  The issue is similar.  Unfortunately, this PR does not also resolve that bug.  If I find a solution to DS-4208, I will add a comment to this PR.

**Review by terrywbrady — APPROVED** [review]
Tested and verified the fix

**Review by nwoodward — APPROVED** [review]
:+1: Tested and confirmed this works.

**Comment by kshepherd** [comment]
merged, thanks @J4bbi

**Pull request merged**
