### PR TITLE
DS 4079: Add flyway script to remove basic workflow steps from the collection table

### PR DESCRIPTION
**Pull request by YanaDePauw**
This is a fix for https://jira.duraspace.org/browse/DS-4079.

The original workflow will be removed in DSpace 7. A flyway class has been added that will clean up the original workflow steps in the collection table to ensure that no conflicts arise when xml workflow is enabled.

### CODE REVIEW

**Review by pnbecker — COMMENTED** [review]
This PR handles the collection table only. Do we have another PR to handle the workflow_task table and the resource policies created by the basic workflows?
Is there a reason why we do not remove the columns 'workflow_step_x' from the collection table by altering it?

**Comment by pnbecker** [comment]
Travis currently complains about a line too long with regard to our checkstyle configuration:
```
There is 1 error reported by Checkstyle 8.8 with /home/travis/build/DSpace/DSpace/dspace-api/../checkstyle.xml ruleset.
[ERROR] src/main/java/org/dspace/storage/rdbms/xmlworkflow/V5_7_2018_11_20__Remove_Old_Workflow_Steps_From_Collections.java:[73] (sizes) LineLength: Line is longer than 120 characters (found 121).
```

**Comment by tdonohue** [comment]
While technically this PR does what DS-4079 says, I agree with @pnbecker here that we'll end up leaving a lot of unused data/tables/columns in the database if we _only apply this PR_.  

We likely should expand the scope of the original ticket to include cleanup of *all* basic workflow step functionality, including database tables, columns & (where necessary) resource policies.  This may require a closer analysis of what data / tables / Java classes still exist in the `master` codebase.

Additionally, we should be able to completely *drop* checks for whether XmlWorkflowService is enabled, as there will be no other valid configuration option in DSpace 7.

**Comment by tdonohue** [comment]
Closing, as this was fixed by #3144

**Pull request closed without merging**
