### PR TITLE
[DS-3244] Fix links on error pages

### PR DESCRIPTION
**Pull request by aschweer**
Make sure the "Go back to DSpace Home" link is correct
Make sure the breadcrumb link back home is correct

### CODE REVIEW

**Comment by hardyoyo** [comment]
Trying to test this with Vagrant-DSpace, I can confirm the "DSpace Home" link is correct, however the breadcrumb link looks like it is unchanged. I have tried to clear cache (browser and Cocoon). Not sure what's up, but wanted to give you that feedback.

**Comment by aschweer** [comment]
Thanks @hardyoyo -- I squashed a couple of local commits when I made the PR, maybe I missed something for the breadcrumb trail.

**Comment by aschweer** [comment]
@hardyoyo, could you give some more detail on the steps you're using to test this? What URL do you use for testing, and what are the resulting hrefs for the two links (go home / breadcrumb) on the error page?

I just double checked in a fresh build of master + this PR (not using DSpace-Vagrant though) and the breadcrumb trail is correct for me. Test URL is http://localhost:8080/nosuchpage

**Comment by rradillen** [comment]
for me the breadcumb link _is_ correct

**Comment by hardyoyo** [comment]
The test URL I have been using is http://127.0.0.1:8080/xmlui/nosuchpage. The go home link has an added slash at the end, the breadcrumb link has no such slash.

**Comment by aschweer** [comment]
@hardyoyo the bug only shows up when you test with XMLUI deployed at /, not /xmlui. The slash / no slash thing when deployed at /xmlui is interesting -- but it still works even thought it's different, no? So maybe this is good enough since it fixes one deployment case and doesn't break the other?

**Comment by hardyoyo** [comment]
OK... I don't deploy XMLUI that way, so I can't say. As long as it still works (and I agree, it all seems to work OK), I won't stand in the way of this change.

**Comment by tdonohue** [comment]
Closing as this PR must be recreated on `dspace-6_x` branch. XMLUI has been removed from `master`. See this mailing list notice: https://groups.google.com/d/msg/dspace-devel/aEFqSn46ryM/iPRr_IMLCwAJ

**Comment by aschweer** [comment]
Thanks @tdonohue - I don't have a lot of DSpace time at the moment but will try to make a new PR today or tomorrow.

**Pull request closed without merging**
