### PR TITLE
DS-3198 - NullPointException in OAIHarvester

### PR DESCRIPTION
**Pull request by ghost**
The class org.dspace.harvest.OAIHarvester is launching a exception when harvesting a collection.

### CODE REVIEW

**Comment by tdonohue** [comment]
+1 via code review. Obvious fix.

**Comment by hardyoyo** [comment]
+1 by inspection

**Comment by tdonohue** [comment]
Note: Just realized this PR looks to be duplicated in the (much larger) fixes in #1326

**Comment by pnbecker** [comment]
I merged #1326 today and it seems that it fixed this issue as well. I close this PR, but please feel free to open a new one if you find this issue isn't fully resolved.

**Pull request closed without merging**
