### PR TITLE
Fixed dso endpoint returning 500 for unauthorized users

### LINKED ISSUE #9154: Status 500 for items without READ permission for Anonymous
**Describe the bug**
If an item does not have READ permissions for Anonymous, the `dso` Endpoint of the REST API is responding to requests for that item with a status 500 (instead of the status 401 or 403, which I would be expecting).
I actually don't know, if this endpoint is being used at all or what it's actually good for, but I found error messages in my apache logfile (on DSpace-CRIS) and was able to reproduce such errors on the public DSpace Demo instance.

**To Reproduce**
1. Remove READ permission for Anonymous to an arbitrary item
2. Try to get this item via the `dso` endpoint (http://[dspace-server]/server/api/dso/find?uuid=[UUID of the item])

I have created an example on the public DSpace Demo instance: I have removed READ permission to item 5db5b893-7728-4f3f-9bdd-eb3878eac0a6 for Anonymous, so that nobody except for administrative users can read that (apologies, if this confused anybody). So, getting https://demo.dspace.org/server/api/dso/find?uuid=5db5b893-7728-4f3f-9bdd-eb3878eac0a6 results in an error page with the status 500 - if you try it with a browser (via URL or via HAL browser). However, when you use wget to test it, you'll get a correct status 403 (I cannot explain, why that happens).

**Expected behavior**
I would expect status 403 or 401 when I try to access the item via the `dso` endpoint (https://demo.dspace.org/server/api/dso/find?uuid=5db5b893-7728-4f3f-9bdd-eb3878eac0a6)

**Related work**
https://demo.dspace.org/items/5db5b893-7728-4f3f-9bdd-eb3878eac0a6 is responding with the correct status code (403), so I guess the problem only affects the `dso` endpoint.

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #9154

## Description
Fixed a 500 error being returned by the `/api/dso/find?uuid={uuid}` endpoint when you are unauthorised/unauthenticated.

## Instructions for Reviewers
List of changes in this PR:
* Added an `AuthorizeService#authorizeAction` check to the endpoint to return the correct authorization response code

**Guidance for how to test or review this PR:**
- Create a DSpaceObject for example a community and remove the READ resource policies on `/communities/{uuid}/edit/authorizations`
- Request the community as an unauthenticated user, it should return 401
- Request the community as an regular user, it should return a 403 

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
Thanks @alexandrevryghem. Does this need an update in the [RestContract](https://github.com/DSpace/RestContract)? I couldn't find the endpoint documentation for `/api/dso/find` actually.

**Comment by alexandrevryghem** [comment]
@alanorth: That endpoint isn’t documented yet, but a 500 error is never the expected status code. So, these might be seen as separate issues

**Review by nwoodward — APPROVED** [review]
👍 Tested these changes, and they work well. I agree that the 500 status code doesn't make sense, and the 401 Unauthorized is better.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem!  Code looks good & the ITs.  Glad to see @nwoodward was able to give this a manual test as well.

**Pull request merged**
