### PR TITLE
DS-2777 : Fix OAI-PMH to work with Service API refactor

### PR DESCRIPTION
**Pull request by tdonohue**
https://jira.duraspace.org/browse/DS-2777

This PR officially fixes OAI-PMH to work properly (at least at a minimal level) after the Service API refactor.  Note: I have not tested EVERY feature in OAI-PMH, but OAI-PMH now loads properly and functions at a basic level.

Involved the following:
- Updates OAI-PMH to use the same 'applicationContext.xml' as all other webapps (to initialize DSpace Services)
- Stops attempting to inject `HandleService` and just loads it via its provided Factory
- Restores `DSpaceSetRepository` classes (accidentally removed during the initial refactor). They are required for OAI-PMH sets to work.
- Adds a new `CommunityService.findAll()` method that supports limit/offset. I based this off the method of the same name/type in the `CollectionService`. This was required to support the `DSpaceSetRepository`.

@KevinVdV , if you have a moment, can you give this a sanity check?  It all seems to work, but I'd like your opinion as the Service-based API creator/expert.

### CODE REVIEW

**Comment by tdonohue** [comment]
Just realized the `diff` for the `*SetRepository` classes doesn't actually show up in this PR.  These classes both existed in 5.x. They were accidentally deleted during the API refactor, and they needed to be restored for OAI Sets to function.

* The restored `DSpaceSetRepositoryResolver` class is unchanged between 5.x and pre-6. 
* But, the restored `DSpaceSetRepository` class needed to be updated to use the new Service-based API (previously it had hardcoded SQL queries). Here's the 5.x versions of this class for reference: https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace-oai/src/main/java/org/dspace/xoai/services/impl/xoai/DSpaceSetRepository.java

**Comment by helix84** [comment]
exception

    org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.hibernate.hql.internal.ast.QuerySyntaxException: metadatavalue is not mapped [SELECT m FROM metadatavalue m WHERE metadata_field_i
        org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:965)
        org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:844)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    root cause

    org.hibernate.hql.internal.ast.QuerySyntaxException: metadatavalue is not mapped [SELECT m FROM metadatavalue m WHERE metadata_field_id = :metadata_field_id ORDER BY value]
        org.hibernate.hql.internal.ast.util.SessionFactoryHelper.requireClassPersister(SessionFactoryHelper.java:180)
        org.hibernate.hql.internal.ast.tree.FromElementFactory.addFromElement(FromElementFactory.java:110)
        org.hibernate.hql.internal.ast.tree.FromClause.addFromElement(FromClause.java:93)
        org.hibernate.hql.internal.ast.HqlSqlWalker.createFromElement(HqlSqlWalker.java:325)
        org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.fromElement(HqlSqlBaseWalker.java:3544)
        org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.fromElementList(HqlSqlBaseWalker.java:3433)
        org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.fromClause(HqlSqlBaseWalker.java:708)
        org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:564)
        org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.selectStatement(HqlSqlBaseWalker.java:301)
        org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:249)
        org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:250)
        org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:185)
        org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:138)
        org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:104)
        org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:79)
        org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:168)
        org.hibernate.internal.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:222)
        org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:200)
        org.hibernate.internal.SessionImpl.createQuery(SessionImpl.java:1739)
        sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        java.lang.reflect.Method.invoke(Method.java:606)
        org.hibernate.context.internal.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:352)
        com.sun.proxy.$Proxy79.createQuery(Unknown Source)
        org.dspace.core.AbstractHibernateDAO.createQuery(AbstractHibernateDAO.java:108)
        org.dspace.content.dao.impl.MetadataValueDAOImpl.getMinimum(MetadataValueDAOImpl.java:64)
        org.dspace.content.MetadataValueServiceImpl.getMinimum(MetadataValueServiceImpl.java:110)
        org.dspace.xoai.services.impl.DSpaceEarliestDateResolver.getEarliestDate(DSpaceEarliestDateResolver.java:36)
        org.dspace.xoai.services.impl.xoai.DSpaceRepositoryConfiguration.getEarliestDate(DSpaceRepositoryConfiguration.java:95)
        com.lyncode.xoai.dataprovider.handlers.IdentifyHandler.handle(IdentifyHandler.java:44)
        com.lyncode.xoai.dataprovider.OAIDataProvider.handle(OAIDataProvider.java:198)
        org.dspace.xoai.controller.DSpaceOAIDataProvider.contextAction(DSpaceOAIDataProvider.java:104)
        sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        java.lang.reflect.Method.invoke(Method.java:606)
        org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
        org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
        org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
        org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
        org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
        org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
        org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
        org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
        org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
        org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:844)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

**Comment by KevinVdV** [comment]
Yeah looking at that hql query it should be "WHERE m.metadata_field_id = " instead of "WHERE metadata_field_id =".

**Comment by tdonohue** [comment]
I'm not following where/how this error occurs?  More context would be nice here, as this error seems unrelated to my fixes.  The goal of this PR is to get OAI-PMH to actually run...at least on my end, it now runs (though I haven't fully tested all OAI-PMH functionality quite yet). 

Currently on "master" the OAI-PMH interface doesn't even load...an immediate error is thrown and a blank screen appears.

**Comment by helix84** [comment]
I got the stack trace in the browser after loading /oai/request?verb=Identify

After fixing the query (case sensitive table/class name), OAI started up for me:
https://github.com/tdonohue/DSpace/pull/5

Unrelated to this issue, the query above also seems sketchy, there is no metadataField column in the metadatavalue table. As far as I can see, this query is not yet called from anywhere. @KevinVdV, can you please confirm?
https://github.com/tdonohue/DSpace/blob/57eae5388941a9f96a44d85b49730c3b806f70fa/dspace-api/src/main/java/org/dspace/content/dao/impl/MetadataValueDAOImpl.java#L53

**Comment by helix84** [comment]
Next issue:
    $ /dspace/bin/dspace oai import -c                                                                                                                                                                                
    OAI 2.0 manager action started
    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dspace.xoai.app.XOAI': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.dspace.authorize.service.AuthorizeService org.dspace.xoai.app.XOAI.authorizeService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.dspace.authorize.service.AuthorizeService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
            at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:298)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1148)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBean(AbstractAutowireCapableBeanFactory.java:299)
            at org.dspace.xoai.app.XOAI.main(XOAI.java:382)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:606)
            at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
            at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
    Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.dspace.authorize.service.AuthorizeService org.dspace.xoai.app.XOAI.authorizeService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.dspace.authorize.service.AuthorizeService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
            at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:531)
            at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
            at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:295)
            ... 9 more
    Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.dspace.authorize.service.AuthorizeService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.inject.Inject()}
            at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:997)
            at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:867)
            at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:779)
            at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:503)
            ... 11 more

**Comment by tdonohue** [comment]
I've merged @helix84's bug fix to `MetadataValueDAOImpl` into this branch, after confirming that it works correctly.

There are still "known" issues with the CLI tools. They don't yet load our `ServiceManager` properly. But, at this point, the webapp itself should "work".  (I'll dig around into the CLI tooling next)

**Comment by tdonohue** [comment]
Just pushed up two fixes which allow "dspace oai import -c" to function without throwing an error.

However, oddly, it doesn't seem to find any content to *index*.  So, it returns successfully, but always says that it indexed "0" items.  I'm guessing something may still be wrong with the Hibernate queries here?

```
$ ./dspace oai import -c
OAI 2.0 manager action started
Clearing index
Index cleared
Using full import.
Full import
Total: 0 items
OAI 2.0 manager action ended. It took 4 seconds
```

**Comment by tdonohue** [comment]
Pushed up a new fix. 
* The dates should be compared as Timestamps, since the Item "last_modified" column is defined as a Timestamp: https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/content/Item.java#L58
* When a full reindex is performed, the date is passed as "null". So we need to account for that.

**Comment by tdonohue** [comment]
One final fix.  OAI-PMH now loads for me, and `./dspace oai import -c` now functions properly and indexes all content.
* Solr's schema must treat Item IDs as UUIDs (instead of integers)

This PR is ready for review & merging.

**Comment by KevinVdV** [comment]
Tested this pull request & the OAI is operational, the code looks good so +1 from me.

**Comment by helix84** [comment]
Great work, Tim. Regarding null in last_modified, I only had one such item which looks like this:

item_id,in_archive,withdrawn,last_modified,discoverable,uuid,submitter_id,owning_collection
4720,f,f,,t,c7ddd4cc-7ec8-46d2-b20a-395ead851cf9,,

It's some kind of item that's not in archive. Perhaps special handling of these items will be needed because oai import should also keep track of deleted items:
https://jira.duraspace.org/browse/DS-527


One more hiccup during import:

java.lang.NullPointerException
        at org.dspace.xoai.util.ItemUtils.retrieveMetadata(ItemUtils.java:171)
        at org.dspace.xoai.app.XOAI.index(XOAI.java:267)
        at org.dspace.xoai.app.XOAI.index(XOAI.java:209)
        at org.dspace.xoai.app.XOAI.indexAll(XOAI.java:196)
        at org.dspace.xoai.app.XOAI.index(XOAI.java:143)
        at org.dspace.xoai.app.XOAI.main(XOAI.java:393)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)

**Comment by KevinVdV** [comment]
@helix84 This "nullpointer" is part of an another problem that I ran into while testing: https://jira.duraspace.org/browse/DS-2807. Since it is unrelated to the OAI I don't want to hold it against this pull request. (The view item page will also be broken because of this bug).

**Comment by tdonohue** [comment]
@helix84 , you misunderstood my statement about accounting for "null". It's not that the *data* is null, it's that null gets passed into the method as the last modified date.  This line to be exact:
https://github.com/DSpace/DSpace/blob/master/dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java#L185

In any case, I agree with @KevinVdV that we probably should get this merged ASAP. It minimally "works" and allows others to use (or build PRs against) OAI-PMH.  There may still be other bugs around, but they should be fixed in new PRs

**Comment by helix84** [comment]
:+1:

**Pull request merged**
