### PR TITLE
DS-2623 backport set description in the upload step files

### PR DESCRIPTION
**Pull request by lap82**
Backport for #1013 that fix the set description in the upload file and add the possibility to setting up the description for multiple files.

I tested both with simple UploadStep than with UploadWithEmbargoStep and it work fine!

### CODE REVIEW

**Comment by jpiscanc** [comment]
I tested simple UploadStep and UploadWithEmbargoStep on my DSpace-CRIS 5.5 and it work fine! Great Work!

**Comment by pnbecker** [comment]
This is just a backport. Code changes look bigger as they are caused by changed indentation.

+1 by review and test.

**Comment by tdonohue** [comment]
Looks good. Since this has gotten some testing, I'm OK with this going into the 5.6 release.

**Comment by abollini** [comment]
+1 as well, tested it works

**Pull request merged**
