### PR TITLE
[DS-1837] Create a separate Maven artifact for the MultiRemoteDSpaceRepositoryHandlePlugin

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://jira.duraspace.org/browse/DS-1837
Untested.  Just repackaging as a drop-in-able JAR.  Please comment.

### CODE REVIEW

**Comment by mwoodiupui** [comment]
Comments, @pnbecker?

**Comment by pnbecker** [comment]
Code looks fine!
Will test it next week.
Nevertheless: +1 by code review.

**Comment by mwoodiupui** [comment]
@pnbecker did the testing go well?

**Comment by pnbecker** [comment]
I tested it today and the created jar works great. :-) That's a big improvement, thanks a lot @mwoodiupui!

Just one note: currently the jar stays in [dspace-source]/dspace-remote-handle-resolver/target/. I would expect it to be copied to [dspace-source]/dspace/target/dspace-installer/lib as every other jar we build. I think this would make the documentation easier as well, as we could just point to [dspace-install]/lib/dspace-remote-handle-resolver.jar independently whether the binary or the source release was used for the installation. This should not hinder us merging this asap, it is just an idea.

**Comment by mwoodiupui** [comment]
I've adjusted various POMs to get the jar copied to lib/ as requested.  But, I don't think it really belongs there, since it isn't meant to be on the classpath of e.g. commandline tools.  We really don't have a good place to put free-standing JARs which are meant to be used by other products.

**Comment by pnbecker** [comment]
I agree with you that this is not the perfect location. But I think it is important to get it copied somwhere below [dspace-install].

Thank you for this PR!
+1

**Comment by mwoodiupui** [comment]
Discussed today in \#duraspace.  Consensus was that this should be pulled out into a separate Github project, so I'm doing that.

**Comment by tdonohue** [comment]
+1 This is just code removal now, as the code has been separated moved to https://github.com/DSpace/Remote-Handle-Resolver

**Comment by mwoodiupui** [comment]
DSpace/Remote-Handle-Resolver should be released before DSpace 6.

**Pull request merged**
