### PR TITLE
DS-2358: Preserves custom policy rules during versioning

### PR DESCRIPTION
**Pull request by pnbecker**

### CODE REVIEW

**Comment by tdonohue** [comment]
@pnbecker , I've tested this today and it *almost* works. The one problem though is that the `Bundle` in the new version does NOT preserve its custom policy rules (but both the Item and the Bitstream successfully do).

I think what is missing is that this new Bundle must also have the custom rules applied:
https://github.com/tuub/DSpace/blob/DS-2358/dspace-api/src/main/java/org/dspace/versioning/AbstractVersionProvider.java#L51

Once that code is in place, this should be ready to merge. Everything else works!

**Comment by tdonohue** [comment]
@pnbecker : Unfortunately, looks like this still doesn't work properly :(

The new behavior is now that Embargo policies are being *doubled up* on `Bitstream` objects.  So, when you create a new Version any pre-existing `Bitstreams` will end up with a duplicated Embargo policy like this:

        Bitstream test.pdf (26)
	227 		READ 	Anonymous [Edit] 	2016-06-03 	
	232 		READ 	Anonymous [Edit] 	2016-06-03

If you then add another version, a third policy of the same type is added:

        Bitstream test.pdf (37)
	273 		READ 	Anonymous [Edit] 	2016-06-03 	
	274 		READ 	Anonymous [Edit] 	2016-06-03 	
	279 		READ 	Anonymous [Edit] 	2016-06-03 	

Essentially, the Bitstream keeps getting more and more duplicative policies, based on the number of versions.

I've located the problem. The problem is that when `bundleNew.addBitstream(bitstreamNew);` is called (see https://github.com/tuub/DSpace/blob/DS-2358/dspace-api/src/main/java/org/dspace/versioning/AbstractVersionProvider.java#L70), it AUTOMATICALLY inherits all the policies of the Bundle (see https://github.com/tuub/DSpace/blob/DS-2358/dspace-api/src/main/java/org/dspace/content/Bundle.java#L452). 

So, the result is that Bitstream policies get applied too many times.

The only "fix" I can think of is to:
  1. Add new Bitstream to Bundle (thus inheriting bundle policies)
  2. Remove all inherited CUSTOM policies from new Bitstream (as they may not be correct if only one bitsteam has an embargo)
  3. Copy correct CUSTOM policies from old Bitstream to new Bitstream

As I believe @pnbecker is out of the office for a while, I'll go ahead and create a new PR based on this one which adds that proposed fix.

**Comment by tdonohue** [comment]
I've replaced this PR by #998. Please test that one instead!

**Comment by pnbecker** [comment]
@tdonohue thank you for taking care!

**Pull request closed without merging**
