### PR TITLE
DS-2699 improve search

### PR DESCRIPTION
**Pull request by aschweer**
https://jira.duraspace.org/browse/DS-2699

### CODE REVIEW

**Comment by aschweer** [comment]
Please don't merge this yet:
* it requires more testing. 
* the syntax fix is currently XMLUI-only; if we agree that the escaping behaviour in this PR is what we want then the same change needs to be made in JSPUI. 
* finally, if we agree to make the default operator change then we may want to add a comment to the legacy option in dspace.cfg to make it clear that the setting in the solr config file is what's actually used.

**Comment by keithgee** [comment]
We are running this at vtechworks.lib.vt.edu, if it's helpful for use in testing. I

**Comment by hardyoyo** [comment]
+1 as-is, when you're happy with the code, @aschweer, please merge it and backport it to the 5_x maintenance branch, thanks!

**Comment by helix84** [comment]
Please, don't backport the change of default search operator. That's a very large change for a bugfix.

**Comment by hardyoyo** [comment]
@helix84: even if the original change to the OR default operator was not discussed or approved, and was unintentional?

**Comment by aschweer** [comment]
As much as I personally believe that defaulting to OR is a bug in search (I can't see any use case where this would make sense; in my experience, users these days want search to "do what Google does" and Google sure doesn't use OR), the officially stated default currently still is OR -- see [dspace.cfg](https://github.com/DSpace/DSpace/blob/master/dspace/config/dspace.cfg#L253). It's just that the setting in dspace.cfg is ignored completely in Discovery.

Is this perhaps a question that should be put to DCAT? Clearly it does at least require more committer discussion, so I'm not merging this yet.

**Comment by hardyoyo** [comment]
Ah, I see, there it is in the dspace.cfg. So... if we don't want to wait for a whole lot of discussion, it seems like the most prudent thing to do is to recode this so that the configuration is honored by Discovery, yes?

**Comment by helix84** [comment]
> the most prudent thing to do is to recode this so that the configuration is honored by Discovery, yes?

I support that.

**Comment by aschweer** [comment]
> the most prudent thing to do is to recode this so that the configuration is honored by Discovery, yes?

That occurred to me on the way home too. Anyone know whether the solr config file is included in the variable expansion thing? And if not, how to make it be included?

**Comment by hardyoyo** [comment]
@aschweer: I like the idea of just filtering the solr config file. Filtering is configured here: https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace/src/main/assembly/assembly.xml

**Comment by hardyoyo** [comment]
You'd have to first add the Solr config to the excludes here: https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace/src/main/assembly/assembly.xml#L56 and then specifically copy and filter it in the same fashion as we copy/filter dspace.cfg: https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace/src/main/assembly/assembly.xml#L56

**Comment by tdonohue** [comment]
-1 to filtering this value from dspace.cfg.  I'd like to get us out of the habit of trying to perform variable replacement on all these various configs, as that variable replacement can be a bit "fragile" (and if it didn't work right, Solr will fail to start with an odd error, likely).  I'd rather we simply document where/how to change this in the `schema.xml` file.

I, personally, like the idea of setting this search operator to AND by default. I think it's a necessary change, and it is the expected behavior.

But, that being said, it could be arguable that we should make the AND switch in 6.0 instead of 5.4.  Historically, looking back at the code, here's how things seem to have played out:
* Since DSpace 1.4.x (or possibly earlier) we've always used boolean OR for Lucene defaults: https://github.com/DSpace/DSpace/commit/9a330458f7727ad65ceb6adb0c0d1c4e27e24d32
* When Discovery (Solr) was introduced in 1.7.x (https://jira.duraspace.org/browse/DS-711), it also used boolean OR.  Why it was set to that is unclear/unknown (perhaps to match with the Lucene defaults, or maybe it was just the default setting of Solr).
* Since 1.7.x, Discovery has always used boolean OR.

I think we should discuss this switch of boolean operators in this week's meeting. The rest of this PR should be added to 5.4. But, it's possible we'd decide to delay the boolean operator change until 6.0

**Comment by aschweer** [comment]
Thanks for the comments everyone. As discussed in today's dev meeting, we'll split this PR and apply the syntax fix to 5.4 but leave the operator change for 6.0. I'll close this PR and will make separate new ones shortly.

**Comment by aschweer** [comment]
* https://github.com/DSpace/DSpace/pull/1107 new PR for syntax fix only - now also for JSPUI, it'd be great if someone could give this a go
* https://github.com/DSpace/DSpace/pull/1106 new PR for default operator change

**Pull request closed without merging**
