### PR TITLE
DS-3511: Fix HTTP 500 errors on REST API bitstream updates

### PR DESCRIPTION
**Pull request by AndrewBennet**
This is a replacement pull request for https://github.com/DSpace/DSpace/pull/1840 - the commit has been cherry-picked onto the `dspace-6_x` branch.

### CODE REVIEW

**Comment by minurmin** [comment]
Sorry to have missed the earlier comments. PR 1840 should be fixed now as well.

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me

**Review by kshepherd — APPROVED** [review]
+1 by inspection, thanks @AndrewBennet !

**Review by terrywbrady — APPROVED** [review]
Tested and confirmed fix

**Pull request merged**
