### PR TITLE
DS-3436 5x Sharding SOLR cores corrupts multivalued fields for master

### PR DESCRIPTION
**Pull request by terrywbrady**
Port Tom Desair's fix in https://github.com/DSpace/DSpace/pull/1613/files to 5x

https://jira.duraspace.org/browse/DS-3436

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 Looks good. Approved in #1613 (6.x version)

**Comment by tdonohue** [comment]
@terrywbrady : crud, this one seems to now have a (minor) code conflict. If you can rebase this one, I'll merge it.

**Comment by terrywbrady** [comment]
@tdonohue , the merge is resolved.

**Comment by tdonohue** [comment]
Thanks @terrywbrady , merging.

**Pull request merged**
