### PR TITLE
DS-3387 ORCID/SolrAuthority Lookup button doesn't work in Mirage2

### PR DESCRIPTION
**Pull request by helix84**
https://jira.duraspace.org/browse/DS-3387

updating handlebars reportedly resolves the problem

### CODE REVIEW

**Comment by alanorth** [comment]
Look at the commit again, I think you committed the wrong change.

**Comment by helix84** [comment]
@alanorth Sorry, fixed.

**Review by seancarte — APPROVED** [review]
After changing the handlebars version from 2.0.0 to 4.0.0 in bower.json, the 'Lookup' button now launches the Person lookup dialogue. 

Unfortunately this change also seems to affect the advanced search filters.
selection_007

**Comment by tobosi** [comment]
Dear guys

You said that it is claimed that updating handlebar fixes the ORCID lookup functionality, which I agree
with you but have you guys looked at the advanced search filters, because now they are blank and when
I revert back to the default version of handlebar that compiled with DSpace in our case 2.0.0 the advanced
search filters now show.

Is any of you guys facing the same issue?

**Review by tobosi — COMMENTED** [review]
Does work but messes up your advanced search filters...

**Review by bram-atmire — CHANGES_REQUESTED** [review]
Unfortunately, the current Mirage 2 templates won't work with handlebars 4.0.0. Would currently advise against merging this until Mirage 2 is thoroughly tested against handlebars 4.0.0

**Comment by tobosi** [comment]
Thanks Bram... The silence got for me worried but it is good to see that
there are people looking into this.

**Comment by tdonohue** [comment]
Closing this ticket, as it sounds like we cannot currently upgrade to Handlebars 4.0.0.  Once it is determined this is possible, we can reopen (as needed). Until then, a different solution would need to be found.

**Comment by tobosi** [comment]
Thank you

**Pull request closed without merging**
