### PR TITLE
Fix DS-1977 v6

### LINKED ISSUE #5343: [DS-1977] "Private" Items are incorrectly listed in Google Sitemaps
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-1977">[DS-1977]</a> created by tdonohue</i>
<p>If you mark an item as "private" in the Submission UI or the Admin UI, it is still listed in the generated Sitemaps.</p>

<p>By definition, a "private" item should be hidden from all browse/search interfaces, and therefore we should not encourage Google and other search engines to index them. Private items are still potentially accessible via direct URL, but should not be easy to discover/find in any search engines.</p>

<p><a href="https://wiki.duraspace.org/display/DSDOC4x/DSpace+Item+State+Definitions" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.duraspace.org/display/DSDOC4x/DSpace+Item+State+Definitions</a></p>

<p>To Reproduce this issue:</p>
<ul>
	<li>Create a Item, and mark it as "private"</li>
	<li>That item will not be discoverable in the DSpace Browse or Search UIs</li>
	<li>However, if you regenerate the DSpace Sitemaps, that item will still be listed in the Sitemap.</li>
</ul>

<p>The expected result:</p>
<ul>
	<li>If an item is marked as "private" it should NEVER appear in the generated SiteMaps.</li>
</ul>

### PR DESCRIPTION
**Pull request by alejandratenorio**
Fixes #5343

### CODE REVIEW

**Comment by tdonohue** [comment]
Alternative implementation in #2555

**Review by nwoodward — APPROVED** [review]
:+1: Tested and confirmed this works. It's also a cleaner, simpler solution than #2555, and it doesn't require any new tests. I think this one should be merged and mine closed.

**Comment by alanorth** [comment]
Tested and working well here too. Very clean solution! Looks good to me.

**Comment by J4bbi** [comment]
@kshepherd , I've not tested but this now has +2

**Comment by J4bbi** [comment]
Just to note, I closed this PR with the intention of restarting the travis/ci checks. But I didn't know the originating repository does not exist anymore. I might have to resubmit this code myself unless @alejandratenorio can? Apologies for the inconvenience

**Comment by tdonohue** [comment]
This PR was recreated in #7930

**Pull request closed without merging**
