### PR TITLE
fix an error when harvesting arXiv OAI-PMH

### LINKED ISSUE #8128: arXiv harvest via OAI-PMH throws NPE
**Describe the bug**

Hi Dspace community, I opened a pull request (#8022) last November to address an error when harvesting arxiv papers. But no response nor feedback about it yet. Only today did I realise that I should open an issue ticket first, after reading the contribution guide. I am new to dspace, sorry about this.

The bug I am reporting has been described thoroughly in the pull request. It only affects arxiv harvest, as far as I tested not for other dspace installations. The first-time harvest is successful but all subsequent harvests fail and throw null exceptions.

**To Reproduce**

1. set up a collection to harvest an arXiv list
2. Wait for it to finish
3. Import it again (not reset and reimport)
4. Throws null pointer exception

**Expected behaviour**

When importing it again subsequently after the initial import success, it should not throw any errors and should finish the incremental harvest fairly quickly.

**Related work**

the pull request that fixed this issue #8022

### PR DESCRIPTION
**Pull request by astrowq**
## Description
Fixes #8128 
Add a new entry to the `parseFmt` array for parsing dates in the format of `yyyy-MM-dd`.

## Instructions for Reviewers

This is a quick fix to the problem I encountered when I was harvesting the metadata from the arXIv OAI-PMH.

The first-time harvest is successful but all subsequent harvest fails and throws a null exception. The problem was that arXiv OAI-PMH gives the date in the format of "yyyy-MM-dd" e.g. `<datestamp>2021-11-02</datestamp>`. Subsequent harvest needs to compare the harvested item's date stamp to the one from the provider. Specifically, the following code causes the null exception (`OAIDatestamp` is null): 

https://github.com/DSpace/DSpace/blob/e297d9809592d63248cceb0155d51143ee535e46/dspace-api/src/main/java/org/dspace/harvest/OAIHarvester.java#L550

`parseISO8601Date` cannot parse a date such as `2021-11-02` as there is no matched date format. The actual error happens in the following for loop:

https://github.com/DSpace/DSpace/blob/e297d9809592d63248cceb0155d51143ee535e46/dspace-api/src/main/java/org/dspace/core/Utils.java#L344

Simply adding a new format `SimpleDateFormat("yyyy'-'MM'-'dd")` wouldn't solve the whole problem. One more step has to be done in the line:

https://github.com/DSpace/DSpace/blob/e297d9809592d63248cceb0155d51143ee535e46/dspace-api/src/main/java/org/dspace/core/Utils.java#L337

to ensure that dates such as `2021-11-02` will not be changed to `2021GMT-11-02`.

A separate commit performs some simple code refactoring.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by astrowq** [comment]
The test `RelationshipTypeRestControllerIT.findAllEntityTypes` fails but I don't think it's caused by my commits...

**Comment by tdonohue** [comment]
@astrowq : There was an IT failure on our `main` branch as you noted. It's been fixed in #8026 which was just merged. So, if you rebase this PR on the latest `main` code, then you should no longer see that random IT failure.

**Comment by tdonohue** [comment]
@astrowq : Apologies that this PR seems to have been forgotten about....it looks like I was waiting on you to rebase, and didn't notice when that work had been completed.  I've now pulled this onto one of our release boards to ensure it gets reviewed. (I've pulled it onto our 7.2 board, but as we are wrapping up 7.2 in the next week, it's possible this may be moved to 7.3, we'll see)

**Review by tdonohue — APPROVED** [review]
Thanks @astrowq ! Gave this a review and test today. The code changes are all useful simplifications/refactors (and I noticed most of these were immediately suggested by my IDE when I opened the `Utils.java).  Also tested a harvest from arXiv and it was successful.  Thanks again!

**Comment by astrowq** [comment]
Thank you too! It's actually my first ever open source contribution on GitHub if I didn't get it wrong.

**Pull request merged**
