### PR TITLE
DS-4078

### PR DESCRIPTION
**Pull request by pnbecker**
https://jira.duraspace.org/browse/DS-4078

Should be cherry-picked to master.

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 Looks obvious, but I didn't test it.

@kshepherd : since you reported, maybe you could do a quick test here?

**Comment by pnbecker** [comment]
I tested it on the code @kshepherd was working on when he discovered it. Works fine. :-)

**Review by terrywbrady — APPROVED** [review]

**Comment by marsaoua** [comment]
I tested it, the bitstream format is set properly!

**Comment by tdonohue** [comment]
Ported this to `master` branch in #2262.  Once Travis approves, we should merge that one immediately too and close the DS-4078 ticket.

**Pull request merged**
