### PR TITLE
[DS-2621] adjust check to enable not mandatory collection via jsp

### PR DESCRIPTION
**Pull request by lap82**
Contribution from DSpace-CRIS (https://wiki.duraspace.org/display/DSPACECRIS/DSpace-CRIS+Home)

### CODE REVIEW

**Comment by abollini** [comment]
+1 please open a pull request also for the master

**Comment by lap82** [comment]
PR for master done at https://github.com/DSpace/DSpace/pull/1328

**Comment by tdonohue** [comment]
Closing this PR. We have no further plans to release 5.x bug fix versions. Its changes were already merged into "master" for the 6.0 release (see #1328)

**Comment by abollini** [comment]
Hi Tim,
I guess that we should always accept/evaluate PR for supported version also if there are not formal plan to make a new release. In this way people can easily found all the fix partially reviewed also if not fully tested (unreleased version). If and when we decide to make a bug fix release or when it is required for some security fix the other bug fix will be already in.
Should we reopen this pull request?

**Pull request closed without merging**
