### PR TITLE
DataCite DOI error fixes

### LINKED ISSUE #9641: DataCite DOI integration: errors caused by DIM2DataCite.xsl matches against dc.identifier.* instead of dc.identifier.uri
**Describe the bug**
The default DataCite DOI integration stores registered dois in dc.identifier.uri:
https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/identifier/DOIIdentifierProvider.java#L74

In the DIM2DataCite.xsl crosswalk, there are several lookup points where dc.identifier.* values are evaluated and checked against the presence of the repository-specific prefix.

One case where this is especially problematic, is for the default use of dc.identifier.citation, the default field where a full citation, including the DOI, is typically stored. Because that citation value very often also contains the DOI, it sets off the detections/evalations, making the crosswalk think that this is the field where DOI is stored.

**Code references**
Here are the places where the crosswalk calls out an evaluation that takes any qualifier into account:

* https://github.com/DSpace/DSpace/blob/main/dspace/config/crosswalks/DIM2DataCite.xsl#L72
* https://github.com/DSpace/DSpace/blob/main/dspace/config/crosswalks/DIM2DataCite.xsl#L248
* https://github.com/DSpace/DSpace/blob/main/dspace/config/crosswalks/DIM2DataCite.xsl#L250
* https://github.com/DSpace/DSpace/blob/main/dspace/config/crosswalks/DIM2DataCite.xsl#L336
* https://github.com/DSpace/DSpace/blob/main/dspace/config/crosswalks/DIM2DataCite.xsl#L563

Of these, the one on 336 is probably the most problematic one
https://github.com/DSpace/DSpace/blob/main/dspace/config/crosswalks/DIM2DataCite.xsl#L336 

```
   <xsl:template match="dspace:field[@mdschema='dc' and @element='identifier' and @qualifier and (contains(., $prefix))]">
        <identifier identifierType="DOI">
            <xsl:if test="starts-with(string(text()), 'https://doi.org/')">
                <xsl:value-of select="substring(., 17)"/>
            </xsl:if>
            <xsl:if test="starts-with(string(text()), 'http://dx.doi.org/')">
                <xsl:value-of select="substring(., 19)"/>
            </xsl:if>
        </identifier>
    </xsl:template>
```

let’s say I have “My fantastic publication 10.5465464/5646546” in dc.identifier.citation, the template will match BUT subsequently, both of the ifs will fail because the field doesn’t start with http or https, leading to a null value.

This null value is then problematic for the evaluation happening here:
https://github.com/DSpace/DSpace/blob/15445904548758337ff2609bb69e2d70cce418c0/dspace-api/src/main/java/org/dspace/identifier/doi/DataCiteConnector.java#L413

**To Reproduce**
1. Make an item with a registered DOI, so that the final DOI ends up in dc.identifier.uri & that the DOI registration process is fully finished
2. Add a value to dc.identifier.citation that includes also the DOI, with the repository specific prefix.
3. Run the DOI organiser

**Observed behavior**
The error can include statements like:

```
2024-06-06 09:34:34,298 ERROR unknown unknown org.dspace.identifier.doi.DataCiteConnector @ While reserving a DOI, the crosswalk to generate the metadata used another DOI than the DOI we're reserving. Cannot reserve DOI doi:10.13025/Q4NC-6E94 for ITEM 4239c009-ca14-4a4a-9fb9-483e0c1c8d81.
```

**Expected behavior**
A reference to the DOI, as part of the dc.identifier.citation value, should not trigger any errors when the metadata needs to be updated.

### PR DESCRIPTION
**Pull request by Atmire-Kristof**
## References
* Fixes #9641 

## Description
`DIM2DataCite.xsl` matched against `dc.identifier.*` to retrieve the DOI from the item's metadata, but this caused the DOI to be empty sometimes (not null), when it was present in another identifier field, but not properly structured (e.g. in the middle of a `dc.identifier.citation`).
This PR aims to fix the issue by specifying `dc.identifier.uri` in the xsl, as well as a fallback change inside `DataCiteConnector` to catch empty values and retrieve the DOI from the database instead (it already did this for null values, but not empty strings).

## Instructions for Reviewers
List of changes in this PR:
* Changed xsl match to target just `dc.identifier.uri`
* Added fallback to empty strings

How to test:
* Setup DOI DataCite registration ([docs](https://wiki.lyrasis.org/display/DSDOC7x/DOI+Digital+Object+Identifier))
* Submit an item and ensure the new DOI is present in the "doi" database table
* Add metadata to the item for `dc.identifier.citation` containing a DOI using the configured prefix, but excluding the URI part (e.g. _without_ "https://doi.org/")
* Run script `doi-organiser -u`

Before my changes, this script would produce errors because it finds a metadata value containing a DOI, but since it's not structured like a uri, it'll return an empty string and cause an error.
After my changes, it should ignore all other identifier fields.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by pnbecker** [comment]
@Atmire-Kristof Thank you for this PR. I think the changes would work out well. I would prefer to push the metadata field as parameter into the XSLT like it is done with the prefix and the publisher (see https://github.com/DSpace/DSpace/blob/main/dspace/config/crosswalks/DIM2DataCite.xsl#L29-L38 and https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/identifier/doi/DataCiteConnector.java#L367-L385). Then the field could be changed in the javacode/configuration only would not have to be reflected in the XSLT. Can you make this small change please?

**Comment by Atmire-Kristof** [comment]
@pnbecker Thank you for the feedback. It's indeed a great idea to move the metadata-field away from the XSL file.
Turning it into a configuration would be the most ideal scenario, but I'd like to avoid that for now, since this would also require at least `DOIIdentifierProvider` to be modified to use the same configuration. As that is a bit too much overhead right now, I decided to keep it to just java code changes within `DataCiteConnector`, but have them reference to the same variables.

I also made sure to write the XSL in a way that would allow for an "empty" qualifier, in case the metadata-field is configured to one without a qualifier. This is possible by passing an empty string to the crosswalk parameters. I also clarified this with an inline comment.

**Review by pnbecker — APPROVED** [review]
+1 by code review.

I haven't tested that. It would be good if someone could give this a quick test run.

**Comment by pnbecker** [comment]
Thank you @Atmire-Kristof for using parameters. This looks good to me. I haven't tested it myself and would appreciate if someone could test it. +1 by code review.

**Pull request merged**
