### PR TITLE
[DS-2784] jersey version changed to 1.19

### PR DESCRIPTION
**Pull request by akotynski**

### CODE REVIEW

**Comment by peterdietz** [comment]
This fixes REST on dspace5x to work on JDK8. +1 Looks good to me.

**Comment by akotynski** [comment]
`DSpace 5.4 is a bug fix release to resolve several issues located in DSpace 5.0, 5.1, 5.2 or 5.3` - is there any chance to merge this PR ?

**Comment by tdonohue** [comment]
:+1:  by inspection. Looks good to merge to me

**Comment by peterdietz** [comment]
Yep, looks good, merging into 5x, after 5.3, before 5.4

**Pull request merged**
