### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by alanorth**
## Description
Bump a handful of dependencies in various `pom.xml` files. I used the [renovate bot](https://docs.renovatebot.com/) in a fork of the DSpace repository to unearth viable dependency updates. In most cases these are _minor_ and _patch_ level updates (ie 2.x.x) , as I specifically excluded major ones. In many cases they updates fix bugs, improve performance, improve compatibility with newer Java versions, and update transitive dependencies.

I have tested browsing, searching, editing items, submitting new ones, and Discovery indexing. All working as expected.

## Instructions for Reviewers

List of changes in this PR:
* Try building DSpace with `mvn -U clean package` to make sure you don't use any old packages
* Try running DSpace
* Try various normal actions in the web interface, command line, HAL browser, and various APIs.

### CODE REVIEW

**Comment by alanorth** [comment]
@tdonohue this one won't apply easily to `dspace-7_x` because there was a previous batch of dependency updates on `main` (https://github.com/DSpace/DSpace/pull/8884) and the two branches have diverged. I can look at doing a batch of similar updates for `dspace-7_x` if you'd like.

**Comment by tdonohue** [comment]
@alanorth : If you are willing, it'd be appreciated.  As much as possible, it'd be nice to backport any minor/patch level dependency updates to 7.6.x.

**Comment by tdonohue** [comment]
@alanorth : Today I discovered how to do a multi-cherry-pick.  So, I tried it out on the old #8884 PR to port it to `dspace-7_x` in order to ensure this PR can be merged more cleanly.  See https://github.com/DSpace/DSpace/pull/9305

Overall, we should try to remember to sync up these minor dependency changes...but major dependency changes likely need to only be on `main`.  Just a reminder for myself as well.

**Comment by alanorth** [comment]
@tdonohue oh that's great! I've used cherry-pick with ranges of commits before though I have to look up the semantics every time. You're right that porting the previous round of dependency bumps to `dspace-7_x` will make applying this easier. I'll keep that in mind in the future.

**Review by tdonohue — APPROVED** [review]
👍 Looks great @alanorth !  I've tested this locally and all seems to be working as before. No obvious issues.  Merging this immediately as I want to have these changes in place before we do more work on #8713 (as that requires even more major dependency changes).

**Pull request merged**
