### PR TITLE
Oracle migration error

### LINKED ISSUE #7958: oracle migration errors
### **Environment:**
	DSpace5.8
	Centos 7
	Apache Tomcat/8.0.36
	Oracle Database 11g Enterprise Edition Release 11.2.0.4.0

I tried to migrate our DSpace to version 7 from version 5 But it ended with a fatal error ,so I tried to run the scripts that fail by hand until the migration was finished

This is the list of scripts that fail me with the adopted solution:

**File:** 		
V6.0_2016.04.04__DS-3086-OAI-Performance-fix.sql
**Sentence:**
CREATE UNIQUE INDEX metadataschema_idx_short_id on metadataschemaregistry(short_id)
**Error Message :**
ORA-01408: such column list already indexed
**My temporal fix :** 
The index already exits in the database. Remove sentence

**File:**
V7.0_2018.04.16__dspace-entities.sql 
**Sentence:**

	CREATE TABLE relationship
	(
		id                      INTEGER NOT NULL PRIMARY KEY,
		left_id                 uuid NOT NULL REFERENCES item(uuid),
		type_id                 INTEGER NOT NULL REFERENCES relationship_type(id),
		right_id                uuid NOT NULL REFERENCES item(uuid),
		left_place              INTEGER,
		right_place             INTEGER,
		CONSTRAINT u_constraint UNIQUE (left_id, type_id, right_id)
	);

**Error Message:** 
ORA-00902: invalid datatype
**My temporal fix:** 
no type uuid. Change uuid for raw(16)

	CREATE TABLE relationship
	(
		id                      INTEGER NOT NULL PRIMARY KEY,
		left_id                 raw(16) NOT NULL REFERENCES item(uuid),
		type_id                 INTEGER NOT NULL REFERENCES relationship_type(id),
		right_id                raw(16) NOT NULL REFERENCES item(uuid),
		left_place              INTEGER,
		right_place             INTEGER,
		CONSTRAINT u_constraint UNIQUE (left_id, type_id, right_id)
	);

**Sentence:**
	
	CREATE INDEX relationship_type_by_left_type_idx ON relationship_type(left_type);
	CREATE INDEX relationship_type_by_right_type_idx ON relationship_type(right_type);
	CREATE INDEX relationship_type_by_left_label_idx ON relationship_type(left_label);
	CREATE INDEX relationship_type_by_right_label_idx ON relationship_type(right_label);

**Error Message:**
ORA-00972: identifier is too long
**My temporal fix:**
shorten identifiers below 30 characters

**File:**
V7.0_2019.07.31__Retrieval_of_name_variant.sql 
**Error Message:**
ORA-00906: missing left parenthesis
**Sentence:**
  
     ALTER TABLE relationship ADD leftward_value VARCHAR(50);
     ALTER TABLE relationship ADD rightward_value VARCHAR(50);

**My temporal fix**:
Specify length. Use VARCHAR2 instead of VARCHAR		

    ALTER TABLE relationship ADD leftward_value VARCHAR2(50);
    ALTER TABLE relationship ADD rightward_value VARCHAR2(50);

**File:**
V7.0_2019.11.13__relationship_type_copy_left_right.sql			

**Sentence:**  

		ALTER TABLE relationship_type ADD copy_to_left BOOLEAN DEFAULT FALSE NOT NULL

**Error Message:**
ORA-00984: column not allowed here

**My temporal fix:** 
No BOOLEAN type in ORACLE. I don't have a clear solution. I have changed BOOLEAN to NUMBER, but this change leads to changes in the DSPACE source code.

### PR DESCRIPTION
**Pull request by jvribell**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #7958
* Related to [REST Contract](https://github.com/DSpace/Rest7Contract)

## Description

Fix incorrect oracle statements

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 The changes here make sense based on the reasons listed in the original ticket #7958, along with the notes in our own Oracle README (which notes we must use NUMBER(1) instead of BOOLEAN and VARCHAR2 instead of TEXT, etc.) https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/oracle/README.md

Unfortunately, I don't have an Oracle test environment to test this out.  @jvribell , has your team tested these changes with DSpace 7 to ensure no major impacts?  (I'm assuming you have, but wanted to double check)

It appears (to me) like this PR *might* also fix at least some of the issues listed in #8008, so perhaps @marianovelasco may also be interested in helping to test these changes.

Overall, I think this PR looks correct & beneficial to merge into 7.2.  However, I'd love some verification that it's been tested before we merge it.

**Comment by tdonohue** [comment]
I'm still looking for some sort of verification that this works for an Oracle site.  If it does, we can go ahead and merge it.  @jvribell have you tested this?  Anyone else interested in chipping in here on a basic test of this PR? Maybe marianovelasco?

**Comment by jvribell** [comment]
Hello

I am having some problems, both with the migration and the deployed version, but I think they are not related to these commits.

The commits are just fixes to the oracle sql syntax , which is quite strict ,I don't think there are many other alternatives.

I will spend some time to find and fix all the bugs in the migration. You can add these commits or wait until we have all the bugs localized and add them all together.

**Comment by tdonohue** [comment]
Merging this with +1 approval.  The Oracle Syntax changes look correct here based on Oracle docs & past Oracle migrations (which performed similar changes).  I've still not been able to test these or find a tester, but the changes in this PR look correct & are likely better than current `main`.  Additional changes are welcome in a future PR, as needed.

**Pull request merged**
