### PR TITLE
[DS-2763] EHCache throwing a NotSerializableException: org.dspace.content.CollectionServiceImpl

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://jira.duraspace.org/browse/DS-2763

Thanks to FindBugs for pointing out numerous difficulties with Serializable.

### CODE REVIEW

**Comment by mwoodiupui** [comment]
I think this is about as Serializable-clean as can be done without more radical restructuring.  A few classes *must* be Serializable but cannot be due to holding references to non-Serializable classes from non-DSpace projects.

I would appreciate some inspection of JSPUI from someone more familiar with Servlet coding.  I had to make some more substantial changes to many Servlets and tag classes.

**Comment by hardyoyo** [comment]
+1, builds, everything still runs (i.e. "smoke test passed"), and I can confirm the serialization error messages are now gone from dspace.log. Unit tests are not currently working in my environment, however I can see the green checkmark above indicating that TravisCI was able to run them successfully.

**Comment by KevinVdV** [comment]
Did an inspection of the code & it looks good, so +1.

**Comment by helix84** [comment]
Cool, glad we can finally squash this bug. Thank you!

**Pull request merged**
