### PR TITLE
Support DSpace 6 REST Report Utilities in DSpace 5_x

### PR DESCRIPTION
**Pull request by terrywbrady**
See https://wiki.duraspace.org/display/DSDOC6x/REST+Based+Quality+Control+Reports#RESTBasedQualityControlReports-InstallinginDSpace5

### CODE REVIEW

**Comment by alanorth** [comment]
As your branch is based on 5.7-snapshot, I cherry-picked the changes into my 5.5 branch and it merges/builds cleanly. Side note: your commits introduce a lot of unnecessary whitespace changes, you should `git checkout -p` to discard some of those.

I tested the endpoints under `/rest/registries` and they work fine, but the reports under `/rest/static/reports/{query,metadata}/index.html` are not available despite being present in the filesystem at those paths.

**Comment by terrywbrady** [comment]
@alanorth , check the following endpoints

- /rest/filters
- /rest/filtered-items
- /rest/filtered-collections
- /rest/hierarchy

If all of those components are working, then I suspect there is a bug in 
/dspace-rest/src/main/webapp/WEB-INF/web.xml

which exposes the html and javascript assets.

**Comment by alanorth** [comment]
These are working fine:

- [x] /rest/filters
- [x] /rest/filtered-items
- [x] /rest/filtered-collections
- [x] /rest/hierarchy

Not sure what to look for in `dspace-rest/src/main/webapp/WEB-INF/web.xml`, I see:

```
    <servlet-mapping>
        <servlet-name>default</servlet-name>
        <url-pattern>/static/*</url-pattern>
    </servlet-mapping>
```

**Comment by terrywbrady** [comment]
@alanorth , it sounds like all of the endpoint code is running properly.  Are you able to see any error messages in the logs when you attempt to load the html resources? 
- /rest/static/reports/index.html
- /rest/static/reports/query.html

 What happens if you try to access one of the javascript files?
- /rest/static/reports/restReport.js?

**Comment by alanorth** [comment]
The files exist in the rest webapp:

```
$ ls ~/dspace/webapps/rest/static/reports
authenticate.html  index.html  query.html  restClient.css  restCollReport.js  restQueryReport.js  restReport.js  spin.js
```

Requests for any of these HTML or JS files fail with an HTTP 404:

```
$ http --print Hh http://localhost:8080/rest/static/reports/index.html
GET /rest/static/reports/index.html HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/0.9.6

HTTP/1.1 404 Not Found
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: origin, content-type, accept, authorization
Access-Control-Allow-Methods: GET, OPTIONS, HEAD
Access-Control-Allow-Origin: http://localhost:8080
Content-Length: 0
Date: Wed, 16 Nov 2016 08:45:12 GMT
Server: Apache-Coyote/1.1
```

The Tomcat localhost access log shows HTTP 200 for the other rest endpoints, but 404's for static reports:

```
127.0.0.1 - - [16/Nov/2016:10:09:51 +0200] "GET /rest HTTP/1.1" 200 6149
127.0.0.1 - - [16/Nov/2016:10:09:57 +0200] "GET /rest/registries/schema HTTP/1.1" 200 35545
127.0.0.1 - - [16/Nov/2016:10:18:30 +0200] "GET /rest/static/reports/index.html HTTP/1.1" 404 -
127.0.0.1 - - [16/Nov/2016:10:40:33 +0200] "GET /rest/static/reports/restReport.js HTTP/1.1" 404 -
```

For what it's worth, I **can** resolve static files in the JSPUI application, ie `/jspui/static/css/jquery.fileupload-ui-noscript.css`. Are there any other logs I should look in?

**Comment by terrywbrady** [comment]
If you look at your deploy directory in ~dspace/rest/webapps/WEB-INF/web.xml, do you see the following

    <servlet-mapping>
        <servlet-name>DSpace REST API</servlet-name>
        <url-pattern>/*</url-pattern>
    </servlet-mapping>
    
    <servlet-mapping>
        <servlet-name>default</servlet-name>
        <url-pattern>/static/*</url-pattern>
    </servlet-mapping>
    
    
    <security-constraint>

**Comment by terrywbrady** [comment]
@alanorth , I posted a question about this in the irc room.  

[09:38:10]	‹mhwood›  It's a mystery to me, alas. I wonder if there is something in non-access Tomcat logs? It could be Servlet security configuration, or file ownership, or some such, and that might be logged elsewhere while Tomcat is being cagey about the response it sends.
[09:38:47]	‹mhwood›  It may require turning up the log level on Tomcat. Dunno.

**Comment by alanorth** [comment]
I see this in `webapps/rest/WEB-INF/web.xml`:

```
    <servlet-mapping>
        <servlet-name>DSpace REST API</servlet-name>
        <url-pattern>/*</url-pattern>
    </servlet-mapping>

    <!-- Security settings and mapping -->
    <!--<security-constraint>-->
        <!--<web-resource-collection>-->
            <!--<web-resource-name>DSpace REST API</web-resource-name>-->
            <!--<url-pattern>/*</url-pattern>-->
        <!--</web-resource-collection>-->
        <!--<user-data-constraint>-->
            <!--<transport-guarantee>CONFIDENTIAL</transport-guarantee>-->
        <!--</user-data-constraint>-->
    <!--</security-constraint>-->
```

There's no mapping for static. I think this might have to do with Atmire stuff, as I also see `com.atmire.dspace.rest` in here, so I guess their modules are fiddling around in rest as well, so our DSpace 5.5 codebase really isn't a very representative test.

**Comment by terrywbrady** [comment]
@alanorth , based on this, I presume you might have a rest module override in dspace\modules\rest\src\main\webapp

If you can get this block into your code, I think those files will become visible
https://github.com/DSpace/DSpace/pull/1568/commits/1db76088ab3307d0fa0a41e21bdae44a1b421ebb

**Comment by alanorth** [comment]
There must be some filters or something in effect, because I have that commit in my code, but the resulting `webapps/rest/WEB-INF/web.xml` doesn't have the static mappings. I think it's an Atmire issue.

**Comment by tdonohue** [comment]
While I appreciate the effort put into this. I don't think we should "backport" this 6.0 REST API feature to the 5.x REST API. We don't make a habit of backporting major features to previous releases (in general).  

However, if others wish to use this PR to backport this on their own instance, they are more than welcome to!

**Comment by terrywbrady** [comment]
Re-opening to document this as an optional upgrade.  Not intended for merge into code base.

**Comment by terrywbrady** [comment]
Re-closing, verified build/install with DSpace 5.8

**Pull request closed without merging**
