### PR TITLE
Add ability to opt-out of relation metadata fields when deriving metadata from relationships.

### PR DESCRIPTION
**Pull request by aprilherron**
## Description
In repositories that contain 100s-1000s of relationships, REST performance can become very slow due to the generation of relation metadata during most REST calls. To mitigate this problem, a solution has been developed to opt-out of any unnecessary relationships. For example, image an OrgUnit with 1000s of Publications. Generating all of the relation metadata for every `isPublicationOfOrgUnit` value can take minutes, leaving page just hanging. Instead, we can exclude `isPublicationOfOrgUnit` and performance is drastically improved.

Note: This does not impact indexing, so virtual metadata and queries which rely on bi-directional relationships still function as expected.

## Instructions for Reviewers
1. Create an item with 100s-1000s of child relationships.
2. Test performance
3. Configure `virtual-metadata.xml` to exclude the parent-to-child relationships label
4. Repeat performance test

List of changes in this PR:
* Add new `ignoredRelationFields` value to `VirtualMetadataPopulator` and config
* When generating relation metadata, don't include relationships with labels in this Set.

## Checklist
- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [N/A] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [N/A] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by tdonohue** [comment]
@KingKrimmson : This might be a silly question, but if we know that this problem can exist *anytime* a "parent" object has 100s or 1000s of "children" objects, then won't we need to essentially **disable** relation metadata for _all_ parent to child relationships?

I took a quick glance at this PR, and it looks OK, but it almost sounds like a "quick workaround" for a larger problem.  Am I wrong though?  Do we need a bug ticket that describes the larger problem so that we can look at a widespread fix (rather than having to add problematic relationships one by one to this new `ignoredRelationFields` listing)?

**Comment by mwoodiupui** [comment]
Here is a counterpoint to my complaint elsewhere, a minute ago, about private `cron`s in every application.  What we *do* need is a facility to run time-consuming stuff like this *asynchronously* in a background thread, so that Requests can be released quickly.

**Comment by KingKrimmson** [comment]
@tdonohue That is essentially true. If _overall_ performance of many parent-to-child relationships was improved, this would be unnecessary. However, there may be other instances in which this is helpful as well (e.g. disabling certain relationships in export). This was the solution we developed to mitigate the issue, but perhaps a more widespreadfix would be more appropriate. Moreover, our original implementation was opt-in to relationships, but this PR was made to be opt-out as to not detract from default DSpace behavior.

Noticed the test errors and will update this PR

**Comment by cwilper** [comment]
> @KingKrimmson : This might be a silly question, but if we know that this problem can exist _anytime_ a "parent" object has 100s or 1000s of "children" objects, then won't we need to essentially **disable** relation metadata for _all_ parent to child relationships?

@KingKrimmson thanks for getting the ball rolling on this.

@tdonohue we were also discussing this internally, and I suggested starting with an "opt out" approach for the PR, but there are a couple other valid approaches to avoiding this kind of automatic creation of relation.xyz "metadata" in lopsided relationships. We have also tried an "opt in" approach along the same lines, which worked just as well.

I think the problem you run up against when trying to do this automatically for people is that there's nothing currently that says whether a relationship is a parent-child one, or even whether it's lopsided. It's conceivable that even in a parent-child type of relationship, the tree in your actual data might be narrow enough that it's practical to have relationships automatically included in both directions.

Maybe some combination of a "parent/child" designator in your entity definitions xml, plus a "lopsided" boolean or something that says you don't want relation.xyz metadata to be automatically added to the parent items? I guess you could use cardinality for this (say if it's over 10 or some configurable threshold).

I think this PR is a useful start because it shows that you can scale entity relationships in a practical way (with the right configuration) with DSpace 7. But if it would make more sense to configure it at a little higher level, that seems reasonable as well.

**Comment by tdonohue** [comment]
@KingKrimmson and @cwilper : I appreciate your feedback on the design behind this PR.  That does make some sense now.  I'm OK with this initial opt-out approach _provided that we preconfigure known "problematic" or "lopsided" relationships as ignored_.  So, if there are specific relationships we know have a tendency to hit this performance issue, we should ignore them **by default** (and add a comment to describe why they are ignored, to warn folks on re-enabling them).   That'd imply to me that `isPublicationOfOrgUnit` likely should be in that ignore list by default....it seems likely that even medium-sized org units will have 100s of publications, so this seems like a relationship that is highly likely to be "lopsided" for most users.

I do think we should continue to brainstorm whether there is a common *pattern* here that can be more easily automated or configured more broadly -- as that's a best case scenario.  But, it's reasonable to start with this opt-out idea, provided that we set some "sane defaults" and we document the known scenarios (either in Wiki docs or in comments in the configuration in this PR) where you may want to disable additional relationships.

If that seems reasonable, we can mostly move this PR forward as-is (once tests are fixed & assuming it passes our code coverage requirements -- as I notice there's no new tests here yet).  I'd just recommend we preconfigure `isPublicationOfOrgUnit` to be disabled by default....and add a more descriptive comment to say something like `Disabled by default as it's highly likely that an OrgUnit will have 100s or 1000s of Publications.  This sort of lopsided relationship currently causes performance issues`

**Comment by cwilper** [comment]
Added WIP label because this needs some re-work. I tested against latest `main` branch and noticed it was introducing some unintended delays.

**Comment by cwilper** [comment]
Closing; the problem we were addressing here is more appropriately solved by this PR:

https://github.com/DSpace/DSpace/pull/3134

**Pull request closed without merging**
