### PR TITLE
DS-2504: Method getLink() returns incorrect context path

### PR DESCRIPTION
**Pull request by ctu-developers**
This is only quick fix. The solution will be improved in a few days.

https://jira.duraspace.org/browse/DS-2504

### CODE REVIEW

**Comment by mdiggory** [comment]
There is no rule that the rest api should be served at the URI "/rest". I would recommend using the servlet context, or externalizing a baseURL.

**Comment by ctu-developers** [comment]
Yes, we are planning to do so. Maybe tomorrow;-)

**Comment by ctu-developers** [comment]
I added static method to class Resource. I dont like that dependency between DSpaceObject and Resource, but i think there is no option. (i do not see any other options).

**Comment by mwoodiupui** [comment]
The <extends Resource>, which knows its context path, could supply that path as a constructor argument to its <extends DSpaceObject>, or DSpaceObject could provide a setter to be used by an <extendsResource>.

Ideally DSpaceObject would just supply the part of the path it knows, and <extends Resource> would concatenate that with the part it knows, but I don't know how to do that with all the JAX-RS magic going on.

**Comment by ctu-developers** [comment]
Good ideas, but if it will be setting by constructor or setter, then many code must be changed. I think this is only way how to do it. Because DSpace Object cannot know context path, because it is not Resource. So, it must get it from Resource.

**Comment by peterdietz** [comment]
+1 I think this looks clean, and gets the job done.

**Comment by helix84** [comment]
Does anyone object to merging this as-is?

**Pull request merged**
