### PR TITLE
OAI-PMH use Templates for compiled XSLT instead of Transformer (thread-safe)

### LINKED ISSUE #8846: High memory usage on OAI-PMH interface during and after harvesting
Version: 6.4

**To Reproduce**
1. Harvest with a client the complete dspace repository with loop over all identifiers with the method GetRecord on OAI.

After a big size of harvested items (3000 items) the memory usage is increased on server. But the CPU usage is yet low.
After a big, big size of harvested items (5000 items) the memory usage is increased and the CPU usage is **continuous HIGH**.
The GC running continously and blocks the application (timeouts on OAI-PMH, UI,...). The memory usage retained increased.

This is a new behaviour and doesn't exists in version 6.3.

### LINKED ISSUE #9043: OAI endpoint throws HTTP 500 on multiple requests
**Describe the bug**
A harvester informed us, that the OAI endpoint throws a HTTP 500 on several times. The Harvester use the Method GetRecord in parallel Requests.
The problem is reproduced with JMeter.

**To Reproduce**
1. Disable the OAI file cache in configuration. We will allways do the XSLT transformation `oai.cache.enabled = false` in `modules/oai.cfg`
2. Do parallel GetRecord requests with valid identifiers (for example in metadataformat oai_dc)
3. Check the response of each request

Response header of an response with error
```
HTTP/1.1 500 
Server: nginx/1.23.4
Date: Tue, 29 Aug 2023 08:58:09 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Content-Language: en
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
```

```
{"timestamp":"2023-08-29T08:58:09.541+00:00","status":500,"error":"Internal Server Error","message":"An exception has occurred","path":"/server/oai/request"}
```

image

With the OAI file cache it was less or no probable, if the reults are often in the cache.

### PR DESCRIPTION
**Pull request by ChrisBethgster**
Fixes #9043 
Fixes #8846

Requires: https://github.com/DSpace/xoai/pull/86

### CODE REVIEW

**Comment by tdonohue** [comment]
@ChrisBethgster : I'm assuming this *requires* also https://github.com/DSpace/xoai/pull/86  (since you changed the version of the `xoai` dependency)?  I'd appreciate it if you can provide details on how to test this PR so that I can get a reviewer assigned.

**Comment by ChrisBethgster** [comment]
> @ChrisBethgster : I'm assuming this _requires_ also [DSpace/xoai#86](https://github.com/DSpace/xoai/pull/86) (since you changed the version of the `xoai` dependency)? I'd appreciate it if you can provide details on how to test this PR so that I can get a reviewer assigned.

Yes. I temporarely change the XOAI version to 3.3.1-SNAPSHOT. But a new release of the XOAI dependency is necessary.

https://github.com/DSpace/DSpace/blob/1160341cb2a2c163c8fddc04ddab46de9041e1b8/dspace-oai/pom.xml#L15-L20

**Comment by ChrisBethgster** [comment]
The automatic build failed, because we have not a new xoai build.

`Error: ERROR] Failed to execute goal on project dspace-oai: Could not resolve dependencies for project org.dspace:dspace-oai:jar:8.0-SNAPSHOT: Could not find artifact org.dspace:xoai:jar:3.3.1-SNAPSHOT in maven-central (https://repo.maven.apache.org/maven2) -> [Help 1]`

Manual review is required.

**Comment by toniprieto** [comment]
Thanks @ChrisBethgster ! 

I've tested this PR and it resolves the issue #9043 . I have seen this issue in a 6.x instance recently. 

I've locally reproduced the error running two parallel commands like that against a test instance (using different record_ids)

```
while :; do clear; wget https://hostname/server/oai/request\?verb=GetRecord\&metadataPrefix=oai_dc\&identifier=oai:<hostname>:<record_id> ; done
```

And check that it shows the error in dspace.log: "java.lang.IllegalStateException: The Controller is being used recursively or concurrently. This is not permitted"

`tail -f dspace.log | grep "java.lang.IllegalStateException"`

Then, I've built the xoai project with the xoai PR and I have installed locally the jar with:

```
mvn install:install-file \
-Dfile=/workspace/source/xoai/target/xoai-3.3.1-SNAPSHOT.jar \
-DgroupId=org.dspace \
-DartifactId=xoai \
-Dversion=3.3.1-SNAPSHOT \
-Dpackaging=jar \
-DgeneratePom=true
```

After applying this PR, the issue is solved and the oai interface seems to work properly.

**Review by toniprieto — APPROVED** [review]

**Review by tdonohue — APPROVED** [review]
👍 Thanks @ChrisBethgster !  Tested this alongside your work on XOAI PR https://github.com/DSpace/xoai/pull/86 and it works well.

However, I cannot merge this yet until I release a new version of XOAI (which I'll be naming v3.4.0).  Once that version is released (hopefully early next week), I'll update your PR here with the new version tag (along with any other minor POM updates if needed) and verify this PR then passes all tests.   

I have verified locally though that tests pass, so I think this should only require that new XOAI release (along with any necessary minor POM updates)

**Comment by tdonohue** [comment]
I just released [XOAI v3.4.0](https://github.com/DSpace/xoai/releases/tag/xoai-3.4.0) and updated the POM in this PR to use that release.  So, the build/tests should hopefully succeed now.

**Comment by tdonohue** [comment]
Thanks again @ChrisBethgster !  This all looks to be working now.  Merging & porting to `dspace-7_x` branch for 7.6.1 release.

**Pull request merged**
