### PR TITLE
 DS-3914: Fix community defiliation

### PR DESCRIPTION
**Pull request by AlexanderS**
This is an alternative for #2063 without changing the `CommunityService.removeSubcommunity()` method.

This fixes in issue in the defiliate method of the community filiator. The
child and parent relations should be managed using the provided methods of the
Community.

This changes the visibility of `Community.removeSubCommunity()` to *public*, but
`Community.removeParentCommunity()` was public before already. So this should
not be a problem.

The second commit is just a bit cleanup of manual loops.

### CODE REVIEW

**Review by pnbecker — APPROVED** [review]
+1 looks good to me. Not tested (yet).

**Review by terrywbrady — APPROVED** [review]
Tested and confirmed the fix.

**Comment by AlexanderS** [comment]
@terrywbrady Sure, see #2284.

**Comment by mauriciorbrito** [comment]
Hello everyone.

I modified the files CommunityFiliator.java and Community.java inmy dspace 6.3, then compiled with "mvn -U clean package" and "ant update" but the command ./dspace community-filiator -r -p [] -c [] still shows the message: 
"Exception: null
java.lang.UnsupportedOperationException
        at java.util.AbstractList.remove(AbstractList.java:161)
        [...]"

Please could you help me?

Kind regards,
Mauricio

maurodbri@gmail.com
mauricio.brito@ucuenca.edu.ec

**Pull request merged**
