### PR TITLE
Pr/2655

### LINKED ISSUE #2816: Search/Import Funded Projects from OpenAIRE API to create new Entities
From release plan; assigned to Dimitris at OpenAIRE. 
Estimate: 60 hours
DEPENDS ON "Convert External Source to Entity" FEATURE.  Would require a new external source to support searching the OpenAIRE API

### PR DESCRIPTION
**Pull request by dimitrispie**
## References
* Fixes #2816 

## Description
Added support for OpenAIRE Funders API.

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

List of changes in this PR:
* First, ...
* Second, ...

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ ] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by paulo-graca** [comment]
@dimitrispie could you solve the merge conflicts and update this code?

**Comment by tdonohue** [comment]
@dimitrispie : This PR also needs a description. It doesn't say what it is.  Please add a description or recreate it.  @paulo-graca noted this may be a replacement for #2655?  Is that true?  If so, we should close that other PR and get this one updated so that it's ready for review.

**Review by paulo-graca — CHANGES_REQUESTED** [review]
Hi @dimitrispie! The source repository isn't available. I think it wouldn't be possible to merge the code. Does it makes sense to keep this PR as is?

**Comment by paulo-graca** [comment]
This PR should be replaced with - https://github.com/DSpace/DSpace/pull/3088
@dimitrispie do you agree that this PR can be closed?

**Pull request closed without merging**
