### PR TITLE
[DS-2318] Added img-thumbnail class to item-view and instances of 'No Th...

### PR DESCRIPTION
**Pull request by dbaker3**
...umbnail' thumbnail

https://jira.duraspace.org/browse/DS-2318
Add border on Thumbnail Item

### CODE REVIEW

**Comment by peterdietz** [comment]
Hi David, 

Thanks for the contribution. What would the before and after of this look like?

Before / Current
screen shot 2015-04-20 at 12 52 37 pm

After / <img class="img-thumbnail"  ...
screen shot 2015-04-20 at 12 52 44 pm

**Comment by dbaker3** [comment]
Sorry, but I'm not sure I understand your question.

**Comment by peterdietz** [comment]
@dbaker3 You submitted a Pull Request to DSpace, and there is no description of what your changes do. Would you like to describe the intent of your changes. What problem are you fixing? I attached some screenshots that show a bootstrap border to the image. Is that the change you were going for?

**Comment by dbaker3** [comment]
I apologize for the ambiguity. Yes, your comments and screenshots are correct. The request is for DS-2318. The change adds the 'img-thumbnail' class to the thumbnails in the Mirage2 theme.

**Comment by aschweer** [comment]
+1
This is particularly helpful for thumbnails of eg thesis cover pages, which typically have a lot of whitespace around the edges - without the border, the text ends up floating in the middle of nowhere.

**Comment by tdonohue** [comment]
+1 This seems like an obvious minor fix. I'm merging this as it now sits at +2 and seems like a quick win.

**Pull request merged**
