### PR TITLE
[DS-3037] Fix completeStep workflow detection

### PR DESCRIPTION
**Pull request by KevinVdV**
https://jira.duraspace.org/browse/DS-3037

### CODE REVIEW

**Comment by tdonohue** [comment]
@KevinVdV can this same logic be used in other classes that also do an "if (workflow type) then" logic?  I see the same logic in all these classes (i.e. not just `CompleteStep`):

* https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/storage/rdbms/xmlworkflow/V5_0_2014_11_04__Enable_XMLWorkflow_Migration.java#L56
* https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/storage/rdbms/xmlworkflow/V6_0_2015_09_01__DS_2701_Enable_XMLWorkflow_Migration.java
* https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/storage/rdbms/DatabaseRegistryUpdater.java#L73
* https://github.com/DSpace/DSpace/blob/master/dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/administrative/collection/AssignCollectionRoles.java#L250
* https://github.com/DSpace/DSpace/blob/master/dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/administrative/FlowContainerUtils.java#L505
* https://github.com/DSpace/DSpace/blob/master/dspace-xmlui/src/main/resources/aspects/Administrative/administrative.js#L2694

So, while I think your fix is worthwhile, I think it's incomplete. We need to analyze all these calls and at a minimum fix the others that call ConfigurationManager.

**Comment by helix84** [comment]
+1, as is, this PR fixes the NPE at the end of the submission process

**Comment by KevinVdV** [comment]
@tdonohue I agree we need to change the other places as well & if possible attempt to remove the property from the workflow.cfg file.
When testing on fixing these issues I also noticed that the XmlWorkflow is currently broken due to the misuse of the ConfigurationManager during sql migration. I will attempt to fix this as well.

Marking this as in progress.

**Comment by pnbecker** [comment]
@KevinVdV In the meanwhile I cretaed DS-3061 and #1301. I'll cherry pick your PR on my to merge them. I greped through the whole code for "workspace.framework" and touched all relevant lines of code.

**Comment by tdonohue** [comment]
@KevinVdV , I'm closing this PR, as your sole commit here has been cherry-picked into #1301 (which was just merged to master).  Please open up a new PR as needed to solve any remaining SQL migration issues.

**Pull request closed without merging**
