### PR TITLE
DS-3725: Adds 'id' property to 'default' and 'site' DiscoveryConfiguration

### LINKED ISSUE #7072: [DS-3725] Homepage DiscoveryConfiguration never used due to missing IDs
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3725">[DS-3725]</a> created by lotte.hofstede</i>
<p>The method SearchUtils#getAllDiscoveryConfigurations(Item) checks if a certain DiscoveryConfiguration has already been added by comparing it's ID to the existing map keys. If the key already exists, the DiscoveryConfiguration is not added to the list of used configurations by this item. </p>

<p>However, both the 'site' and 'default' DiscoveryConfiguration do not have a property 'id' defined in DSpace's vanilla discovery.xml. Because both their ID is 'null', and null can be a key in a hashmap, both configurations will never be added to the same item.</p>

<p>The result is that the 'default' DiscoveryConfiguration is also used on the home page, instead of the 'site' DiscoveryConfiguration.<br/>
Looking at the code, I suspect the issue also exists in DSpace 5 (and maybe earlier versions), but I haven't tested this yet.</p>

<p>I propose we add the id property to each configuration.</p>

### PR DESCRIPTION
**Pull request by nwoodward**
Jira issue: https://jira.lyrasis.org/browse/DS-3725
Fixes #7072

### CODE REVIEW

**Review by kshepherd — APPROVED** [review]
+1 quick win

**Comment by kshepherd** [comment]
@J4bbi could you give this a quick check and +1 if you approve?

**Comment by alanorth** [comment]
I can't reproduce this in our DSpace 6.3 instance. We normally use the same Discovery facets on both the homepage and the rest of the site, but I changed them to be obviously different and it worked as expected without having to add IDs: I see the homepage-specific configuration on the homepage, and the "default" configuration on communities and collections.

Is there some more information about how to reproduce this?

**Comment by kshepherd** [comment]
@alanorth @nwoodward i hadn't tried to reproduce the bug myself, and while I can see that within the spring config, the *bean* IDs are used as value-refs, it is also true that an actual java ID property is checked in SearchUtils.getDiscoveryConfiguration, and it is a member var with getters and setters in the DiscoveryConfiguration class.

Looking at it, I can see how a lack of an ID property could cause these tests to fail, and I don't see how else to set it in the bean other than adding an 'id' property in the config... does that make sense?

`       List<Collection> collections = item.getCollections();
        for (Collection collection : collections) {
            DiscoveryConfiguration configuration = getDiscoveryConfiguration(collection);
            if(!result.containsKey(configuration.getId())){
                result.put(configuration.getId(), configuration);
            }
        }

        //Also add one for the default
        DiscoveryConfiguration configuration = getDiscoveryConfiguration(null);
        if(!result.containsKey(configuration.getId())){
            result.put(configuration.getId(), configuration);
        }`

**Comment by tdonohue** [comment]
Ported to `main` in #2733

**Comment by tdonohue** [comment]
Merging, as this has approval and looks good to me.

The corresponding 7.x PR was closed as a `won't fix` as it turned out to not be needed in 7.x (and breaks tests when implemented). So, this is fix is only being applied to 6.x

**Pull request merged**
