### PR TITLE
DS-3271 : Add -i option to index-discovery

### PR DESCRIPTION
**Pull request by cwilper**
This adds the ability to quickly re-index a single item, collection, or community.

### CODE REVIEW

**Comment by terrywbrady** [comment]
@cwilper, This is a fantastic idea.  Do you have a Jira ticket for this feature?

**Comment by cwilper** [comment]
Sure thing, here ya go: https://jira.duraspace.org/browse/DS-3271

**Comment by tdonohue** [comment]
+1 via code review. Just needs a quick verification test, but the code looks right to me. I also agree this would be a great improvement

**Comment by helix84** [comment]
I tested this - the single-item (by handle) reindex showed the expected log lines.

What surprised me, however, is that after I chaged item title directly in the metadatavalue table and refreshed the page, the updated title showed immediately (i.e. without index-discovery -i) in both recent items and in search results. This is good, obviously, but I can't explain why DSpace reaches into the DB when in 5.x it would reach into Solr search.

**Comment by terrywbrady** [comment]
Tested locally with the following approach.  

- Add a unique dc.subject to an item
- Look at collection facet list, confirm the unique subject term is present
- Update the subject term with sql
- Run index-discovery -i <item handle>
- Refresh collection page, look for updated facet value (SUCCESS)
- Update the subject term with sql
- Run index-discovery -i <collection handle>
- Refresh collection page, look for updated facet value (NOT UPDATED)

The command appears to successfully update an item.  I imagine that it would also update collection/community metadata.

As a user, when I pass in a collection handle or a community handle, I would expect all descendant objects to be updated.

@cwilper , @helix84 , @tdonohue , what do you think?

**Comment by tdonohue** [comment]
Just a minor note to @terrywbrady's question above. Based on my reading of the code, this new `-i` option will only ever reindex a *single object*. So, that means that running it against a Collection or Community will just reindex that Collection or Community object (and will NOT recurse and reindex any child objects).

If that is the intended behavior, we might want to clarify that in the usage notes (in the code).

**Comment by terrywbrady** [comment]
If this is intended only for items, clarify in the code as Tim suggests and in the usage message for that option.  I would also recommend adding a jira enhancement ticket to support communities and collections in the future.  

I have a selfish reason for wanting the collection/community support in place, but I understand that will add to the complexity of the feature.  Locally, we have implemented a process to force the re-indexing of a collection or a community.  It is not as elegant as this approach.

**Comment by helix84** [comment]
I agree with Terry, it would be a worthwhile addition. Meanwhile, it would make sense if the command complained when given a community/collection rather than fail silently.

**Comment by tdonohue** [comment]
Another small clarification here... this code actually does *work* for all types of objects, but it is currently limited by the way the `SolrServiceImpl` class is implemented.  In that class, there's really only two ways to index/reindex content:

1. Reindex everything : see [updateIndex()](https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java#L391) methods
2. OR, reindex a single object (without recursing to child objects): see [indexContent()](https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java#L195) methods

This PR uses the second approach to allow you to trigger a reindex of a single object via the new `-i` flag.  That means this new `-i` flag actually **does work** for Communities or Collections, but it only reindexes the metadata about that Community or Collection itself and **doesn't recurse** to any child objects.

I agree that this might not be the expected behavior.  The only way I can see to fix this would be to either change the behavior of `SolrServiceImpl` (a large scale change), or possibly add some basic recursion code into `IndexClient` which can ensure the expected recursive indexing occurs when `-i` is used on a Community or Collection.

**Comment by cwilper** [comment]
I agree that recursion is a reasonable expectation for users to have. I'm taking a quick stab at doing it within IndexClient (rather than SolrServiceImpl, which as @tdonohue noted, is a bigger change). If my local test is successful, I'll update the PR.

**Comment by cwilper** [comment]
The above worked for me locally, but should be reviewed again by other folks. Note that, in order to avoid memory exhaustion and slowness as observed with [DS-3086](https://jira.duraspace.org/browse/DS-3086), the new `Context` `enableBatchMode` and `clearCache` methods are used.

I actually think it's important to switch to using these for *all* batch-oriented methods in DSpace, as @tomdesair noted in the comments of `DS-3086`, but I limited the changes done here to the -i option.

**Comment by mwoodiupui** [comment]
Make it a curation task?  Then you get this-object-and-children for free from the task framework.  If the framework is not yet using batch mode, it probably should.

**Comment by cwilper** [comment]
Doing it as a curation task occurred to me as well, but that's also a larger code change. Currently, the curation task framework isn't using batch mode, and it definitely should (along with discovery re-indexing, in general). See [DS-3286](https://jira.duraspace.org/browse/DS-3286), which I just submitted.

**Comment by terrywbrady** [comment]
I tested this locally and it generally does what I expect.  I found a couple of communities/collections that repeatedly fail with the following exception.  I cannot identify what makes these communities/collections unique.

[dspace@dspace-aux-1 dspace6x-aux-prs]$ /opt/dspace/bin/dspace index-discovery -i 10822/707889
Exception: failed to lazily initialize a collection of role: org.dspace.content.DSpaceObject.handles, could not initialize proxy - no Session
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.dspace.content.DSpaceObject.handles, could not initialize proxy - no Session
        at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:569)
        at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:188)
        at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:139)
        at org.hibernate.collection.internal.PersistentBag.isEmpty(PersistentBag.java:249)
        at org.apache.commons.collections.CollectionUtils.isEmpty(CollectionUtils.java:979)
        at org.apache.commons.collections.CollectionUtils.isNotEmpty(CollectionUtils.java:992)
        at org.dspace.content.DSpaceObject.getHandle(DSpaceObject.java:133)
        at org.dspace.discovery.SolrServiceImpl.indexContent(SolrServiceImpl.java:198)
        at org.dspace.discovery.SolrServiceImpl.indexContent(SolrServiceImpl.java:2305)
        at org.dspace.discovery.IndexClient.indexAll(IndexClient.java:180)
        at org.dspace.discovery.IndexClient.main(IndexClient.java:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:229)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:81)

**Comment by cwilper** [comment]
Terry, thanks for testing. That particular type of error can occur when the Hibernate session cache is cleared (which in this code, happens every so often when processing a list of items), but someone tries to continue accessing a field whose value was previously cached. In this case, I think it's revealing that the .handles member of one of the objects is trying to be accessed, but that object's data has been de-cached from the session.

You can see in the code above where try to I avoid this "stale entity" issue by reloading the community (see the line that populates the reloadedCommunity value). Without doing that, I got a similar error when the .collections member of "community" was accessed on the subsequent line, in cases where cache clearing had occurred (processing a collection with more than a few items).

I think the problem now may be the community.getHandle() call...that member is also cacheable and may be stale as well. A simple solution may be to put that into a communityHandle as early as possible in this code, and just use that so we're not trying to call *any* methods on a potentially-stale entity.

**Comment by cwilper** [comment]
The above commit should protect from use of a potentially-stale community.handles member, but it may not address the specific problem you're seeing. The stack trace indicates it may actually be the collection.handles member that is problematic. I just don't see how the collection entity could have possibly been de-cached at this point in the code..

**Comment by terrywbrady** [comment]
@cwilper , I am seeing the same repeatable errors on the same collections/communities.  This makes me suspect that there is some relationship in the database that is triggering this.

**Comment by terrywbrady** [comment]
@cwilper , the following code seems to fix the issue.

            for (Community subcommunity : community.getSubcommunities()) {
                subcommunity = ContentServiceFactory.getInstance().getCommunityService().find(context, subcommunity.getID());
                count += indexAll(indexingService, itemService, context, subcommunity);
            }
            //final Community reloadedCommunity = (Community) HandleServiceFactory.getInstance().getHandleService().resolveToObject(context, communityHandle);
            for (Collection collection : community.getCollections()) {
                collection = ContentServiceFactory.getInstance().getCollectionService().find(context, collection.getID());

@tdonohue , I think this could be evidence of a larger hibernate issue.

**Comment by terrywbrady** [comment]
+1, I logged the hibernate issue in https://jira.duraspace.org/browse/DS-3293 since it may be beyond the scope of this enhancement request.  Assuming that issue is accepted as a separate issue, I support merging this code.

**Comment by tdonohue** [comment]
I can reproduce the `LazyInitializationException` with a very simply hierarchy.
```
Top-Level Community
    - Collection #1
        - Single Item
    - Collection #2
```

In this setup, if you run this new `index-discovery -i` command passing in the handle of the `Top-Level Community`, then a `LazyInitializationException` will be thrown when it attempts to index `Collection #2` (but all other items are indexed successfully). 

Not sure yet if this PR's code is to blame, but it's now easily reproducible.

**Comment by terrywbrady** [comment]
@cwilper , I commented out the following block and the issue goes away.  I imagine that a different method is needed for clearing the cache.

https://github.com/cwilper/DSpace/blob/3c72564c6a9b894014165cdf2e2815fc083646d2/dspace-api/src/main/java/org/dspace/discovery/IndexClient.java#L206-L209

            // Every so often, clear the context cache to preserve
            // memory, and commit the changes to the search index.
            if (context.getCacheSize() > 50) {
                context.clearCache();
                indexingService.commit();
            }

**Comment by tdonohue** [comment]
To build off of @terrywbrady's last comment, the problem is specifically with `context.clearCache()`, which in turn calls [`DBConnection.clearCache()`](https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/core/HibernateDBConnection.java#L120) which flushes Hibernate's session.  This behavior doesn't seem to play well with the recursive method implemented here, and causes the `LazyInitializationException`.

Removing `context.clearCache()` also removes the need to reload the Community on this line: https://github.com/cwilper/DSpace/blob/3c72564c6a9b894014165cdf2e2815fc083646d2/dspace-api/src/main/java/org/dspace/discovery/IndexClient.java#L178

So, this PR either needs to avoid using `context.clearCache()`, or that `clearCache()` method needs to be fixed/improved to support usage in recursive methods.

**Comment by cwilper** [comment]
The problem is definitely wider in scope and I'm not as concerned about the "-i" capability at this point as I am about the practicality of doing big batch operations (recursively) without running into memory/performance problems or `LazyInitializationException`s. It seems that careful execution of such operations (holding on to the handles as Strings) while recursing down into the hierarchy could avoid this, while still allowing cache-clearing to occur.

As for this PR, my inclination at this point is to concentrate on the broader issue affecting pre-existing functionality first (see [DS-3286](https://jira.duraspace.org/browse/DS-3286) ...and maybe revisit this after a working pattern is established. Further comments from me on the broader issue will be in DS-3286's comments.

**Comment by tdonohue** [comment]
@cwilper : sounds reasonable. There is definitely a need for a new working pattern for dealing with the Hibernate cache in recursive batch operations, so it makes sense to find a generalizable solution. Thus far, the only usages of  `clearCache()` have been non-recursive (and the method does work well for such non-recursive batch operations).

**Comment by tdonohue** [comment]
Closing in favor of #1495, which implements this feature as well.

**Pull request closed without merging**
