### PR TITLE
[DS-4115] Update JRuby and SASS version for maven based Mirage2 build

### PR DESCRIPTION
**Pull request by terrywbrady**
https://jira.duraspace.org/browse/DS-4115

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 Tested locally and this works when `mirage2.deps.included=true`  (Previously an error occurred).

I enhanced this PR slightly by adding an additional comment & moving an existing comment. But, I think this is ready to merge as soon as Travis gives the green light.

**Comment by tdonohue** [comment]
This PR also replaces #2304 (as the `rb-inotify` error occurred cause the version of JRuby being used was not compatible with Ruby 2.2 or above)

**Comment by tdonohue** [comment]
This PR should be backported to 5.x to fix the issue there as well.

**Review by kshepherd — APPROVED** [review]
+1, travis passes and this is a quick win to fix a blocker. merging now

**Pull request merged**
