### PR TITLE
[DS-3695] Solr 7 fixes for upgrading to DSpace 7

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://jira.duraspace.org/browse/DS-3695
This is changes needed for Solr 7 by sites upgrading to DSpace 7, **excluding sharded statistics**.  Thanks to Bill Tantzen for kicking off this phase by finding some problems with date fields.

### CODE REVIEW

**Comment by cwilper** [comment]
@mwoodiupui Thanks, these worked for me. I grabbed these changes, updated slightly for latest master, and added the libs as well, and put my copy here for reference: https://github.com/atmire/DSpace/tree/DS-3695-solr-fixes . I also wrote up steps I was able to successfully follow to upgrade a DSpace 6 repo to DSpace 7, then re-index discovery, here: https://gist.github.com/cwilper/50c33ab861e47936f45a8909a0ee7a8b

**Comment by mwoodiupui** [comment]
I think I've addressed all of the early comments.  I've updated the upgrade procedure in the v7 manual.  (https://wiki.duraspace.org/display/DSDOC7x/DSpace+7.x+Documentation)

I've loaded several years' worth of live data into the statistics core, reindexed search and OAI, and loaded some sample data into authority, all without incident  I sampled the statistics documents in the Solr console, and found nothing obviously wrong.

**Review by cwilper — APPROVED** [review]
@mwoodiupui I reviewed this again today and agree with all changes here (which we've also cherry-picked for various other WIP branches). I ran it and observed ant deploy works fine, and indexing was working fine as well, without library errors we were seeing before. The only thing I did not run was `RepairDump` because I didn't understand its purpose or whether you felt it was still necessary. If unnecessary, that and the pom change to add the csv lib it uses should be dropped prior to merging. Thanks.

**Comment by mwoodiupui** [comment]
@cwilper Thank you for the review!

I had forgotten about RepairDump.  I needed it to make some of our older production data ingestable.  (We have some statistics documents which lack a value for the `uid` field, for some reason.)  It's not a mandatory part of the upgrade, but since I knew one site that had the problem and I had written the code anyway, I included it, in case others run into the same issue.  I can remove the tool if we don't want it.

**Review by tdonohue — APPROVED** [review]
👍 Very minor fixes here now (after the merger of #2495).  I haven't tested, but they seem pretty obvious.

**Comment by tdonohue** [comment]
Merging as this is now at +2

**Pull request merged**
