### PR TITLE
DS-3969 Added check for null during indexing of OAI to avoid NullPointer

### PR DESCRIPTION
**Pull request by christian-scheible**
This solves a Problem with broken ResourcePolicies and OAI indexing.

To recreate the Error:

- Create and Accept Items with DSpace 6.2 (or an older version) and XMLWorkflow enabled (see https://jira.duraspace.org/browse/DS-3522?jql=project%20%3D%20DS%20AND%20status%20%3D%20Closed%20AND%20text%20~%20%22Resource%20Policies%22%20ORDER%20BY%20created%20DESC)
- This leads to Resource Policies without EPersonGroup
- Upgrade to 6.3 and try reindexing the OAI index with [dspace]/bin/dspace oai import -c

This leads to a NullPointerException so the index will never be updated/recreated in this setting

### CODE REVIEW

**Review by helix84 — APPROVED** [review]
LGTM!

**Comment by J4bbi** [comment]
We had this problem in a sever upgraded from 4.2. I believe XMLWorkflow was not enabled (as is described as a precondition in the [jira](https://jira.duraspace.org/browse/DS-3969)).

The `NullPointerException` seems to be caused by a legacy `ResourcePolicy` that either does not have a group or a name for whatever reason.

The function  `willChangeStatus` that causes the `NullPointerException` needs to find a `ResourcePolicy` that has
- start date or end date after today
- belongs to a group that has the name "Anonymous"

in order to return `true`. So adding a check that it's in a group and that it's got a name to begin with can't be inimical because an embargoed item by definited has to have a `ResourcePolicy` set for a future date with READ access for Anonymous group. Else it is restricted.

**Comment by christian-scheible** [comment]
Hi @J4bbi, you are right maybe the issue title is to specific. The error this pull request fixes might happen in other cases to. It was just the reason why it happend in our case.

But as you also mention. Checking for null to prevent a NullPointerException will not result in unwanted effects in this case.

**Comment by minurmin** [comment]
This seems to be more or less the same fix as in #2213 (with additional check for null group name) so DS-3969 and DS-4019 are probably the same issue. In our DSpace instance (6.2) there have been OAI indexing problems even if XMLWorkflow is not active and our local fix was equivalent to #2213, adding null group name check had (at least in out instance) no additional effect. In addition, I'm confused about commit "Merge branch 'dspace-6_x' into DS-3969" (and not into dspace-6_x).

**Comment by tdonohue** [comment]
Closing, as this duplicates #2213 which is already merged

**Pull request closed without merging**
