### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by alanorth**
## Description
Bump a handful of dependencies in various `pom.xml` files. I used the [renovate bot](https://docs.renovatebot.com/) in a fork of the DSpace repository to unearth viable dependency updates. In most cases these are _minor_ and _patch_ level updates (ie 2.x.x) , as I specifically excluded major ones. In many cases they updates fix bugs, improve performance, improve compatibility with newer Java versions, and update transitive dependencies (for example, this resolves one old transitive dependency from Jaxen / xom, but introduces a new one with javassist).

**Note:** while the unit and integration tests are passing, and I have verified that basic functionality like browsing, submitting new items, Flyway migrations, etc are working, we might want to wait to merge this once 7.6 is released.

## Instructions for Reviewers

List of changes in this PR:
* Try building DSpace with `mvn -U -Pdspace-rest clean package` to make sure you don't use any old packages
* Try running DSpace
* Try various normal actions in the web interface, command line, HAL browser, and various APIs.

### CODE REVIEW

**Comment by alanorth** [comment]
@tdonohue I was hoping to get this merged after 7.6.0 was released so they could get onto `main` as early in the next development cycle as possible. The changes are all minor version bumps. All tests passing, and I've been using a branch based on this locally for a few weeks.

**Comment by tdonohue** [comment]
@alanorth : Don't worry, haven't forgot about this.  I've been in the midst of post-7.6 cleanup.  I will look to merge this soon, as soon as I've split off new `dspace-7.x` maintenance branch & `main` becomes ready for 8.0.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alanorth !  Deployed this locally to test things out manually.  No issues discovered.  I'm going to merge this immediately so that we have plenty of time to test this prior to 8.0

**Comment by tdonohue** [comment]
Ported to `dspace-7_x` in #9305

**Pull request merged**
