### PR TITLE
DS-3743 Expose existent submissions over REST

### PR DESCRIPTION
**Pull request by abollini**
This PR is an attempt to simplify the review of the work done around the workspaceitems endpoint.

In the branch https://github.com/4Science/DSpace/tree/D4CRIS-338 we have a working solution to
- list existent submissions (DS-3743)
- create new empty submission (DS-3740)
- patch existent submissions (DS-3759)

making a PR directly from the above branch will make the PR a bit hard to review (it is large) so I'm trying to split the history in subsequent steps. Unfortunately, the development has been not linear so we have refactored the solution for DS-3743 implementing DS-3740 and working on DS-3759...

### CODE REVIEW

**Comment by tdonohue** [comment]
@abollini : I gave this a quick review, and it looks pretty reasonable overall.  I notice it's a lot of removal of existing code that was used for the current XMLUI and JSPUI.  Much of that code doesn't seem to be replaced in this PR (I see a lot of `// TODO Auto-generated method stub` in methods), but my assumption is that it is coming in future PRs (either #1888 or #1889)

That said, I'll note that there seems to be some duplication across the three PRs.  Just as an example, all three PRs seem to to make the same changes to `AccessStep.java`:
* In this PR: https://github.com/DSpace/DSpace/pull/1887/files#diff-73fbb80b6cbf3f6c2b563cbe5d8ff0f3
* In 1888 PR: https://github.com/DSpace/DSpace/pull/1888/files#diff-73fbb80b6cbf3f6c2b563cbe5d8ff0f3
* In 1889 PR: https://github.com/DSpace/DSpace/pull/1889/files#diff-73fbb80b6cbf3f6c2b563cbe5d8ff0f3
This duplication of changes in several PRs makes me wonder if these are truly "standalone", or if each PR is actually based off the same root branch?  This duplication of changes makes it difficult to review each as standalone, as it's hard to tell which changes were made in each individual PR.

I will note I also do wish we could add in some unit tests while we are doing this refactor. I notice that Travis currently isn't working properly on these three PRs, so we aren't getting the code coverage percentage reported back.

**Comment by tdonohue** [comment]
Per my above comments, I'm not entirely sure what to recommend here. It's unclear to me if these three PRs can be made 100% standalone (easily), or if it's just going to be easier in the long term to have a single massive PR, despite the difficulties in reviewing such a massive PR.  If the massive PR route is just easier, maybe we could minimally have some sample tests (curl commands or similar) to run to verify the functionality here.

**Comment by abollini** [comment]
Hi @tdonohue  thanks to take the time to look to this. Yes this PR share the same commit history than #1888 and #1889 it is only the first part of the history.
So the three pr are not independent. Only this PR can be eventually used and merged alone but I don't know if this make easier the review at all.

Please note that #1889 is still unfinish (read the comment in it) because we want to implement the full REST contract proposed but it will be easier to review along the line instead to wait for the latest commit.

Last but not least, the removed code in the dspace-api is due to the way that the configurable submission was originally developed... dspace have some code in the dspace-api that were placed here mainly because it was shared between the two UIs but it wasn't really "core" code. For instance it uses request, session, etc. proper of the web layer and nothing else than the UIs were linked with such code...

so, up to now we have all the logic in the new REST code, the dspace-api classes are still here because the refactoring is not completed but they are likely to be completely removed.

I have resolved the conflict in the #1889 PR, should be easier to discard this PR and #1888 (the second step)?

**Comment by abollini** [comment]
in the DSpace 7 meeting it was decided to just review the final PR #1889 using integration test and curl looking to the doc.
https://wiki.duraspace.org/display/DSPACE/2017-11-30+DSpace+7+Working+Group+Meeting+notes

**Pull request closed without merging**
