### PR TITLE
[DS-3456] 6x Fix Command Line Parameters for statistics import/export tools

### PR DESCRIPTION
**Pull request by terrywbrady**
## Addresses the following
* https://jira.duraspace.org/browse/DS-3456
* https://jira.duraspace.org/browse/DS-3464
* https://jira.duraspace.org/browse/DS-3437

## Same fix on other branches
* master version: #1635 
* 5.x version: #1623 

The context for this PR and a suggested test plan is documented here: https://wiki.duraspace.org/display/~terrywbrady/Statistics+Import+Export+Issues

### CODE REVIEW

**Comment by terrywbrady** [comment]
@kshepherd , I migrated the latest changes to the 6x branch

**Review by kshepherd — APPROVED** [review]
all tests passed, and i like the new flag as per feedback from pr-1623.
detailed notes/results at https://wiki.duraspace.org/pages/viewpage.action?pageId=79794259

**Comment by hardyoyo** [comment]
+1 by review

**Review by tdonohue — APPROVED** [review]
👍 Code looks good, and approved in DevMtg today

**Pull request merged**
