### PR TITLE
Remove old webui properties from dspace.cfg

### LINKED ISSUE #8906: DSpace config references webui.browse.thumbnail still
**Describe the bug**
Per the documentation https://wiki.lyrasis.org/display/DSDOC7x/Release+Notes#ReleaseNotes-7.0ConfigurationsRemoved `webui.browse.thumbnail.*` was removed, however there are still references to it in the dspace.cfg file.

https://github.com/DSpace/DSpace/blob/main/dspace/config/dspace.cfg#L1449 and https://github.com/DSpace/DSpace/blob/main/dspace/config/dspace.cfg#L1449

### PR DESCRIPTION
**Pull request by alanorth**
## Description
Remove old configuration properties from `dspace.cfg`:

- webui.itemlist.widths
- webui.itemlist.tablewidth
- webui.itemlist.browse.*
- webui.browse.thumbnail.show (Fixes #8906)

These are legacy properties that were used in XMLUI and JSPUI, but no longer needed.

*Note: after this PR is merged I will clean up references of the same properties in the wiki.*

## Instructions for Reviewers
Test that the code builds and runs as expected. This pull request modifies configuration related to browse and thumbnails so you should see if browse indexes and item views are working as expected.

List of changes in this PR:
* Remove several old "webui" properties from `dspace.cfg`

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by misilot** [comment]
Looks good to me @alanorth! Thank you!

**Review by misilot — APPROVED** [review]

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alanorth . Looks good & noticed no issues. Therefore, I'll also port this back to 7.6.x...I think this cleanup is useful there as well since it simply removes unused, commented out configs.

**Comment by alanorth** [comment]
Thanks, @tdonohue. I will also do a sweep of the DSpace 7 wiki to make sure there are no more references to these.

**Comment by tdonohue** [comment]
Docs have already been updated in https://wiki.lyrasis.org/display/DSDOC8x/Configuration+Reference

**Pull request merged**
