### PR TITLE
fixed DS-2751 by checking for null

### PR DESCRIPTION
**Pull request by tmguimaraes**
Fixed https://jira.duraspace.org/browse/DS-2751

### CODE REVIEW

**Comment by pnbecker** [comment]
+1 by inspection, haven't tested it.

**Comment by terrywbrady** [comment]
+1 by inspection as well

**Comment by tdonohue** [comment]
As discussed in our DevMtg today, one of the questions is why/how `null` values get into this `getISSNs()` list to begin with. It looks like one of the classes that implements `ISSNItemExtractor` must be adding null values to the list. Here's the two possible culprits:
* https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/app/sherpa/submit/MetadataAuthorityISSNExtractor.java
* https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/app/sherpa/submit/MetadataValueISSNExtractor.java

**Comment by pnbecker** [comment]
I think the culprit is the MethadataAuthorityISSNExtractor. It expects every metadata value to have an authority value. We probably need a null check here: https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/app/sherpa/submit/MetadataAuthorityISSNExtractor.java#L40

**Comment by tmguimaraes** [comment]
Updated the null check to check at MethadataAuthorityISSNExtractor like @pnbecker suggested.

**Comment by pnbecker** [comment]
@tmguimaraes thanks, that is great! Have you tested it?
Your PR is now a little bit messy, containing two merge commits and a commit that is mostly reverting a previous one. Can you please file a clean PR containing only one commit that adds the null check?

To do so, I would create locally a new branch from DSpace/master, add the null check and push it using -f to the branch on github you used to create this PR. Changing the branch used to create this PR automatically updates the PR.

**Comment by tmguimaraes** [comment]
Only tested this change in my dspace 5.2 VM.
I'm currently installing DSpace 6 to test this.

**Comment by pnbecker** [comment]
@tmguimaraes thanks a lot for cleaning this PR!
+1 by inspection, looks obvious and good to me.

**Comment by tmguimaraes** [comment]
Tested on vagrant-dspace.

**Comment by DylanMeeus** [comment]
+1, obvious fix, thanks @tmguimaraes :-)

**Comment by pnbecker** [comment]
I'll merge this as it is such an obvious fix.

**Pull request merged**
