### PR TITLE
input-forms localization in xmlui

### PR DESCRIPTION
**Pull request by kosarko**
If I haven't missed it anywhere it's currently not possible to localize input-forms in xmlui. DS-1484 seemed to resolve this only by better documentation.

with this accessing input-forms_LOCALE.xml should be possible, any thoughts on the solution?

### CODE REVIEW

**Comment by KevinVdV** [comment]
Wouldn't it be better to use actual keys in the input forms to make them more multilingual friendly ? (For both the JSPUI & XMLUI, just like for the item-submissions.xml ?

See: https://github.com/DSpace/DSpace/blob/master/dspace/config/item-submission.xml#L222

This would allow for easier localization without having to make changes in multiple input-form.xml files.

**Comment by kosarko** [comment]
I agree that having to manage one input-forms file would be easier than managing two or more. One could probably wrap the DCInput getLabel, getHints and getWarnings (+ handling the key-value pairs) calls with `messages()` in xmlui and with `LocaleSupport.getLocalizedMessage` in jspui, thus making it possible to have keys in the input-forms file.
But, since input-forms_LOCALE.xml, should already be working in jspui I thought it would be reasonable to go the same path for xmlui. But yes the only advantage I can see - sharing the localized input-forms - might not be worth it.

**Comment by tdonohue** [comment]
This needs rebasing on the latest master, because of merge conflicts

**Comment by kosarko** [comment]
@tdonohue completely forgotten this one. Are you even interested in it as it is? I mean the input-forms_LOCALE.xml approach? We've eventually taken the "messages keys in input-forms" path...This one above was working, but nobody wanted to manage the extra file(s)...
I could create the PR from that version instead, if it sounds better, but it's only the XMLUI part...let me know...

**Comment by tdonohue** [comment]
Hi @kosarko : Sorry, I missed the comments above about the proposal to use message keys instead. I agree, that'd be a preferable solution (as do others in our DevMtg today). I'm going to close this PR as it seems like we all agree that the other option is better.

**Pull request closed without merging**
