### PR TITLE
DS-2654: Enhanced Configurations via Apache Commons Configuration

### PR DESCRIPTION
**Pull request by tdonohue**
(_Replaces #991: This is a newly rebased version which is now compatible with our refactored API_)

As described in DS-2654, this refactors our ConfigurationService and DSpaceServiceManager to use [Apache Commons Configuration](http://commons.apache.org/proper/commons-configuration/userguide_v1.10/user_guide.html):
- Ticket: https://jira.duraspace.org/browse/DS-2654
- Documentation: https://wiki.duraspace.org/display/DSPACE/Enhanced+Configuration+Scheme
## Basic Usage

More detailed documentation is at https://wiki.duraspace.org/display/DSPACE/Enhanced+Configuration+Scheme. 

But, at a basic level, here's all you need to know to get started.
1. Pull down the PR
2. `cd [dspace-src]`
3. Create your own `local.cfg`, e.g. `cp local.cfg.EXAMPLE local.cfg`
   - `build.properties` no longer exists. `local.cfg` is the "replacement" but it's more powerful in that you can override ANY configuration in that file. You never need to edit `dspace.cfg` or `modules/*.cfg` files again.
4. Build / Compile as normal
   - `mvn clean package`
   - `cd dspace/target/dspace-installer`
   - `ant update`
5. Restart Tomcat and have fun.  A few things to note:
   - Many configuration settings had to be renamed in order to ensure their _uniqueness_ across all of our configuration files.  So, older config files (5.x or below) are not 100% compatible.
   - Config files (all *.cfg, log4j.properties, and Spring configs) are NOT filtered anymore. All those `${setting}` references will be figured out at runtime
   - Any configuration can be overridden in your `local.cfg`. Just copy it over and set a new value.
   - Optionally, any configuration can also be overridden as a System Property (e.g. `-D[key]=[value]`) or environment variable. It'll even override the value in your `local.cfg`.
   - The order of precedence of configs is in the new `[dspace]/config/config-definition.xml` file. You can even tweak it to add new config files or config locations (e.g. database tables).  For more info on the format of this file, see the [Configuration Definition file](http://commons.apache.org/proper/commons-configuration/userguide_v1.10/howto_configurationbuilder.html) documentation for Apache Commons Configuration
   - All `modules/*.cfg` files are auto-loaded into the `dspace.cfg` via a series of `include=` statements (see end of dspace.cfg file).  You can now simply specify new `include=` lines in your `local.cfg` to enable configs for non-default modules.
   - All configuration files are automatically checked each minute. If they've changed the new values are loaded (see configuration-definition.xml for this setting).  They can also be reloaded on demand by calling `ConfigurationService.reloadConfig()`. (NOTE: currently on-demand reloads is not yet wired into the UIs or command-line, but it could be done pretty easily.)
     - Unfortunately, this doesn't actually mean that the **UIs** will notice all configuration changes. Too often, configuration values are loaded into a `static` variable or cached in some way. This PR doesn't ensure that the new values are automatically seen in the UI-layer. But, additional "bug-fix" PRs could be submitted to enable reloading of specific configs.
## Changelog

More specifically, it does ALL of the following:
- [x] Replaces our custom `DSpaceConfig` and `ServiceConfig` classes with Commons Configuration. Uses the [DefaultConfigurationBuilder](http://commons.apache.org/proper/commons-configuration/userguide_v1.10/howto_configurationbuilder.html) and a new `config-definition.xml` file to configure which configuration sources are loaded. See https://github.com/tdonohue/DSpace/commit/f14b9823ff80ab6ac57a2cf1bf658c5361ad6075
- [x] Refactors all `ConfigurationService` and ServiceManager related classes to support the removal of `DSpaceConfig` and `ServiceConfig`
- [x] Adds a new `ConfigurationService.reloadConfig()` method which will reload all configurations when called. This method could be triggered via commandline or UI, and it comes with Unit Tests.
- [x] Minor updates to Unit Tests for `dspace-services` to support the refactoring. Also added some new tests.
- [x] Updates `ConfigurationService` to provide the widely-used, type-based convenience methods that are available in `ConfigurationManager` (e.g. `getBooleanProperty()`, `getIntProperty()`, etc). Add new unit tests. See https://github.com/tdonohue/DSpace/commit/51f6d36bc043ab3aa138dda02560a160e4946882
- [x] Rewrites old `ConfigurationManager` to simply wrap `ConfigurationService` calls. Marks `ConfigurationManager` as deprecated  (This resolves [DS-2115](https://jira.duraspace.org/browse/DS-2115)). See https://github.com/tdonohue/DSpace/commit/35e2f60a62337bf454c8eb99a04f726f95b75f71
  - Also removes the `dspace-config` servlet param (from all `web.xml` files) and `dspace.configuration` System property as both of those were only used by `ConfigurationManager`
  - These two properties are now replaced by a single `dspace.dir` property, which can be specified either in dspace.cfg or as a System / Env property
- [x] Ensure all "modules" configurations get loaded into Commons Configuration
- [x] Prepend configuration keys with module name to ensure uniqueness (E.g. "[module].enable=true"). See https://github.com/tdonohue/DSpace/commit/ad5fcda132256ec5a717421a2c617d8447e7555a
- [x] Changes name of `disseminate-citation.cfg` to `citation-page.cfg` as it configures the PDF citation page, and has nothing to do with disseminating citations.
- [x] Refactor `PluginManager` into `PluginService` and `LegacyPluginServiceImpl` (and added Unit Tests). Ensures its static dependencies on ConfigurationManager can be removed. See https://github.com/tdonohue/DSpace/commit/755c4f5475341aee0b648bf0202c7092c1496b43
  - Plugin instances also are no longer "reusable" (i.e. cached) and they are instantiated when they are needed. So the `plugin.reusable.*` configs were removed.  This allows plugin instances to take advantage of dynamic configs, instead of caching themselves.
- [x] Get all Unit Tests to succeed
- [x] Get all UIs to function without major errors
- [x] Update Spring settings to automatically & dynamically interpolate any variables in Spring XML configs. This means _any_ Spring XML config can include variables like `${dspace.dir}` and they will be dynamically loaded via our ConfigurationService
- [x] Create a default `local.cfg` which will take over the role of DSpace's `build.properties`. It allows you to override _any_ configuration from any `*.cfg` file simply by specifying a new value in your `local.cfg`.
  - Unit test framework also now uses its own `local.cfg` instead of merging a custom `dspace.cfg.more` into the main `dspace.cfg`
- [x] Remove all custom "variable interpolation" logic from our Maven / Ant scripts. This logic is no longer needed, as Commons Config automatically does real-time variable interpolation of configs
  - All filtering/interpolation logic was removed EXCEPT for the `web.xml`. Unfortunately, we still need to filter that file to initialize the DSpace Kernel for a given webapp.
- [x] Documentation

(NOTE: This PR is loosely related / inspired by #61, but it takes a different approach by integrating Commons Configuration into `ConfigurationService` and refactoring `ConfigurationManager` to just use `ConfigurationService`. It also loads configurations via `DefaultConfigurationBuilder` and a `configuration-definition.xml`, therefore allowing for extensions where sites could choose to start storing some or all configurations in a database or other locations supported by Commons Configuration.)

### CODE REVIEW

**Comment by helix84** [comment]
After trying to build this, ant update gives me:

migrate_database:
     [java] Exception in thread "main" java.lang.ExceptionInInitializerError
     [java] Caused by: java.lang.IllegalStateException: DSpace kernel cannot be null
     [java]     at org.dspace.utils.DSpace.getServiceManager(DSpace.java:63)
     [java]     at org.dspace.utils.DSpace.getConfigurationService(DSpace.java:71)
     [java]     at org.dspace.core.ConfigurationManager.getProperty(ConfigurationManager.java:92)
     [java]     at org.dspace.app.launcher.ScriptLauncher.getConfig(ScriptLauncher.java:256)
     [java]     at org.dspace.app.launcher.ScriptLauncher.<clinit>(ScriptLauncher.java:35)

**Comment by tdonohue** [comment]
@helix84 : this is marked "work in progress" for a reason. :) It is not yet ready for review. It's been rebased against master so that it compiles, but it is not fully "compatible" with master yet (e.g. almost all unit tests now fail cause of database connection issues).  I'll let you know when it's actually ready for testing/review.

**Comment by tdonohue** [comment]
Updates on this ticket. As of today, this PR is "minimally functional".  DSpace builds and can be updated/installed. All UIs seem to work (at least with minimal testing).  So, the basics of integrating Apache Commons Config are completed.  

However, the next step is to completely replace `build.properties` (and all our custom variable interpolation via Maven/Ant) with a simple `local.cfg` (which allows you to add a local override for any config from *any* `*.cfg` file).  I also have not yet implemented any UI tools for configuration management. 

As of today, this PR simply implements the following:
* Creates a new `ConfigurationService` which uses Apache Commons Config to auto-reload DSpace configurations every minute (the timing of the auto-reload is tweakable in `[dspace]/config/config-definition.xml`). 
* The `ConfigurationManager` is now just a wrapper of `ConfigurationService`
* Refactors/renames configs in many of our `*.cfg` files to avoid accidental config "conflicts" (where two keys have the same name in different *.cfg files)
* *IMPORTANT NOTE:* Finally, it is worth noting that while the configurations are automatically reloaded in `ConfigurationService`. This does NOT guarantee that configuration updates are 100% recognized by DSpace. There are situations where individual API classes **cache** configurations (either by loading them into a static variable or by caching entire class instances in memory).  In those situations, even if the configs are changed, the cached class will not properly reload the change.  I've not tried to track down every instance of this issue, as it's very hard to discover in an automated fashion.
* More details on specific changes are in the checklist in the PR description above (which I have been keeping up-to-date)

**Comment by tdonohue** [comment]
I've removed the "work in progress" label on this PR.  This PR is in a workable state and is ready for review & testing by others.  Documentation is still lacking (and I'll be working on that), but the basics are now detailed in the "Usage" section in the description of this PR (top of this page).

**Comment by hardyoyo** [comment]
One note for testers: please verify UTF-8 characters still work in the cfg files, thanks!

**Comment by tdonohue** [comment]
I've begun detailed documentation of this feature at: https://wiki.duraspace.org/display/DSPACE/Enhanced+Configuration+Scheme

**Comment by tdonohue** [comment]
NOTE: I've just rebased this PR against the latest master, as I wanted to ensure this branch had several recent bug fixes that were applied to master.

**Comment by tdonohue** [comment]
In discussion in IRC with @pnbecker and @mwoodiupui it was noted that it might be nice to add back in support for passing a `-Denv=[environment]` flag into DSpace to select a particular configuration file (other than `local.cfg`).

Should we decide that would be worthwhile, this is likely implementable by simply adding a new config file (`${env}.cfg`) into the `config-definition.xml` which would *override* `local.cfg` defaults.  We'd then also want to suppress the (scary looking) warning if "env" was not passed in (as Commons Config would then look for a file named ".cfg").  Suppressing the warning from logs seems possible as noted here: http://mail-archives.apache.org/mod_mbox/commons-user/200804.mbox/%3C47FBCCC0.1030205@oliver-heger.de%3E

This entire concept would be similar in nature to what is detailed in the FAQ at: https://wiki.duraspace.org/display/DSPACE/Enhanced+Configuration+Scheme#EnhancedConfigurationScheme-CanIhavedifferentlocal.cfgfilesfordifferentenvironments%28e.g.development/testing/staging/production%29?

I'm just noting this as a topic of discussion. I have no plans as of yet to add this to this particular PR (yet), until we decide what the "sane defaults" are that we want added to `config-definition.xml`.

**Comment by KevinVdV** [comment]
I did some reviewing & things look great so far I do have a few remarks/questions & was able to find one bug:

**Bug ?**

Because the web.xml in the solr module is no longer "filtered" you get the following exception:
java.io.FileNotFoundException: /log/solr.log (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:136)

We may need to alter the "ConfigureLog4jListener" class as filtering of the web.xml is no longer an option (the log file is configured in the web.xml).

**Remark(s)/Questions**

* Would it be possible to filter the local.cfg file (only requires one additional line in the assembly.xml file). Then people who want to use maven profiles for certain properties can still use maven. Only the local.cfg would be filtered so there is no real downside to this (if no properties are found the local.cfg remains unaffected).
* I noticed that in non spring classes the ConfigurationService class is retrieved by using new DSpace()..... would it not be easier to create a factory call to retrieve it in this case ? (As is the case with all other services).

**Comment by tdonohue** [comment]
Hi @KevinVdV - That sounds like a possible bug.  To be clear, `web.xml` files ARE still filtered (they are the only file that is). The only way we could avoid filtering `web.xml` files would be to *require* `dspace.dir` be specified to the servlet container (i.e. Tomcat). More info on that issue in my docs at: https://wiki.duraspace.org/display/DSPACE/Enhanced+Configuration+Scheme#EnhancedConfigurationScheme-ConfigurationInterpolation

So, the filtering of the `web.xml` files still occurs, but now it only happens within Ant. It's here:
https://github.com/tdonohue/DSpace/blob/DS-2654-common-config/dspace/src/main/config/build.xml#L651 
I'll have to look into why it's not working for the Solr `web.xml` specifically (as I must have overlooked that).

Regarding your Questions:
* Yes, we could filter `local.cfg` only in Maven. I'm not against that, but I hadn't heard a good reason why (until now).  That'd be a small fix as you noted.
* I never got around to creating a Factory for ConfigurationService. You are correct that it might be slightly cleaner to do so (in general, not just specific to this PR). As one didn't exist already, I kept just calling `new DSpace()` as you saw in the code.

**Comment by tdonohue** [comment]
A few updates:
* Merged in a (code cleanup) fix from @KevinVdV (adds new `DSpaceServiceFactory` to replace calling `new DSpace()` everywhere you need the ConfigurationService).
* Rebased again on latest master (as of Dec 14)

**Comment by mwoodiupui** [comment]
I started testing but ran into a roadblock instantly:  if 'local.cfg' is a symlink, maven-assembly-plugin fails.  I tend to have several configurations that I work on alternately in the same directory tree, so I'd like to make this work, but for the moment I will just make a copy and move on.  I'm writing the maven-users ML to see if there is something I can do to make this work.

**Comment by mwoodiupui** [comment]
Tested.  +1.  My earlier difficulty with symlinked local.cfg must be a Maven bug.

**Comment by hardyoyo** [comment]
Tested in Vagrant-DSpace, +1, works as advertised.

**Comment by KevinVdV** [comment]
+1, all my previous remarks were resolved.

**Comment by KevinVdV** [comment]
We have enough +1's to merge this pull request, now the only question that remains is do we merge it now ? Is there a chance that other ongoing pull requests will be broken by this merge ? (As we are already delayed with our planning).

**Comment by rradillen** [comment]
does the filtering of the robots.txt file still work after this PR? https://github.com/DSpace/DSpace/blob/master/dspace-xmlui/src/main/webapp/static/robots.txt.

**Comment by tdonohue** [comment]
@rradillen : yes, robots.txt files are still filtered in Ant's `copy_webapps` target. That was unchanged: 
https://github.com/tdonohue/DSpace/blob/master/dspace/src/main/config/build.xml#L668

**Comment by tdonohue** [comment]
FYI. I just pushed up minor bug fixes to a few configs/settings which still require filtering:
* Maven still needs to filter web.xml files to allow webapps to be run/debugged in IDEs
* Ant still needs to filter a few specific configs (e.g. Solr log4j, RDF configs, OAI configs) which cannot be auto-interpolated via Commons Configuration.

**Comment by tdonohue** [comment]
Just rebased this PR against the latest master.

**Comment by tdonohue** [comment]
Rebased & refactored again.

I also had to modify the `rest.cfg` configurations and some Java code from #1239 to be compatible with the new `ConfigurationService` and `PluginService`. See https://github.com/DSpace/DSpace/commit/82c27218cdad0f30c4570ba13649af5392fedc92 for necessary changes

**Comment by tdonohue** [comment]
Another rebase, which included a few minor changes:
* The `dspace.oai.url`config in `oai.cfg` was renamed to `oai.url` (This was somehow overlooked in initial renaming of configs)
* Minor refactoring of code from #970 to use ConfigurationService and PluginService

**Comment by tdonohue** [comment]
Rebased again, and just added a few comments to dspace.cfg on behalf of PR #801 (as it accidentally forgot to add comments explaining its newly added configuration).

**Comment by helix84** [comment]
I tested the latest code again. So far, everything works as advertised. I changed a couple of properties both in dspace.cfg and local.cfg and observed them change in both XMLUI and JSPUI.

Regarding next steps (not necessarily part of this PR), we should:
* Produce the full list of all configuration properties used in DSpace and their default values
in order to check whether they are reloadable.
* Agree on where default values are defined. In code or the default configuration file?
* Run with just a few essential properties set in configuration and make DSpace pick up the defaults for the rest.

**Pull request merged**
