### PR TITLE
DS-3787 Impossible to retrieve the community or collection logo

### PR DESCRIPTION
**Pull request by abollini**
Trying to access the logo of a community or collection results in a 500 error code.
After investigation I found that the issue is related to the absence of a dc.title for such bitstreams that is used to store the name of the file. The Bitstream endpoint (MultipartFileSender) want to force a name in the response header so flag the response as not valid in absence of the file name

I have also added tests to show the bug see the result of the build of the first commit https://travis-ci.org/4Science/DSpace/builds/315096151#L5562

nevertheless, we now have a failure on the findAllBitstreamTest...

### CODE REVIEW

**Comment by abollini** [comment]
@tomdesair  can you help with the test failure? what I'm missing?

**Comment by tomdesair** [comment]
Hi @abollini, there was a problem with deleted bitstreams. The logo's are marked as "deleted" but not removed from the database. In the `BitstreamBuilder` class, we do expunge bitstreams after deleting them. But since the logo is created by DSpace API (and not via a `BitstreamBuilder`), it is  not expunged automatically.

Therefore I've added an "expunge deleted bitstreams" step in the test cleanup method here https://github.com/4Science/DSpace/pull/22

In the future, this will also catch bitstreams created by other processes like for example filter-media.

**Comment by abollini** [comment]
thanks @tomdesair can you formally approve the PR once travis confirm that it works?

**Review by tomdesair — APPROVED** [review]
Tests prove that this works now. Good catch and nice job @abollini !

**Pull request merged**
