### PR TITLE
Corrects reading of configuration options in LDAPAuthentication

### LINKED ISSUE #3207: LDAP Authentication does not work properly without the authentication-ldap.login.groupmap option
When I try to login via LDAP, this keeps failing with this error:

```
2021-03-25 11:16:29,930 ERROR org.springframework.boot.web.servlet.support.ErrorPageFilter @ Forwarding to error page from request [/api/authn/login] due to exception [Index 1 out of bounds for length 1]
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.dspace.authenticate.LDAPAuthentication.assignGroups(LDAPAuthentication.java:699) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.authenticate.LDAPAuthentication.authenticate(LDAPAuthentication.java:265) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.authenticate.AuthenticationServiceImpl.authenticateInternal(AuthenticationServiceImpl.java:108) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.authenticate.AuthenticationServiceImpl.authenticate(AuthenticationServiceImpl.java:80) ~[dspace-api-7.0-beta5-SNAPSHOT.jar:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.security.EPersonRestAuthenticationProvider.authenticateNewLogin(EPersonRestAuthenticationProvider.java:97) ~[classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.security.EPersonRestAuthenticationProvider.authenticate(EPersonRestAuthenticationProvider.java:71) ~[classes/:7.0-beta5-SNAPSHOT]
```

I have not configured any authentication-ldap.login.groupmap option (as I thought I won't need them). But apparently LDAPAuthentication does not work properly without this option.

### PR DESCRIPTION
**Pull request by olli-gold**
fixes #3207

This PR updates the way of reading configuration options for login.groupmap for authentication-ldap.

### CODE REVIEW

**Comment by mwoodiupui** [comment]
The old code is clearly wrong:  it looks for "authentication-ldap", doesn't find it, and defaults to "login.groupmap.1".  The exception comes a few lines further down:  since the value contains no colons, it is split to a 1-element array, which is then indexed by [1].

The new code is more correct.  It can still fail, though, if e.g. "authentication-ldap.login.groupmap.1" is correctly found but contains no colon.  We really should check the size of the array returned by `.split` and throw an exception if it is not 2.

The way that we read the LDAP group map is simply awful.  This should have been converted to a single multi-valued configuration property, so that it could be fetched with getArrayProperty.  Then an "enhanced for loop" could just iterate over it simply and clearly.

Overall this looks like something that we simply missed when we adopted Commons Configuration.

**Comment by olli-gold** [comment]
I agree, that more refactoring might be necessary to improve the code in this point. But I would propose to postpone that improvement as this PR should fix the main problem and make the LDAP authentication basically work again...

**Review by mwoodiupui — APPROVED** [review]
+1 by inspection.  This should correct the reported issue, if `authentication-ldap.login.groupmap.*` are either not set or set to valid values.

**Comment by tdonohue** [comment]
Thanks @olli-gold!  Looks correct to me too.

**Pull request merged**
