### PR TITLE
DS-3075: Comma-separated configurations now need to be loaded via getArrayProperty()

### PR DESCRIPTION
**Pull request by tdonohue**
https://jira.duraspace.org/browse/DS-3075

This commit fixes comma-separated configuration loading where it still occurs in our codebase. I've created a separate commit per module, to hopefully help ease the review process.

Please note: I also made a minor configuration change to SWORDv2 in this PR by changing the default value of this setting to "false" (it's "true" on master):
`swordv2-server.on-behalf-of.enable = false`

I changed that value because of the stern warnings about enabling "on-behalf-of" in that same file:
https://github.com/DSpace/DSpace/blob/master/dspace/config/modules/swordv2-server.cfg#L125
(Somehow these warnings have slipped past us until now, but I stumbled on them as I was fixing up the SWORDv2 codebase)

This all compiles but needs some further testing to ensure nothing major breaks.

### CODE REVIEW

**Comment by aschweer** [comment]
Just a very quick comment regarding the default value for `swordv2-server.on-behalf-of.enable` -- I stumbled over that yesterday and also thought the default value wasn't great given what the comment says. So +1 from me on changing the default to false (sorry, I don't have time to review the whole PR).

**Comment by tdonohue** [comment]
I just found a few more cases where `split()` was being used with a regex that included commas (e.g. `split(",\\s*")` or similar. I've now gone through all usages of `split()` with a fine toothed comb, and I think I've found (and fixed) all the examples where we did a split on comma-separated values coming from a configuration file.

This is ready for code review & basic testing.  (Thorough testing may need to wait for Testathon, as this touches so many different areas of the application in minor ways.  But, it is necessary, as without these changes, all these comma-separated configs will not work properly)

**Comment by tdonohue** [comment]
Thanks for that feedback, @mwoodiupui. I've fixed that typo.

If anyone could give this a quick read through and/or test, I'd appreciate it. This has the risk of hitting conflicts with future bug-fix PRs, as it fixes a variety of configuration related issues.

**Comment by tdonohue** [comment]
I've done some general testing of this today. I'm not noticing anything major that is broken from these changes (and it fixes several small bugs throughout master).  I'd lean towards trying to merge this sooner rather than later, as it does cleanup a lot of minor issues (and may conflict with future PRs).

**Comment by tdonohue** [comment]
Merging this, as it has no objections, and it resolves a lot of minor issues on master.

**Pull request merged**
