### PR TITLE
DS-9142: prevent UUID exception by adding check for -1 value for the id field

### LINKED ISSUE #9142: Mystery exception thrown in CommunityServiceImpl.findByIdOrLegacyId
**Describe the bug**
`findByIdOrLegacyId` uses StringUtils.isNumeric to test for a String representation of an integer value.  This test is wrong:  "-1" is an integer but contains a non-numeric character, which is what the method actually tests.  This causes "-1" to be fed instead to a UUID conversion, which throws IllegalArgumentException, leading to much puzzlement when it ends in returning 400 to the front-end.

**To Reproduce**
1. At this time I do not know where the "-1" is coming from.  It is likely data-dependent:  I cannot make my development system produce it, but it is consistent on production.

**Expected behavior**
I think that `findByIdOrLegacyId` should return null, as the string is a valid integer but cannot be the legacy ID of any DSO.

**Notes**
All of the DSO subclasses which can have legacy IDs have the same problem.

The problem was found while searching for the cause of a Community statistics page failing with perpetual marching dots when a request for "total visits per month" fails with status 400.  The search continues.  (Grumble, the page should not fail; it should post a warning in the notice area and continue, showing nothing for the unavailable statistic.)

### PR DESCRIPTION
**Pull request by nwoodward**
## References
* Fixes #9142 

## Description
This PR adds a check for a "-1" value in the id field in `findByIdOrLegacyId` function. 

## Instructions for Reviewers
1. Use the Solr GUI admin to update one ore more records in the statistics core related to the DSO in Step 3 and change the value of the "id" field to -1.
2. In `[dspace]/config/modules/usage-statistics.cfg` set `usage-statistics.authorization.admin.usage=false`.
3. Go to a community/collection/item page and click on the Statistics link at the top.
4. Observe that the page never loads and 400 Error appears in the browser console.

Apply this PR, build and deploy. Then observe that the community/collection/item page now loads.

## Checklist
- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [X] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by mwoodiupui** [comment]
The fixed code still seems fragile.  We should not assume that the `id` parameter has *any* particular content.  I would suggest simply passing it to `Integer.parseInt` and catching exceptions.  If it won't parse as an integer, pass it to `UUID.fromString` and catch exceptions.  If it won't parse as UUID either, it's garbage:  return `null`.  "-1" will parse as integer but will not be found, so `null` will be returned in this case, but a specific test for `-1` *after parsing successfully as integer* would be sensible and efficient.

It's quite unlikely that this field would have a value of "-2" or "Aloysius" but best to handle all possibilities.

**Comment by mwoodiupui** [comment]
I wonder if this method can be factored out, to save most of that duplicate fixing.

**Comment by tdonohue** [comment]
@nwoodward :  That may work...though it also might be as simple as surrounding the existing code in a try/catch like this:
```
try {
        if (StringUtils.isNumeric(id)) {
            return findByLegacyId(context, Integer.parseInt(id));
        } else {
            return find(context, UUID.fromString(id));
        }
} catch (NumberFormatException | IllegalArgumentException e) {
  // Not a valid legacy ID or valid UUID
  return null;
}
```

Your code looks like it should work in the same general manner, but wanted to point out an option that doesn't involve nested try/catch clauses.

**Comment by nwoodward** [comment]
Yeah, I wondered if the the nested try-catch was an anti-pattern, so I asked first. I'll update the PR to do it your way.

**Comment by mwoodiupui** [comment]
@tdonohue That will work, but it leaves the confusing `StringUtils.isNumeric` test to make people wonder why the code took the UUID branch for "-1".  I won't hold things up over this, but I would have liked to see that thing disappear.

**Comment by alanorth** [comment]
Thanks @nwoodward. I've tested this patch and it allows statistics to load in the frontend, where before it loaded forever.

A minor request would be to rebase/squash these two commits so we don't have the refactoring in the git log—we should only have the final fix. You should be able to `git rebase -i HEAD~2` and then mark the second commit as `s` to squash it into the first one, then update the commit message.

<hr />

We should also ask where these statistics records with invalid UUIDs are coming from, perhaps in a new issue. From looking at my statistics core I see:

```console
$ curl 'http://localhost:8983/solr/statistics/select?q=-id%3A%2F.\{36\}%2F&facet.range=time&facet=true&facet.range.start=2023-01-01T00:00:00Z&facet.range.end=NOW&fac
et.range.gap=%2B1MONTH&rows=0'
{
  "responseHeader":{
    "status":0,
    "QTime":1533,
    "params":{
      "facet.range":"time",
      "q":"-id:/.{36}/",
      "facet.range.gap":"+1MONTH",
      "rows":"0",
      "facet":"true",
      "facet.range.start":"2023-01-01T00:00:00Z",
      "facet.range.end":"NOW"}},
  "response":{"numFound":803957,"start":0,"numFoundExact":true,"docs":[]
  },
  "facet_counts":{
    "facet_queries":{},
    "facet_fields":{},
    "facet_ranges":{
      "time":{
        "counts":[
          "2023-01-01T00:00:00Z",1,
          "2023-02-01T00:00:00Z",0,
          "2023-03-01T00:00:00Z",0,
          "2023-04-01T00:00:00Z",0,
          "2023-05-01T00:00:00Z",0,
          "2023-06-01T00:00:00Z",0,
          "2023-07-01T00:00:00Z",0,
          "2023-08-01T00:00:00Z",27621,
          "2023-09-01T00:00:00Z",59165,
          "2023-10-01T00:00:00Z",115338,
          "2023-11-01T00:00:00Z",96147,
          "2023-12-01T00:00:00Z",355464,
          "2024-01-01T00:00:00Z",129219], <--- DSpace 7 migration
        "gap":"+1MONTH",
        "start":"2023-01-01T00:00:00Z",
        "end":"2024-02-01T00:00:00Z"}},
    "facet_intervals":{},
    "facet_heatmaps":{}}}
```

Looking at the past year I see most where created in the last six months. And what's bizarre is that we were running DSpace 6 for years at that point. And we migrated to DSpace 7 this month, but I still see 100,000+ stats records with invalid UUIDs.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @nwoodward !  Code looks good.  Already tested by @alanorth .  Merging immediately and porting to 7.x

**Pull request merged**
