### PR TITLE
Ds 3264 fix groupname export

### PR DESCRIPTION
**Pull request by aschweer**
https://jira.duraspace.org/browse/DS-3264

### CODE REVIEW

**Comment by aschweer** [comment]
I have no idea whether I'm doing the right thing for the test -- I'm happy to remove that class/commit from this PR if required.

**Comment by aschweer** [comment]
The original reporter of the issue said on dspace-tech that this PR appears to fix the problem they encountered: https://groups.google.com/d/msg/dspace-tech/fwYVvXhV3ik/HjK8XWKOBAAJ

**Comment by tdonohue** [comment]
+1 tested and it works.  I coincidentally ran into this same bug today myself (by simply exporting a Collection AIP and trying to reimport it). I applied this PR, and it fixes the issue of the bad group names.

**Comment by tdonohue** [comment]
This issue is annoyingly getting in the way of my ability to test or debug other issues related to AIP export/import (e.g. #1396).  I.e. this bug fix is needed on master to allow me to proceed in testing other AIP related bug fixes.

As this PR has been verified by two people (one in the email thread, and myself), was created by a Committer and comes with its own Unit Tests, I'm going to merge this immediately. Additional fixes/changes can come in additional PRs (as needed).

**Comment by mwoodiupui** [comment]
+1 by inspection.

**Pull request merged**
