### PR TITLE
DS-4253 Avoid oom during discovery reindex

### PR DESCRIPTION
**Pull request by cwilper**
Tested locally, this resolves https://jira.duraspace.org/browse/DS-4253

### CODE REVIEW

**Review by benbosman — APPROVED** [review]
I haven't tested this on my machine, but what I think is:
* ImmutableList.copyOf will indeed cause memory issues
* Using the normal iterator similar to the code prior to the MyDSpace merge will solve this issue
* A race condition may occur with the normal iterator, but I don't think it's relevant to catch here because the indexing process doesn't create/delete items

So this looks good to merge for me (without having deployed and tested it anywhere)

**Review by abollini — APPROVED** [review]
it seems quite obvious to me by code inspection and it is also aligned with the previous existing code, so +1

**Review by tdonohue — APPROVED** [review]
+1. Agreed this is obvious.  Thanks @cwilper for catching this quickly!

**Comment by mwoodiupui** [comment]
Making a `List` out of the content of an `Iterator` is clearly not a good idea unless we *know* that the content is not (potentially) huge.  But it is unfortunate that we have `Iterator`s over potentially long content streams which do not also implement `Iterable`.  We are stuck with the uncomfortable, error-prone `Iterator` interface when looping instead of writing a simple `for` loop and letting the compiler do the Right Thing.  It's easy to implement `Iterable` if `Iterator` is also implemented:  usually `public Iterator<Something> iterator() { return this; }` will do.

**Pull request merged**
