### PR TITLE
DS-4328

### LINKED ISSUE #7668: [DS-4328] Error after checking published during initial questions submission step
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4328">[DS-4328]</a> created by philipatmire</i>
<p>When you don't check the published checkbox on the initial questions step, and after starting the describe step you return to the initial questions step and do check the Published checkbox, an error occurs when continuing to the describe step:</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Java stacktrace: java.lang.NullPointerException
at org.dspace.content.DCDate.getYear(DCDate.java:298)
at org.dspace.app.xmlui.aspect.submission.submit.DescribeStep.renderDateField(DescribeStep.java:624)
at org.dspace.app.xmlui.aspect.submission.submit.DescribeStep.addBody(DescribeStep.java:233)
</pre>
</div></div>

<p>This happens because value "today' is added as date issued when the item is not published before. Once you select that the item is published before, the issue date can be filled in during the describe step. But "today" can't be parsed into a date by the DCDate class, causing the nullpointer when rendering the issue date field on the describe step. </p>

<p>Suggested solution:<br/>
Clear the dc.date.issued metadata field when published is selected in the initial questions submission step. </p>

<p> </p>

### PR DESCRIPTION
**Pull request by PhilipVis**
This change will clear the dc.date.issued item metadata field when published is selected during the initial questions submission step. 

Jira ticket: https://jira.duraspace.org/browse/DS-4328
Fixes #7668

### CODE REVIEW

**Review by nwoodward — APPROVED** [review]
:+1: Tested and confirmed it works.

**Comment by PhilipVis** [comment]
Thanks for the review @nwoodward. I have actually found a bug with my fix after this initial contribution, so i'll try to contribute my improved fix soon. 

The issue introduced by my fix is that date issued gets cleared when in the workflow. A better solution is to only clear the "today" value.

**Comment by nwoodward** [comment]
Ah, OK. I noticed that the error disappeared when you leave the Initial Questions step, but then the Date of Issue is empty. I'll wait for your fix to review again.

**Comment by PhilipVis** [comment]
The improved fix is now pushed to this PR.

**Review by nwoodward — APPROVED** [review]
:+1: Tested the new fix and confirmed it works.

**Comment by tdonohue** [comment]
NOTE: doesn't need to be ported to `main`, as the InitialQuestionsStep no longer exists.  Simply closing & reopening to ensure it still passes builds.

**Comment by tdonohue** [comment]
Already tested & approved.  Passes build as well.  Merging.  Thanks @PhilipVis !

**Pull request merged**
