### PR TITLE
[#9192] Makes forgot-password link removable

### LINKED ISSUE #9192: Make forgot-password link removable
Is your feature request related to a problem? Please describe.
Make the forgot-password anchor removable as it is now working with the new-user one.

Describe the solution you'd like
Create a new AuthorizationFeature that will handle this behavior by checking a configuration property, and if the user is specified also that the user can update the password, i.e. org.dspace.app.util.AuthorizeUtil#authorizeUpdatePassword.

**Additional context**
linked `dspace-angular` issue: https://github.com/DSpace/dspace-angular/issues/2622

### PR DESCRIPTION
**Pull request by vins01-4science**
## References
* Fixes #9192 
* Requires DSpace/dspace-angular#2624

## Description
This PR introduces a new `AuthorizationFeature` that checks for the forgot-password feature.
The same feature can also check, whenever is provided, that the user is able to update its password.

## Instructions for Reviewers
Try to enable the additional configuration:
```cfg
user.forgot-password = false
```
inside the `authentication-password.cfg` and check that it is not shown inside the login-component, in both:
- dropdown login menu
- login page

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@vins01-4science : Thanks!  Overall, this looks good.  I reported most of my feedback in my [frontend review](https://github.com/DSpace/dspace-angular/pull/2624#pullrequestreview-1863250013). 

That said, I did notice some IT cleanup that can be done in this PR.  You don't need to reset configurations back to the original values (they do that automatically).  There's also a missing IT that we probably should add.  See inline comments below.

**Comment by vins01-4science** [comment]
> @vins01-4science : Thanks! Overall, this looks good. I reported most of my feedback in my [frontend review](https://github.com/DSpace/dspace-angular/pull/2624#pullrequestreview-1863250013).
> 
> That said, I did notice some IT cleanup that can be done in this PR. You don't need to reset configurations back to the original values (they do that automatically). There's also a missing IT that we probably should add. See inline comments below.

@tdonohue Thank you for the review.

All the changes have been addressed on this PR.

Let me know if you  find something else.

**Review by tdonohue — APPROVED** [review]
👍 Thank you @vins01-4science !  This looks good to me now.

I will note though that we MUST add documentation for this new `user.forgot-password` configuration to the DSpace 8.x docs.  It probably should just be added next to `user.registration` here: https://wiki.lyrasis.org/display/DSDOC8x/Authentication+Plugins#AuthenticationPlugins-ConfiguringAuthenticationbyPassword

I'll get this merged, but will add a `needs documentation` label until the docs have been added.  If you can find time to add them, please link them here & we can remove that label.

**Comment by tdonohue** [comment]
Thanks @vins01-4science !  The documentation looks good to me.  https://wiki.lyrasis.org/display/DSDOC8x/Authentication+Plugins#AuthenticationPlugins-ConfiguringAuthenticationbyPassword

I'll remove the `needs documentation` label.

**Pull request merged**
