### PR TITLE
Fixing internal server errors for external sources

### LINKED ISSUE #2981: Internal server errors when retrieving entries for externalsources
**Describe the bug**
Currently, on the demo rest api, the `/api/integration/externalsources/<:source-name>/entries` endpoint throws a 500 in many situations:
- sherpaJournal, sherpaPublisher and pubmed always return a 500 when you use their entries link
- orcidV2 crashes for certain queries, or if a query does work it can crash on certain pages.

It is possible that this is due to configuration errors and not code bugs.

**To Reproduce**
- Go to [/api/integration/externalsources](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources) and use the entries link on the following sources
	- sherpaJournal: [example](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/sherpaJournal/entries?query=)
	- sherpaPublisher: [example](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/sherpaPublisher/entries?query=)
	- pubmed: [example](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/pubmed/entries?query=)

	
- Go to [/api/integration/externalsources](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources), and follow the link for orcidV2.
	- fill in the query "yes", and you'll get a 500: [example](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/orcidV2/entries?query=yes)
	 - fill in the query "test" and that will work: [example](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/orcidV2/entries?query=test)
	- but click on the "last" link and you'll get a 500: [example](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/integration/externalsources/orcidV2/entries?query=test&page=5758&size=20) 

**Expected behavior**
They should never throw a 500 if you pass valid parameters. If there are no results I'd expect an empty paginated response

### PR DESCRIPTION
**Pull request by jonas-atmire**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #[2981](https://github.com/DSpace/DSpace/issues/2981)

## Description
For the full scope/history of the problem, have a read through the linked issue.
Long story short: A bunch of the externalsources endpoints resulted in 500 code error.
This PR adds in additional checks to avoid these exceptions ending up in the response, but rather, that if there are no results, an empty paginated response is sent.

#### Changes done to the code
For the [**sherpaJournal/sherpaPublisher**](https://github.com/DSpace/DSpace/compare/main...atmire:74329-Internal-server-errors-for-external-sources?expand=1#diff-1e43d6223133bb406254a2671087123eaf3018806b1798f2f727baa9b2c003feR161), it returns an empty list similar to the [other providers](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/external/provider/impl/LCNameDataProvider.java#L120) (Where it previously returned null.
 
ORCID NullPointerException -> This was partly because the actual processing code needed some additional NullPointer checks. (If a person is being returned without 'name' information). The code now adds in additional checks to avoid these kinds of errors.
After that fix, there was another issue however when going through the calls:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<error xmlns="http://www.orcid.org/ns/error">
    <response-code>400</response-code>
    <developer-message>The start parameter for API users without credentials must be an integer between 0 and 10,000 Full validation error: The start parameter for API users without credentials must be an integer between 0 and 10,000</developer-message>
    <user-message>The start parameter for API users without credentials must be an integer between 0 and 10,000</user-message>
    <error-code>9043</error-code>
    <more-info>https://members.orcid.org/api/resources/troubleshooting</more-info>
</error>
```

The underlying reason is that the query being done contained too much results, and the pagination simply took that number of results as is. The actual ORCID API can't properly handle it in all cases through (As mentioned in the `<developer-message>`, it can only handle up to 10k records in a call)
This has been subsequently handled by making sure that 
1. the initial call only retrieves the max number of results that the API allows
2. This limit is also propagated to the pagination (So that for example the 'last' page link doesn't link to records that don't exist/can't be retrieved)

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by abollini** [comment]
hi @jonas-atmire 
thanks to work on that. Unfortunately, the orcid v2 provider will be replaced soon by the updated v3 so I think that your fixes if needed should be redone on the new version, see https://github.com/DSpace/DSpace/pull/2780

**Comment by jonas-atmire** [comment]
> #2780

@abollini I agree that these fixes would need to be redone on the new version, but since this feature upgrade hasn't been merged into main just yet, I think it would not be the best course of action to first merge v3 into main, then check if the errors are there as well, and then create another PR to fix them separately. (Since that would basically mean we are merging 'broken' code into main at that point).
Since these fixes are not very extensive, and at the moment, specific to v2 code that is in main (Basically some NullPointer checks and setting a 'max' parameter on a particular call)
Could you
1. Make sure that these particular types of errors are also present in the ORCID v3 PR
2. If so -> Check out if the code that is related to those errors is similar to the code in this PR
3. Check if the fixes done in these PR also fix those in the V3 
4. Update the related [PR](https://github.com/DSpace/DSpace/pull/2780)

This way we are not introducing code creeps into this PR (Possibly delaying a PR with some fixes that are not extremely extensive)

**Comment by tdonohue** [comment]
Hi @jonas-atmire : Just a note... the ORCID v3 changes have now been merged into `main`, which caused merge conflicts in this PR.  If you can find time to rebase & fix those conflicts it'd be appreciated!

**Comment by tdonohue** [comment]
@jonas-atmire : Just to follow-up.  It looks (to me) like your changes in this PR to `OricdV2AuthorDataProvider` can be easily copied into the new `OrcidV3AuthorDataProvider` class (on `main`).  The code differences between those two classes is _very minor_ (only 64 lines changed...most were renaming "V2" to "V3" with a few other minor syntax changes required to call the V3 API)...see https://github.com/DSpace/DSpace/pull/2780/files#diff-e7212bf9756781b0531484b7f600b948a7374f97009bcc18e4d3debc5c89a784

So, the next steps for this PR should be to simply move your changes to `OrcidV3AuthorDataProvider`, as they seem to be applicable there as well.  At that point, I'll gladly do a review/test & (if needed) pull in @abollini for secondary advice.

**Review by tdonohue — APPROVED** [review]
👍 Code looks good. Gave it some light testing and I'm no longer seeing the 500 errors that I can reproduce on the demo site.  Thanks @jonas-atmire !

**Pull request merged**
