### PR TITLE
Fix for Bump org.apache.commons:commons-configuration2 from 2.9.0 to 2.10.1

### PR DESCRIPTION
**Pull request by abollini**
## References
Fix for the issue in https://github.com/DSpace/DSpace/pull/9430
due to https://issues.apache.org/jira/browse/CONFIGURATION-846

## Description
Create a local copy of the fixed version of the class for the DSpace usage.

### CODE REVIEW

**Comment by tdonohue** [comment]
@abollini : Usually, when we create a **custom** class, I license it with DSpace license (as we created the code) and link it back to any code / licenses it was generated from.  But, if you prefer to exclude this single class and keep the Apache license (because this change was also contributed back to Apache Commons Config), then that is OK with me.

**Comment by abollini** [comment]
The last commit align our custom copy  DSpaceConfigurationPropertySource to the fix in https://github.com/apache/commons-configuration/pull/431 nevertheless we still have Integration Test failures.
I spent several hours going deeper in the analysis of the latest Integration Test failure and I believe to have finally identified the cause.
Our "custom" fixed `DSpaceConfigurationPropertySource` is only used in the spring context created by our Kernel, the spring context created by Springboot uses it own `ConfigurationPropertySource` to read the configuration from application.properties, application-test.properties and other internal properties file used by springboot. This mean that spring boot is still affected by the bug in commons-configuration CONFIGURATION-846. Indeed, the health actuator are using a configuration like that to determine the order of the different status (see https://docs.spring.io/spring-boot/reference/actuator/endpoints.html#actuator.endpoints.health.writing-custom-health-indicators )
```
management.endpoint.health.status.order=down,outofservice,up,unknown
```
but due to the bug in commons-configuration only the `down` value is keep. When the health check aggregate the status of the different dspace actuator as all of them return UP or UP_WITH_ISSUES (geoip) the aggregated status become unknown (see `org.springframework.boot.actuate.health.SimpleStatusAggregator.getAggregateStatus(Set<Status>)` )

So I see two options
1. we need to release our own patched version of commons-configuration or wait for the 2.11.0 release assuming that my second PR for CONFIGURATION-948 will be merged too
2. we can try to configure our own implementation of https://docs.spring.io/spring-boot/api/java/org/springframework/boot/actuate/health/StatusAggregator.html that would not rely on configuration properties

I will resume the activity on this task over the next days due to upcoming Open Repository event

**Comment by abollini** [comment]
@tdonohue it should be ready to go now

**Review by tdonohue — APPROVED** [review]
👍 Thanks @abollini !  This all looks correct to me.  I've also downloaded the PR and tested the frontend with it, to ensure no changes in behavior.  Everything seems to work as before.

**Pull request merged**
