### PR TITLE
[DS-2949] XSLT crosswalks should be parameterizable

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://jira.duraspace.org/browse/DS-2949
Not yet tested as I write this.

### CODE REVIEW

**Comment by helix84** [comment]
This is cool, I didn't know stylesheets could take parameters, too. Here's a succint overview of the technique used in this PR: https://www.oxygenxml.com/archives/xsl-list/200403/msg01013.html

**Comment by mwoodiupui** [comment]
I've now done some testing and fixed several problems.  This appears to be working as intended.

**Comment by mwoodiupui** [comment]
Rebasing as requested, to take up master changes that would interfere with a PR to *this* branch.

**Comment by pnbecker** [comment]
the code looks great. Before we can merge this, we still need to extend org.dspace.identifier.doi.DataCiteConnector to use this.

**Comment by mwoodiupui** [comment]
Since we use EZID, I'm not set up to test DataCiteConnector, but it builds cleanly.  Testers welcomed.

**Comment by tdonohue** [comment]
Is this aimed for 6.0?  If so, we need to move this forward quickly before "feature freeze".  Testers?

**Comment by mwoodiupui** [comment]
Actually I thought I'd missed the cutoff, but it is a response to DS-2924 which could use it, and that *is* scheduled for 6.0.

**Comment by mwoodiupui** [comment]
How I test:  I've added a command line tool to DataCiteXMLCreator.  You need to create an Item and get its handle.  Then run something like this:

`bin/dspace dsrun org.dspace.identifier.DataCiteXMLCreator 123456789/4`

The output (on standard out) is the generated XML document, which you can inspect, validate, format, etc.

**Comment by pnbecker** [comment]
I assigned this to me, hope to test it end of this week (I'm out of office again tomorrow and the day after).

**Comment by pnbecker** [comment]
I tested this with DataCite (haven't tested EZID, but mhwood did for sure) and it works great! Thanks @mwoodiupui ! +1

Just two small notes:
1.) I had to rebase this as we have crucial bugfixes to our DataCite connection in our master branch.
2.) When I run the doi-organiser I got the following warning:
```
Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
```
This is not a problem of this PR, this is a more general problem. @mwoodiupui will create a separate issue in Jira about that.

I merge this as it is as @helix84 likes it, I do and it comes from a trusted developer.

**Comment by pnbecker** [comment]
The warning I described above is now documented here: https://jira.duraspace.org/browse/DS-3119

**Pull request merged**
