### PR TITLE
DS-2630: New autocomplete options and enhancements

### PR DESCRIPTION
**Pull request by jamarisi**
https://jira.duraspace.org/browse/DS-2630

### CODE REVIEW

**Comment by amarisi** [comment]
Hi @tdonohue 
I rebased the branch to master so it has no longer merge conflicts.

**Comment by amarisi** [comment]
I updated the code to fix a missing method definition into an interface.

**Comment by tdonohue** [comment]
This needs rebasing on the latest master, because of merge conflicts

**Comment by tdonohue** [comment]
Closing as this PR must be recreated on `dspace-6_x` branch. XMLUI has been removed from `master`. See this mailing list notice: https://groups.google.com/d/msg/dspace-devel/aEFqSn46ryM/iPRr_IMLCwAJ

**Pull request closed without merging**
