### PR TITLE
Fix: Bitstream's retrieval's response without filename

### PR DESCRIPTION
**Pull request by BrunoNZ**
This adds bitstreams's filename to retrieval's response, and it fixes the bug that all bitstreams are downloaded using the same filename ("retrieve").

### CODE REVIEW

**Comment by peterdietz** [comment]
Looks good to me. You have a merge conflict, so perhaps you will need to pull/rebase against current master (beware of the hibernate refactor).

**Comment by BrunoNZ** [comment]
Is there something that i can do to help you with these conflicts? Maybe it is the spaces that my editor added when saved the file. I can try to rip them off.

I've used the master branch as basis to do these modifications, and i made sure that everything was updated. So i don't get why there are these conflicts.

**Comment by pnbecker** [comment]
@BrunoNZ: You must rebase the branch you created this PR from against our master branch. Then git will show you the conflicts.

**Comment by BrunoNZ** [comment]
Hey guys, sorry for the delay. I didn't had time to figure out how to do the rebase instead of just merging, and i've also forgot to reply here. My mistake.
For what i've seen the checks are all ok now. Do you want me to do something else? Did my last commit really resolve the merge conflicts?
Thanks!!

**Comment by tdonohue** [comment]
+1: Code looks good to me. This just needs a quick tester before we can merge.

**Comment by tdonohue** [comment]
This looks to have a minor merge conflict again. @helix84, looks like you assigned this to yourself. Are you working on getting this fix in?  Seems like a minor, quick fix that'd be useful for 6.0

**Comment by helix84** [comment]
Tested on 5.x, merged to dspace-5_x for DSpace 5.6. d6412e9af3be0b1534c7e19dd9a0a58366f2539e

**Comment by tdonohue** [comment]
@helix84: are you working on rebasing this on master, so we can merge it into master as well?  I don't want us to forget to fix this on master after backporting to 5.x.  Normally, I'd recommend we merge to each branch at the same time to avoid such confusion.

**Comment by helix84** [comment]
@tdonohue Yes, I was just testing it.

Tested on 6.x, merged to master for DSpace 6.0. b9d34144cbc899c4884308b9ebe340ab57713124

**Comment by tdonohue** [comment]
Thanks @helix84!

**Pull request closed without merging**
