### PR TITLE
[DS-2345] Fixes wrong start index starting at 0 instead of 1 for OpenSearch

### PR DESCRIPTION
**Pull request by christian-scheible**
This fixes the bug for the Discovery implementation. I think for the StandardOpenSearchGenerator (old Lucene based) implemenatation there are 2 lines which should be changed too. 
Line 72 and Line 114. But we are using Discovery which makes it harder to test it. 

https://jira.duraspace.org/browse/DS-2345

### CODE REVIEW

**Comment by christian-scheible** [comment]
I accidentally merged the changes on dspace master to the Branch [DS-2345]. Not sure how this affects the pull request.

**Comment by helix84** [comment]
Don't worry, we have a way to get just the stuff we need.

**Comment by christian-scheible** [comment]
Here is more Information on the bug: 
If you look at the result xml file of this query: 
http://demo.dspace.org/xmlui/open-search/discover?format=kops&query=author%3A*&start=0 
it says that start index is 1 `<opensearch:startIndex>1</opensearch:startIndex>` 
This query says the same:
http://demo.dspace.org/xmlui/open-search/discover?format=kops&query=author%3A*&start=1

but the result is different (starting with the second result of the first query)

The expected behaviour would be: 
the same query result for both querys because OpenSearch starts counting at 1 not at 0 and if   `<opensearch:startIndex>1</opensearch:startIndex>`  is equal in both cases the result has to be the same too.

**Comment by helix84** [comment]
+1 tested, cherry-picked

**Pull request closed without merging**
