### PR TITLE
[DS-3693] Port pull request #1838 to master

### PR DESCRIPTION
**Pull request by MW3000**
After #1838 was integrated to the 6_x branch, I now ported it to master.

> Hi. I wrote a tiny plugin, SolrServiceFileInfoPlugin, (implementing SolrServiceIndexPlugin) to make filenames and file descriptions from the ORIGINAL bundle searchable.
>
>The plugin must be added as a bean to discovery.xml.
To see it's effect, you have to reindex the Solr search core by executing:
[dspace]/bin/dspace index-discovery -b
>
>I documented it on https://gist.github.com/MW3000/5771c0488f8952bb888357ce8c655279

@kshepherd wrote:
>Just a note that we'll need to port this to master branch as well, should be pretty easy, we just won't want the changes to messages.xml (as xmlui isn't in master)

I just have not been able to test it on master. Is there already a REST endpoint available for this functionality?

### CODE REVIEW

**Comment by MW3000** [comment]
I run tests locally by executing:
`mvn test -Dmaven.test.skip=false`
But this does not seem to trigger all the tests that are run by TravisCI. Especially Travis runs a test named `org.dspace.app.rest.DiscoveryRestControllerIT` that is failing. How do I trigger the execution of this test?

**Comment by mwoodiupui** [comment]
Integration tests (IT*, *IT) are run in a different step, and controlled by a different property.  Add -DskipITs=false to enable them.

**Comment by kshepherd** [comment]
Hi @MW3000 , if it helps, the full output of the test is below. It's probably a case of us updating the integration tests to test for this new filter... it looks as though DiscoveryRestControllerIT.discoverSearchTest looks for the default range of filters using hardcoded SearchFilterMatcher tests:

`.andExpect(jsonPath("$.filters", containsInAnyOrder(
                       SearchFilterMatcher.titleFilter(),
                       SearchFilterMatcher.authorFilter(),
                       SearchFilterMatcher.subjectFilter(),
                       SearchFilterMatcher.dateIssuedFilter(),
                       SearchFilterMatcher.hasContentInOriginalBundleFilter()
                   )))`

Even though Discovery filters themselves are technically spring beans, and so the integration tests are including your spring config in the test item, which is why it's failing, because there's no corresponding filter to match it. I **think** that's what's going on. If you'd like a hand updating the integration tests I can chip in, perhaps we could ask for clarification in the #rest-api channel in Slack.

`Failed tests: 
  DiscoveryRestControllerIT.discoverSearchTest:756 JSON path "$.filters"
Expected: iterable over [(is json with json path "$['filter']" evaluated to is "title" and (is json with json path "$['operators']" evaluated to iterable over [is json with json path "$['operator']" evaluated to is "equals", is json with json path "$['operator']" evaluated to is "notequals", is json with json path "$['operator']" evaluated to is "authority", is json with json path "$['operator']" evaluated to is "notauthority", is json with json path "$['operator']" evaluated to is "contains", is json with json path "$['operator']" evaluated to is "notcontains"] in any order)), (is json with json path "$['filter']" evaluated to is "author" and (is json with json path "$['operators']" evaluated to iterable over [is json with json path "$['operator']" evaluated to is "equals", is json with json path "$['operator']" evaluated to is "notequals", is json with json path "$['operator']" evaluated to is "authority", is json with json path "$['operator']" evaluated to is "notauthority", is json with json path "$['operator']" evaluated to is "contains", is json with json path "$['operator']" evaluated to is "notcontains"] in any order)), (is json with json path "$['filter']" evaluated to is "subject" and (is json with json path "$['operators']" evaluated to iterable over [is json with json path "$['operator']" evaluated to is "equals", is json with json path "$['operator']" evaluated to is "notequals", is json with json path "$['operator']" evaluated to is "authority", is json with json path "$['operator']" evaluated to is "notauthority", is json with json path "$['operator']" evaluated to is "contains", is json with json path "$['operator']" evaluated to is "notcontains"] in any order)), (is json with json path "$['filter']" evaluated to is "dateIssued" and (is json with json path "$['operators']" evaluated to iterable over [is json with json path "$['operator']" evaluated to is "equals", is json with json path "$['operator']" evaluated to is "notequals", is json with json path "$['operator']" evaluated to is "authority", is json with json path "$['operator']" evaluated to is "notauthority", is json with json path "$['operator']" evaluated to is "contains", is json with json path "$['operator']" evaluated to is "notcontains"] in any order)), (is json with json path "$['filter']" evaluated to is "has_content_in_original_bundle" and (is json with json path "$['operators']" evaluated to iterable over [is json with json path "$['operator']" evaluated to is "equals", is json with json path "$['operator']" evaluated to is "notequals", is json with json path "$['operator']" evaluated to is "authority", is json with json path "$['operator']" evaluated to is "notauthority", is json with json path "$['operator']" evaluated to is "contains", is json with json path "$['operator']" evaluated to is "notcontains"] in any order))] in any order
     but: Not matched: <{filter=original_bundle_filenames, operators=[{"operator":"equals"},{"operator":"notequals"},{"operator":"authority"},{"operator":"notauthority"},{"operator":"contains"},{"operator":"notcontains"}]}>`

**Comment by MW3000** [comment]
@mwoodiupui @kshepherd Thank you for your help. I adapted the test.

**Review by kshepherd — APPROVED** [review]
+1, looks good to me

**Comment by terrywbrady** [comment]
Resolved the merge conflict.  I see that this one is still marked "work in progress".

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me. Main code is a port of #1838, with minor updates for new REST API.  As this was previously also approved by @kshepherd , I'll merge.

**Pull request merged**
