### PR TITLE
[DS-2898] Add support for all authentication methods in the rest api

### PR DESCRIPTION
**Pull request by KevinVdV**
https://jira.duraspace.org/browse/DS-2898

Shared credits with @rradillen 

Use spring security to support all authentication methods in DSpace, leaves out the token but returns a JSESSIONID. When you pass this "JSESSIONID" along to future requests the user is automatically logged in.
By no longer using the token the issue that tokens only expire on tomcat restart/logout is also solved.

Bonus feature with this pull request: Special groups are also supported in the rest api.

**Verified authentication methods**

Although all authentication methods should work, I haven't been able to verify them all. before accepting this pull request please aid me in testing. Below is a breakdown of which ones have been verified.
- [x] Password (use /login endpoint)
- [x] LDAP (use /login endpoint)
- [ ] Shibboleth (use /shibboleth-login endpoint)
- [x] IP (use /login endpoint)
- [ ] X.509 (use /login endpoint)

**Basic implementation documentation**

The heart of the spring security is the "security-applicationContext.xml" file, since login is "optional" in our rest implementation I have made use of a filter chain. The following bean is setup to provide filters depending on the url:
https://github.com/KevinVdV/DSpace/blob/DS-2898-rest-all-authentication-methods/dspace-rest/src/main/webapp/WEB-INF/security-applicationContext.xml#L23

All requests made to "/login" & "shibboleth-login" will pass the "passwordLoginAuthenticationFilter", this filter is setup to use the "dspaceAuthenticationManager" who in turn uses the "DSpaceAuthenticationProvider".
The DSpaceAuthenticationProvider will attempt to login our user using the DSpace authentication mechanism.

The filter that is called on all requests is the "SecurityContextPersistenceFilter", this will populate the "SecurityContextHolder", this object contains all our credential information. The createContext() will translate this object to a DSpace context and setup the EPerson & special groups. https://github.com/KevinVdV/DSpace/blob/DS-2898-rest-all-authentication-methods/dspace-rest/src/main/java/org/dspace/rest/Resource.java#L83

The benefit of using a third party framework like spring security is that it can be easily extended to add additional functionality by altering a single xml file.

**How to test this pull request (using curl)** 

> curl -v "http://localhost:9090/dspace-kevin-rest/login?email=atmirenv@gmail.com&password=******"

returns among other things:

> Set-Cookie: JSESSIONID=04E85C78D1097CC3D0BD5599B25585FA; Path=/dspace-kevin-rest

subsequent request:

> curl -v "http://localhost:9090/dspace-kevin-rest/status" --cookie "JSESSIONID=04E85C78D1097CC3D0BD5599B25585FA"

returns a document like this:

> <?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><authenticated>true</authenticated><email>atmirenv@gmail.com</email><fullname>Atmire NV</fullname><okay>true</okay></status>

### CODE REVIEW

**Comment by terrywbrady** [comment]
@KevinVdV , the following change is needed to Shibb Authenticate to DSpace XMLUI and to DSpace REST.

https://github.com/DSpace/DSpace/pull/1227

I think your PR needs more documentation.  Looking at the code, I see the following method, but I cannot invoke it from a browser.

https://github.com/KevinVdV/DSpace/blob/DS-2898-rest-all-authentication-methods/dspace-rest/src/main/java/org/dspace/rest/RestIndex.java#L154-L155

I expected to be able to call GET /rest/login or GET /rest/login-shibboleth to be redirected to my Shibboleth authentication page.

I used a REST client to POST to /rest/login with no payload. After doing this, /rest/status indicated that I was authenticated, but I was assigned to the wrong eperson record.  I was assigned to an eperson record that does not have an e-mail address.

**Comment by KevinVdV** [comment]
@terrywbrady Thank you for testing this pull request, I made the following improvements:
* Ensured that the "login-shibboleth" can is now GET (as a post would make a little sense)
* When authentication fails due to faulty credentials a 401 is now returned instead of 200
* Added some documentation to the security-applicationContext from spring security, see original post. 

As to the issue with the other person login, could you search the logs for "login" or "failed_login" logged in the "DSpaceAuthenticationProvider" class ?

**Comment by KevinVdV** [comment]
Rebased on latest master + tested LDAP & this works as well.

Ps: LDAP was not tested against latest master since LDAP appears to be broken there: https://jira.duraspace.org/browse/DS-3014

**Comment by helix84** [comment]
@KevinVdV Could you please rephrase your comment regarding LDAP, I didn't understand what you tested and what works/doesn't work.

**Comment by tdonohue** [comment]
@KevinVdV : LDAP should now be working on master. In reality, the only issue on master was the configuration *examples* in the `authentication-ldap.cfg` file.  Any commas in configurations must now be escaped. See #1261 PR for examples of how to change your `authentication-ldap.cfg` as necessary.

**Comment by KevinVdV** [comment]
@tdonohue Thanks for the heads up on the LDAP.
Rebased onto latest master & tested LDAP & Password authentication & both still work.

**Comment by mwoodiupui** [comment]
I'm testing password login, and I don't get back the header (rest-dspace-token) that the documentation says I should, although the log seems to show a successful login.

mwood@mhw ~/dspaces/DS-2898 $ curl --verbose -D headers --data 'email=mwood@iupui.edu' --data 'password=apassword' https://mhw.ulib.iupui.edu:8443/DS-2898/rest/login
*   Trying 2001:18e8:3:10ab::100...
* Connected to mhw.ulib.iupui.edu (2001:18e8:3:10ab::100) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*        subject: C=US; ST=IN; L=Bloomington; O=Indiana University; OU=University Library; CN=mhw.ulib.iupui.edu
*        start date: Sep 29 00:00:00 2014 GMT
*        expire date: Sep 28 23:59:59 2017 GMT
*        subjectAltName: mhw.ulib.iupui.edu matched
*        issuer: C=US; ST=MI; L=Ann Arbor; O=Internet2; OU=InCommon; CN=InCommon RSA Server CA
*        SSL certificate verify ok.
> POST /DS-2898/rest/login HTTP/1.1
> Host: mhw.ulib.iupui.edu:8443
> User-Agent: curl/7.45.0
> Accept: */*
> Content-Length: 36
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 36 out of 36 bytes
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Set-Cookie: JSESSIONID=101326BC9A37179CC2EA312A749743F6; Path=/DS-2898/rest/; Secure; HttpOnly
< Content-Length: 0
< Date: Thu, 25 Feb 2016 20:00:47 GMT
< 
* Connection #0 to host mhw.ulib.iupui.edu left intact
mwood@mhw ~/dspaces/DS-2898 $

2016-02-25 15:00:47,146 INFO  org.dspace.authenticate.PasswordAuthentication @ anonymous::authenticate:attempting password auth of user=mwood@iupui.edu
2016-02-25 15:00:47,148 INFO  org.dspace.authenticate.PasswordAuthentication @ mwood@iupui.edu::authenticate:type=PasswordAuthentication
2016-02-25 15:00:47,148 INFO  org.dspace.eperson.EPersonServiceImpl @ mwood@iupui.edu::update_eperson:eperson_id=8e56dbf2-39ba-4d11-ab1d-8fbbde5061da
2016-02-25 15:00:47,148 INFO  org.dspace.rest.authentication.DSpaceAuthenticationProvider @ mwood@iupui.edu::login:type=explicit

**Comment by KevinVdV** [comment]
@mwoodiupui I haven't altered the documentation yet as this PR hasn't been verified by anybody but myself. But take a look at the original description, you need to use the "JSESSIONID" parameter that is returned by curl (for your request this would have been "101326BC9A37179CC2EA312A749743F6").

You can pass it along in curl by using: 
curl -v "http://localhost:9090/dspace-kevin-rest/status" --cookie "JSESSIONID=04E85C78D1097CC3D0BD5599B25585FA"

**Comment by terrywbrady** [comment]
@KevinVdV , @mwoodiupui, I am still unable to verify success with this code.

Note: Because of the shibboleth re-direct to a sign on page, I cannot simulate the entire flow with curl or with a rest client.

Config 1. Default Configuration (no shibboleth rule in apache)
- open /rest/login-shibboleth in a browser
- redirect to shibb login page occurs
- provide correct credentials
- browser redirects to /rest/shibboleth-login with a failure (no JsessionID can be retrieved)

Config 2: Add apache rule to force shibboleth authentication at /rest
- open /rest/login-shibboleth in a browser
- redirect to shibb login page occurs
- provide correct credentials
- browser redirects to /rest/shibboleth-login with a success 
- if I attempt to use the jsessionid that is present after this call using curl or a rest client, I am redirected to the shibboleth login page

I would be happy to meet with someone over a web meeting session to illustrate the behavior that I am seeing.

IMHO, this PR does not resolve shibboleth functionality, but it may be better to merge it and move forward than to keep all of the authentication methods in limbo.

**Comment by mwoodiupui** [comment]
+1 insofar as password authN is concerned.  I tested it and got the expected result.

**Comment by KevinVdV** [comment]
Added a new commit to fix the unit tests.

@terrywbrady I think I might have a way to test this PR with curl, login through the UI with shibboleth. Your session will not be persisted since the token has been replaced with a JSESSIONID cookie. But you can sniff the returned JSESSIONID out of the response after login, pass this argument through curl.

**Comment by tdonohue** [comment]
In DevMtgs, we agreed this should be merged and any outstanding Shib issues should be logged as a separate ticket (so that we can verify and resolve them)

**Pull request merged**
