### PR TITLE
[DS-3336] Properly sort collections in move item drop-down

### PR DESCRIPTION
**Pull request by aschweer**

### CODE REVIEW

**Comment by aschweer** [comment]
https://jira.duraspace.org/browse/DS-3336

**Comment by misilot** [comment]
I just tried this on my 5.5 install and it does not sort.

I have attached what it looks like after the patch.
capture

**Comment by misilot** [comment]
Tested on 5.5 and it works here. Thanks @aschweer!

**Review by tdonohue — APPROVED** [review]
👍 This seems like a small, useful patch. To me it seems like one we should merge to 5.x and cherry-pick over to 6.x

**Comment by tdonohue** [comment]
This was merged, and also cherry-picked (after testing minor updates to code) to 6.x: https://github.com/DSpace/DSpace/commit/97785d778f5c414a4e793009dee246e2cec16197

**Pull request merged**
