### PR TITLE
DS-2962: Robots.txt disallows site /discovery but not /handle/*/discover

### PR DESCRIPTION
**Pull request by rradillen**
https://jira.duraspace.org/browse/DS-2962

### CODE REVIEW

**Comment by KevinVdV** [comment]
+1, but if we accept for master it might collide with: https://github.com/DSpace/DSpace/pull/1104

**Comment by helix84** [comment]
Just a note about asterisk in URL - it's not supported by the robots exclusion protocol (http://www.robotstxt.org/robotstxt.html), although it may be supported by the Google crawler (https://en.wikipedia.org/wiki/Robots_exclusion_standard#Universal_.22.2A.22_match).

**Comment by bram-atmire** [comment]
Google, Bing, Yahoo and Ask support * and $ according to this information:
https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt?hl=en#url-matching-based-on-path-values

**Comment by hardyoyo** [comment]
+1 I've been running this patch in production from the day it was submitted, 12/21/2015

**Pull request merged**
