### PR TITLE
[DS-1140] Update MSWord Media Filter to use Apache POI (like PPT Filter) and also support .docx

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://jira.duraspace.org/browse/DS-1140

Patch to create a new POI-based text extractor for Microsoft Word (.doc and .docx).

### CODE REVIEW

**Review by tomdesair — CHANGES_REQUESTED** [review]
I don't think there is an explicit need to cast to XWPFWordExtractor or WordExtractor.

Wouldn't it also be better to merge the PPT and Word filters into one "Microsoft Office" Filter? POI also supports Visio and Publisher files etc and the code will always look the same.

That way DSpace would support text extraction for a lot of new files.

**Comment by mwoodiupui** [comment]
You're right about not needing the casts.  I eventually found enough documentation on this area of POI to see that I didn't have to follow the pattern in the .ppt extractor.

There's already [work](https://github.com/richardrodgers/ctask/tree/master/mediafilter) to replace all the POI stuff with Tika, which would cover much more than just MS Office, so I'm trying to keep to the original scope of the issue for now.  I'd like to see the Tika/curation-task approach adopted in the future, but that's too much change for a maintenance release.  The current Word extraction is arguably broken because it doesn't handle current formats, so I think that it's reasonable to make this smaller change in order to to fix that.

**Comment by tomdesair** [comment]
I agree that having one "MS Office" filter would be a chance that is too big for a minor release.

It looks like the repository you mention is not actively maintained.

**Comment by mwoodiupui** [comment]
Unit tests pass.  I examined of the resulting String by eye and saw no obvious faults.

**Review by tomdesair — APPROVED** [review]
Reviewed and tested. Works as expected. Nice job!

**Review by hardyoyo — APPROVED** [review]
+1 by review

**Review by tdonohue — APPROVED** [review]
👍 Approved in DevMtg

**Comment by tdonohue** [comment]
Also cherry-picked over to `master`

**Pull request merged**
