### PR TITLE
Add limit, offset, and total facet count to Solr query for the metadata browse index

### LINKED ISSUE #9244: Browse always retrieves all facet results from Solr, only to discard most of them
**Describe the bug**
`SolrBrowseDAO` uses Solr facets to generate browse entries.
Browse pages are paginated to limit the amount of these browse entries on the given page.

However, DSpace retrieves _the full facet_ to build up the list of browse entries. For example, in a client repository we're working on, DSpace requests a list of 87+ _thousand_ authors from Solr, and returns only a few tens of them.

We don't appear to do any custom filtering on this full list of facets, so this should not be necessary.

There are built-in Solr parameters to paginate facets: [`facet.limit`](https://solr.apache.org/guide/6_6/faceting.html#Faceting-Thefacet.limitParameter), [`facet.offset`](https://solr.apache.org/guide/6_6/faceting.html#Faceting-Thefacet.offsetParameter), and DSpace already [supports](https://github.com/DSpace/DSpace/blob/4bf7d178049a28e24b452455bf2db64cc13953b8/dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java#L922-L924) them.
Resolving this issue should be as easy as patching `limit` and `offset` through to the constructor [here](https://github.com/DSpace/DSpace/blob/4bf7d178049a28e24b452455bf2db64cc13953b8/dspace-api/src/main/java/org/dspace/browse/SolrBrowseDAO.java#L183-L191)

**To Reproduce**
1. Debug any DSpace instance with many Items
1. Go to a browse page, set the page size to more than the total number of results
1. Place a breakpoint [here](https://github.com/DSpace/DSpace/blob/4bf7d178049a28e24b452455bf2db64cc13953b8/dspace-api/src/main/java/org/dspace/browse/SolrBrowseDAO.java#L267)
   * You'll see that the `result.facets` contains _all_ results for the given facet
   * A few lines down, the list is truncated to the given `offset`/`limit`

**Expected behavior**
We should avoid such huge Solr requests and let Solr handle the pagination instead.

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by toniprieto**
## References

* Fixes #9244

## Description
This modifies the Solr query for the metadata browse index to include `limit` and `offset` parameters. Additionally, it uses the `json.facet` parameter to calculate the total number of values the query would return without applying limits. This significantly improves performance for metadata indices with a large number of values.

## Instructions for Reviewers

The current Solr query used to retrieve values for a metadata browse index does not include limits, as retrieving the total number of entries in the facet is necessary for paginating the results.

After exploring alternatives, I found that the functionality offered by the [JSON Facet API](https://solr.apache.org/guide/8_1/json-facet-api.html) makes it possible to retrieve the total number of facet entries without fetching all the data. This can be achieved by adding something like the following to the Solr query:

```
json.facet={
  "entries_count": {
    "type": "terms",
    "field": "bi_2_dis_filter",
    "limit": 0,
    "numBuckets": true
  }
}
```

This query returns the total number of entries in the `numBuckets` attribute, in a response snippet like this::

```
"facets": {
  "count": 218359,
  "entries_count": {
    "numBuckets": 157086,
    "buckets": []
  }
}
```

For example, the following query uses this approach:

http://localhost:8983/solr/search/select?f.bi_2_dis_filter.facet.limit=20&f.bi_2_dis_filter.facet.offset=0&f.bi_2_dis_filter.facet.sort=index&facet.field=bi_2_dis_filter&facet.mincount=1&facet.offset=0&facet=true&fl=search.resourcetype%2Csearch.resourceid%2Csearch.uniqueid%2Cdatabase_status&fq=(search.resourcetype%3AItem%20AND%20latestVersion%3Atrue)%20OR%20search.resourcetype%3ACollection%20OR%20search.resourcetype%3ACommunity&fq=-withdrawn%3Atrue%20AND%20-discoverable%3Afalse&fq=NOT(discoverable%3Afalse)&indent=true&json.facet=%7B%22entries_count%22%3A%7B%22type%22%3A%22terms%22%2C%22field%22%3A%22bi_2_dis_filter%22%2C%22limit%22%3A0%2C%22numBuckets%22%3Atrue%7D%7D&q.op=OR&q=*%3A*&rows=0&start=0&version=2&wt=json

With this type of query, it is no longer necessary to fetch all values, resulting in much faster responses. In a test repository with 157,082 author entries, the API query execution time dropped from 3,40 seconds to 100 ms. (request /api/discover/browses/author/entries?sort=default,ASC&page=0&size=20)

### Testing

To review, verify that the author and subject indices work correctly and accurately return the total number of values, regardless of whether filters are applied.

## Checklist

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
Thanks @toniprieto! I have not tested this patch yet, but it is exciting. What is the equivalent query for the old way without the JSON facets? Other than testing whether or not the repository still functions as expected, it would be interesting to profile or at least time the old way versus the new way.

**Comment by alanorth** [comment]
I tested this on DSpace 7.6 (patch applies cleanly) in a repository with 120,000 authors. Here is a before and after of the API call showing a large improvement.

Before:

```console
$ hyperfine -N 'curl https://dspace.me.org/server/api/discover/browses/author/entries?sort=default,ASC&page=0&size=20'         
Benchmark 1: curl https://dspace.me.org/server/api/discover/browses/author/entries?sort=default,ASC&page=0&size=20
  Time (mean ± σ):      1.550 s ±  0.040 s    [User: 0.020 s, System: 0.005 s]
  Range (min … max):    1.498 s …  1.623 s    10 runs
```

After:

```console
$ hyperfine -N 'curl https://dspace.me.org/server/api/discover/browses/author/entries?sort=default,ASC&page=0&size=20'
Benchmark 1: curl https://dspace.me.org/server/api/discover/browses/author/entries?sort=default,ASC&page=0&size=20
  Time (mean ± σ):     694.5 ms ±  58.9 ms    [User: 21.5 ms, System: 6.1 ms]
  Range (min … max):   630.4 ms … 759.3 ms    10 runs
```

So the mean response time reduced by 55%. :+1:

**Comment by toniprieto** [comment]
@alanorth Thanks for testing it! 

The current Solr query being used is something like: 

http://localhost:8983/solr/search/select?facet.field=bi_2_dis_filter&fl=search.resourcetype,search.resourceid,search.uniqueid,database_status&start=0&f.bi_2_dis_filter.facet.limit=-1&fq=(search.resourcetype:Item+AND+latestVersion:true)+OR+search.resourcetype:Collection+OR+search.resourcetype:Community&fq=-withdrawn:true+AND+-discoverable:false&fq=NOT(discoverable:false)&rows=0&f.bi_2_dis_filter.facet.sort=index&version=2&q=*:*&facet.mincount=1&facet=true&wt=json&facet.offset=0

The response from this query might be fast, but the main issue is that it doesn't limit the facet values, and processing it to get the total number of returned values is costly. Testing with the API query you've used makes more sense to evaluate performance.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @toniprieto !  I've verified this speeds up the Browse by Author and Browse by Subject pages significantly.  I didn't find any obvious bugs...everything works the same as before.

**Pull request merged**
