### PR TITLE
8968 - request-a-copy email: non ASCII characters are encoded as HTML…

### LINKED ISSUE #8968: request-a-copy email: non ASCII characters are encoded as HTML character entity references
## Bug Description

Currently, non ASCII characters, e.g. German umlauts, are encoded as HTML character entity references (instead of UTF-8) in  the body of a request-a-copy email. Since the mail header `Content-Type` is set to `text/plain; charset=UTF-8` mail clients may display non ASCII characters inappropriately.

### Example input in request-a-copy form:

image

### Payload of request-a-copy email:

image

### Rendered output in mail client (in this case Thunderbird)

image

## Expected behavior

Do not use HTML character entity references. As the email body is UTF-8 encoded, switch to UTF-8 encoding instead.

### PR DESCRIPTION
**Pull request by aroman-arvo**
## References
* Fixes #8968 

## Description
Removed entity conversion

## Instructions for Reviewers
Make a request copy and check the email recieved by administrator

## Checklist

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [X] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by kshepherd** [comment]
Is there a way to fix this that doesn't also remove potential XSS attacks? Maybe some HTML sanitization rather than fully escaping? Or is the XSS comment no longer relevant?

`// Requester's message text, escaped to evade nasty XSS attempts`

Should / do we force all emails to be sent as plain text?

**Comment by aroman-arvo** [comment]
I think plain-text email cannot contain a cross-site scripting attack. And request item emails are send as plain text. 
(...)
```
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable


Dear arvo arvo,

A user of DSpace at My University, named =C3=AB=C3=B6=C3=A1 and using the e=
mail aroman@arvo.es, requested a copy of the file(s) associated with the do=
cument: "Request copy prueba" (http://localhost:4000/handle/123456789/55) s=
ubmitted by you.

This request came along with the following message:

"=C3=A9=C3=A1=C3=B3=C3=B4=C2=A8z
@=C3=B6"
```
(...)
And email viewers show it as:

```
Dear arvo arvo,

A user of DSpace at My University, named ëöá and using the email [aroman@arvo.es](mailto:aroman@arvo.es), requested a copy of the file(s) associated with the document: "Request copy prueba" (http://localhost:4000/handle/123456789/55) submitted by you.

This request came along with the following message:

"éáóô¨z
@ö"
```

**Review by pnbecker — CHANGES_REQUESTED** [review]
I'm afraid, that this makes us vulnerable for anyone putting nasty JavaScript Code into the name field. I have not tested this, but I would ask to change this PR. While plain text mail might be save, it would then highly depend on the email client, and that is a risk, I would like to avoid.

I read around a little bit and many sources tells us, that escaping is context specific (compare https://stackoverflow.com/a/14900233/3891302 and https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/html/HtmlEscapers.html). It is general not a good idea to write security code yourself, whenever libraries exists, that already take care, but in this case, I have the feeling that most libraries seem to escape too much, which resulted in the bug this PR tries to fix.

We can test Spring's HtmlUtils. It contains a [method](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/HtmlUtils.html#htmlEscape(java.lang.String,java.lang.String)) that we can give an encoding (for example UTF-8) and it escapes only the characters, that are not supported by the encoding. We should ensure, that it escapes at least `&`, `<`, `>`, `"`, `'`, `#`.

Google's guava escapes "only" `&`, `<`, `>`, `"`, `'` and points out that escaping is tricky and context sensitive (see again
https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/html/HtmlEscapers.html). Google's Guava could be another solution to fix this, but would probably mean to add another dependency to DSpace.

**Comment by pnbecker** [comment]
https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html looks pretty comprehensive.

**Comment by aroman-arvo** [comment]
How naive of me. Security is never redundant.
I created a custom StringEscapeUtils with the rules that you indicate. It is easily extensible, if there are more dangers it is the moment.

**Comment by pnbecker** [comment]
From a first glance on the code this looks much better to me. I will have to test this.

One question to @tdonohue: It is good practice to not write security relevant methods yourself, if libraries exists doin what you need. In this case I would argue that most of the libraries are doing more than we need. Furthermore the documentation of Google's Guava states to do what this method does (see my comment above for a link to that documentation) but it is not worth to add the dependency for just this tiny method. @tdonohue, would you agree with me, that this is secure enough and we can go with a custom implementation here?

**Comment by tdonohue** [comment]
@pnbecker and @aroman-arvo :  I would much rather we did *not* write our own, custom escape utilities.  It can be a security risk if we accidentally overlook a problematic character, and generally external utilities will be better about ongoing maintenance than we can be.  Ideally, we should rely on external libraries as much as possible and avoid "do it yourself" approaches.

Looking around it appears to me that `HtmlUtils.htmlEscape()` (mentioned also by @pnbecker ) provided in Spring might be all we need.  According to reports, it will not escape Unicode characters in other languages. This StackOverflow answer claims it will leave Russian and Chinese characters unescaped: https://stackoverflow.com/a/1265366/3750035  Additionally, we should already have it in our dependencies as it's under `org.springframework.web.util.HtmlUtils`: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/HtmlUtils.html

If that library works, I'd much prefer using it than writing our own customized encoder into Apache's StringEscapeUtils.  It's also a much smaller code change.

If somehow it doesn't work, I'm not against this PR as-is.  But, if we go with this "custom" approach, then we should **require** Unit Tests that prove it is acting exactly as we expect it to.

**Comment by aroman-arvo** [comment]
```
System.out.println(HtmlUtils.htmlEscape("áéíóúñÁÉÍÓÚÑß - < > ' \" & # ", "UTF-8")); returns:
áéííóúñÁÉÉÍÓÚÑß - &lt; &gt; &#39; &quot; &amp; #. 
```
The "#" character is not escaped.
If it is not necessary to escape it, it will work.

Guava would do the same without contributing anything, so I would discard it.

If it is necessary to escape the "#" character, as pnbecker comments, there doesn't seem to be a library that includes it by default. You would have to customize it, like StringScapeUtils.

**Comment by pnbecker** [comment]
It is not necessary to escape #. HtmlUtils seems to be perfect.

**Comment by aroman-arvo** [comment]
Implemented using HtmlUtils

**Review by kshepherd — APPROVED** [review]
+1 thanks @aroman-arvo for the fix and the patience in going through the different escaping scenarios with us :)

**Review by pnbecker — APPROVED** [review]
Thank you, that's perfect now.

**Pull request merged**
