### PR TITLE
DS-2188 : Remove remaining artifacts/configs of DBMS Browse system

### PR DESCRIPTION
**Pull request by tdonohue**
https://jira.duraspace.org/browse/DS-2188

While the core functionality of the DBMS Browse system was removed in #1083 (Service API refactor), some artifacts and configs still remain.

This PR is seeking to remove any remaining unused classes / configurations that related to the old DBMS Browse system.

This PR is now ready for review / additional testing. I've cleaned up the main artifacts I've found. Most other Browse classes seem to have Solr-based DAOs behind them.

The PR includes a new Flyway Java migration to drop all DBMS Browse table/views/schemas from your database. One simple way to test it out is:
1. Find a 5.x (or prior) database/instance
2. Ensure it is configured to use a database specific `browseDAO.class`, `browseCreateDAO.class` and `ItemCountDAO.class` in your dspace.cfg. See: https://wiki.duraspace.org/display/DSDOC5x/Legacy+methods+for+re-indexing+content#Legacymethodsforre-indexingcontent-ConfiguresearchandbrowsetousePostgreSQL
3. Re-index all your content into DBMS browse: `./dspace index-db-browse -f -r`
4. Run the itemcounter to also add all Community/Collection item counts into your DBMS: `./dspace itemcounter`
5. At this point, you'll have a 5.x (or earlier) database which is using DBMS browse + itemcounter. The Flyway migration should be able to successfully drop all tables, sequences, views related to both...including:
   - All `bi_*` tables and any related sequences (these are the browse index tables)
   - `communities2item` table (no longer needed/used)
   - `collection_item_count` table and `community_item_count` table (used by old `itemcounter`).

### CODE REVIEW

**Comment by tdonohue** [comment]
I just realized I neglected to write in a DB (Flyway) migration to automatically remove any artifacts of DBMS browse from the database. I'm working on a fix to that, which I should have pushed up tomorrow.

**Comment by tdonohue** [comment]
Just pushed up a Flyway Java migration which is based heavily on the old `./dspace index-db-browse -f -d" command (I borrowed the general logic and the DB specific DROP commands). It removes all DBMS browse tables, along with the `communities2item` table, and the itemcounter tables (`collection_item_count` and `community_item_count`).

I've tested the migration against a 5.x database which had DBMS browse index tables, etc. and it seems to work fine.

This PR is ready for review/testing.

**Comment by helix84** [comment]
The flyway migration successfully removes the default browse indices, but fails to remove any custom ones (bi_5_dis, bi_5_dmap, bi_6_dis, bi_6_dmap, ...). These are useless without DB browse, so they should be removed, too.

**Comment by helix84** [comment]
Most things seem to work. I didn't wait for the reindex to complete, but I noticed that browse by title and date already showed data during reindex, whereas subject and author had no entries (both XMLUI and JSPUI).

**Comment by helix84** [comment]
I re-tested the missing author and subject browse indices. This time I waited for the reindex to complete and they were still missing.

I also tested latest master, there is no such problem there.

**Comment by tdonohue** [comment]
Thanks for your testing, @helix84! I was able to verify and resolve both of the issues you noted: (1) failure to remove custom browse index tables, and (2) missing author/subject indices.

I've pushed up commits that should fix both issues (at least it seems to now be working on my end).

This PR has also been rebased on the latest master.

**Comment by helix84** [comment]
+1 looks good, I re-tested and both problems seem to be fixed

**Pull request merged**
