### PR TITLE
DS-2461 Escape some colons in queries

### PR DESCRIPTION
**Pull request by aschweer**
This allows searching for titles with colons while still allowing fielded searches

### CODE REVIEW

**Comment by aschweer** [comment]
https://jira.duraspace.org/browse/DS-2461

**Comment by hardyoyo** [comment]
This is a tiny change, if you're running it in production, I don't think much review is required. We trust you.

**Comment by aschweer** [comment]
Thanks @hardyoyo -- sorry, I should have mentioned this on here too not just on the ticket, but I think this can still be improved a bit more. Not sure it should be merged now. I'll see if I can make the changes that I think would be good.

**Comment by aschweer** [comment]
I've changed the code to escape the colons in the back end. Tested locally. I'll push the button.

**Pull request merged**
