### PR TITLE
DS-2583: Quality Control Reporting via REST API (v6)

### PR DESCRIPTION
**Pull request by terrywbrady**
This is intended to resolve a rebase issue with https://github.com/DSpace/DSpace/pull/1086

https://jira.duraspace.org/browse/DS-2583

Extend the REST API to support quality control reports. 
- GET /reports - Return a list of report tools built on the rest api
- GET /reports/{nickname} - Return a redirect to a specific report
- GET /filters - Return a list of use case filters available for quality control reporting
- GET /filtered-collections - Return collections and item counts based on pre-defined filters
- GET /filtered-collections/{collection_id} - Return items and item counts for a collection based on pre-defined filters
- GET /filtered-items - Retrieve a set of items based on a metadata query and a set of filters
## GET /reports

Configured in dspace/config/modules/rest.cfg

```
# return report tool html by name
#rest-report-url.collections = static/rest/index.html
#rest-report-url.item-query = static/rest/query.html
```
## GET /filters

Configured in dspace/config/modules/rest.cfg.  
These filters are referenced in the other reporting actions.
Each of these classes contains an enumerated list of useful ways to filter DSpace items.

```
# configurable filters for filter-collections and filtered-items
plugin.sequence.org.dspace.rest.filter.ItemFilterList = \
        org.dspace.rest.filter.ItemFilterDefs,\
        org.dspace.rest.filter.ItemFilterDefsMisc,\
        org.dspace.rest.filter.ItemFilterDefsPerm
```
## Sample Reporting Application

The following JavaScript application illustrates how these new REST actions can provide quality control reporting to repository managers.

https://wiki.duraspace.org/display/DSDOC6x/REST+Reports+-+Summary+of+API+Calls

### CODE REVIEW

**Comment by hardyoyo** [comment]
+1 I've tested this branch out in Vagrant-DSpace, the demo reports work well. The interface is enjoyable, I would like to have this in production, as this is a tool I think our repository managers would really appreciate.

**Comment by hardyoyo** [comment]
There has been much more comment on this work in the original PR #1086, my reading of the comments on that PR is that this work was ready for a final test. From the looks of things in my test environment, everything works as intended. I think this is ready for merging.

**Comment by tdonohue** [comment]
Thanks for getting this moved forward! 

One sidenote here... Unfortunately in #1104, I'm going to need to rename nearly *all* of the new configurations added in this PR (I should have noticed it sooner). The naming convention used in this PR was to prepend everything with `rest-*`, while in #1104, everything gets prepended with `rest.*`.  So, any documentation regarding this PR will need to be updated with the new configuration names, as soon as #1104 is merged.

**Comment by terrywbrady** [comment]
Updated reference to wiki pages: https://wiki.duraspace.org/display/DSDOC6x/REST+Reports+-+Summary+of+API+Calls

**Pull request merged**
