### PR TITLE
DS-3643: Use correct license on ingest

### LINKED ISSUE #6992: [DS-3643] Ingest adds empty license file for collections using the default license
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3643">[DS-3643]</a> created by sulfrian</i>
<p>On ingest the packager will add a license, if the package does not contain a license bundle. The packager will use the license of the collection, even if the collection is using the repository default license. It will simply add an empty license file and does not fall back for the global default license.</p>

### PR DESCRIPTION
**Pull request by AlexanderS**
https://jira.duraspace.org/browse/DS-3643
Fixes #6992

### CODE REVIEW

**Comment by pnbecker** [comment]
@alexanderS Can you please provide some more context? What is the problem and how can it be reproduced?

If I understand the jira issue correctly there is a problem with the license files while ingesting content into DSpace using the packager cli. Right? Will DSpace fall back to the default.license without/with your patch? Will it use a collection license without/with your patch?

**Comment by AlexanderS** [comment]
@pnbecker You can reproduce the issue, if you ingesting an item without a license using the cli. The target collection should not have a license (so the default license should be used). Without this patch an empty license is created and the default.license is not used.

**Review by tdonohue — APPROVED** [review]
👍 Looks obvious to me, once you look at the implementation of the two methods.

Here's the method that was being used: `collection.getLicenseCollection();` https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/content/Collection.java#L238

And here's the correct method: https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java#L524

**Review by pnbecker — APPROVED** [review]
+1 (not tested, just reviewed)

**Review by toniprieto — APPROVED** [review]
:+1: Tested using the packager utility, it uses the correct license now. Thanks!

**Comment by tdonohue** [comment]
Merging...approved & tested and passes all tests.  Thanks @AlexanderS !

**Pull request merged**
