### PR TITLE
[DS-3286] Remove clearCache() and allow uncacheEntity() on specific objects

### PR DESCRIPTION
**Pull request by terrywbrady**
Rather than working around the risks of calling clearCache() allow the user to manage the presence of specific objects within the cache.

I want to get some feedback on this approach to the issue.

I have tested this with a small database instance.  I plan to test this with a very large instance.

### CODE REVIEW

**Comment by terrywbrady** [comment]
Includes code from https://github.com/DSpace/DSpace/pull/1469 in order to demonstrate removal of items from cache

**Comment by terrywbrady** [comment]
I tested with a larger database instance and the process seems to be able to index thousands of items without running out of memory.

**Comment by cwilper** [comment]
The idea behind removing specific entities from the cache seems reasonable. I don't think the communities/collections should really take that much space in the cache, but it depends on the site I suppose. Did OOM go away after making the addition evict calls?

**Comment by terrywbrady** [comment]
@cwilper , thanks for taking a look at this.  I will be posting another commit to clean up some of the comments.

I reran my test with the latest commit and it succeeded.  I also explicitly set a -xmX memory declaration to match my cron.  I am uncertain if the latest commit is essential or if my original test had insufficient resources.  

I have an index process running against my full repo.  The repo has 500,000 items so it will take much of the day to complete.  Hopefully it will not run out of memory.  I will post back with results.

**Comment by terrywbrady** [comment]
The process has successfully reindexed 200,000 items without a memory error.  Removing work in progress.

**Comment by tdonohue** [comment]
+1 via code review.  I like this idea much better than the old way of calling `clearCache()` (which had some serious issues with recursion, as noted in comments of https://jira.duraspace.org/browse/DS-3286)

**Comment by hardyoyo** [comment]
+1 via code review

**Comment by mwoodiupui** [comment]
+1 by inspection.  It make much more sense to only invalidate cache content that we know is garbage.

**Comment by tdonohue** [comment]
Just tested this locally (on a much smaller test dspace site) and it works without any issues.

**Pull request merged**
