### PR TITLE
[DS-3788] drop indexes, update, recreate

### PR DESCRIPTION
**Pull request by kardeiz**
Fixes https://jira.duraspace.org/projects/DS/issues/DS-3788

### CODE REVIEW

**Review by terrywbrady — APPROVED** [review]
I do not have an Oracle instance available, so I am unable to test this change.  The code looks correct to me.

**Comment by mwoodiupui** [comment]
This addresses the problem:  'Flyway migration "Hibernate Workflow Migration" fails'

**Review by mwoodiupui — APPROVED** [review]
Looks right.  Migration performed successfully.

**Comment by tdonohue** [comment]
Note: while I generally think this PR is "looking good", we've just had a second Oracle Migration ticket created which notes possible further issues with Oracle indexes: https://jira.duraspace.org/browse/DS-3829

So, I'd recommend we *pause* this PR briefly to get more info on 3829. If the two issues are closely related, we may want to split these changes out into a new migration that runs pre-6.0 migrations, or similar.

**Comment by tdonohue** [comment]
Regarding my previous comment of putting this PR on "pause", I now think it can move forward.  From what I've seen from ticket DS-3829 and its PR (#1954), that work seems only tangentially related to this one.  

So, I think this is good to move forward. 

However, as this PR changes an existing SQL migration, we need to be aware that anyone who previously ran this migration (i.e. 6.x Sites on Oracle + XML Workflow) will need to run a `dspace database repair` after the next upgrade.  The reason is that changing a SQL migration changes the checksum of this file, and Flyway will through validation errors (and a `repair` tells Flyway that this change is expected and to accept the new checksum).  So, that is a minor documentation need out of this ticket.

**Pull request merged**
