### PR TITLE
DS-3697: Enable autowiring of DSpace Services in the Spring REST webapp

### PR DESCRIPTION
**Pull request by tomdesair**
This is a fix for https://jira.duraspace.org/browse/DS-3697

### CODE REVIEW

**Comment by abollini** [comment]
Are we saying that the Factories should be used only in class not initialized by Spring? in the very long run do we want to remove the factory and rely only on autowiring? if so, I'm perfectly fine with that.

**Comment by tomdesair** [comment]
Yes I've discussed this with @KevinVdV and we think that the Factories should only be used in non-Spring beans. What do you think @tdonohue ?

@abollini Can you double check/test that this PR doesn't break the Spring Boot web app?

**Comment by tdonohue** [comment]
@tomdesair : I'm in favor of moving towards autowiring things where we can do so (as that aligns us better with the "Spring-way"). So, this approach seems good to me, and if everything ends up being autowired then (as @abollini notes we can get rid of the factories)

**Comment by mwoodiupui** [comment]
Let me add my concurrence with using injection rather than factories wherever we can.  'new ThingFactory().getInstance().getThingService()' is too ugly for words, even after you recall which Factory creates the Service that you want.

**Comment by abollini** [comment]
I want to check (and merge) that tomorrow. Can you please cleanup the PR as it looks to include many unnecessary formatting changes (generic impor of full packages, reordering of imports/methods). This make a bit difficult to immediately recognize the real changes

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me.  I agree with @abollini's point that the number of minor formatting tweaks (likely by an IDE) are distracting.  But, if it's significant effort to cleanup, I'm OK with letting this in as-is.

**Comment by mwoodiupui** [comment]
Aside:  I try to remember to do formatting cleanup in a separate commit, then do the work.

It appears that different IDEs have different notions of the proper ordering of imports.

**Comment by abollini** [comment]
**The PR cannot be merged as the webapp fails** to start with the following error

> Caused by: java.lang.RuntimeException: Failure during SpringApplicationBuilder configuration: DSpace home directory could not be determined. It MUST include a subpath of '\config\config-definition.xml'. Please consider setting the 'dspace.dir' system property or ensure the dspace-api.jar is being run from [dspace]/lib/.
> 	at org.dspace.app.rest.Application.configure(Application.java:104)

The issue is mostly due to the dspace.home configuration property that look like as not yet injected in the dspaceHome attribute at the time that configure method is trigged. This is why now the DSpace kernel is instantiated "later" in the contextInitializer method https://github.com/DSpace/DSpace/blob/master/dspace-spring-rest/src/main/java/org/dspace/app/rest/Application.java#L84

If you use ENV variable to set the dspace.home you will not hit the issue but, obviously we cannot always force the use of this strategy as this will prevent to run multiple dspace instances on the same server

**Review by abollini — CHANGES_REQUESTED** [review]
See my previous comment.

**Comment by abollini** [comment]
As said in my first comment, I'm in favour of the idea driven by this PR. Other than the specific issue reported above that need to be solved before to merge I want to be sure that all us are aware of the big change that this imply.
Right now all the dspace webapps have two separated spring context, the one held by the kernel and the one of the webapplication (eventually hierarchical as spring mvc create it own subcontext for the controller mapping). The webapplication context is linked to the kernel context thanks to the DSpace class that retrieve some selected beans from the kernel context and re-register these beans also in the webapplication context.
Having a single context we will be able to autowire and access all the beans in the kernel context directly and I don't see any specific issue with that, the glitches could be:
- we could have name collision between spring bean defined in the webapp and in the kernel 
- the single context approach will be followed only by the new REST webapp making the old webapps (sword, oai) a bit more peculiar... but we have the plan to merge all the webapps in the long run in a single one

**Comment by mwoodiupui** [comment]
Are there any issues with running the commandline tools in a WebApplicationContext rather than a plain ApplicationContext?

**Comment by mwoodiupui** [comment]
The actual configuration parameter seems to be "dspace.dir".  This name is manifested in the constant named org.dspace.servicemanager.config.DSpaceConfigurationService.DSPACE_HOME and is used there and in the configuration service.

DSpaceKernelServletContextListener looks for this name in JNDI and then in the Servlet context init-parameters.

DSpaceConfigurationService looks for it as a system property, then whatever it may have been given by the ContextListener if it was called, then tries '~/dspace/', '~', and '/'.

The system property works for commandline, but by itself is a poor choice for a webapp because it is shared by multiple instances if you have them.  JNDI works in commandline and servlet contexts, but is cumbersome for commandline.  Context parameters only work for servlets.  The process environment (as noted above) has the same problem as system properties.

What problems would we face if we move the above logic into the root Spring context, and let the result be injected wherever it is wanted, including the ConfigurationService?

**Comment by tomdesair** [comment]
I've moved the DSpace Kernel startup back to the Servlet Context Initialisation phase. After startup, I set the Kernel context as a parent of the Spring Boot context manually. 

@abollini, this should allow you to start the application even without environment or process variable. Can you please retest?

I've also tried to revert as much of the imports as possible.

**Comment by abollini** [comment]
hi @tomdesair  thanks for the extra effort to cleanup the import statements.
I will test the PR in my return flight from Argentina so I should be able to report on that on Friday.

@mwoodiupui I'm sorry but I haven't understand your questions, can you elaborate?

> Are there any issues with running the commandline tools in a WebApplicationContext rather than a plain ApplicationContext?

why should we  do that?

> What problems would we face if we move the above logic into the root Spring context, and let the result be injected wherever it is wanted, including the ConfigurationService? We still have to account for the possibility that we are in webapp. context and may have been given an init-parameter.

which is the root Spring context that you refer here?

**Comment by mwoodiupui** [comment]
I had understood comments above to mean that we should merge the various ApplicationContext instances into one.  But then, since we use features of WebApplicationContext, that single instance would have to be a WebApplicationContext.  This would mean that bin/dspace would be running in a WebApplicationContext, outside of a Servlet environment.

Up to now, we've had a root ApplicationContext and, in the webapp.s, a child WebApplicationContext.  The WebApplicationContext refers to its parent ApplicationContext for objects not defined to itself. I'm told that this is a common pattern in Spring webapp.s.

My point is that we must care for both Servlet and non-Servlet usage, because the same dspace-api supports both.

**Comment by abollini** [comment]
Thanks to clarify @mwoodiupui . It is not an issue as we are trying here to have the webapp to store and lookup the beans directly in the existent kernel spring context (setup in the usual way that work also from the cmd line). The latest commits from @tomdesair looks better as the webapp spring context should be seen as a children of the kernel context solving also my concerns about potential name collision. I'm going to test to verify that it works as expected

**Comment by tomdesair** [comment]
> Up to now, we've had a root ApplicationContext and, in the webapp.s, a child WebApplicationContext. The WebApplicationContext refers to its parent ApplicationContext for objects not defined to itself. I'm told that this is a common pattern in Spring webapp.s.

With this PR, this should also become the case for the Spring Boot REST web app.

**Comment by tdonohue** [comment]
In today's DSpace 7 meeting we discussed this. @mwoodiupui said his concerns seem to be addressed. So, this sounds like it can move forward, as soon as @abollini is OK with it (currently he has an outstanding request for changes that is blocking merger of this PR).

**Review by abollini — APPROVED** [review]

**Pull request merged**
