### PR TITLE
DS-3445 Only add "ResultCode" if not default

### PR DESCRIPTION
**Pull request by jonas-atmire**
JIRA ticket
https://jira.duraspace.org/projects/DS/issues/DS-3445
Only try to search for the "ChecksumResultCode" enum if the resultCode string is not default.
Avoiding breaking enum search

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 Code looks good to me. I'd request someone else give it a quick test run.  

@hardyoyo, would you be able to quickly test this fix, since you opened DS-3445?

**Comment by kshepherd** [comment]
I've tested this successfully. Reproduced the error in master and 6_x, and the error is not encountered when building against this pull request.

**Comment by hardyoyo** [comment]
I have also tested this sucessfully, and have confirmed that it fixes the error. +1

**Comment by tdonohue** [comment]
@hardyoyo : thanks for merging...could you please also ensure it is cherry-picked to `master`?

**Comment by hardyoyo** [comment]
@tdonohue alas, I cannot... when I try to push to upstream master, I get the following error:

` ! [remote rejected] master -> master (protected branch hook declined)`

**Comment by hardyoyo** [comment]
I will make a new PR instead

**Comment by tdonohue** [comment]
Thanks @hardyoyo

**Comment by hardyoyo** [comment]
see #1620

**Pull request merged**
