### PR TITLE
DS-3448 Multi-select in submission for workflow and workspace items

### PR DESCRIPTION
**Pull request by jonas-atmire**
Pull request for JIRA ticket
https://jira.duraspace.org/projects/DS/issues/DS-3448

See description for functionality overview

### CODE REVIEW

**Review by bram-atmire — APPROVED** [review]
+1 Should be merged when reviewed by a non-atmire committer

**Comment by tdonohue** [comment]
The idea here seems great to me. However, I'd want to verify that selectboxes work normally with Javascript disabled?  Based on the code, my guess is they should.

**Comment by jonas-atmire** [comment]
The checkboxes do work with javascript disabled as this is only a html element.
But, obviously the actual functionality will not work as this requires javascript, but neither will half of DSpace, so I don't think that would be a problem.

**Comment by tdonohue** [comment]
👍

**Pull request merged**
