### PR TITLE
[DS-3895] Bitstream size can't be referenced in HQL queries

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://jira.duraspace.org/browse/DS-3895
All automated tests succeed.

### CODE REVIEW

**Comment by mwoodiupui** [comment]
Something strange happened to Travis.  BitstreamServiceImpl doesn't contain the string "getSize", and that line is calling Bitstream.getFormat().  I've restarted the build.  I'm sure that I built this code locally, without the noted error.  Will build it again.

**Comment by mwoodiupui** [comment]
I checked my local source tree:  it is in sync. with GitHub, and on the DS-3895-6x branch.  Here, the code builds without error and all tests pass.  Travis rebuilt it and got the same nonsensical error at the same place.  ???

**Comment by mwoodiupui** [comment]
Aha, I had a stale version of dspace-6_x.  Upstream has a new method in BitstreamServiceImpl that uses getSize().  Rebased, testing now.

**Comment by mwoodiupui** [comment]
...aaaand now I've actually committed the update.

**Review by tdonohue — APPROVED** [review]
👍 Obvious fix, looks correct to me & tests all pass!

**Review by pnbecker — APPROVED** [review]
:+1:

**Pull request merged**
