### PR TITLE
DS-2539: REST: Export Metadata Schema and Field Registries

### PR DESCRIPTION
**Pull request by terrywbrady**
https://jira.duraspace.org/browse/DS-2539

Export the DSpace Metadata Schema and Field Registries.

This exported file can be used in conjunction with the FileAnalyzer to validate metadata field while generating DSpace Ingest Folders.

https://github.com/Georgetown-University-Libraries/File-Analyzer/wiki/Create-Ingest-Folders-for-a-Set-of-Files

The FileAnalyzer is a desktop application containing a number of automation tasks for library and digitization projects. A set of DSpace related tasks are included in the code base.

### CODE REVIEW

**Comment by helix84** [comment]
+1, tested

I ran this and it's good to merge as-is. Documentation would be a trivial change.

Terry, would you like to extend this endpoint with additional POST/PUT/DELETE verbs? They may come in as an additional PR.

**Comment by helix84** [comment]
Maybe one more thing - since we have both fileformat and metadata registries, it might make more sense to change the endpoint to /registries/metadata.

**Comment by terrywbrady** [comment]
@helix84, I concur with your endpoint recommendation.

I will be glad to provide code for the POST/PUT/DELETE after I upgrade to DSpace 5.  Looking at the REST differences between DSpace 4&5, it looks like the REST code in DSpace 5 provides a convention to follow for those verbs.

**Comment by terrywbrady** [comment]
I have added the POST/PUT/DELETE methods into this PR

**Comment by terrywbrady** [comment]
@helix84 , updated with your recommended changes

**Comment by terrywbrady** [comment]
Closing since this work is contained in DS-2583

**Pull request closed without merging**
