### PR TITLE
Setting access condition to "administrator" won't restrict access to the file after archival

### PR DESCRIPTION
**Pull request by KevinVdV**
## Description
Setting a file to "administrator" access condition during submission will still lead to the file being public after archival. 

## Instructions for Reviewers

* Start a new submission
* Upload a file
* Click on edit
* Change the “Access condition type” to “administrator”
* Save the file changes
* Finish the submission & archive the item

The file should now be private

List of changes in this PR:
* Change in the backend to ALSO check for custom permissions before applying the default collection permissions.
* Test to prove that it works. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by abollini** [comment]
hi,
I was not able to find references but I'm pretty sure that this aspect were discussed when the dspace 7 submission implementation was provided. This is what I remember and what I still suggest to adopt to solve this issue
- if a collection enable an embargo step (or better the option to restrict the permission during the submission) the default bitstream read of the collection should be setup in a consistent way or completely removed
- the default permissions set at the collection level should be always added to the item

In this way it is possible to setup the collection to always add some special permissions (like a READ policy for a group linked to a special IP used by an harvester / deep archive robot / etc) or maintain the basic configuration for open access collection where the embargo step is not used.

Alternatively, we should limit the special treatment only to the READ Anonymous group a minimal change to this PR should be required to do that and the test will demonstrate that this alternative approach resolve as well the problematic scenario reported in the issue

**Comment by tdonohue** [comment]
@abollini : I'm not sure I understand your review on this PR.  Could you add inline notes with your recommended approach?

From what I can see, this scenario is not about an embargo or Collection-inherited permissions...it's about the `administrator` access condition, which allows you to "permanently" restrict the file to the Administrator group. 

So, it's not an embargo, and it obviously should also override any Collection default READ permissions. Based on my quick look at the code & the ITs in this PR, the current implementation "seems reasonable" (but I haven't tested it yet).  I'm not quite understanding what your concerns seem to be.

**Review by tdonohue — APPROVED** [review]
👍 I've verified the bug on `main` & that this PR fixes the issue.  Thanks @KevinVdV !

On `main`, when selecting the `administrator` access condition, two policies are added to the Bitstream:
1. The `administrator` access condition policy, which is of `type=TYPE_CUSTOM`, `action=READ` and `group=Administrator.
2. The default Collection policy, which for my test was of `type=TYPE_INHERITED`, `action=READ` and `group=Anonymous`.

Because those two policies exist on the Bitstream, the Anonymous policy will override the Administrator one, making the Bitstream publicly accessible.

After installing this PR (and as proven in ITs), the default Collection policy is _not added_ if (and only if) the Item already has an existing `type=TYPE_CUSTOM` policy with the **same** `action`.  So, in the above example, it sees there's already a `TYPE_CUSTOM`, `READ` policy on the Item. Therefore, default permissions from the Collection are NOT inherited. This allows for the `administrator` access condition to override the default Collection READ permissions.

All in all, this looks good to me.  @abollini I'll leave this open for a day or so for you to respond to my prior question about your possible concerns.  After that, I'll go ahead and merge it & we can clean things up further in 7.2 if necessary.

**Comment by tdonohue** [comment]
@abollini : How would you resolve this bug then?  To clarify, this bug exists in a default configuration of DSpace. The `administrator` option does not work out-of-the-box, on a normal Collection (with no special permissions assigned) -- this means it's a minor security issue because restricting a Bitstream to `administrator` will result in a public Bitstream.

At this point, I'd recommend we resolve the security issue in 7.1 (by merging this PR) and rework it in 7.2 (to better align with the use case you describe), unless you have a more immediate solution to how both options can be fixed in 7.1

**Pull request merged**
