### PR TITLE
Fix metadata value move patch operation bugs

### PR DESCRIPTION
**Pull request by ybnd**
## Description

We fixed some issues that arose when rearranging metadata in DSOs using a drag-and-drop interface in Angular

#### Changes

* In certain situations, `ObjectUpdatesService.getMoveOperations` can interpret a single move operation as an equivalent sequence of operations; e.g. [4→1] becomes [1→2, 1→3, 2→4, 3→1]

* `DSpaceObjectServiceImpl.moveMetadata` couldn't handle multiple move operations in a single PATCH request because it assumed that the _order_ of metadata values in `getMetadata` is correct, which wasn't the case due to caching.

  We fixed this by explicitly re-sorting the cached metadata list by `getPlace`

* Added some ITs to cover PATCH operations to *DSO metadata* as `PatchMetadataIT` used to only cover `/submission` patch requests.

  `PatchMetadataIT.moveMetadataAuthorFourToOneMultiOpTest` is expected to fail at first in order to demonstrate that we fix it with the subsequent commit

  

## Checklist

_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
Thanks @ybnd!  Reviewed the code and the detailed tests, and they both look great. The tests do a great job of proving moves result in the correct ordering.

The strange thing is that I'm having difficulty testing this in the UI (to verify the fix fully).  It seems like the Submission UI's author field drag & drop reorder isn't working properly at the moment (with or without this PR).  Is this supposed to affect the Submission UI's author field? Or is there some other way to test this from the UI?

Overall, I'll approve this as it **looks correct**.  I'm just finding it difficult to verify & test from the UI, and I'd like to verify it works there before merging.

**Comment by ybnd** [comment]
@tdonohue This shouldn't affect the submission UI, only regular DSO endpoints. AFAIK there is no way to test this with the base DSpace UI as of yet, we stumbled upon this problem when working on a custom UI feature.

@Raf-atmire Maybe we could assign someone from Atmire to also review it ~ the actual client frontend in question?

**Comment by Raf-atmire** [comment]
@tdonohue The submission UI uses a different patch operation than the one we've fixed here, so it can't be tested with that I'm afraid. I'm not actually sure if there's a default way to test this in the UI, it should be the default way of moving metadatavalues between places.

**Comment by tdonohue** [comment]
Thanks @Raf-atmire and @ybnd for verifying that this cannot really be tested from the UI at this time.  Since that's the case, this looks good to me. The ITs here prove that it works (and I've checked that the ITs look correct).  So, I'll go ahead and merge this.  If we find later issues we can clean them up in a later PR.

**Pull request merged**
