### PR TITLE
DS-2315: export Simple Archive Format without bitstreams

### PR DESCRIPTION
**Pull request by kohts**
Replacement for https://github.com/DSpace/DSpace/pull/760

https://jira.duraspace.org/browse/DS-2315

### CODE REVIEW

**Comment by pnbecker** [comment]
This PR is just a new clean PR of #760. #760 was reviewed by helix84 in November 2014 and mhwood in June 2015. @kohts rebase his PR against the service API.

I think we should add another small review and test as the service API is a major change. Nevertheless the original PR of course existed before our PR deadline for DSpace 6.0.

**Comment by kohts** [comment]
This one has been tested and I confirm it works as expected.

The only thing it needs to make sense is DS-2844; to be more specific, one index from it
-- CREATE INDEX metadatavalue_object on metadatavalue(dspace_object_id)

Without this index whole export (either with -x or without it) takes much more time,
than expected because of slow Postgres (this is not really an individual issue
of this PR, but rather a problem for a lot of other places).

Please merge.

**Comment by helix84** [comment]
+1, I re-tested the PR and it still works fine after the migration to service api.

I'd have one minor request tangential to this PR - please include item handle in the message:
Exporting Item 19474d60-9dba-47ea-b8d2-a5a7e6bf43b5 to /tmp/export/69

https://github.com/DSpace/DSpace/blob/master/dspace-api/src/main/java/org/dspace/app/itemexport/ItemExportServiceImpl.java#L125

**Comment by kohts** [comment]
Added logging of item handle during export.

**Pull request merged**
