### PR TITLE
Fix authentication problem in SwordV2 implementation (DS-3310).

### PR DESCRIPTION
**Pull request by wgresshoff**
Reimplemented the getBundles(String name) in the Item class and fixed the SwordAuthenticator accordingly.

### CODE REVIEW

**Comment by tdonohue** [comment]
👍 This refactor looks reasonable to me. However, it's unclear to me the extent that it has been tested.  @wgresshoff does this simple refactor fix the authentication errors you were seeing?

**Comment by wgresshoff** [comment]
I only tested the integration between Archivematica and DSpace, so only the method canSubmitTo(SwordContext swordContext, Item item) was tested. Don't know under which circumstances the other methods are called do to proper testing.
I simply reimplemented the array based approach of DSpace 5.x with the collection classes approach after the refactoring.

**Review by tdonohue — APPROVED** [review]
👍 While this PR is messy (lots of unnecessary code realignment), the basic changes (which is simply adding a new `item.getBundles(name)` method) seem quite reasonable.  If we merge this, we'd likely need to make a new PR for `master` as the code realignment in this PR is not in line with our new Code Style.

**Review by kshepherd — APPROVED** [review]
+1 if this just reverts behaviour back to 5.x, and changes look OK -- I agree some commits look a little messy but the spacing/indent changes are actually positive overall, eg 5-space intends to 4-space to match rest of code, realigning multiline method parameters etc so it does help clean up 6.x a bit at least (and we know it'll need refactoring for 7 anyway)

**Pull request merged**
