### PR TITLE
fix migration problem from 6.1 to 7.0

### PR DESCRIPTION
**Pull request by corrad82-4s**
## Description
Short summary of changes (1-2 sentences).

We encountered problems while migrating from versions 6.1+ to 7.x in migrating workflow items. 
The problem was related to flyway not executing script `V6_0_2015_09_01__DS_2701_Enable_XMLWorkflow_Migration` as it was considered as already executed. 
We added an extension of this script, with 6.99 as version number, so that, despite of which is 6 minor version, the existence of `cwf_workflowitem` table is always checked during migration

List of changes in this PR:
* added `org.dspace.storage.rdbms.xmlworkflow.V6_99_2021_10_21__Enable_XMLWorkflow_Migration` wrapping class

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@corrad82-4s : Could you provide more information about how this bug can be reproduced?

It doesn't make sense to me how this migration would be skipped if you are upgrading using the `./dspace database migrate ignored` command in the Upgrade docs.

What was the state/status of the Flyway migration `V6_0_2015_09_01__DS_2701_Enable_XMLWorkflow_Migration` on the database where you encountered this issue?  Was it "Ignored" or "Out of Order" or something else?

I'm not against this PR overall, but I don't understand the reason why this migration could have not already been executed.  So, I'd like to better understand that reason before we merge this... If the original migration is flawed, then we obviously don't want to reproduce that problem simply by copying this migration again to `V6_99...`.

**Comment by corrad82-4s** [comment]
@tdonohue thank you for your message, I'll try to share further information

We started from a 6.1 with this database situation

```
+----------------+-----------------------------------------------------+---------------------+---------+
| Version        | Description                                         | Installed on        | State   |
+----------------+-----------------------------------------------------+---------------------+---------+
| 1              | << Flyway Baseline >>                               | 2017-05-12 13:13:55 | Baselin |
| 1.1            | Initial DSpace 1.1 database schema                  | 2017-05-12 13:13:55 | Success |
| 1.2            | Upgrade to DSpace 1.2 schema                        | 2017-05-12 13:13:55 | Success |
| 1.3            | Upgrade to DSpace 1.3 schema                        | 2017-05-12 13:13:55 | Success |
| 1.3.9          | Drop constraint for DSpace 1 4 schema               | 2017-05-12 13:13:55 | Success |
| 1.4            | Upgrade to DSpace 1.4 schema                        | 2017-05-12 13:13:55 | Success |
| 1.5            | Upgrade to DSpace 1.5 schema                        | 2017-05-12 13:13:56 | Success |
| 1.5.9          | Drop constraint for DSpace 1 6 schema               | 2017-05-12 13:13:56 | Success |
| 1.6            | Upgrade to DSpace 1.6 schema                        | 2017-05-12 13:13:56 | Success |
| 1.7            | Upgrade to DSpace 1.7 schema                        | 2017-05-12 13:13:56 | Success |
| 1.8            | Upgrade to DSpace 1.8 schema                        | 2017-05-12 13:13:56 | Success |
| 3.0            | Upgrade to DSpace 3.x schema                        | 2017-05-12 13:13:56 | Success |
| 4.0            | Upgrade to DSpace 4.x schema                        | 2017-05-12 13:13:56 | Success |
| 4.9.2015.10.26 | DS-2818 registry update                             | 2017-05-12 13:13:56 | Success |
| 5.0.2014.08.08 | DS-1945 Helpdesk Request a Copy                     | 2017-05-12 13:13:56 | Success |
| 5.0.2014.09.25 | DS 1582 Metadata For All Objects drop constraint    | 2017-05-12 13:13:56 | Success |
| 5.0.2014.09.26 | DS-1582 Metadata For All Objects                    | 2017-05-12 13:13:56 | Success |
| 5.6.2016.08.23 | DS-3097                                             | 2017-05-12 13:13:56 | Success |
| 5.7.2017.04.11 | DS-3563 Index metadatavalue resource type id column |                     | Ignored |
| 5.7.2017.05.05 | DS 3431 Add Policies for BasicWorkflow              |                     | Ignored |
| 6.0.2015.03.06 | DS 2701 Dso Uuid Migration                          | 2017-05-12 13:13:56 | Success |
| 6.0.2015.03.07 | DS-2701 Hibernate migration                         | 2017-05-12 13:13:56 | Success |
| 6.0.2015.08.31 | DS 2701 Hibernate Workflow Migration                | 2017-05-12 13:13:56 | Success |
| 6.0.2016.01.03 | DS-3024                                             | 2017-05-12 13:13:56 | Success |
| 6.0.2016.01.26 | DS 2188 Remove DBMS Browse Tables                   | 2017-05-12 13:13:56 | Success |
| 6.0.2016.02.25 | DS-3004-slow-searching-as-admin                     | 2017-05-12 13:13:56 | Success |
| 6.0.2016.04.01 | DS-1955 Increase embargo reason                     | 2017-05-12 13:13:57 | Success |
| 6.0.2016.04.04 | DS-3086-OAI-Performance-fix                         | 2017-05-12 13:13:57 | Success |
| 6.0.2016.04.14 | DS-3125-fix-bundle-bitstream-delete-rights          | 2017-05-12 13:13:57 | Success |
| 6.0.2016.05.10 | DS-3168-fix-requestitem item id column              | 2017-05-12 13:13:57 | Success |
| 6.0.2016.07.21 | DS-2775                                             | 2017-05-12 13:13:57 | Success |
| 6.0.2016.07.26 | DS-3277 fix handle assignment                       | 2017-05-12 13:13:57 | Success |
| 6.0.2016.08.23 | DS-3097                                             | 2017-05-12 13:13:57 | Success |
| 6.1.2017.01.03 | DS 3431 Add Policies for BasicWorkflow              | 2017-11-07 22:11:44 | Success |
+----------------+-----------------------------------------------------+---------------------+---------+
```

When version was migrated, script  `6.0.2015.09.01` was `Ignored`
```
| Versioned | 5.7.2017.04.11  | DS-3563 Index metadatavalue resource type id column              | SQL      |                     | Ignored  |
| Versioned | 5.7.2017.05.05  | DS 3431 Add Policies for BasicWorkflow                           | JDBC     |                     | Ignored  |
| Versioned | 6.0.2015.09.01  | DS 2701 Enable XMLWorkflow Migration                             | JDBC     |                     | Ignored  |```

while our version run with success

```+-----------+-----------------+------------------------------------------------------------------+----------+---------------------+----------+
| Category  | Version         | Description                                                      | Type     | Installed On        | State    |
+-----------+-----------------+------------------------------------------------------------------+----------+---------------------+----------+
|           | 1               | << Flyway Baseline >>                                            | BASELINE | 2017-05-12 13:13:55 | Baseline |
| Versioned | 1.1             | Initial DSpace 1.1 database schema                               | SQL      | 2017-05-12 13:13:55 | Success  |
| Versioned | 1.2             | Upgrade to DSpace 1.2 schema                                     | SQL      | 2017-05-12 13:13:55 | Success  |
| Versioned | 1.3             | Upgrade to DSpace 1.3 schema                                     | SQL      | 2017-05-12 13:13:55 | Success  |
| Versioned | 1.3.9           | Drop constraint for DSpace 1 4 schema                            | JDBC     | 2017-05-12 13:13:55 | Success  |
| Versioned | 1.4             | Upgrade to DSpace 1.4 schema                                     | SQL      | 2017-05-12 13:13:55 | Success  |
| Versioned | 1.5             | Upgrade to DSpace 1.5 schema                                     | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 1.5.9           | Drop constraint for DSpace 1 6 schema                            | JDBC     | 2017-05-12 13:13:56 | Success  |
| Versioned | 1.6             | Upgrade to DSpace 1.6 schema                                     | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 1.7             | Upgrade to DSpace 1.7 schema                                     | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 1.8             | Upgrade to DSpace 1.8 schema                                     | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 3.0             | Upgrade to DSpace 3.x schema                                     | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 4.0             | Upgrade to DSpace 4.x schema                                     | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 4.9.2015.10.26  | DS-2818 registry update                                          | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 5.0.2014.08.08  | DS-1945 Helpdesk Request a Copy                                  | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 5.0.2014.09.25  | DS 1582 Metadata For All Objects drop constraint                 | JDBC     | 2017-05-12 13:13:56 | Success  |
| Versioned | 5.0.2014.09.26  | DS-1582 Metadata For All Objects                                 | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 5.6.2016.08.23  | DS-3097                                                          | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 6.0.2015.03.06  | DS 2701 Dso Uuid Migration                                       | JDBC     | 2017-05-12 13:13:56 | Success  |
| Versioned | 6.0.2015.03.07  | DS-2701 Hibernate migration                                      | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 6.0.2015.08.31  | DS 2701 Hibernate Workflow Migration                             | JDBC     | 2017-05-12 13:13:56 | Success  |
| Versioned | 6.0.2016.01.03  | DS-3024                                                          | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 6.0.2016.01.26  | DS 2188 Remove DBMS Browse Tables                                | JDBC     | 2017-05-12 13:13:56 | Success  |
| Versioned | 6.0.2016.02.25  | DS-3004-slow-searching-as-admin                                  | SQL      | 2017-05-12 13:13:56 | Success  |
| Versioned | 6.0.2016.04.01  | DS-1955 Increase embargo reason                                  | SQL      | 2017-05-12 13:13:57 | Success  |
| Versioned | 6.0.2016.04.04  | DS-3086-OAI-Performance-fix                                      | SQL      | 2017-05-12 13:13:57 | Success  |
| Versioned | 6.0.2016.04.14  | DS-3125-fix-bundle-bitstream-delete-rights                       | SQL      | 2017-05-12 13:13:57 | Success  |
| Versioned | 6.0.2016.05.10  | DS-3168-fix-requestitem item id column                           | SQL      | 2017-05-12 13:13:57 | Success  |
| Versioned | 6.0.2016.07.21  | DS-2775                                                          | SQL      | 2017-05-12 13:13:57 | Success  |
| Versioned | 6.0.2016.07.26  | DS-3277 fix handle assignment                                    | SQL      | 2017-05-12 13:13:57 | Success  |
| Versioned | 6.0.2016.08.23  | DS-3097                                                          | SQL      | 2017-05-12 13:13:57 | Success  |
| Versioned | 6.1.2017.01.03  | DS 3431 Add Policies for BasicWorkflow                           | JDBC     | 2017-11-07 22:11:44 | Success  |
| Versioned | 6.99.2021.10.21 | Enable XMLWorkflow Migration                                     | JDBC     | 2022-10-21 12:20:33 | Success  |
| Versioned | 7.0.2017.10.12  | DS-3542-stateless-sessions                                       | SQL      | 2022-10-21 12:20:35 | Success  |
```
Fixing the issue with `./dspace database migrate ignored` command would not work because other ignored (`5.7.2017.04.11` and `5.7.2017.05.05`) would have gone in error. 

As side note, this is not the first time we encounter this issue while migrating from a 6.1+ version to 7.x. It already did happen during another migration and we solved the problem in the same way. 
When we have encountered this issue the second time, we realized there was a structural problem.

**Comment by tdonohue** [comment]
@corrad82-4s :  I'd argue then that the problem here is really the ignored `5.7.2017.04.11` and `5.7.2017.05.05` scripts which are failing when you run `./dspace database migrate ignored`.  Without fixing those scripts or removing the `Ignored` status from those scripts, you will never be able to run `./dspace database migrate ignored` again in the future.

Therefore, I don't think this fix should be applied, as you still won't be able to run  `./dspace database migrate ignored`  without an error occurring.  A better fix here might be to find a way to allow us to *skip* older migrations (which are failing).  For example, if we had a way to run something like `./dspace database skip 5.7.2017.04.11` (which would change that script from `Ignored` to `Success`), then you'd be able to simply skip those failing scripts and run the normal `./dspace database migrate ignored` command (which is what we recommend in our [Upgrading docs](https://wiki.lyrasis.org/display/DSDOC7x/Upgrading+DSpace#UpgradingDSpace-UpgradingtheBackendSteps)) 

So, I think this PR as-is shouldn't be moved forward.  I feel it's a bad pattern as it doesn't fix the core issue, it just _temporarily works around_ it in order to allow you to run the `V6_0_2015_09_01__DS_2701_Enable_XMLWorkflow_Migration` script.

We can talk about this more in an upcoming Developer Meeting if you feel that's necessary.  But, I think there are times where it is necessary to run `./dspace database migrate ignored`... and this PR doesn't solve your issue with running that command.

**Comment by tdonohue** [comment]
@corrad82-4s : I've created an alternative PR which adds the `./dspace database skip [version]` command [that I suggested in my last comment](https://github.com/DSpace/DSpace/pull/8582#issuecomment-1346982914): #8611 

I'd recommend we consider that approach as an alternative solution to the [problem you mentioned](https://github.com/DSpace/DSpace/pull/8582#issuecomment-1346910694).

**Comment by tdonohue** [comment]
Per discussion in today's DevMtg, we are closing this as "won't fix" as #8611 fixes this same issue in a different way.  So, there's no need to duplicate this migration anymore.

**Pull request closed without merging**
