### PR TITLE
DS-2020 null check & turning _ to / in handles

### PR DESCRIPTION
**Pull request by kosarko**

### CODE REVIEW

**Comment by aschweer** [comment]
I haven't tested this, but +1 based on looking at the code.

**Comment by aschweer** [comment]
https://jira.duraspace.org/browse/DS-2020

**Comment by peterdietz** [comment]
Not tested, but code looks okay. +1

**Comment by hardyoyo** [comment]
I'll note that Tim Donohue gave the original patch a +1 a while ago, so that's +3, I'm going to merge this to master and backport this to 5_x now.

**Pull request merged**
