### PR TITLE
[DS-2778] Properly configure BasicDataSource pool

### PR DESCRIPTION
**Pull request by KevinVdV**
Removes the c3p0 config & dependency & configures the data source as before the hibernate change.

### CODE REVIEW

**Comment by hardyoyo** [comment]
@KevinVdV are you waiting for any specific testing for this change? Or is this something you are comfortable merging yourself?

**Comment by KevinVdV** [comment]
@hardyoyo I don't like to merge changes like these directly without somebody else at least testing it quickly. It are changes to the way database connections are setup, so if something works for me but not everybody else it would break the master.

**Comment by helix84** [comment]
+1, I built (using the included build.properties and -Dmaven.test.skip=false -DskipITs=false flags) this branch and took a brief look at the webapps. Database access works.

**Comment by tdonohue** [comment]
+1 tested & works. I'll merge it shortly since it has necessary votes.

**Comment by tdonohue** [comment]
After merging this, I just realized that "max.connections" seems to no longer be used, but still exists in "build.properties".  Am I correct that it should be removed, @KevinVdV ?

**Pull request merged**
