### PR TITLE
[DS-2996] Fix retrieval of hierarchical of communities from a collection

### PR DESCRIPTION
**Pull request by KevinVdV**
https://jira.duraspace.org/browse/DS-2996

The collection.getCommunities() method only retrieves direct parents, the old method used to retrieve them all. I create a new service method on community to retrieve all parent communities from a collection. All places which use this method & didn't just retrieve the first one have been altered.

### CODE REVIEW

**Comment by pnbecker** [comment]
@KevinVdV this need to be rebased.

**Comment by KevinVdV** [comment]
Rebased.

**Comment by terrywbrady** [comment]
+1, tested locally, closed https://github.com/DSpace/DSpace/issues/1414 in favor of this

**Comment by aschweer** [comment]
Code looks good, +1 after testing on XMLUI. @terrywbrady, did you test jspui or xmlui? Or both?

**Comment by terrywbrady** [comment]
@aschweer , I tested via the REST interface

**Comment by aschweer** [comment]
Thanks @terrywbrady -- ah right you tested for DS-2750 I guess. I've just tested it with JSPUI and it works as advertised there too.

**Comment by tdonohue** [comment]
+1, I also tested that this resolves both DS-2996 and DS-2766.  Merging it.

**Comment by LuizClaudioSantos** [comment]
Hi @KevinVdV , I'm sorry it is more a question than a suggestion, in the method  dspace-api/src/main/java/org/dspace/content/CommunityServiceImpl.java
```
public List<Community> getAllParents(Context context, Collection collection) throws SQLException {
 List<Community> result = new ArrayList<>();
 List<Community> communities = collection.getCommunities();
 result.addAll(communities);
 for (Community community : communities) {
 result.addAll(getAllParents(context, community));
 }
 return result;
}
```

You can get duplicated Communities in the ArrayList results, what do you think about a set? In this way you could avoid the duplicated reference to the same Community?

Best regards
Luiz

**Pull request merged**
