### PR TITLE
[DS-3694] Clean up EHCache configuration mess

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://jira.duraspace.org/browse/DS-3694

### CODE REVIEW

**Comment by mwoodiupui** [comment]
I think #1860 is unrelated, a good idea, and any collision would be easily mended.

**Comment by tdonohue** [comment]
Please rebase this PR against the latest `master` branch.  The `master` branch now requires adherence to our new Java Code Style documented at: https://wiki.duraspace.org/display/DSPACE/Code+Style+Guide

If you have any questions, feel free to ask in this PR or on our Slack: https://wiki.duraspace.org/display/DSPACE/Slack

**Review by tdonohue — APPROVED** [review]
👍 This looks good to me. I haven't tested it, but the changes seem reasonable.

**Review by kshepherd — APPROVED** [review]
+1 tested using legacy REST, all builds and works well

**Pull request merged**
