### PR TITLE
DS-2589: A validation was added in case you want to access the stats …

### PR DESCRIPTION
**Pull request by nicolasschwab**
https://jira.duraspace.org/browse/DS-2589

…of an item that does not exist and the trail of the statistics page was modified to be like this  /home/community/collection/item/Statistics , where item anchor references to the item and statistics has no target.

### CODE REVIEW

**Comment by tdonohue** [comment]
Thanks for the PR, @nicolasschwab !  At a glance, the code itself looks reasonable. 

We just need to find another developer to verify the fix works, and we'll get this added.

**Comment by nicolasschwab** [comment]
Hi Tim, i've done a successful rebase!
So the merge conflict is solved

**Comment by terrywbrady** [comment]
+1, tested locally, confirmed the update to the page name/path name.  A nice improvement.

**Comment by tdonohue** [comment]
Closing as this PR must be recreated on `dspace-6_x` branch. XMLUI has been removed from `master`. See this mailing list notice: https://groups.google.com/d/msg/dspace-devel/aEFqSn46ryM/iPRr_IMLCwAJ

**Pull request closed without merging**
