### PR TITLE
DS-2629 mediafilter addition: ExcelFilter.java

### PR DESCRIPTION
**Pull request by edgo914**
DS-2629 Add ability to filter Excel (xls and xlsx) files for full text searching

https://jira.duraspace.org/browse/DS-2629

### CODE REVIEW

**Comment by tdonohue** [comment]
+1 by inspection. Code looks good, just needs testing.

**Comment by hardyoyo** [comment]
+1 by inspection from me as well, I will try to test soon

**Comment by hardyoyo** [comment]
I can't spend much time on this, however, I did try to run a test of 989 today, and like a good tester I rebased the PR on master first. After doing so, the code refuses to compile in maven, throwing the following error:

[ERROR] /home/vagrant/dspace-src/dspace-api/src/main/java/org/dspace/app/mediafilter/ExcelFilter.java:[36,8] org.dspace.app.mediafilter.ExcelFilter is not abstract and does not override abstract method getDestinationStream(org.dspace.content.Item,java.io.InputStream,boolean) in org.dspace.app.mediafilter.FormatFilter

Which is to say I think we have a conflict, resulting from the ServiceAPI work. This PR needs rebasing and further testing.

**Comment by KevinVdV** [comment]
Created a new pull request that replaces this one: https://github.com/DSpace/DSpace/pull/1236. Commits from this pull request were cherry picked.

**Pull request closed without merging**
