### PR TITLE
[DS-3332] Handle resolver is hardcoded in org.dspace.handle.UpdateHandlePrefix

### PR DESCRIPTION
**Pull request by Generalelektrix**
Centralized most references of http://hdl.handle.net/ and of handle.canonical.prefix to HandleService. Created a new method: getCanonicalPrefix() in HandleService, adjusted getCanonicalForm(). As far as I can tell, remaining references of http://hdl.handle.net/ should stay like that since they are used as default values or are just included in documentation sections.

This PR needs a reviewer, especially the XMLUI part.

### CODE REVIEW

**Comment by Generalelektrix** [comment]
Bump. This Pull Request needs a reviewer, anyone interested? Thanks!

**Review by tdonohue — COMMENTED** [review]
👍  I like this idea, and at a glance the code looks good.  It would need some more detailed testing if we were to include it in DSpace 6.x.  It also may be possible to push this more directly into the upcoming DSpace 7 work.

**Review by tdonohue — APPROVED** [review]

**Comment by mwoodiupui** [comment]
+1 by inspection.  This is a good idea.

**Review by hardyoyo — APPROVED** [review]
+1 by inspection, tested in vagrant-dspace, works as expected

**Comment by tdonohue** [comment]
@mwoodiupui just a friendly reminder that this likely also should be cherry-picked or ported to `master`

**Comment by kshepherd** [comment]
reminder this still needs porting to master

**Pull request merged**
