### PR TITLE
DS-2971 Make bitstream description deletable again (5.x)

### PR DESCRIPTION
**Pull request by cjuergen**
Via edit item it is now possible to delete the bitstream description for an item.

### CODE REVIEW

**Comment by tdonohue** [comment]
We need to recreate this PR against the "master" branch. There are no more planned 5.x releases at this time.

**Comment by aschweer** [comment]
I can't reproduce this on master.

**Comment by tdonohue** [comment]
Descheduling this from 6.0.  It sounds like it may have been fixed during the 6.x Service API refactor (perhaps accidentally).  This patch may still be useful for individuals using 5.x.

**Comment by tdonohue** [comment]
Closing this PR, as the associated ticket was closed as "fixed".  This PR may still be useful for 5.x users, but has been fixed in 6.0.  See DS-2971 for more info.

**Pull request closed without merging**
