### PR TITLE
[DS-4149] support for additional "metadata" insertion on "item.compile" solr document field from external plugin (6.x)

### PR DESCRIPTION
**Pull request by lap82**
As agreed on https://github.com/DSpace/DSpace/pull/2709#issuecomment-653817186 this PR is a simplify version of https://github.com/DSpace/DSpace/pull/2709 that contains only the  core infrastructure to address the insert of additional metadata into item.compile via spring beans

### CODE REVIEW

**Review by kshepherd — APPROVED** [review]
+1, I haven't thoroughly tested the new functionality, but my main concern is impact on existing non-OpenAire 4 OAI, and everything there seems to be working well, including the minor xoai dependency update and date creation change in the mets stylesheet
So I think this is ready for merge! Thanks @lap82

**Review by toniprieto — APPROVED** [review]
I have tested it. I have done a complete reindex on a large test instance and it works ok and the new metadata fields are properly loaded

**Comment by nwoodward** [comment]
👍 I've tested this code locally and found that the new metadata fields appear after a reindex.

**Comment by tdonohue** [comment]
Just a quick note...this PR looks similar (almost identical) to this 7.x PR: https://github.com/DSpace/DSpace/pull/2756  I only wanted to call that out because there _has been some suggested improvements_ to PR #2756 (see reviews) that don't seem to have been addressed.  They are all minor, however, so this PR likely could move forward as-is for 6.4, and we could choose to only make those improvements in 7.x.

**Comment by kshepherd** [comment]
(Finally!) merging this work, thanks @lap82 for the patience and changes!

**Pull request merged**
