### PR TITLE
Performance updates for oai / discovery indexing

### PR DESCRIPTION
**Pull request by KevinVdV**
## Description
This is a performance enhancement to the OAI / discovery index scripts. These loop over all items using an "Iterator" & makes use of the "context. uncacheEntity()" method to keep memory consumption low.
In one of our bigger clients that we are migrating to DSpace 7 (+-275000 items) the discovery index took DAYS to finish (same for the OAI). A lot of time was lost with the constant uncaching of entities.

When searching for performance improvements we ran into the "ScrollableResults" objects in hibernate. This allows us to:
* Loop over the items
* Clear the entire DB cache every X number of items (we have chosen for 1000)

This alongside some other minor code changes got the scripts down from 3 days to around 10 hours each ! Not tested yet with smaller datasets, but I see no reason why it wouldn't be faster there as well.

## Instructions for Reviewers
List of changes in this PR:
* A couple of find() methods in the ItemService where renamed to make it clear that they should be used as "read only" (These where only used to read the data) 
* Added a new "findAllReadOnly()" method that works with the ScrollableResults

In order to test this PR: Test the speed of the oai index & discovery index script with & without these changes & compare the timing.

### Open questions
We COULD potentially wrap the "ScrollableResults" into an iterator that automatically clears the DB cache every X number of items, right now one will have to do this manually for every call.
We COULD make the cache clearance number configurable.

## Follow up actions

Don't merge as yet, depending on the answer of the question above the findAll() method will have to refactored to the readOnly version as well for:
* generation of the sitemaps
* the csv export

Furthemore we should be creating a "write" find as well so that things like filter media also receive similar performance boosts. (This should be done in a follow up PR after this one).

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by LucaGiamminonni — COMMENTED** [review]
Hi @KevinVdV, I don't really agree with using the readOnly flag directly in queries to try to improve performance. The context that sets the transaction to read-only should already optimize the queries made in that transaction (for example avoiding checks to make unnecessary flushes). What operations are avoided by setting read-only at the single query level? If such operations should be avoided even with a read-only transaction then perhaps we have a problem with the context read-only configuration.
Also I don't understand why to use the ScrollableResults object rather than the iterator. Are you sure the ScrollableResults doesn't pull up all items with a single query? What is the difference between ScrollableResults and an iterator obtained through  iterate() method?

**Comment by tdonohue** [comment]
Just to connect a few thoughts here...

@mwoodiupui is correct... we are already using `Query.stream()`, and it is the code behind all our `Iterator`s.  See the `iterate()` method here: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/core/AbstractHibernateDAO.java#L305

So, this does bring up the question of why `ScrollableResults` should have any effect on performance, if it's already used by that call to `stream()`.  

While I appreciate the early analysis here from @KevinVdV , it's very clear that this PR needs a lot more work/analysis.  If there's anyone interested in digging further here, please get in touch.  I'm not sure how to move this forward currently, as it's currently bringing up more questions than answers on how to resolve the performance issues behind indexing.  (If the Atmire team has time to dig more for 7.2, this seems like work that could be funded, but I'd need an estimate of effort here first.)

**Comment by KevinVdV** [comment]
@tdonohue It COULD be that we overlooked something, we can try to reinstate the Iterator & see what effect that has on the performance. But to be clear the reason why we switched to the `ScrollableResults` is so that we can **clear the entire cache**.

The key performance enhancer here is that that clear the entire cache, we already remove resource policies / items when we are done with those, but removing these from the cache individually takes a lot of time. I seem to remember that IF we clear the entire cache that the Iterator will stop working, we will be investigating if this is still the case next week.

**Comment by tdonohue** [comment]
Thanks @KevinVdV ! Let us know what you find, as it sounds like we all need to understand where the performance improvement comes from exactly.  It's also unclear to me why your new `HibernateDBConnection.clearSession()` method (to clear the entire cache) in this PR would require using `ScrollableResults`, but hopefully your testing will help clarify that.  All in all though, I'm supportive of this work, I just don't want us to move forward without understanding better where the performance improvement comes from.

**Comment by LucaGiamminonni** [comment]
hi @KevinVdV @tdonohue, most likely the performance problem related to indexing depends on the wrong way in which the mode is set in the Context. Some time ago in dspace-cris we realized that even if a Context is initialized as READ_ONLY the actual transaction is not necessarily read_only because the instantiation of a new Context leads to the overwriting of the mode set in HibernateDBConnection (which is a singleton bean). For example, in the IndexClient class the Context is set READ_ONLY by the setup () method but then, if the clean is done, the SolrServiceImpl.cleanIndex (boolean) method initializes a new Context overwriting the previously set mode. Fixing this should avoid doing many check for flushes when indexing and thus improve performance. We have already tried to handle this problem in dspace-cris and so if you agree we can do a porting of the functionality. Sorry but I thought a similar fix had already been reported on dspace7 as well, I checked internally and this was not intentionally. This improvement can be ported to dspace. 
Regarding the changes reported in this PR, I believe that the performance improvement is due to the read-only setting on the queries, which avoids checking on many items if it is necessary to flush. However, this behavior must also occur when setting the context as read-only.

**Comment by tdonohue** [comment]
@LucaGiamminonni : I'd very much appreciate it if you / your team could create a PR with your ported changes, as it sounds like you've already found a solution.  Ideally, if you could port it soon (in the next week or so), we could see if @KevinVdV 's team can review/test it on their end to ensure it solves the problem they are seeing.

Thanks for adding in your thoughts here, as it does sound like your previous discovery may be this same bug.  In the future, obviously, it's best to try to ensure any performance improvements make it back into core DSpace (to avoid DSpace-CRIS diverging from core DSpace code), but obviously I understand that mistakes can sometimes happen.

**Comment by tdonohue** [comment]
Closing this PR in favor of #8046, which we've found provides better performance and is a smaller fix. See discussion in that PR for more details.

**Pull request closed without merging**
