### PR TITLE
Controlled Vocabulary: Provide ability to store the id of a controlled vocabulary node and offer localized labels using cv.xml files per locale

### LINKED ISSUE #9317: Controlled Vocabulary: Provide ability to store the id of a controlled vocabulary node; Offer localized labels using cv.xml files per locale
In DSpace 6 it was possible to use localized controlled vocabularies by having a controlled vocabulary file per locale (and fallback to english in case the current locale was not supported) This feature, along with a change we made for ourselves enabling us to store the id of a controlled vocabulary node instead of the label, would make a good adition to the controlled vocabulary functionality present in DSpace 7.

In order to support the optional storage of id instead of label value, a new configuration option per controlled vocabulary should be introduced, i.e: ```vocabulary.plugin.<CONTROLLED_VOCABULARY>.storeIDs``` - where ```<CONTROLLED_VOCABULARY>``` is the name of the controlled vocabulary. The class ```org.dspace.content.authority.DSpaceControlledVocabulary``` must be enhanced to consider the new configuration option and use ```id``` attribute instead of ```label``` attribute when constructing the choice based on the xml node.

In order to support the localized controlled vocabularies, the ```init``` method of the class ```org.dspace.content.authority.DSpaceControlledVocabulary``` must be enhanced to receive the current locale. (The public methods of that class already receive the locale, so we can simply pass the value to ```init```) Inside the ```init``` method, a logic similar to DSpace6 will be implemented. The method will check for existance of a file named ```<CONTROLLED_VOCABULARY>_<LOCALE>.xml``` - where ```<CONTROLLED_VOCABULARY>``` is the name of the controlled vocabulary and ```<LOCALE>``` is the current locale. If that file exists, it is used to contruct the controlled vocabulary. Otherwise, a fallback to the "standard" controlled vocabulary file ```<CONTROLLED_VOCABULARY>.xml``` is made.

### PR DESCRIPTION
**Pull request by mahnkong**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #9317 

## Description
This PR fixes #9317. With this PR it is possible to use localized controlled vocabularies by having a controlled vocabulary file per locale (and fallback to english in case the current locale was not supported) Additionally, this PR provides the feature to store the id of a controlled vocabulary node instead of the label (configurable per controlled vocabulary)

## Instructions for Reviewers

List of changes in this PR:
* First, with this PR it is possible to use localized controlled vocabularies by having a controlled vocabulary file per locale (and fallback to english in case the current locale was not supported)
In order to support the localized controlled vocabularies, the init method of the class org.dspace.content.authority.DSpaceControlledVocabulary was enhanced to receive the current locale. (The public methods of that class already received the locale, so we simply pass the value to init) Inside the init method, a logic similar to DSpace6 was implemented. The method checks for existance of a file named ```<CONTROLLED_VOCABULARY>_<LOCALE>.xml``` - where ```<CONTROLLED_VOCABULARY>``` is the name of the controlled vocabulary and ```<LOCALE>``` is the current locale. If that file exists, it is used to contruct the controlled vocabulary. Otherwise, a fallback to the "standard" controlled vocabulary file ```<CONTROLLED_VOCABULARY>.xml``` is made.

* Second, In order to support the optional storage of id instead of label value, a new configuration option per controlled vocabulary was introduced: ```vocabulary.plugin.<CONTROLLED_VOCABULARY>.storeIDs``` - where ```<CONTROLLED_VOCABULARY>``` is the name of the controlled vocabulary. The class org.dspace.content.authority.DSpaceControlledVocabulary was enhanced to consider the new configuration option and use id attribute instead of label attribute when constructing the choice based on the xml node.

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

The ```DSpaceControlledVocabularyTest``` test class was updated with test methods covering the PR changes. This, together with the change description above covers the configurations required to use the PR changes.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by paulo-graca — COMMENTED** [review]
Thank you @mahnkong, for adding this!

**Comment by mahnkong** [comment]
just merged latest main into feature branch and corrected errors due to new changes in DSpaceControlledVocabulary.java which required adjustments to be compatible to changes introduced in this feature branch

**Comment by qzhao-ulb** [comment]
Thanks @mahnkong for sharing! We added this PR in our system, it works! Only ID stored in the metadata, this record has no authority, but I can use discovery it by value but with tree view as well.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @mahnkong !  This looks to have been tested by several others.  I gave it a quick test and code review. It works for me and the code looks good.  Thanks for adding additional tests as well!

**Comment by z-stoynova** [comment]
Is there a possibility to port this feature to 7.x or it will be only available from 9.x DSpace versions? Thank you very much for your answer in advance!

**Comment by mahnkong** [comment]
I doubt, there will be another 7.x release containing new features (please correct me, if I'm wrong @tdonohue)  

But this feature should work in DSpace 7, we started developing it in DSpace 7 before now having it locally running in DSpace 8. If it might help, we could create a branch for dspace 7 in a fork, so that you could take over the change and test?

**Comment by tdonohue** [comment]
Correct. both DSpace 7.x and 8.x will not receive any more features as they are both in maintenance.  They will receive bug/security fixes and small improvements (e.g. accessibility fixes) only.

**Comment by z-stoynova** [comment]
> I doubt, there will be another 7.x release containing new features (please correct me, if I'm wrong @tdonohue)
> 
> But this feature should work in DSpace 7, we started developing it in DSpace 7 before now having it locally running in DSpace 8. If it might help, we could create a branch for dspace 7 in a fork, so that you could take over the change and test?

Thank you @mahnkong for your suggestion. However I am developing a DSpace-CRIS instance (2023.02.06 till now) and I managed to port/merge this code in our instance. This did not solve the main problem that we are having since the frontend is not fully adjusted to handle this behaviour in submission-forms but to whom might be interested this PR code provides for sure the described functionality. We will upgrade soon to the newest DSpace-CRIS version and we can try again. At the latest this summer should come out the first 2025.x.x version of DSpace-CRIS based on DSpace 9.0 and then we can take it from there.

**Pull request merged**
