### PR TITLE
Fix for #8732 and #8750

### LINKED ISSUE #8732: Default filter always applies in Register DOI via Item status page in UI
**Describe the bug**
It was my understanding that the functionality of registering doi via the item status page should always bypass any default filter defiened in the DOIIdentifierProvider bean (identifier-service.xml config) by applying the TrueFilter.

I am seeing something very odd when trying this functionality and looking at the logs (I have added some additional logging). It looks like Truefilter is being checked twice, and an additional check is run that uses the default filter:

```
Before request [POST /server/api/pid/identifiers] originated from /items/69a962a1-0af5-4323-94f2-646fd500d8c5/edit/register-doi
org.dspace.identifier.DOIIdentifierProvider @ Check filter: class org.dspace.content.logic.TrueFilter

org.dspace.identifier.DOIIdentifierProvider @ Result of filter for 1810/347135 is true
...
org.dspace.identifier.DOIIdentifierProvider @ Check filter: class org.dspace.content.logic.TrueFilter

org.dspace.identifier.DOIIdentifierProvider @ Result of filter for 1810/347135 is true

org.dspace.identifier.DOIIdentifierProvider @ Check filter: class org.dspace.content.logic.DefaultFilter

org.dspace.content.logic.condition.IsArchivedCondition @ Result of isArchived is true

org.dspace.content.logic.condition.IsWithdrawnCondition @ Result of isWithdrawn is false

org.dspace.content.logic.condition.InCollectionCondition @ item 1810/347135 is in collection 1810/294790, returning true

org.dspace.identifier.DOIIdentifierProvider @ Result of filter for 1810/347135 is false

org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)

java.lang.IllegalStateException: Failed to register identifier: null
	at org.dspace.app.rest.repository.IdentifierRestRepository.registerDOI(IdentifierRestRepository.java:248)
```

In the UI, I get the error message banner twice, and I can see two API calls in the developer tools. Is the method somehow being called multiple times?

**To Reproduce**
1. Log in as admin and choose an archived item without a DOI
2. Go to Edit item > Item status
3. Click on Register DOI
4. Confirm DOI registration

**Expected behavior**
The registration always takes place, bypassing any default identifier filters

**Related work**
Link to any related tickets or PRs here.

### LINKED ISSUE #8750: doi-organiser command line NPE when using VersionedDOIIdentifierProvider
**Describe the bug**
An NPE is thrown when trying to reserve (--reserve-doi) or register (--register-doi) an individul DOI for an item

```
/home/dspace/dspace/bin/dspace doi-organiser --reserve-doi 1810/347187
Exception: null
java.lang.NullPointerException
	at org.dspace.identifier.doi.DOIOrganiser.reserve(DOIOrganiser.java:502)
	at org.dspace.identifier.doi.DOIOrganiser.reserve(DOIOrganiser.java:492)
	at org.dspace.identifier.doi.DOIOrganiser.runCLI(DOIOrganiser.java:310)
	at org.dspace.identifier.doi.DOIOrganiser.main(DOIOrganiser.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:277)
	at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:133)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:98)
```

**To Reproduce**
1. Enable VersionedDOIIdentifierProvider in identifier-service.xml
2. Run command doi-organiser with --reserve-doi or --register-doi option

**Expected behavior**
The DOI is reserved or registered successfully

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by amgciadev**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #8732
* Fixes #8750 

## Description
Short summary of changes (1-2 sentences).

## Instructions for Reviewers
The register method in being called in IdentifierRestRepository was not supported in VersionedDOIIdentifierProvider and a number of calls to register and mint methods were not passing the filter parameter, which in turn was causing for the doi provider to use the default filter defined in identifier-service.xml
List of changes in this PR:
* IdentifierRestRepository: call mint method with filter prior to call register method and pass along the minter identifier to make use of method that is supported both in DOIdentifierProvider and VersionedDOIIdentifierProvider
* VersionedDOIIdentifierProvider: fix calls to mint methods to make use of the filter passed on as a parameter

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

To test this PR the VersionedDOIIdentifierProvider needs to be configured in identifier-service.xml

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
@amgciadev : Thanks for the fixes!  I've reviewed the code and it all looks reasonable based on the bug descriptions.

However, I don't have the ability to **test** DOI-specific code (I don't have a DOI test server or anything).  So, I'd appreciate it if @kshepherd could give this a look and/or test before we merge it.  @kshepherd : I've assigned you as a reviewer as well.

**Review by kshepherd — DISMISSED** [review]
+1 looks great and works as advertised, thanks @amgciadev !

My only note is that while the change to the `IdentifierRestRepository` works well to force proper registration for the versioned provider now (it always worked for the nonversioned provider) and will not introduce any problems, a slightly cleaner approach might be to override the `register(..., filter)` method in `VersionedDOIIdentifierProvider`, so that it mints with filter then registers with doiValue and filter args (see the super method), rather than manually repeating those steps in the REST repository. I just tested this quickly now and it seems to work OK for me. However that is just a small note, not a blocker.

Test procedure:

1. Enabled versioning, versioned DOI provider, versioned handle provider
2. Created a new version of an item with versioned DOI provider, satisfying the configured filter. No exceptions, the DOI was queued for registration successfully
3. Created another version of the item that did **not** satisfy the filter conditions. No exceptions and as expected, there was no new DOI queued for registration
4. Used the administrative "Register DOI" button on this new version which does not satisfy the DOI filter, and as expected the new DOI was queued for registration (special TrueFilter used)
5. Performed remote registration and update using the doi-organiser (datacite test service) and all operations completed successfully

**Comment by amgciadev** [comment]
@kshepherd  thanks a lot for taking the time to review and verify that the fix works. I have now taken into account your feedback and modified the branch with the changes you suggest.

**Comment by tdonohue** [comment]
@kshepherd : I've asked for a follow-up review. The improvements look good to me, but would appreciate it if you could verify that they work on your end.  Thanks!

**Comment by kshepherd** [comment]
@amgciadev i went to test this on a new installation and unfortunately got an error when i tried to create a community (non-item).. the "DOI only supports items" error shouldnt be fatal but it appears that it was in this case.. could you have a quick test of that on your end, just in case there's something wrong with my testing?

**Review by kshepherd — APPROVED** [review]
1. Community and collection creation working nicely again
2. Add a new item that passed the default filter, new DOI minted and reg'd successfully
3. Add a new version for this item with no meaningful changes, new versioned DOI minted and reg'd successfully
4. Add a new version for another item that didn't match the filter, DOI not minted (this is expected)
5. Force DOI with the Register DOI admin button for this new version, DOI minted with expected version suffix

Everything looking great! +1 from me, will merge this PR shortly. Thanks @amgciadev

**Comment by amgciadev** [comment]
Great that is all now working as expected, thanks for the review and testing!

**Pull request merged**
