### PR TITLE
Adding new Relationships in Edit Item is difficult for entities with many relationships - REST

### PR DESCRIPTION
**Pull request by Micheleboychuk**
## References
Rest Contract: DSpace/RestContract#170
Related to the issue: DSpace/dspace-angular/issues/1148

## Description
This PR introduce search methods intended to facilitate an efficient management of the edit relationship. It allows to verify in a single call which if any items in a list have already a specified relationship with an item.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by paulo-graca — COMMENTED** [review]
Just noted some missing java docs. I will test it with my server.

**Comment by paulo-graca** [comment]
The PR works as expected (https://github.com/DSpace/RestContract/blob/main/relationships.md#search-methods)
image

So, to me it's ready to go as soon as you add the missing java docs. Thank you for this contribution!

**Review by tdonohue — APPROVED** [review]
👍 @Micheleboychuk : Tested this today and the code looks good & seems to work as described in the REST Contract.  That said, I'm leaving this PR open as it's possible minor updates will need to be made to support the [changes requested in the corresponding Angular PR](https://github.com/DSpace/dspace-angular/pull/1329#pullrequestreview-765567066)

(Also please do add the JavaDocs that @paulo-graca suggested, as I agree they should be added)

**Review by paulo-graca — APPROVED** [review]
Thank you for adding the missing java docs!

**Comment by Micheleboychuk** [comment]
@paulo-graca @tdonohue thanks for the review,
fixing the java docs I also found a pagination bug, so I added a test to prove it and then added the fix.

**Review by paulo-graca — APPROVED** [review]
Thank you again @Micheleboychuk !

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me. Thanks @Micheleboychuk !

This is at +2, so it's ready to merge.  However, I'm going to wait to merge until the Frontend PR (https://github.com/DSpace/dspace-angular/pull/1329) is also completed (just in case additional minor updates are needed).

**Pull request merged**
