### PR TITLE
Tighten security of our Auth Token (JWT) via CSRF prevention techniques

### LINKED ISSUE #2938: JWT Authentication Token(s) should not store IP address by default
**Describe the bug**
This bug was encountered on the demo site (https://dspace7-demo.atmire.com/) backend and was the cause of two other bugs (#2920 and #2935) which only existed on the demo site.

The problem is simply that, *by default* the JWT authentication token stores the user's IP address.  While this works fine in simple DSpace setups, it is problematic if you are using a Proxy or ISP or hosting service where the IP address may change in the middle of a user session.  When the IP changes, the user's session is invalidated and they need to login again.

**Expected behavior**
The JWT authentication token should NEVER store a user's IP address as that information is not guaranteed to be stable/consistent. As soon as the IP changes, the token can no longer be validated.

Therefore, ideally, once we have reenabled CSRF protection (#2922), we should **completely remove the following settings**:
* `jwt.login.token.include.ip`
* `jwt.shortLived.token.include.ip`

**Quick Fix**
If any users encounter either previous bug (especially #2935 which is easy to test), they should disable the existing settings in their `local.cfg` by adding:
```
jwt.login.token.include.ip = false
jwt.shortLived.token.include.ip = false
```
Once this bug is fixed, those settings can be removed as the IP will never be included in those authentication tokens.

**Related Work**
* Somewhat depends on #2922.  Including the IP address in these tokens is a form of basic "protection" against attacks like CSRF.  However, it's a flawed solution as described above.  That said, the IP address in the token is completely unnecessary once #2922 is merged.

### PR DESCRIPTION
**Pull request by tdonohue**
## References
* Replaces #2922 , which was unable to be implemented because of conflicts with both Shibboleth (as Spring Security's CSRF protection requires sending back a token header, which cannot be sent via redirects after login in Shib), and conflicts with hosting backend and frontend on separate origins (as Spring Security's CSRF protection relies on cookies, which cannot be sent cross origin)
* Corresponding UI PR: https://github.com/DSpace/dspace-angular/pull/907
* Also fixes #2938

## Description
This PR takes a different approach of tightening our security while keeping Spring Security's default CSRF protection _disabled._

Our application security is tightened in the following ways:
1. By default, each Auth Token (JWT) can only be used from the origin in which it was created.  I.e. each JWT knows which origin sent the original authentication request, and that same origin is the only one that can reuse the generated token.  This is achieved by validating against the `Origin` header (which aligns with OWASP's CSRF Prevention technique of "[Verifying Origin with Standard Headers](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#verifying-origin-with-standard-headers)"). This feature can be disabled via `jwt.login.token.include.origin=false` (but is enabled by default)
    - If `Origin` header not provided in the request, the `Referer` header will be used. If neither are provided (e.g. Angular Universal SSR does not always provide these headers), then we look for a custom `X-DSpace-UI` header sent from the UI/client.
2. Authentication Token is _only sent/read_ via `Authorization` header (which is [not susceptible to CSRF attacks](https://security.stackexchange.com/a/170414)), **except in one scenario:**
    - If Shibboleth is enabled, then the `ShibbolethLoginFilter` will generate a single-use cookie to pass the token back to the UI/client (as a header cannot be passed via a redirect).  This single-use cookie is secure (requires HTTPS to read), disables Javascript access (HTTPOnly), but can be sent cross origin (SameSite=None).  (Keep in mind though that the Token within the cookie can only be used by one, trusted origin.)
   - _This Cookie is not allowed/created or read if Shibboleth is not enabled._  I.e. if Shibboleth is disabled, DSpace will only send/receive auth tokens via Headers.
3. Updated `/logout` endpoint to **require** `POST` requests (previously it allowed for `GET` or `POST`).  This aligns with the OWASP principle ["Do not use GET requests for state changing operations"](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#introduction)

A few additional minor changes were included:
* Removed old `jwt.login.token.include.ip` setting, as it has been replaced by `jwt.login.token.include.origin`
* Added a large amount of new JavaDocs and inline code comments to better describe how authentication works (especially how Shibboleth authentication works).
* Added tests to verify that Auth Tokens can never be used by untrusted Origins (i.e. any not listed in `rest.cors.allowed-origins`).
* Updated all `jwt.shortLived.*` settings to default to the same values as the corresponding `jwt.login.*` setting (except the "expiration" which is the only difference between these tokens).  This just makes it easier to configure both values at once (as often they should be kept in sync in a given site).
* Renamed `ShibbolethAuthenticationFilter` to `ShibbolethLoginFilter`, as it extends `StatelessLoginFilter` (not `StatelessAuthenticationFilter`).  Added some verification checks to this Filter to ensure Shibboleth is enabled before allowing for redirects.
* Updated Spring Boot's `application.properties` to include `server.forward-headers-strategy=FRAMEWORK`. This seems like a "sane default" for DSpace as it ensures Spring Boot will try to handle `X-Forwarded-*` Headers automatically (by default they are ignored).  I ran into this while testing the previous PR (#2459  across IPs/origins and found these headers were being dropped.  This setting can be overridden in `local.cfg` however (as most Spring settings can be overridden in our local.cfg) if ever needed.

## Instructions for Reviewers
* Review the code & the tests, as I tried to write tests to validate all the new code/behavior. There are also tests that validate Cookies are being trusted when shib is enabled, and ignored when not enabled.
* Test authentication via HAL Browser.  Verify Logout requires POST
* Test authentication via Angular UI : Requires installing https://github.com/DSpace/dspace-angular/pull/907
* Test authentication via Shibboleth : Requires installing https://github.com/DSpace/dspace-angular/pull/907  (I have not tested this yet, but I suspect it should still work based on my reading of the Shibboleth code)

**TODO:** Once this PR is accepted, minor updates to the REST Contract will need to be made to clarify that the [`/logout`](https://github.com/DSpace/Rest7Contract/blob/main/authentication.md#logout) endpoint requires POST and that all other methods will return a 405 error.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by paulo-graca — COMMENTED** [review]
Not sure yet what happens. But this PR breaks my Shibboleth authentication feature using angular UI (with dspace-angular#907). But It's working when I'm using the HAL browser. After all redirections done, a established session isn't available at angular UI.

```
{
  "id": null,
  "okay": true,
  "authenticated": true,
  "type": "status",
  "_links": {
    "eperson": {
      "href": "https://myhost.pt/server/api/eperson/epersons/931054dc-f4c2-40e8-ace3-37d288b87512"
    },
    "self": {
      "href": "https://myhost.pt/server/api/authn/status"
    }
  }
}
```
It might be related with some required cookie at angular side that is lost between redirections.
`POST https://myhost.pt/Shibboleth.sso/SAML2/POST`
`Location: https://myhost.pt/server/api/authn/shibboleth?redirectUrl=https://myhost.pt/home
`

`GET https://myhost.pt/server/api/authn/shibboleth?redirectUrl=https://myhost.pt/home`
` Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlaWQiOiI5MzEwNTRkYy1mNGMyLTQwZTgtYWNlMy0zN2QyODhiODc1MTIiLCJzZyI6W10sImV4cCI6MTYwNDA2NTg4OX0.S9vS5lUVPjcaTjyXvil8H6YbiR71aLvJJv7aYsYRFRg`
`Set-Cookie: JSESSIONID=A458FE5708B1F1480D02997F086471F3; Path=/server; Secure; HttpOnly`
`Set-Cookie: Authorization-cookie=eyJhbGciOiJIUzI1NiJ9.eyJlaWQiOiI5MzEwNTRkYy1mNGMyLTQwZTgtYWNlMy0zN2QyODhiODc1MTIiLCJzZyI6W10sImV4cCI6MTYwNDA2NTg4OX0.S9vS5lUVPjcaTjyXvil8H6YbiR71aLvJJv7aYsYRFRg; Secure; HttpOnly; SameSite=None`
`Location: https://myhost.pt/home`

`GET https://myhost.pt/home`
`ETag: W/"274-BJhuoiRwSGbZC9uVM0EphlDUzdk"`

**Comment by tdonohue** [comment]
@paulo-graca : thanks for the review here & the extra information. 

Based on the info you've given, my suspicion is the problem is with the new `jwt.login.token.include.origin` setting.  By default, it's set to `true`, which means you *cannot* reuse a JWT from a different origin.  This backend code determines the origin based on the `Origin`, `Referer` or `X-DSpace-UI` header (in that order).  If none of those headers exist, then the JWT is signed with an empty origin.

This all works great using Password Auth, and it sounds like it works fine using Shib from the Hal Browser.  I suspect the difference with Shib via the UI is the number of redirects (as you've noted).  I was *hoping* that Shib would automatically set a `Referer` header as part of it's redirect....but it's possible that's not happening.  
 
So, I think what may be occurring here is this: _technically everything works, **but** the JWT is created with a null/empty Origin, and then attempted to be used by the UI (under a different Origin) and the **JWT usage therefore gets blocked**._

As a simple test, I'd suggest trying to retest with `jwt.login.token.include.origin = false`.  If my suspicions above are correct, this likely **will work** for Shibboleth + Angular UI.   If that's indeed the case, I'll have to dig in to see if I can figure out a way for Shibboleth to work when that setting is `true` (as it's more secure to block JWTs from being used from different Origins).

**Comment by paulo-graca** [comment]
@tdonohue Has you suggested I tested again, but now with this setting on my local.cfg
`jwt.login.token.include.origin = false`

and it worked as expected.

**Comment by tdonohue** [comment]
@paulo-graca : I've just pushed up a fix which I believe will fix the issue of getting Shibboleth working from the Angular UI when using the default setting of `jwt.login.token.include.origin = true`.   Simply put, the fix ensures that the `redirectUrl` sent to Shib (and later received back after a successful login) is trusted as the `Origin`, which allows the JWT origin check to succeed.

If you could give this new version a test, I'd appreciate it!

**Review by paulo-graca — COMMENTED** [review]
I'm getting this error:

```
2020-11-09 10:28:09,055 ERROR org.dspace.app.rest.security.RestAuthenticationService @ Error parsing EPerson from token
java.text.ParseException: Invalid serialized unsecured/JWS/JWE object: Missing part delimiters
        at com.nimbusds.jose.JOSEObject.split(JOSEObject.java:222) ~[nimbus-jose-jwt-7.9.jar:7.9]
        at com.nimbusds.jwt.SignedJWT.parse(SignedJWT.java:110) ~[nimbus-jose-jwt-7.9.jar:7.9]
        at org.dspace.app.rest.security.jwt.JWTTokenHandler.getSignedJWT(JWTTokenHandler.java:334) ~[classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.security.jwt.JWTTokenHandler.parseEPersonFromToken(JWTTokenHandler.java:141) ~[classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.security.jwt.JWTTokenRestAuthenticationServiceImpl.getAuthenticatedEPerson(JWTTokenRestAuthenticationServiceImpl.java:168) [classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.security.StatelessAuthenticationFilter.getAuthentication(StatelessAuthenticationFilter.java:125) [classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.security.StatelessAuthenticationFilter.doFilterInternal(StatelessAuthenticationFilter.java:82) [classes/:7.0-beta5-SNAPSHOT]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
...
2020-11-09 10:28:09,146 ERROR org.dspace.app.rest.security.RestAuthenticationService @ Error parsing EPerson from token
java.text.ParseException: Invalid serialized unsecured/JWS/JWE object: Missing part delimiters
        at com.nimbusds.jose.JOSEObject.split(JOSEObject.java:222) ~[nimbus-jose-jwt-7.9.jar:7.9]
        at com.nimbusds.jwt.SignedJWT.parse(SignedJWT.java:110) ~[nimbus-jose-jwt-7.9.jar:7.9]
        at org.dspace.app.rest.security.jwt.JWTTokenHandler.getSignedJWT(JWTTokenHandler.java:334) ~[classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.security.jwt.JWTTokenHandler.parseEPersonFromToken(JWTTokenHandler.java:141) ~[classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.security.jwt.JWTTokenRestAuthenticationServiceImpl.getAuthenticatedEPerson(JWTTokenRestAuthenticationServiceImpl.java:168) [classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.security.StatelessAuthenticationFilter.getAuthentication(StatelessAuthenticationFilter.java:125) [classes/:7.0-beta5-SNAPSHOT]
        at org.dspace.app.rest.security.StatelessAuthenticationFilter.doFilterInternal(StatelessAuthenticationFilter.java:82) [classes/:7.0-beta5-SNAPSHOT]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77) [spring-security-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]

```

**Comment by tdonohue** [comment]
@paulo-graca : Could you provide more information about when that error occurs, or perhaps check your logs for other odd behavior or exceptions?  That exception almost seems to be saying that you have something that is *not* a JWT Auth Token in your `Authorization` Header or (single-use) `Authorization-cookie` cookie.   That's really odd, as I'm not sure how a completely invalid JWT would have gotten in that header or cookie....**unless** maybe the original JWT Auth Token could not be created or threw an earlier error (check a bit earlier in your logs to see if there's a earlier error here).

I'll also start to investigate if there's a way to get a simple Shib environment running locally in Docker -- it is sounding like I might need to debug this behavior more.  Thanks!

**Comment by paulo-graca** [comment]
Probably there was something between my tests that polluted cookies request.

Using this setting:
`jwt.login.token.include.origin = true`

Some requests after `POST` to `/Shibboleth.sso/SAML2/POST`:

GET https://myhost.pt/server/api/authn/shibboleth?redirectUrl=https://myhost.pt/items/981a864e-eb03-402d-9c3e-9eae71e578ec

```
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlaWQiOiI5MzEwNTRkYy1mNGMyLTQwZTgtYWNlMy0zN2QyODhiODc1MTIiLCJzZyI6W10sImV4cCI6MTYwNTAwMDMwOH0.LIiKfsjrNMVkw3lMAOGyZYqcmspQU9za7kZjIk7I0J4
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: close
Content-Language: en
Content-Length: 0
Date: Tue, 10 Nov 2020 08:55:07 GMT
Expires: 0
Location: https://myhost.pt/items/981a864e-eb03-402d-9c3e-9eae71e578ec
Pragma: no-cache
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Set-Cookie: JSESSIONID=179AE714C54E0D5B6340D3F667E91F67; Path=/server; Secure; HttpOnly
Set-Cookie: Authorization-cookie=eyJhbGciOiJIUzI1NiJ9.eyJlaWQiOiI5MzEwNTRkYy1mNGMyLTQwZTgtYWNlMy0zN2QyODhiODc1MTIiLCJzZyI6W10sImV4cCI6MTYwNTAwMDMwOH0.LIiKfsjrNMVkw3lMAOGyZYqcmspQU9za7kZjIk7I0J4; Secure; HttpOnly; SameSite=None
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```

The requested page (redirection after login):
image



`GET ` `https://myhost.pt/server/api/authn/status`
```
{"id":null,"okay":true,"authenticated":false,"type":"status","_links":{"eperson":{"href":"https://myhost.pt/server/api/authn/status/eperson"},"self":{"href":"https://myhost.pt/server/api/authn/status"}}}
```

Here is my request log:

```
2020-11-10 08:54:31,253 INFO  org.dspace.usage.LoggerUsageEventListener @ anonymous::view_item:handle=123456789/26
2020-11-10 08:55:08,005 INFO  org.dspace.content.MetadataValueServiceImpl @ anonymous::delete_metadata_value: metadata_value_id=1400
2020-11-10 08:55:08,110 INFO  org.dspace.content.MetadataValueServiceImpl @ anonymous::delete_metadata_value: metadata_value_id=1401
2020-11-10 08:55:08,123 INFO  org.dspace.eperson.EPersonServiceImpl @ anonymous::update_eperson:eperson_id=931054dc-f4c2-40e8-ace3-37d288b87512
2020-11-10 08:55:08,178 INFO  org.dspace.authenticate.ShibAuthentication @ myemail@example.com has been authenticated via shibboleth.
2020-11-10 08:55:08,179 INFO  org.dspace.eperson.EPersonServiceImpl @ myemail@example.com::update_eperson:eperson_id=931054dc-f4c2-40e8-ace3-37d288b87512
2020-11-10 08:55:08,179 INFO  org.dspace.app.rest.security.EPersonRestAuthenticationProvider @ paulo.graca@fccn.pt::login:type=explicit
2020-11-10 08:55:08,453 INFO  org.dspace.authenticate.ShibAuthentication @ Added current EPerson to special groups: []
2020-11-10 08:55:08,500 INFO  org.dspace.eperson.EPersonServiceImpl @ paulo.graca@fccn.pt::update_eperson:eperson_id=931054dc-f4c2-40e8-ace3-37d288b87512
2020-11-10 08:55:19,446 WARN  org.dspace.app.rest.security.jwt.JWTTokenHandler @ EPerson 'myemail@example.com' at Origin 'https://myhost.pt' tried to reuse a token which is not valid for this Origin or EPerson.
2020-11-10 08:55:22,144 INFO  org.dspace.usage.LoggerUsageEventListener @ anonymous::view_item:handle=123456789/26
```

**Comment by paulo-graca** [comment]
But using:
`jwt.login.token.include.origin = false`

GET https://myHost.com/server/api/authn/shibboleth?redirectUrl=https://myHost.com/home

Response:
```
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlaWQiOiI5MzEwNTRkYy1mNGMyLTQwZTgtYWNlMy0zN2QyODhiODc1MTIiLCJzZyI6W10sImV4cCI6MTYwNTAwNjA4OX0.r_5zQEx6EQV-LprfGDSG-7kAvGI30N_5w2XtzYqhS8c
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: close
Content-Language: en
Content-Length: 0
Date: Tue, 10 Nov 2020 10:31:29 GMT
Expires: 0
Location: https://myHost.com/home
Pragma: no-cache
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Set-Cookie: JSESSIONID=926A9DA8B513FC4E772FF53E6A85D778; Path=/server; Secure; HttpOnly
Set-Cookie: Authorization-cookie=eyJhbGciOiJIUzI1NiJ9.eyJlaWQiOiI5MzEwNTRkYy1mNGMyLTQwZTgtYWNlMy0zN2QyODhiODc1MTIiLCJzZyI6W10sImV4cCI6MTYwNTAwNjA4OX0.r_5zQEx6EQV-LprfGDSG-7kAvGI30N_5w2XtzYqhS8c; Secure; HttpOnly; SameSite=None
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```

Request:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-BR,pt;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Cookie: JSESSIONID=FE54FFD223CC4915A56E4FF7BE96091E; dsLanguage=pt; dsAuthInfo={%22accessToken%22:%22eyJhbGciOiJIUzI1NiJ9.eyJlaWQiOiI5MzEwNTRkYy1mNGMyLTQwZTgtYWNlMy0zN2QyODhiODc1MTIiLCJzZyI6W10sImV4cCI6MTYwNTAwMTkyOX0.X7tW5IE3h66_ReYCv58BITKjtUvd-lRomK3uH4R5t_k%22%2C%22expires%22:1605001929000}; klaro-931054dc-f4c2-40e8-ace3-37d288b87512={%22authentication%22:true%2C%22preferences%22:true%2C%22acknowledgement%22:true%2C%22google-analytics%22:true}; _shibsession_64656661756c7468747470733a2f2f646576352e72636161702e7074=_f4994568f21e8c13ccf0192808fb3b4a
Host: myHost.com
Referer: https://login-conta-dev.ciencia-id.pt/
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: cross-site
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
```

The requested page (redirection after login):

image

`GET ` `https://myhost.pt/server/api/authn/status`
```
{"id":null,"okay":true,"authenticated":true,"type":"status","_links":{"eperson":{"href":"https://myHost.com/server/api/eperson/epersons/931054dc-f4c2-40e8-ace3-37d288b87512"},"self":{"href":"https://myHost.com/server/api/authn/status"}}}
```

Server side log:

```
2020-11-10 10:31:00,165 INFO  org.dspace.usage.LoggerUsageEventListener @ anonymous::view_site:site_id=987ebb10-97f6-477b-b249-d9191fe81677
2020-11-10 10:31:29,111 INFO  org.dspace.content.MetadataValueServiceImpl @ anonymous::delete_metadata_value: metadata_value_id=1459
2020-11-10 10:31:29,117 INFO  org.dspace.content.MetadataValueServiceImpl @ anonymous::delete_metadata_value: metadata_value_id=1460
2020-11-10 10:31:29,122 INFO  org.dspace.eperson.EPersonServiceImpl @ anonymous::update_eperson:eperson_id=931054dc-f4c2-40e8-ace3-37d288b87512
2020-11-10 10:31:29,141 INFO  org.dspace.authenticate.ShibAuthentication @ myEmail@example.com has been authenticated via shibboleth.
2020-11-10 10:31:29,142 INFO  org.dspace.eperson.EPersonServiceImpl @ myEmail@example.com::update_eperson:eperson_id=931054dc-f4c2-40e8-ace3-37d288b87512
2020-11-10 10:31:29,142 INFO  org.dspace.app.rest.security.EPersonRestAuthenticationProvider @ myEmail@example.com::login:type=explicit
2020-11-10 10:31:29,309 INFO  org.dspace.authenticate.ShibAuthentication @ Added current EPerson to special groups: []
2020-11-10 10:31:29,311 INFO  org.dspace.eperson.EPersonServiceImpl @ myEmail@example.com::update_eperson:eperson_id=931054dc-f4c2-40e8-ace3-37d288b87512
2020-11-10 10:31:40,448 INFO  org.dspace.content.MetadataValueServiceImpl @ anonymous::delete_metadata_value: metadata_value_id=1461
2020-11-10 10:31:40,452 INFO  org.dspace.content.MetadataValueServiceImpl @ anonymous::delete_metadata_value: metadata_value_id=1462
2020-11-10 10:31:40,454 INFO  org.dspace.eperson.EPersonServiceImpl @ anonymous::update_eperson:eperson_id=931054dc-f4c2-40e8-ace3-37d288b87512
2020-11-10 10:31:40,467 INFO  org.dspace.authenticate.ShibAuthentication @ myEmail@example.com has been authenticated via shibboleth.
2020-11-10 10:31:40,467 INFO  org.dspace.eperson.EPersonServiceImpl @ myEmail@example.com::update_eperson:eperson_id=931054dc-f4c2-40e8-ace3-37d288b87512
2020-11-10 10:31:40,467 INFO  org.dspace.app.rest.security.EPersonRestAuthenticationProvider @ myEmail@example.com::login:type=explicit
2020-11-10 10:31:43,111 INFO  org.dspace.usage.LoggerUsageEventListener @ myEmail@example.com::view_site:site_id=987ebb10-97f6-477b-b249-d9191fe81677
```

**Comment by tdonohue** [comment]
@paulo-graca : Thanks for including the two different request behaviors.  The key difference that I see is that when you set `jwt.login.token.include.origin = true`, you are seeing this in your logs:
```
2020-11-10 08:55:19,446 WARN  org.dspace.app.rest.security.jwt.JWTTokenHandler @ EPerson 'myemail@example.com' at Origin 'https://myhost.pt' tried to reuse a token which is not valid for this Origin or EPerson.
```
That message is saying that a JWT Auth Token is *successfully* being created (after a successful Shibboleth login), but when the UI goes to use it, the `Origin` from the UI doesn't match & therefore gets blocked.  That log statement is saying that the UI is sending a request with `Origin=https://myhost.pt`, but that Origin seems not to match the Origin that initially signed/created the JWT Auth Token.

The Origin that signs the JWT Auth Token is set via the `JWTTokenHandler.getRequestOrigin()` method in this PR...it uses several different sources, accepting the first one that is not empty.  First, it checks the `Origin` header, then the `Referer` header, then our custom `X-DSpace-UI` header and *finally* if none of those have values it uses the `?redirectUrl` param that Shibboleth tends to use.  

Strangely, in your example, it *looks* like the `redirectUrl` param also uses "https://myhost.pt", which means it should match the Origin of your UI.  So, that makes me wonder if your Shibboleth is passing back an `Origin` or `Referer` HTTP Header that is being used instead.  I notice in the **second** example, your `Request` includes `Referer: https://login-conta-dev.ciencia-id.pt/`.... Maybe it's possible that's the Origin being used to sign the JWT token (that's just a guess though).

If you wanted to, you could enable debug logging and look for a DEBUG message that says "Using Origin '[ ]' for token signing key..." (as that's the Origin that originally signs the JWT, see `JWTTokenHandler.buildSigningKey()` method in this PR.   My guess is that *might* report that the token is being signed by `https://login-conta-dev.ciencia-id.pt`....which means that when `https://myhost.pt` tries to use the same token, it gets blocked.

All that said, I'm not yet sure how to solve this.  I didn't expect Shibboleth to return an Origin or Referer Header...and if it did, I expected the Referer to point back at the DSpace UI (as that's what started the request off).  Your logs here seem to imply that the `Referer` _might_ sometimes point at the Shibboleth server (I'm assuming that's what https://login-conta-dev.ciencia-id.pt is) ....which might mean we need to *ignore it* when Shibboleth is enabled.

**Comment by atarix83** [comment]
@tdonohue 

I did some test on our dev server (https://dspace7test.dev01.4science.cloud/) and it doesn't seem to work properly, Indeed both password ans shibboleth authentications work only if i configure `jwt.login.token.include.origin = false` in the `local.cfg` file.
Also trying to authenticate from my local angular application to remote server works only with `jwt.login.token.include.origin = false` even if I've added `http://localhost:4000` to `rest.cors.allowed-origins` property

**Comment by tdonohue** [comment]
@paulo-graca and @atarix83 : I've just pushed up a major fix which I hope will resolve issues with Shibboleth (I've also verified that Password Auth now works again from the UI or from the HAL Browser).  This fix adds more logic to the `ShibbolethLoginFilter` (renamed from `ShibbolethAuthenticationFilter`) which determines when a Shib redirect is going to occur, so that the Auth Token can be signed with the Shib `redirectUrl` as the Origin.  This ensures that the Auth Token is not accidentally signed with the wrong Origin (which was previously resulting in the UI not being able to use the token when `jwt.login.token.include.origin = true`).

Overall, I *think* this newly pushed up code should fix things for Shibboleth (based on my analysis of the logs/headers that @paulo-graca previously shared above).  As noted, I've already verified it fixes issues with Password auth as well.

If you two could find time to retest this in the next week, I'd appreciate it.  Thanks!

**Comment by paulo-graca** [comment]
Password authentication works for me with most recent changes.

**Comment by paulo-graca** [comment]
Didn't change `jwt.login.token.include.origin`. It's as is. The default setting.

But it doesn't work with Shibboleth authentication:
`POST` `https://dev5.rcaap.pt/Shibboleth.sso/SAML2/POST`
image

and the 401 error (didn't happen to see this error yet):
GET https://myhost.pt/server/api/authn/shibboleth?redirectUrl=https://myhost.pt/home
image

**Comment by paulo-graca** [comment]
With `jwt.login.token.include.origin = false` the result is the same as above.

**Comment by paulo-graca** [comment]
The same 401 error occurs also with HAL Browser, but after refreshing the page, I'm sign in:
image

**Comment by tdonohue** [comment]
Closing, replaced by #3103.  I've figured out a way to simply enable CSRF Protection in Spring Security with customizations to allow it to work for Shibboleth & cross domain. Therefore, this "tighten security" approach is no longer necessary.  That said, some minor useful code comments, etc from this PR will be copied into #3103

**Pull request closed without merging**
