### PR TITLE
DS-4438 Respect client-provided projections for non-GETs

### PR DESCRIPTION
**Pull request by cwilper**
https://jira.lyrasis.org/browse/DS-4438

This PR reverts "quick fix" PR: https://github.com/DSpace/DSpace/pull/2682 in favor of updating all relevant REST requests to support a client-provided projection parameter.

Prior to this, projections were only respected for GETs. Now, it's supported for POSTs and other verbs.

This should be merged AFTER the following, related PR is merged for Angular: https://github.com/DSpace/dspace-angular/pull/584

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@cwilper : The code here looks good to me, and I appreciate the extra ITs to prove that projections are working as expected.

However, I ran into what looks like a bug in testing this.  Starting a new submission works, and editing an existing submission works.  But, clicking on "Deposit" to complete a submission results in an error.

In Chrome's DevTools, I'm seeing that the "Deposit" button sends a `POST` to `http://localhost:8080/server/api/workflow/workflowitems?projection=full` which returns a `422` status code, with this exception:
```
org.dspace.app.rest.exception.UnprocessableEntityException: The given URI list could not be properly parsed to one result
at org.dspace.app.rest.repository.WorkflowItemRestRepository.createAndReturn(WorkflowItemRestRepository.java:143)
```

**Comment by cwilper** [comment]
@tdonohue we were able to reproduce this issue and confirmed it is happening in `master` as well. Even when the associated recent angular PR (for force projection=full for submission-rest calls) is reverted. This makes me wonder how far back the breakage goes. @AndrewZWood is investigating and we'll report back any findings.

**Comment by tdonohue** [comment]
@cwilper : FWIW, I doubt the breakage goes back very far.  I recall testing the submission completion process when testing https://github.com/DSpace/DSpace/pull/2682 (the quick fix REST PR), and that was merged on Feb 19.  I admit though, I'm not sure I've testing submission completion again until now though.

**Review by tdonohue — APPROVED** [review]
👍 Code looks good and it improves behavior on `master`.  As noted in the comments above, there are still issues with completing a submission, but that's a separate bug tracked in https://github.com/DSpace/dspace-angular/issues/592 

So, in my opinion, this is ready to merge

**Comment by tdonohue** [comment]
We decided in today's DevMtg that this needs only one approval. Merging.  Thanks @cwilper  for your continued hard work on improving Projections!

**Pull request merged**
