### PR TITLE
[DS-3056] added and configured xml-maven-plugin to validate all XML 

### PR DESCRIPTION
**Pull request by hardyoyo**
[DS-3056](https://jira.duraspace.org/projects/DS/issues/DS-3056): Validate all XML and XSL files during the testing phase, using the [xml-maven-plugin](http://www.mojohaus.org/xml-maven-plugin/) to check for well-formed-ness.

### CODE REVIEW

**Comment by aschweer** [comment]
As I mentioned on github - would it work to include *.xmap (sitemaps!) and *.xconf (though admittedly it looks like that's just xmlui.xconf at this point) files in the validation sets?

**Comment by helix84** [comment]
+1, tested

**Comment by hardyoyo** [comment]
I've merged this change into my own fork of DSpace, it has already helped avert a situation where a contributor made a PR with malformed XML. They saw the failed Travis-CI build, made a revision, and now their PR is ready for merging.

**Comment by mwoodiupui** [comment]
+1 by inspection

**Pull request merged**
