### PR TITLE
DS-3409 Handle of collections and communities are lost

### PR DESCRIPTION
**Pull request by arvoConsultores**
https://jira.duraspace.org/browse/DS-3409

During migration this sql dont update handles for communities and collections

### CODE REVIEW

**Comment by helix84** [comment]
Thanks for the fix. But we can't change a migration that was already released because it won't run again. We need to make this a new migration.

**Comment by arvoConsultores** [comment]
Extracted to external file, but is not tested. 
If other sql use the collection or community uuid from the V6.0_2015.03.07__DS-2701_Hibernate_migration.sql ant this sql will get a null value and can have unpredictable results

**Review by mwoodiupui — APPROVED** [review]
I tested this and it appears to work.  +1

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me at a glance. This looks ready to merge, as it's been tested/reviewed.

**Comment by cidus** [comment]
Hello,
I don't see these changes in either 6.1 or 6.2 tag, even though it's in the 6.1 milestone. Why is that? Still having issues migration Dspace installation with Oracle.
Sorry if this is the wrong place to ask...

**Pull request merged**
