### PR TITLE
DS-1995: JSPUI Bootstrap dropdowns don't display properly in IE8 or 9

### PR DESCRIPTION
**Pull request by kardeiz**
See https://jira.duraspace.org/browse/DS-1995 for details.

This PR:
1. Removes the CSS `filter` rules on the header navbar which are causing the dropdown to display incorrectly.
2. Adds Paul Irish's conditional comments hack which allows specific IE versions to be targeted.
3. Adds a `background-image` rule for the header navbar targeting IE9 only, which provides a SVG gradient similar to that provided by the vendor-prefixed `background-image` gradients. IE8 does not support SVG, so it is not targeted. With this PR, IE8 displays the header navbar with the default `background-color`.

I'm not very active in this community, and I've never submitted a pull request before, so hopefully I'm doing this right...

### CODE REVIEW

**Comment by aschweer** [comment]
Marking as milestone 5.2 since the Jira ticket has fix version = 5.2. Though I note that there is an alternative (much smaller) change suggested in the Jira comments, so this may have to be put off to a later version while we investigate what solution is better.

**Comment by pnbecker** [comment]
While I haven't tested one or the other solution, I don't like the idea of removing the html tag and putting it in browser specific commented code.  The solution in the Jira ticket is a one liner in css without touching the html structure.

**Comment by kardeiz** [comment]
I agree that this PR is overkill for the sake of a gradient in the navbar and shouldn't be merged as is.

I just took a [quick look](https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap-theme.css) and Bootstrap latest has changed some of the `.navbar-inverse` style rules, so this may not even be an issue anymore if the Bootstrap version is updated (I haven't had a chance to test it).

**Comment by pnbecker** [comment]
I close this PR as @kardeiz agreed that it is overkill. Another idea is documented in Jira (https://jira.duraspace.org/browse/DS-1995).

@kardeiz: Please don't hesitate to create a new PR with a simpler solution, maybe following the idea in Jira.

**Pull request closed without merging**
