### PR TITLE
Add support for the primary bitstream flag

### PR DESCRIPTION
**Pull request by Micheleboychuk**
**_Please note that this development has been funded by the University of California - California Digital Library._**

## References
Related to https://github.com/DSpace/DSpace/issues/8834
Rest Contract PR: https://github.com/DSpace/RestContract/pull/242
Angular PR: https://github.com/DSpace/dspace-angular/pull/2631

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
Thanks @Micheleboychuk !  I gave this a code review today and tested it with the frontend PR.  Overall, it looks good and I'm not finding any obvious bugs.   I just have a very minor request to add a few more integration tests... but if I'm overlooking them, let me know.

(I'm essentially +1 this PR overall, just wanted you to review my comments on the ITs)

**Comment by tdonohue** [comment]
@Micheleboychuk : Just a friendly reminder that, if you can find time to address my feedback, this PR is nearly ready to merge.  The [frontend PR also is almost ready](https://github.com/DSpace/dspace-angular/pull/2631#pullrequestreview-1881454305), so it'd be good to get these merged together.

**Comment by tdonohue** [comment]
@Micheleboychuk or @abollini :  Sorry to pester about this PR.  But, it looks like the frontend PR is ready to go now.  However, I cannot merge it until the feedback in this PR has been addressed.  I believe this PR just needs a single IT added as [described above](https://github.com/DSpace/DSpace/pull/9195#discussion_r1471933908).

Once that IT is added, then I can merge both PRs.

**Comment by Micheleboychuk** [comment]
@tdonohue 
Sorry for the delay.
 I've added the missing tests.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @Micheleboychuk !

**Pull request merged**
