### PR TITLE
fix for #9311: set default configFile

### LINKED ISSUE #9311: CLI dspace stats-log-converter is failing with undefined configFile
**Describe the bug**
We are currently leaving legacy DSpace 5.X in favor of DS7 with completely new infrastructures. We had some statistical stored as logs that we want to recover and ingest it on the new system. But for the tests running so far, we can execute `stats-log-converter` command on DS5, but that same exact command doesn't work for DS7.

**To Reproduce**
1. Perform a 
```
/dspace/bin/dspace stats-log-converter -n -v -i dspace.2015-12-17.log-20151222 -o dspace-converted
```

An exception occurs:

```
Exception: null
java.lang.NullPointerException
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:149)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.base/java.io.FileReader.<init>(FileReader.java:60)
        at org.dspace.app.statistics.LogAnalyser.readConfig(LogAnalyser.java:986)
        at org.dspace.app.statistics.LogAnalyser.readConfig(LogAnalyser.java:956)
        at org.dspace.statistics.util.ClassicDSpaceLogConverter.main(ClassicDSpaceLogConverter.java:338)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:283)
        at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:134)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:99)
```

**Expected behavior**
Digging a little bit, the error is related with configFile that is set as null.

```
    /**
     * the configuration file from which to configure the analyser
     */
    private static String configFile;
```

and this call:

    public static void readConfig() throws IOException {
        readConfig(configFile);
    }

when configFile is undefined.

The expected result was a csv file with the extracted content ready to be used with:
```
[dspace]/bin/dspace stats-log-importer
```

for ingesting log data into Solr.

**Related work**
[Link to any related tickets or PRs here](https://github.com/DSpace/DSpace/issues/2852)

### PR DESCRIPTION
**Pull request by IgorBaptist4**
## References
* Fixes #9311

## Description
fix stats-log-converter command that was throwing a NullPointerException because the configFile is not set properly

List of changes in this PR:
Adds default value to configFile variable in DSpace/dspace-api/src/main/java/org/dspace/app/statistics/LogAnalyser.java

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR **passes Checkstyle** validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR **includes Javadoc** for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR **passes all tests and includes new/updated Unit or Integration Tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by IgorBaptist4** [comment]
@tdonohue The command stats-log-converter works with this changes, but no events are recorded, because of the difference between formats in the logs of the 6x and the 7x later versions. Is needed to change the regex on this lines https://github.com/DSpace/DSpace/blob/a5e8d7aa15bc56c268ba67f19657f19edaa45253/dspace-api/src/main/java/org/dspace/app/statistics/LogAnalyser.java#L898 to make it record events.

I just changed the regex on the logLine13 variable to make it works with the 7x format, I did it locally and was able to record events, should I put this into this pr? Open another issue and pr for this part?

Maybe should change the code to receive a param to identify which version log is being converted and keep both regex for 6x and 7x~ ? What you think about it

here is the regex for 7x~ versions in case you want to test it out:
String logLine13 = "^(\\d\\d\\d\\d-\\d\\d-\\d\\d) \\d\\d:\\d\\d:\\d\\d,\\d\\d\\d (\\w+)\\s+\\S+\\s+\\S+\\s+\\S+\\s+@\\s+([^:]+)::([^:]+):([^=]+=[^/].*)$";

**Review by nwoodward — APPROVED** [review]
Thanks @IgorBaptist4! I tested and confirmed this fixes the bug. It's an easy win. The `configFile` should be set to a default value, and that isn't happening when `LogAnalyser` gets instantiated in some other classes.

I agree that the issue described in https://github.com/DSpace/DSpace/pull/9815#issuecomment-2341475951 is a problem that needs to be fixed, but I think it should be done in a separate GitHub issue to track the work.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @IgorBaptist4 !  This looks good to me too

**Comment by IgorBaptist4** [comment]
Thanks @nwoodward and @tdonohue! I just opened a new issue to fix the problem mentioned above in the https://github.com/DSpace/DSpace/pull/9815#issuecomment-2341475951 here is the link https://github.com/DSpace/DSpace/pull/10168

**Pull request merged**
