### PR TITLE
[DS-2714] Oracle migration script for the service based api

### PR DESCRIPTION
**Pull request by KevinVdV**
Oracle migration changes

### CODE REVIEW

**Comment by tdonohue** [comment]
:+1: Looks reasonable. I haven't tested it yet, but the code changes themselves make sense to me.

**Comment by KevinVdV** [comment]
It would be great if prior to merging somebody else could test it with both postgres & oracle. Just to be sure.... Testing can just be to create a comm/coll/item from the XMLUI.

**Comment by pnbecker** [comment]
I tried to update from DSpace 5.3 on postgres with this PR. Beside some problems with discovery (which I think I got fixed by rebuilding the index) everything works fine. I haven't tested a fresh install with this PR.

+1

**Comment by peterdietz** [comment]
People are +1 on this, we can merge, and resolve issues that arise as a result.

**Pull request merged**
