### PR TITLE
Fixed: Clear metadata if value has not set. Reference issue no #1612

### LINKED ISSUE #1612: Clearing bitstream description leaves and empty dc.description entry for the bitstream
**Describe the bug**
Clearing description of bitstream via UI leave an empty dc.description metadata entry. Is this intentional rather than fully removing the entry?

**To Reproduce**
1. Edit any bitstream via the Edit item section
2. Clear the description
3. Check via the API HAL browser
Example item: https://api7.dspace.org/server/api/core/bitstreams/5415158c-ee79-4313-b150-296b6c1b5556/ and https://demo7.dspace.org/items/ca791d64-2dff-47ab-ad80-a42f8c5756cb/edit

**Expected behavior**
The metadata entry for "dc.descrition" is fully removed from the bitstream's metadata.

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by md1222**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes https://github.com/DSpace/dspace-angular/issues/1612

## Description
Worked on DSpacemetadataReplaceOperation to handle empty value. Code will check value and then perform operation according to value.

## Instructions for Reviewers
To test just edit bitstream, clear the description field and update. And then see bitstream API you will see their is no any description field. Previously it was returning with null value.
/server/api/core/bitstreams/<bitstreamid>

### CODE REVIEW

**Comment by tdonohue** [comment]
@md1222 : Thanks for submitting a PR!  However, it looks like this small change has a couple issues to be resolved before we can move it forward:

1. It has checkstyle violations in the style of the code.  You can run `mvn -U checkstyle:check` from the commandline to see them. For more on checkstyle requirements see https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide
2. This small change also results in several Integration Test failures.  You should be able to see them locally by running the Integration tests: https://github.com/DSpace/DSpace/#running-tests   It's unclear why they are all failing, but it appears that a number of tests that clear metadata are now throwing 500 errors.... which implies there may be a bug in the code of this PR.

**Comment by md1222** [comment]
@tdonohue,

Yes sir, we are working on it. Will provide fix very soon.
Thank you.

**Review by abollini — CHANGES_REQUESTED** [review]
The proposed change would fix the issue but it is not aligned with the JSON Patch specification.
The replace operation should not be used to perform a delete. An empty value should be rejected with a 422 error assuming that the json payload is still valid. Indeed, according to the specification a replace with an empty or null value should perform as in the current implementation except that DSpace has the business rule to avoid empty metadatavalue. So a 422 error would be appropriate.

The noted issue is actually two different issues
- REST side, a replace with an empty value should fail with 422
- Angular side, an empty value should be rejected without performing the patch request or eventually if we want to support this behavior it should translate the empty value in a delete patch operation instead than a replace

**Comment by md1222** [comment]
> Moving this to 7.6 as it doesn't appear it will be ready in time for 7.5. Feedback in this comment needs to be resolved/answered: [#8645 (review)](https://github.com/DSpace/DSpace/pull/8645#pullrequestreview-1273988602)

Sorry for the late reply,

> The proposed change would fix the issue but it is not aligned with the JSON Patch specification. The replace operation should not be used to perform a delete. An empty value should be rejected with a 422 error assuming that the json payload is still valid. Indeed, according to the specification a replace with an empty or null value should perform as in the current implementation except that DSpace has the business rule to avoid empty metadatavalue. So a 422 error would be appropriate.
> 
> The noted issue is actually two different issues
> 
> * REST side, a replace with an empty value should fail with 422
> * Angular side, an empty value should be rejected without performing the patch request or eventually if we want to support this behavior it should translate the empty value in a delete patch operation instead than a replace.

Sir, I studied based on your comment and found that we should work on angular side, currently it's sending replace to perform operation for all the cases(update/null) , so if we send delete patch operation it will be good to handle null value.

We are working on it to handle on angular side.

**Comment by tdonohue** [comment]
Closing this PR as it's replaced by a new dspace-angular PR: https://github.com/DSpace/dspace-angular/pull/2112

**Pull request closed without merging**
