### PR TITLE
Cannot claim PoolTasks created before you were added to a workflow approval group

### LINKED ISSUE #3175: Cannot claim PoolTasks created before you were added to a workflow approval group
**Describe the bug**
It's currently not possible to claim a PoolTask if that PoolTask was created prior to your being added to the workflow group with access to that PoolTask.

**To Reproduce**
Steps to reproduce the behavior:  (It's easiest to reproduce via the UI)
1. Login as an Admin & Create a Collection with Workflow enabled
2. Submit several Items into that Collection (creating 2+ PoolTasks)
3. Now, add a *new* EPerson to the list of reviewers for that Collection
4. Login as that new EPerson, go to "My DSpace", Show: "All Tasks".  You'll see the 2+ PoolTasks in your list of items to review.
5. Click "Claim" next to one of the PoolTasks.  You'll get a `403 Access is denied` exception, with the following underlying error:
    ```
    org.dspace.app.rest.exception.RESTAuthorizationException: org.dspace.authorize.AuthorizeException: You are not allowed to to perform this task.
    ```
6. Now, login as an Admin again & submit a new Item to that same Collection (creating another PoolTask)
7. Login as the new EPerson (created in step 3).  You'll be able to claim that newly created PoolTask successfully.

**Expected behavior**
As in DSpace 6, Configurable Workflow should allow you to claim PoolTasks which were created before you were given reviewer rights.

Tests should also be added to prove that a newly added reviewer can immediately claim existing PoolTasks.

### PR DESCRIPTION
**Pull request by Micheleboychuk**
## Description
Fixes #3175

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by Micheleboychuk** [comment]
@tdohunue I have tried to reproduce the issue without success... maybe the error were due to other issue that have been resolved since your test, anyway we have worked on the issue and added a test that proof that there is no issue at least on the rest side.

**Comment by jonas-atmire** [comment]
@Micheleboychuk Seems like the last round of merges yesterday has created a merge conflict with your piece of code.
Could you resolve these conflicting files please, so we can have a 'clear' state to review against, thanks.

**Comment by Micheleboychuk** [comment]
Thanks @jonas-atmire , I have resolved the conflict.

**Review by tdonohue — APPROVED** [review]
👍 @Micheleboychuk : Thanks for retesting & writing this test to verify the functionality.  After further testing on my end, I realized it was the fault of an "ignored" database migration that I had forgotten to run on my test database -- [namely this one](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.0_2019.05.02__DS-4239-workflow-xml-migration.sql).  

After running the migration, everything works perfectly & I'm no longer able to reproduce the issue either.  Thanks for creating a test here though to ensure we don't break this functionality in the future

**Comment by jonas-atmire** [comment]
@Micheleboychuk, thanks for the update.
I've subsequently also gone through the entire testing of [the issue](https://github.com/DSpace/DSpace/issues/3175) and the feature works as expected.
A user that is added AFTER the item is added to the pool, can claim that particular item, and go through the workflow steps

**Review by jonas-atmire — APPROVED** [review]
@Micheleboychuk 
Thanks for the update of the code with the latest main codebase.

I've setup the last main REST/Angular locally, and the feature now indeed works as expected 
An item that was put in the workflow pool is 'claimable' by a user that is added to the related workflow group after the actual item was created.
(All related actions are also available to the user)

As Tim mentioned, these tests will also help us in the future to keep this feature properly tested/ up to date

**Pull request merged**
