### PR TITLE
[DS-2900] Java date format usage as static variable is not thread safe

### PR DESCRIPTION
**Pull request by KevinVdV**
https://jira.duraspace.org/browse/DS-2900

### CODE REVIEW

**Comment by helix84** [comment]
We might also consider migrating to Java 8's java.time. Not sure if Java 7 compatibility could be kept at the same time using Joda-Time.

**Comment by mwoodiupui** [comment]
IIRC java.time and Joda Time do much the same things, but with different signatures and organization.

**Comment by tdonohue** [comment]
+1 via code review. Looks reasonable. Does this still need a test?

**Comment by KevinVdV** [comment]
@tdonohue Shouldn't be to hard to test one or two of the classes. The code is the same all over so if you test a couple of instances & these work we can rest assured that the rest will work.

**Comment by hardyoyo** [comment]
+1 by review

**Comment by tdonohue** [comment]
As a sidenote, I ran some basic tests of the logic and found that it worked (e.g. when using the `org.dspace.eperson.Groomer` commandline tool). Just wanted to note this did get some basic testing

**Pull request merged**
