### PR TITLE
MediaFilter over large repository result in downtime

### LINKED ISSUE #9272: MediaFilter over large repository result in downtime
**Describe the bug**
If you attempt to run the filter-media script over a large repository is really likely to cause a downtime.
The issue is related to the fact that during the execution that could take also days in some scenario (milions of files to process) a single database transaction is keep open and as soon as an item is processed the pending update query put a lock on the database preventing also the normal access to the information from the REST API/UI.

**To Reproduce**
1. If you have a large repository you can run the script, better in force mode as this would force all the item to be re-processed taking the process longer
2. look to the log to see which items have been processed, you will be unable to access it via the UI

alternatively you can hack the code a bit or use your IDE to pause the execution of the filter-media process after having processed a couple of item. You can also monitor your DB to see the evidence of that is described above.

Please note that the updates are written to the transaction as soon as an item is processed as we uncache the item to avoid memory issue, this require the hibernate session to flush. Of course, we cannot (and should not) remove this uncache but also doing that there is no guarantee that Hibernate will not flush the session when it becomes to huge.

This issue is also related to https://github.com/DSpace/DSpace/issues/8731

**Expected behavior**

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by abollini**
## References
* Fixes #9272 
* Related to https://github.com/DSpace/DSpace/issues/8731

## Description
I have introduced a utility iterator that keeps the list of the DSpace objects' UUID returned by a query retrieving the `next()` object individually when needed. In this way the database resources are freed as soon as possible without keeping a result set open while iterating. This is the solution that we have recently adopted in DSpace-CRIS.

Having a result set open is problematic because it prevents us to commit while iterating that in turn means to make the db transaction long with lock at the database level.

We don't need to worry about memory issues, as this approach is usually much more efficient than the current one because the database results are reduced to just the UUID and a list of 1M UUIDs in memory only takes a few megabytes.

## Instructions for Reviewers
The easier way to review this PR is to look to the source code changes, the commit have been performed to help the reviewer to verify the appropriateness of the introduced changes

1. https://github.com/DSpace/DSpace/commit/2227d14e9f9d07fe0198f32f659daf146d5588e7 introduces an IT for the MediaFilterScript that was not previously covered by test, result of the build (success) are visible here https://github.com/abollini/DSpace/actions/runs/7595083847
2. https://github.com/DSpace/DSpace/commit/4dd3120cc5ce58544c3a9b4270ff8b0d8a3ede01 introduces the commit after that an item has been processed to unlock the database row / transaction. The build, visible here https://github.com/abollini/DSpace/actions/runs/7595151201 , is failing due to the expected issue due to the attempt to access a closed result set
3. https://github.com/DSpace/DSpace/commit/729e3898db5f8803bb5e95d321b2d83a6fb20332 introduces the UUIDIterator, the build show that it solves the problem when we are iterating over all the items https://github.com/abollini/DSpace/actions/runs/7595321386/job/20687749715#step:4:621 (first test pass the other three fail) but test that involve visit the communities and collections are still failing
4. last commit https://github.com/DSpace/DSpace/commit/29fa7379778746e9827e15cb64492651941e61e8 shows how to fix the issue when the bulk operation is traversing the DSpace hierarchy while committing

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [n/a] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [n/a] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [n/a] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
_Quick note:_  I'm hoping to get to test/review this once we get more features merged/ready to merge for 8.0.  At a very quick glance, I like the overall direction here. It does seem like the performance improvements in this PR (namely the `UUIDIterator`) would extend _beyond MediaFilters_. 

That all said, I think we need to pay close attention to whether the `UUIDIterator` change requires updating **other commandline scripts** to ensure they work in the same way.  Basically, we should test how other scripts may be affected by this PR.  It's a good sign that all ITs pass...but not every CLI script has ITs at this time.

**Comment by mwoodiupui** [comment]
Agreed that we need to ensure that this custom Iterator works wherever it is returned.  But this patch does a good job of hiding the clever bit inside the Iterator.  I don't see how it would break.

**Review by mwoodiupui — APPROVED** [review]
+1 by inspection.

**Comment by tdonohue** [comment]
@abollini : The code looks good in this PR.  I went to test it out today, but I cannot get it to compile when merged on top of the latest `main`.  I suspect some other change has caused a code conflict in this PR which isn't being recognized by GitHub.

When you have a moment, could you rebase this on latest `main` to ensure it's compiling again?  No rush, as we can always merge this after the feature freeze if needed.

**Comment by abollini** [comment]
@tdonohue  done, let's see if the build pass. Locally I'm able to `mvn clean package` and execute the new tests

**Review by tdonohue — APPROVED** [review]
👍 Thanks @abollini  !  I had a chance to fully test this today and it works well.  I see no behavioral change to the filter-media scripts.  Code looks good too.  I'll see if this can be auto-ported to 7.x as well.

**Comment by tdonohue** [comment]
@abollini : The port to 7.x failed cause of merge conflicts (see above).  Could you create a manual port of this for the `dspace-7_x` branch?  This seems like a bug that we should fix in 7.x as well.

**Pull request merged**
