### PR TITLE
DS-2871 remove Modernizer from Mirage; it's unused

### PR DESCRIPTION
**Pull request by helix84**
https://jira.duraspace.org/browse/DS-2871

### CODE REVIEW

**Comment by terrywbrady** [comment]
@helix84 , Moderizr appears to be used here https://github.com/DSpace/DSpace/blob/master/dspace-xmlui-mirage2/src/main/webapp/scripts/forms.js#L11

**Comment by kshepherd** [comment]
@terrywbrady it is used by mirage2, but it's referred to in that theme at https://github.com/DSpace/DSpace/blob/master/dspace-xmlui-mirage2/src/main/webapp/xsl/core/page-structure.xsl#L268

@helix84 's PR just removes modernizr from Mirage, not MIrage2, so i think this is all OK.

+1 from me!

**Comment by terrywbrady** [comment]
Sorry for the delayed response, +1 from me as well.

**Comment by tdonohue** [comment]
Merging. Looks good to me as well, already at +2.

**Pull request merged**
