### PR TITLE
Fix Item Counts (webui.strengths) by refactoring ItemCounter and ItemCountDAO to act like other Spring beans

### LINKED ISSUE #9434: Item Counts (webui.strengths): Cached Counts Not Updating
**Describe the bug**
Cached item counts are not updating (unless Tomcat is restarted). (Edited to add version **7.6.1**)

**To Reproduce**

1. Log in to the demo instance as an administrator: https://demo.dspace.org

2. Navigate to an existing community with a small collection, such as: https://demo.dspace.org/communities/bd0943b0-1c46-4980-b831-f9300e4740e2. Note the item count badges for the community and the collection (in this example, as of this moment, 0). Observe that there are actual items in the collection. 

3. Add some new items to the small collection: https://demo.dspace.org/collections/55a12ef1-cecc-4005-8f65-d0a4d17644ce

4. Run the index-discovery process, check item count badges again, they have not changed (still 0 as of this moment). 

5. Log out, navigate away, clear browser cache, reload in new window, and/or open in incognito mode. Check the item count badges again. They have not changed. 

6. On my test instance, if I restart the Tomcat service, the item counts update immediately.

**Expected behavior**
Item counts, even cached item counts, should update after discovery job and/or after full reload triggered by new window, logout, clearing browser cache, etc.

### LINKED ISSUE #9437: Item Counts (webui.strengths): Live Counts Break the Community List
**Describe the bug**
Live item counts prevent the community list from loading in 7.6.1

**To Reproduce**
1. Enable live item counts in the config file (set webui.strengths.show = true and webui.strengths.cache=false) and restart Tomcat.
2. Reload the home page. 
3. Communities & collections will not load, although recent submissions do load as expected. 
- GUI errors include: "Error fetching collection" and "error.top-level-communities". 
- Console and dspace.log state: 
```
java.lang.NullPointerException: Cannot invoke "org.dspace.core.DBConnection.getSession()" because the return value of "org.dspace.core.Context.getDBConnection()" is null
        at org.dspace.core.AbstractHibernateDAO.getHibernateSession(AbstractHibernateDAO.java:59) ~[dspace-api-7.6.1.jar:7.6.1]
        at org.dspace.core.AbstractHibernateDAO.createQuery(AbstractHibernateDAO.java:137) ~[dspace-api-7.6.1.jar:7.6.1]
        at org.dspace.content.dao.impl.ItemDAOImpl.countItems(ItemDAOImpl.java:395) ~[dspace-api-7.6.1.jar:7.6.1]
        at org.dspace.content.ItemServiceImpl.countItems(ItemServiceImpl.java:1589) ~[dspace-api-7.6.1.jar:7.6.1]
        at org.dspace.browse.ItemCounter.getCount(ItemCounter.java:131) ~[dspace-api-7.6.1.jar:7.6.1]
        at org.dspace.content.CommunityServiceImpl.countArchivedItems(CommunityServiceImpl.java:723) ~[dspace-api-7.6.1.jar:7.6.1]
        at org.dspace.content.Community.countArchivedItems(Community.java:275) ~[dspace-api-7.6.1.jar:7.6.1] ...
```
(etc)

**Expected behavior**
Normal home page should load showing top-level communities and accurate item-count badges. 

**Related work**
Cached item counts are inaccurate but the system is still useable: https://github.com/DSpace/DSpace/issues/9434

### PR DESCRIPTION
**Pull request by tdonohue**
## References
* Fixes #9437
* Fixes #9434 

## Description
This PR refactors the `ItemCounter` and `ItemCountDAO` to be Spring beans defined in `core-services.xml`.  This fixes issues with Item Counts not reloading & issues where it was not possible to use live, database-based counts (via `webui.strengths.cache=false`).

This refactor involved the following:
* Define both `ItemCounter` and `ItemCountDAO` as beans in `core-services.xml`
    * Remove `ItemCountDAO` configuration from `dspace.cfg` as it is now configured via `core-services.xml`
* Remove caching of `Context` object in `ItemCountDAO`.  This resulted in database connection errors when the Context was outdated
* Remove duplicative `countArchivedItems()` methods from `Community` and `Collection` as these were just wrappers around the same methods in `CommunityService` and `CollectionService`.
* Update code to latest standards (minor code cleanup & autowiring of all necessary service classes)
* Remove unnecessary `ItemCountDAOFactory` and `ItemCountException` (the exception handling was updated to use log.error as otherwise item counting exceptions would crash the UI).

## Instructions for Reviewers
* Deploy PR
* Ensure #9434 is fixed by doing the following:
    * Set `webui.strengths.show = true` and `webui.strengths.cache=true` on the backend. This tells the backend to use Solr for all Item Counts
    * In the UI, Look at the current item count for any Collection and its parent Community(ies)
    * Submit a new Item to that Collection.
    * Once item is archived, ensure the Collection item count & parent Community item counts increase by one.   This should happen almost immediately, but a reload of the page may be required.
* Ensure #9437 is fixed by doing the following:
    *  Set `webui.strengths.show = true` and `webui.strengths.cache=false` on the backend.  This tells the backend to use the Database for all Item counts.
    * In the UI, ensure Item Counts on homepage & Community/Collection lists all still work & are accurate.  (Currently, on `main` and `dspace-7_x` they will throw errors as described in the ticket)

### CODE REVIEW

**Comment by damian-joz** [comment]
Hi @tdonohue, I've started testing phase. I've noticed that when item is withdrawn, the counter still include it. I've done some small fix for that. Can I push it directly to your branch?

**Comment by tdonohue** [comment]
@damian-joz : If GitHub allows you to push to my branch, then please feel free.  If it doesn't allow you, then you could send me a PR to my branch (by creating at PR against my GitHub account: https://github.com/tdonohue/DSpace), or send me the code.

Thanks for testing & for finding a fix to the issue you discovered!

**Comment by damian-joz** [comment]
@tdonohue  I've created a PR to your branch. I've also tested a few scenarios:
- adding a new item
- withtdrawing an item
- making an intem non-discoverable
- moving item from one collection to another
- deleting item
- mapping item to another collection,

both for cache(Solr) and non cache solution(Database query) and it works fine. Sometimes it required the refresh of the UI.

Just one thing worth to mention, when we will map item to another collection we end up with something like this:
image. And for some users it can be confusing because community counter is not even with the sum of collection counters. However it is ok because Collection 1 has 3 items with one item shared between collections.

**Review by damian-joz — APPROVED** [review]

**Comment by tdonohue** [comment]
I've merged the improvements that @damian-joz made in https://github.com/tdonohue/DSpace/pull/15 to this branch.  Those are now included in this PR.

As @damian-joz has given approval (thanks!), I'll give this another test on my end to make sure everything still works well (after this most recent update).  Assuming everything is working well, I'll get this merged for 8.0 and backported to 7.x

**Review by tdonohue — COMMENTED** [review]
Retested this again today and verified that @damian-joz 's changes work well.  Non-discoverable items are no longer included in counts.  Additionally, withdrawn items are no longer included in counts.  When withdrawing an Item or making it undiscoverable, the counts for parent collections/communities update almost immediately.

So, I think this all looks good!  Merging for 8.0 and backporting to 7.x

**Pull request merged**
