### PR TITLE
DS-2316 Wrong visualization of files in detail view of ORE items in Mirage 2

### PR DESCRIPTION
**Pull request by rivaldi8**
Fixes https://jira.duraspace.org/browse/DS-2316

### CODE REVIEW

**Comment by aschweer** [comment]
I've given this the milestone 5.2 since the corresponding Jira ticket is marked fix version = 5.2. However, it looks like this may need some more work / review, so it may need to be rescheduled.

**Comment by hardyoyo** [comment]
+1 rescheduling

**Review by tdonohue — CHANGES_REQUESTED** [review]
Needs rebasing or recreating to move forward.

**Comment by tdonohue** [comment]
Closing as this PR must be recreated on `dspace-6_x` branch. XMLUI has been removed from `master`. See this mailing list notice: https://groups.google.com/d/msg/dspace-devel/aEFqSn46ryM/iPRr_IMLCwAJ

**Pull request closed without merging**
