### PR TITLE
[Port to dspace-7_x] Enforce resource policies to have group or eperson

### LINKED ISSUE #9190: Resource policies with null groups and eperson
**Describe the bug**
The DSpace code currently does not enforce that a created resource policy has either a connected group or eperson. 
As a consequence, it can happen that a resource policy is created with neither. 

This will then cause issues down the line where DSpace assumes that all resource policies have either a group or eperson connected to it. 

**Expected behavior**
It should not be possible to have resource policy objects in the 

**Related work**
Fixed in #9191

### PR DESCRIPTION
**Pull request by YanaDePauw**
## References
* Fixes #9190 
* Main version: #9502

## Description
The DSpace code currently does not enforce that a created resource policy has either a connected group or eperson.
As a consequence, it can happen that a resource policy is created with neither.

This will then cause issues down the line where DSpace assumes that all resource policies have either a group or eperson connected to it.

## Instructions for Reviewers
Verify that it is no longer possible to create a resource policy without a group or eperson. 

## Checklist
- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@YanaDePauw : This is currently failing tests & appears to have compilation errors.  I suspect the new code refactors have not been applied everywhere in the codebase

**Comment by YanaDePauw** [comment]
@tdonohue Is it possible that there is some caching happening for the code? The reported compile issue does not actually occur in the code. Furthermore the forked branch does not seem to have this issue.

**Comment by tdonohue** [comment]
@YanaDePauw : I don't believe we have any code caching.  However, it is possible the branch this PR is based on is now slightly outdated.  We've merged a *lot* of code changes in the last 48 hours as we are heading into the 7.6.1 release next week.  So, when CI runs this PR, it might be trying to run it against the latest code on `dspace-7_x` branch, and encountering errors in doing so.

So, the build failures here might be a sign of a "code conflict" between this PR and some recent change on `dspace-7_x`.  I won't have time to debug it further until I'm done reviewing PRs for 7.6.1, but that's my best guess.

**Comment by YanaDePauw** [comment]
@tdonohue There was indeed an issue with a test that was added on `dspace-7_x` branch. The issue is fixed now.

**Comment by tdonohue** [comment]
@YanaDePauw :  Thanks for the update!  One quick question about this PR:

I notice there's no script to _cleanup_ existing resources policies that have no group or eperson.  Should that be part of the new Flyway migration here?  Otherwise, I'm worried this change may cause sites to throw errors if they have these invalid policies in their databases.

**Comment by YanaDePauw** [comment]
@tdonohue I added a line to the sql file to remove any faulty resource policies

**Comment by tdonohue** [comment]
@YanaDePauw : Would you have time to update this based on the latest code on `dspace-7_x` and also create a PR port for `main`?  

I tried to install this into `main` and it doesn't work (lots of code conflicts).   Ideally, we'd try to get this into 8.0 & 7.6.x, but this is currently difficult to test as there's no way to easily verify behavior on `main` as well.

**Comment by YanaDePauw** [comment]
@tdonohue I'll look into this, this week.

**Review by tdonohue — APPROVED** [review]
👍 Verified this is identical to #9502 (8.x version) and tested this on 8.x.  This is ready to merge as soon as #9502 is cleaned up (see [comments on that PR](https://github.com/DSpace/DSpace/pull/9502#issuecomment-2086072441))

**Pull request merged**
