### PR TITLE
DS-3461 : cleanup command fails to properly delete object files from storage

### PR DESCRIPTION
**Pull request by albertocpbranco**
Cleanup command fails to properly delete object files from storage
https://jira.duraspace.org/browse/DS-3461

Implementation of Google Cloud Storage bitstore
https://jira.duraspace.org/browse/DS-3462

### CODE REVIEW

**Comment by peterdietz** [comment]
Hi @albertocpbranco, this looks pretty good (get/put/about/remove). However, one thing that I don't see is how the GCS authentication is handled. For the S3 implementation there is access key, secret, and bucket, but for GCS, I see that if you run DSpace on Google Cloud, it will provide you a service account through the cloud platform environment, but I don't see a way to set a service account for use outside of Google Cloud Platform.

**Comment by ammopt** [comment]
Hello @peterdietz ! Thanks for your review !
I have it documented on https://jira.duraspace.org/browse/DS-3462?filter=-2 and I have placed a comment at the start of the class explaining it:

------------------------

You need to set GOOGLE_APPLICATION_CREDENTIALS environment variable pointing to json key file given by GCP after creating a service account (see https://developers.google.com/identity/protocols/application-default-credentials)

------------------------

A service account in GCP is an account to be used only by an application, which is exactly the case. You create the account and follow the instructions on the documentation, then a .json file is provided. That file should then be defined in the GOOGLE_APPLICATION_CREDENTIALS environment variable. Once "storage" is called in the code, the authentication happens behind the scenes, and the environment variable checked/validated, otherwise an authentication exception is thrown.

There are other ways to implement GCP Storage authentication but this is the way I decided to implement it because every other way I found documented are for GCP specific installations (App Engine or Compute Engine). This way works for every installation, independent of platform, at least that's what I learned.

Let me know if I wasn't clear enough or if it should be implemented differently.

Thanks,

Pedro Amorim

**Comment by peterdietz** [comment]
Thanks @ammopt, environment variable GOOGLE_APPLICATION_CREDENTIALS that has path to the json file from Google. I'm trying to balance how exactly this would be set. For tomcat you would alter something like /path/to/tomcat/bin/setenv.sh, and before JAVA_OPTS you have GOOGLE_APPLICATION_CREDENTIALS = /path/to/auth.p12.json. But, because DSpace is also command-line, you have to alter /path/to/dspace/bin/dspace to declare the GOOGLE_APPLICATION_CREDENTIALS as well.

For us, we wouldn't be able to set this environment variable server-wide, would could have multiple DSpace instances on a single application server.

Also, this might be an even more esoteric sounding use-case, but one feature that the current bitstore implementation allows is for migrating bitstreams from assetstore to another. We've made a lot of use of this as we've migrated local filesystem assetstores to S3. And we've even migrated from S3 to a different S3 access/secret/bucket, as we've cleaned up our AWS accounts. If you had a single environment variable GOOGLE_APPLICATION_CREDENTIALS, I don't believe you would be able to migrate from GCS bucket dspace-app-1 owned by XYZ University to bucket acme-dspace-xyz owned by Acme company (in case you migrated DSpace hosting provider from campus maintained in Google cloud to a hosting company using Google Cloud), as the credential key wouldn't be able to access both buckets owned by different companies. I suppose this could be fine, you would just have to note that you can only have one Google Cloud Storage configured for a DSpace at a time.

**Comment by ammopt** [comment]
Hey Peter,

Once again, thanks a bunch for your help and guidance.
I have implemented it differently now and tested it to confirm it works as before, but now the secret file and project id must be configured at the bitstore level, instead of the previous environment variable level.

Can you take a quick look?

Thanks,

Pedro Amorim

**Review by peterdietz — APPROVED** [review]
+1 I'm in favor of adding this. The lastest changes to have GCS be configured via bucketName, projectID, secretFile are good to make this a stable implementation, and not dependent on system variables. Your implementation for GCS looks good (DS-3462), and this also adds the fix for cleanup script (DS-3461).

**Comment by ammopt** [comment]
Hello @peterdietz 
Thank you for your review and all your help in this implementation.

I would like to ask advice of you or someone else who can help regarding the mime type of a bitstream in DSpace.

After a couple of days using this implementation on a test installation, I noticed that GCS adds metadata for the object automatically (size, checksum, create date) but doesn't add the content-type metadata.
We can set the content-type metadata when creating the BlobInfo for GCS like so:

`BlobInfo blobInfo = BlobInfo.newBuilder(blobId).setContentType("image/jpg").build();`

But, of course, I'd like to set that content type dynamically, depending on the bitstream, so I tried this:

`Context context = new Context();
BlobInfo blobInfo = BlobInfo.newBuilder(blobId).setContentType(bitstream.getFormat(context).getMIMEType()).build();`

However, it's setting the content-type as **application/octet-stream** for every file instead of the normal image/jpg or image/png.

Is there some other way I should be attempting this? Also, I have no idea what "Context" is and why it's needed for this.

Thank you

**Comment by tdonohue** [comment]
Duplicate of / fixed by #1851.

**Pull request closed without merging**
