### PR TITLE
[DS-3824] Bitstream metadata duplicated when creating a version

### PR DESCRIPTION
**Pull request by KevinVdV**

### CODE REVIEW

**Comment by KevinVdV** [comment]
Oracle query to remove the duplicate rows has NOT been tested yet.

**Comment by pnbecker** [comment]
This would need to be cherry-picked to master.
This seems to be related to #1883

**Comment by kshepherd** [comment]
@KevinVdV does this PR fix the same issue as https://github.com/DSpace/DSpace/pull/1883 and if so, do you have a preference for which implementation to use?

**Comment by kshepherd** [comment]
No answer from author and PR now has conflicts, moving to 6.4 until we can resolve

**Pull request closed without merging**
