### PR TITLE
[DS-3456] 5x Clarify command line options for statisics import/export tools

### PR DESCRIPTION
**Pull request by terrywbrady**
## Addresses the following
* https://jira.duraspace.org/browse/DS-3456
* https://jira.duraspace.org/browse/DS-3464
* https://jira.duraspace.org/browse/DS-3437

The context for this PR and a suggested test plan is documented here: https://wiki.duraspace.org/display/~terrywbrady/Statistics+Import+Export+Issues

## Additional PRs
The following PR is also needed, but the code change may require more discussion.
See changes to SolrLogger.createCore()
* https://github.com/DSpace/DSpace/pull/1625/files

### CODE REVIEW

**Review by kshepherd — APPROVED** [review]
All tests passed. My only notes were: should we have a think about which flag to use exactly for the ignore/overwrite option? (-o is a bit loaded especially in stats commands) and does it matter that we force both ignore/overwite this way with reindex
I also wonder if we really want to export/import _version_?
My detailed notes/resuls pages for this and related PRs is at https://wiki.duraspace.org/pages/viewpage.action?pageId=79794259#Solrstatisticsimport/export/shardissuetesting(PR-1623,PR-1625)-Resultsoverview

**Comment by tdonohue** [comment]
I agree with @kshepherd's point about using `-o` to represent `overwrite`, as my mind tends to also always assume `-o` is "output" (as it's almost always used that way).  So, I'd like to reconsider the flag here...maybe `-f` (for "force overwrite") or `-w` (the "write" in overwrite) or similar.

**Comment by terrywbrady** [comment]
@kshepherd , I like the suggestion to exclude version from export.  Unfortunately, it does not look like there is a supported mechanism to exclude a field in an export query (without enumerating every field to retain): http://stackoverflow.com/questions/16109273/how-to-exclude-fields-in-a-solr-query  

Perhaps the proper solution would be to always ignore version on import.  It appears that one cannot import a record containing a version element.  This would resolve the command line option overloading issue.

I will plan to switch the -o option to -f for "force-overwrite".

**Comment by terrywbrady** [comment]
@kshepherd , I was able to reproduce the issue you encountered with Proposal 1.  See the following commit.  

https://github.com/DSpace/DSpace/pull/1623/commits/b34dff11301220a014c0c97a696b34db19dcb394

**Comment by terrywbrady** [comment]
@kshepherd , I believe I have addressed all of the notes from your testing doc.

**Review by tdonohue — APPROVED** [review]
Approved in #1624 (6.x version of this PR)

**Pull request merged**
