### PR TITLE
[Ticket DS-3730] make item and bitstream endpoints resourcepolicy aware

### PR DESCRIPTION
**Pull request by Raf-atmire**
Made the Item and Bitstream REST endpoints aware of the resource policies on the given objects. The database query will check whether the item contains a resource policy that gives a group, which the current user belongs to, read rights on the given item. If this is true, the item will be returned.
Link to Jira ticket: https://jira.duraspace.org/browse/DS-3730

### CODE REVIEW

**Comment by tomdesair** [comment]
@Raf-atmire and I worked together on this. We know that checking the resource policies in the query is not an ideal situation (as it duplicates the logic to check resource policies). But we could not find another efficient way to support paging and total counts while taking into account the resource policies. 

[DSpace 6 does this in-memory](https://github.com/DSpace/DSpace/blob/dspace-6.2/dspace-rest/src/main/java/org/dspace/rest/ItemsResource.java#L179), but this can be very slow and it doesn't give you a total number of results or correct support for pagination.

**Comment by tomdesair** [comment]
Hi @abollini, thanks for the review.

It is correct that we are missing the `isAdmin` check which should result in using the normal `findAll` service method. We should add that. While I agree that restricting these endpoints to administrators only is the most easy solution, I don't think this is the most flexible solution and could harm the reusability of the REST API for other purposes.

But this doesn't cover the case of community/collection administrators. Note that SOLR also does not cover that case. The [Resource restriction index plugin only looks at READ resource policies](https://github.com/DSpace/DSpace/blob/56dcd2d915f73de4379b244f994a67aec9dac4b1/dspace-api/src/main/java/org/dspace/discovery/SolrServiceResourceRestrictionPlugin.java#L59) on the current DSO (just like the new database query) and does not look at the admin permissions on the container. So using SOLR here, would currently not solve the issue.

I'm not sure a caching table would scale well for repositories with a lot of items because that table would contain at least "#number-of-groups times #number-of-items" records. For my current test database, that would mean more than 150 000 000 records. It also introduces the risk of the cache going out-of-sync with the actual policies.

**As a second point:** We also need to do authorisation checks on the `/api/core/collections` and `/api/core/communities` endpoints because in DSpace 6 you can modify the read permission of these containers to turn them into private collections/communities (http://demo.dspace.org/xmlui/admin/authorize).

Since our implementations works on any DSpace object, we can also apply this implementation to those endpoints.

**Comment by abollini** [comment]
Hi Tom,
the search endpoint must be able to return authorization aware results. You are right about the current implementation of the resource restriction plugin but I tend to consider that a bug or at the least a known limitation that we need to fix (and it should be easy).
That said, we will have a search endpoint that will be able to provide the needed functionality to the REST client. Not sure we need and can spent time to make also the core resource collections endpoints authorization aware and, if we decide to do so we should consider if it makes sense to go with another strategy (the database) or reuse the must to have SOLR strategy.
Yes, having a cache table make things more complex and can lead to out-of-sync situation exactly as using SOLR but **I don't think it is possible to implement a single query able to "explode" potentially infinite level of hierarchy**  but please correct me if I'm wrong (if it is possible it must be also efficient ;) ).

Finally, I'm not convinced that the cache table will have a number of rows **>** #groups times #items 
I think that a more accurate estimation is
count(cache table rows) **<** 3 times #items times #max-levels times 
3 is the number of actions inherited for an ADMIN permission (READ, WRITE, REMOVE)
#max-levels is the max depth of communities & collections in the repository (as an item gives inherited permissions to all the administrator of all its parent)

the bitstreams will have a similar behavior as we typically don't have ADMIN permission at the item level but their inherit from the item parents as well. So at the end, considering that an item has in the worst case one or two bitstreams (the license and a single file) 
we will have not more than 2 times 3 times #max-levels times #bitstreams
that mean less than 30M of rows for a very large repository (500K items, 1M of bitstreams, 5 levels)

Most of the groups comes from the repository structure and the communities and collections administrators and workflows. Custom groups should not change the figure here. In any case this seems to me to be a size that can be managed in the database with proper indexes and with less rows than our current metadatavalue table.

**Comment by tdonohue** [comment]
Finally getting to joining this discussion. I don't believe the current implementation is ideal for the reasons previously stated...namely that it doesn't support inheritance of permissions, which is a core requirement here (and without that, I worry we'll hit other implementation isssues).

My personal opinion is that the idea of a cache table is a bit "dated".  Yes, we've done that before with `group2groupcache`, but I think it is much better implemented these days in Solr (as we already use Solr to "cache" a lot of info needed to speed up browse/search, etc).  Since this ticket is essentially about access-aware browsing (in this case of lists of Items/bitstreams), I think we should be using Solr to implement this, similar to how we already achieve access-aware browsing via Discovery (in DSpace 6).

If this means we need additional fields/indexes in Solr and/or need to fix the existing flaws of the `SolrServiceResourceRestrictionPlugin` (to properly support access rights inheritance), then I'd recommend doing so as part of this implementation.  That way we are not building in yet another (duplicative) way to query access rights (as @tomdesair rightfully noted this implementation currently is)

**Comment by tdonohue** [comment]
@abollini and I discussed this a bit more in today's DSpace 7 meeting.  I'm starting to see his point about how these endpoints may be better implemented as Admin-Only, simply because we already provide this same capability through other endpoints (namely Browse/Search).

For normal (non-Admin) users, they can easily find items that they have access to via the [`/api/discover/browses`](https://github.com/DSpace/Rest7Contract/blob/master/browses.md) or [`/api/discover/search`](https://github.com/DSpace/Rest7Contract/blob/master/search-endpoint.md) endpoints.  In fact, if they want to retrieve *all* items they have access to, they should be able to use the search endpoint with an empty query.  That endpoint is already access-rights aware and should give them access to the same information proposed here. Once they are down to requesting individual (singular) items or bitstreams, then we can do a quick access check to ensure they have rights to do so.

However, that said, Admin users may require being able to access all Items or Bitstreams for administrative tasks (e.g. Curation Tasks or similar).  So, this sort of endpoint would be useful as an Admin-specific one.  We could consider simply documenting (in the REST Contract) that this is an Admin-Only endpoint, and that non-Admins should utilize search or browse to retrieve items, etc.

So, I'd like to take a step back here and ensure we have a common understanding around the use cases / needs of this endpoint, and see if we could consider treating this as Admin-Only. In the end, I'd recommend against creating duplicative endpoints/code, and instead enhance our documentation to explain which endpoint to use for different purposes.

**Comment by tdonohue** [comment]
Please rebase this PR against the latest `master` branch.  The `master` branch now requires adherence to our new Java Code Style documented at: https://wiki.duraspace.org/display/DSPACE/Code+Style+Guide

If you have any questions, feel free to ask in this PR or on our Slack: https://wiki.duraspace.org/display/DSPACE/Slack

**Comment by tomdesair** [comment]
Closing this PR since https://github.com/DSpace/DSpace/pull/1976 was merged. That PR made sure that the find-all endpoints for items and bitstreams can only be called by administrators.

**Pull request closed without merging**
