### PR TITLE
DS-3680: Database changes of consumers aren't persisted anymore

### PR DESCRIPTION
**Pull request by pnbecker**
https://jira.duraspace.org/browse/DS-3680

This needs to be cherry-picked to master too.

### CODE REVIEW

**Comment by hardyoyo** [comment]
I'm currently running this code on our staging server, which is running a fork of DSpace 6.x. So far, so good. Passes the smoke test.

**Review by tdonohue — APPROVED** [review]
Code changes look fine (haven't had a chance to test it though). This is essentially a one-liner after reverting the changes to `Context.commit()` applied in https://github.com/DSpace/DSpace/commit/646936a3d8d2d39792bd4a5ebb7e2a536d1a8f6e

I would request though that we retest/re-verify the bugs in https://jira.duraspace.org/browse/DS-3656 and
https://jira.duraspace.org/browse/DS-3648 are still fixed.

**Comment by pnbecker** [comment]
@tdonohue I tested it against DS-3656.

**Review by hardyoyo — APPROVED** [review]
I've been testing these commits on our staging server for a few days, we've been using it as normal, and I have heard no complaints from my users. I say this is a fine change. To be clear, I have verified that batch loading via zip files still works, the site reindexes correctly, and the event consumer system functions as expected.

**Comment by tdonohue** [comment]
Verified in today's DevMtg that @hardyoyo has tested DS-3648 and confirmed it is still fixed

**Comment by tdonohue** [comment]
Also cherry-picked to `master`

**Comment by jawadmakki** [comment]
I applied the changes in Context.java according to this pull #1830. below are the results:

The batch import (ZIP) works fine (from XMLUI and from the command with workflow enabled).
The indexer is working correctly.
the problem is that the performance of DSpace is affected, I've encountered a serious slow performance in the response time of tomcat. each request is taking around 20 seconds to get the response !!!

**Comment by Generalelektrix** [comment]
Changes applied in our dev branch here and I don't have that performance issue, is it on specific requests that writes to database or all requests to Tomcat?

**Comment by jawadmakki** [comment]
It's on all requests to Tomcat.
I didn't face this slowness before this modification

**Pull request merged**
