### PR TITLE
[DS-3217] removed testGetCurrent

### PR DESCRIPTION
**Pull request by hardyoyo**
not worth the trouble, as written it will fail between 23UTC and 24 UTC, possibly through 1 UTC

### CODE REVIEW

**Comment by hardyoyo** [comment]
https://jira.duraspace.org/browse/DS-3217

**Comment by LuizClaudioSantos** [comment]
Hi @hardyoyo 

It more a question than a suggestion, the code of the test should no be like the code below, I mean, you need to set the time to the object Date to compare?

Best
Luiz

`
@Test		
 public void testGetCurrent()		
  {		
        Calendar calendar = Calendar.getInstance();
         calendar.setTimeInMillis(System.currentTimeMillis());		
         assertTrue("testGetCurrent 0", DateUtils.isSameDay(DCDate.getCurrent().toDate(), calendar.getTime()));		
  }


`

**Comment by hardyoyo** [comment]
Alternate PR: https://github.com/DSpace/DSpace/pull/1448

**Comment by hardyoyo** [comment]
Closing this, since #1449 provides fixes for all the similarly-broken tests, no need to remove them

**Pull request closed without merging**
