### PR TITLE
[DS-3217] fix more than one test

### PR DESCRIPTION
**Pull request by hardyoyo**
Revised a few tests to make them work no matter the time of day (they were failing between 23UTC and 24UTC). Used Calendar instead of Date, thanks to a hint from LuizClaudioSantos, set the time zone on the Calendar object thanks to a hint from Helix84. Swapped out some old string hacking for a nice standard SimpleDateFormat object.

### CODE REVIEW

**Comment by hardyoyo** [comment]
https://jira.duraspace.org/browse/DS-3217

**Comment by hardyoyo** [comment]
https://jira.duraspace.org/browse/DS-3217

**Comment by hardyoyo** [comment]
this PR replaces #1448

**Comment by hardyoyo** [comment]
Tested using Vagrant-DSpace:

sudo service vboxadd-service stop && sudo date --set 23:01:00 #set the time to 23UTC to trigger the error
date #confirm the time is set
mvn test -Dmaven.test.skip=false

Confirmed working.

**Comment by aschweer** [comment]
+1 after testing and code inspection
I set my local time to just after 11am NZ time (corresponding to just after 23 UTC). Without this patch, there are test failures that are clearly related to date issues (installItem, checking whether "install" date matches expectations). With this patch, and time still in the hour between 23 and 24 UTC, all tests pass on current master.

**Comment by tdonohue** [comment]
+1 via code review. Looks good, and I trust the testing by @hardyoyo and @aschweer

**Pull request merged**
