### PR TITLE
Migrate Mirage2 build from bower and compass to yarn and node-sass

### PR DESCRIPTION
**Pull request by alanorth**
**Closing this PR in favor of a newer one: https://github.com/DSpace/DSpace/pull/8292**

## References
* [Recent mailing list post about build issues related to torquebox.org](https://groups.google.com/g/dspace-tech/c/7_fUBxsxkhs/m/xTpRzyDUAQAJ)

## Description
In short, this pull request replaces bower with yarn and compass with node-sass in order to fix the ancient Mirage2 build when using the "slow" `-Dmirage2.deps.included=true` maven build.

For more background, the Mirage2 build system uses bower for package management and Ruby sass/compass for SASS processing. Bower has been deprecated for years and is an increasing source of obscure build issues. Compass is Ruby based and requires the user to preinstall Ruby and several gems, or use those provided by JRuby via torquebox.org during build time. As of last week the torquebox.org domain expired and is likely abandoned, making it impossible to build Mirage2.

## Instructions for Reviewers
Test building Mirage2 at your site using the `-Dmirage2.deps.included=true` option to maven. I have tested both vanilla Mirage2 and a slightly modified one with style overrides in `dspace/modules/xmlui-mirage2`.

List of changes in this PR:
* Use eirslett/frontend-maven-plugin to install Node.js and yarn during maven build. JavaScript packages that were previously installed by bower are now installed by yarn.
* Remove JRuby and compass stuff from build. Use node-sass as the SASS processor and essentially polyfill the compass SASS mixins using compass-sass-mixins. Allow building with Node.js 12.
* Use a static copy of Modernizr.min.js because the version we need is not available on NPM.
* Update CI to use latest Node.js 12 and remove useless pre-requisite step (as GitHub CI already has yarn and grunt installed).

### CODE REVIEW

**Comment by J4bbi** [comment]
Many thanks to @alanorth for this PR. Great job. I readily admit to not understanding this build process, what exactly is happening is beyond me.

I am building from this PR and seeing the following:

```
[INFO] [2/5] Resolving packages...
[INFO] warning autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[INFO] warning cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[INFO] warning cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[INFO] warning cssnano > postcss-svgo > svgo@0.7.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
[INFO] warning cssnano > postcss-merge-rules > postcss-selector-parser > flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
[INFO] warning datatables@1.10.5: This NPM package for DataTables has now been deprecated and the 'datatables.net' set of packages should be used in preference to this one. Please see the NPM installation guide for DataTables for more details: https://datatables.net/download/npm.
[INFO] warning grunt-contrib-coffee > coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
[INFO] warning grunt-node-sass > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[INFO] warning grunt-node-sass > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[INFO] warning grunt-node-sass > node-sass > node-gyp > tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
[INFO] warning grunt-node-sass > node-sass > request > har-validator@5.1.5: this library is no longer supported
[INFO] warning grunt-node-sass > node-sass > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[INFO] warning pixrem > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
```

Auto-prefixer is at v. 10 and Cssnano at v. 5, perhaps an opportunity to use latest version of packages?

There's a lot of outdated info in `/dspace-xmlui-mirage2/readme.md` and while I would never ask you to add information there :) it would be good if you could throw out the obsolete Ruby/Gem stuff. Note also that https://wiki.lyrasis.org/display/DSDOC6x/Installing+DSpace links to that readme file to give instructions on how to pre-install dependencies.

Builds fine, with no problems. Runs fine in docker and opens up and yes, it's Mirage2.

I can't easily apply massively modified Mirage2 frontends. @alanorth , if there are specific instructions you would recommend?

**Comment by alanorth** [comment]
@J4bbi thank you for testing. I tried a modified Mirage2 by adding a custom CSS rule here:

> dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/styles/_style.scss

Regarding autoprefixer and cssnano, actually those are not used by vanilla Mirage2, but they were introduced on our site. I should technically remove them from this PR since that is not in the scope!

**Comment by alanorth** [comment]
@J4bbi I've removed the autoprefixer, cssnano, and postcss stuff, as it was not relevant for this PR. Please try again! Also, I've updated the Mirage2 readme (that reminds me, I will need to update the installation notes on the wiki when this gets merged).

**Comment by alanorth** [comment]
Closing this PR in favor of a newer one: https://github.com/DSpace/DSpace/pull/8292

The newer one uses npm directly instead of yarn, which means one less thing we need to install to build Mirage 2. As a bonus, npm comes with the Node.js distribution so users will already have it once they install Node.js.

**Pull request closed without merging**
