### PR TITLE
DS-3052 improvements to PDFBox-based code

### PR DESCRIPTION
**Pull request by helix84**
https://jira.duraspace.org/browse/DS-3052

### CODE REVIEW

**Comment by mwoodiupui** [comment]
Overall this looks very good to me.

**Comment by peterdietz** [comment]
The existing PDFBox 1.8 has problems rendering non-ASCII, and unfortunately PDFBox 2 doesn't appear to be better.

I used the PDF from https://oaarchive.arctic-council.org/handle/11374/1647  (I used the original for this test). And it failed to render.

```
2016-02-09 09:02:45,060 ERROR org.dspace.app.xmlui.cocoon.BitstreamReader 
@ Caught an error with intercepting the citation document:U+0421 ('Escyrillic') is not 
available in this font's encoding: WinAnsiEncoding
```

**Comment by helix84** [comment]
@peterdietz As I don't try to address this issue in this PR yet, it would be better to discuss this in the relevant issue https://jira.duraspace.org/browse/DS-2224 .
Could you also point to your branch ported to the PDFBox 2 API which produces this error? Or have you just run your previous code unchanged?

**Comment by KevinVdV** [comment]
Do we have any idea on the timeline of the final release of the PDFBox 2.0.0, because I'm not such a fan of having a release candidate dependency.

**Comment by helix84** [comment]
@KevinVdV I know, me neither. I can't speak on behalf of another team regarding their release date, but my good faith is based on this data (they're a couple of RCs ahead of us and release steadily):

https://jira.duraspace.org/browse/DS-3035?focusedCommentId=47913&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-47913

**Comment by helix84** [comment]
@mwoodiupui I believe I addressed all your comments. Thanks for your review.

**Comment by tdonohue** [comment]
I'm placing the "work in progress" label on this PR (and other PDFBox v2 PRs), as I agree with @KevinVdV and @helix84 that we really should wait for the final PDFBox v2 release before merging any of this code. 

Once PDFBox 2.0.0 is released, we can change our dependencies to point at it, and remove the "work in progress" label.

**Comment by helix84** [comment]
Update about PDFBox 2 release from today:

> We don't have a fix date, but I'm pretty sure that the next release will be the
final one and I guess it'll be releases quite soon.
http://mail-archives.apache.org/mod_mbox/pdfbox-dev/201602.mbox/browser

**Comment by tdonohue** [comment]
PDFBox 2.0.0 is now released. This PR should be updated & the merge conflict resolved. Then we can remove the "work in progress" label.

**Comment by helix84** [comment]
Updated to release version and rebased on top of master.

**Comment by terrywbrady** [comment]
+1 - Tested with a few sample files.  Confirmed the creation of thumbnail images.  I am unsure of specific issues to inspect.  Tested a PDF file with non-ascii characters.  I compared the text bitstream with a text bitstream produced in DSpace 5.4 and the results are similar.

I loaded a PDF containing English and Arabic and indexed it with DSpace 5.4 and with this PR.  Comparing the text bitstreams, there were some portions of the document in which the DSpace 5.4 version of the document incorrectly ordered the English characters.  For this very specific use case, this PR seems to be an improvement.

**Comment by tdonohue** [comment]
+1 via code review. Merging for 6.0 RC1.

**Pull request merged**
