### PR TITLE
In workflow-attached curation, separate task-list building from execution.

### LINKED ISSUE #9496: Workflow curation incorrect nesting causes multiple applications of the same task per object.
**Describe the bug**
Code in org.dspace.curate.XmlWorkflowCuratorServiceImpl is incorrectly nested.  We should first fill the Curator with Tasks and then queue or curate the object.  What we're actually doing is curating the object once for each Task in the taskset of the Step as Tasks are added to the Curator.  The comment is wrong too:  it is the Step that has a queue, not each Task.

https://github.com/DSpace/DSpace/blob/10362d990167501de8540e3a9163e77e9b1046a9/dspace-api/src/main/java/org/dspace/curate/XmlWorkflowCuratorServiceImpl.java#L141-L150

**To Reproduce**
Unknown at this time, but the code is clearly wrong.  Probably just set up a workflow step with two tasks, submit an item through that workflow, and observe double execution of one of the tasks by inspecting the log.

**Expected behavior**
The tasks attached to a workflow step should each be run only once over the workflow item whenever the step is entered.

### PR DESCRIPTION
**Pull request by mwoodiupui**
The old code would curate the object once for each task, meaning that all but one task would be executed N times up to the length of the list.  This patch first configures the Curator with tasks, and then runs it once (or queues it).

## References
* Fixes #9496

## Description
Completely configure the Curator before using it.

## Instructions for Reviewers
List of changes in this PR:
* Moved Curator.curate out of the loop that configures the Curator with tasks.
* Replaced literal `%n` with newline in report output
* Extended the internal documentation of the package

See comments for a good test procedure.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [x] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
Thanks @mwoodiupui. I tested on DSpace 7.6.1 with the following workflow curation task configuration:

```xml
...
 <tasksets>
   <taskset name="metadata-curation">
     <flowstep name="editstep">
       <task name="normalizedois" />
     </flowstep>
     <flowstep name="finaleditstep">
       <task name="countrycodetagger" />
     </flowstep>
   </taskset>
 </tasksets>
```

# Before the patch

Immediately after depositing the submission into the workflow, I see the following:

```console
$ tail -f dspace.log | grep -A1 org.dspace.curate
2024-04-24 07:47:36,759 INFO  1859f123-6a5c-42a2-813d-ed0b2b1ef962 e09685ef-ecf5-40c9-b01d-6b776c4cd65e org.dspace.curate.Curator @ Curation task: normalizedois performed on: workflow item: bf20d42e-b9a6-4125-87d5-ed84a75a3755 with status: 0. Result: 'Normalized 1 DOI(s)'
2024-04-24 07:47:36,759 WARN  1859f123-6a5c-42a2-813d-ed0b2b1ef962 e09685ef-ecf5-40c9-b01d-6b776c4cd65e org.dspace.curate.XmlWorkflowCuratorServiceImpl @ No contacts were found for workflow item 50129:  task normalizedois returned action none with message Normalized 1 DOI(s)
2024-04-24 07:47:36,759 INFO  1859f123-6a5c-42a2-813d-ed0b2b1ef962 e09685ef-ecf5-40c9-b01d-6b776c4cd65e org.dspace.curate.XmlWorkflowCuratorServiceImpl @ Curation tasks over item bf20d42e-b9a6-4125-87d5-ed84a75a3755 for step editstep report:%nNormalized 1 DOI(s)All DOIs already normalizedAll DOIs already normalizedAll DOIs already normalizednull: no countries, skipping.Normalized 1 DOI(s)
2024-04-24 07:47:36,761 INFO  1859f123-6a5c-42a2-813d-ed0b2b1ef962 e09685ef-ecf5-40c9-b01d-6b776c4cd65e org.dspace.content.Item @ aorth@mjanja.ch::update_item:item_id=bf20d42e-b9a6-4125-87d5-ed84a75a3755
```

Note how the "Normalize DOIs" task runs multiple times, and the country code tagger task also runs, despite only being configured for the `finaleditstep`. (Also note the poorly formatted report)

# After the patch

Immediately after depositing the submission into the workflow, I see the following:

```console
$ tail -f /home/dspace7/log/dspace.log | grep -A1 org.dspace.curate
2024-04-24 07:56:37,439 INFO  1859f123-6a5c-42a2-813d-ed0b2b1ef962 1b8d1bfc-b4c3-413a-8a46-13edb456ca0f org.dspace.curate.Curator @ Curation task: normalizedois performed on: workflow item: 51c38bf0-fabe-4b41-aad8-fb27ee42b177 with status: 0. Result: 'Normalized 1 DOI(s)'
2024-04-24 07:56:37,440 WARN  1859f123-6a5c-42a2-813d-ed0b2b1ef962 1b8d1bfc-b4c3-413a-8a46-13edb456ca0f org.dspace.curate.XmlWorkflowCuratorServiceImpl @ No contacts were found for workflow item 50130:  task normalizedois returned action none with message Normalized 1 DOI(s)
2024-04-24 07:56:37,441 INFO  1859f123-6a5c-42a2-813d-ed0b2b1ef962 1b8d1bfc-b4c3-413a-8a46-13edb456ca0f org.dspace.curate.XmlWorkflowCuratorServiceImpl @ Curation tasks over item 51c38bf0-fabe-4b41-aad8-fb27ee42b177 for step editstep report:
Normalized 1 DOI(s)
```

The "Normalize DOIs" task runs once, and the country code tagger task is not run. This is the correct behavior.

**Comment by tdonohue** [comment]
As it sounds like this is working, I'm pulling this over to the 8.0 board and flagging as `port to dspace-7_x` in the hopes that we can get this fix into both releases.  That said, obviously we'll have to wait until @mwoodiupui takes this out of draft status.

**Comment by mwoodiupui** [comment]
It was draft because I hadn't had time to test it.

**Comment by alanorth** [comment]
Let's hold off on this. I tested current DSpace 7.6.1 again several times and I cannot re-produce the original issue. :thinking:

**Review by kshepherd — APPROVED** [review]
+1 thanks @mwoodiupui, the code changes all make sense to me and the output matches what I expect -- I will note that though the `curator.queue` call is made N times for the tasks in current code as you mention, the fact that Sets are used in the FileTaskQueue means that when the same task is "re queued" with the same task name, it won't be added, it will replace the existing one, so I didn't actually see N instances of each distinct task in the queue files when I tested.

I did see expected output though - the item is queued up once for each task, not grouped with all tasks queued for a single item entry.

Without this PR, the queue file ends up looking like:
```
kim@the-library-code.de|1722528706853|noop|41e66e7e-7d0a-4866-9abc-9e982b164513
kim@the-library-code.de|1722528706854|noop2|41e66e7e-7d0a-4866-9abc-9e982b164513
kim@the-library-code.de|1722528706854|noop3|41e66e7e-7d0a-4866-9abc-9e982b164513
```
The run log looks like:
```
Curating id: 41e66e7e-7d0a-4866-9abc-9e982b164513
Curation task: noop performed on: 41e66e7e-7d0a-4866-9abc-9e982b164513 with status: 1
Curating id: 41e66e7e-7d0a-4866-9abc-9e982b164513
Curation task: noop3 performed on: 41e66e7e-7d0a-4866-9abc-9e982b164513 with status: 1
Curating id: 41e66e7e-7d0a-4866-9abc-9e982b164513
Curation task: noop2 performed on: 41e66e7e-7d0a-4866-9abc-9e982b164513 with status: 1
```

After this PR, the queue file looks like:
```
kim@the-library-code.de|1722529126707|noop,noop2,noop3|858faa60-c74f-47b6-8315-b45e1e8ea8cd
```
The run log looks like:
```
 Curating id: 858faa60-c74f-47b6-8315-b45e1e8ea8cd
 Curation task: noop performed on: 858faa60-c74f-47b6-8315-b45e1e8ea8cd with status: 1
 Curation task: noop2 performed on: 858faa60-c74f-47b6-8315-b45e1e8ea8cd with status: 1
 Curation task: noop3 performed on: 858faa60-c74f-47b6-8315-b45e1e8ea8cd with status: 1
```

**Review by tdonohue — APPROVED** [review]
👍 Thanks @mwoodiupui !  This looks correct to me.

**Pull request merged**
