### PR TITLE
DS-3584 when editing an eperson, trying to change its email address is ignored if another user already has that email address.

### PR DESCRIPTION
**Pull request by samuelcambien**
https://jira.duraspace.org/browse/DS-3584

### CODE REVIEW

**Comment by samuelcambien** [comment]
also committed to dspace 5 branch:
https://github.com/DSpace/DSpace/pull/1733
also committed to dspace 4 branch:
https://github.com/DSpace/DSpace/pull/1734

**Comment by AlexanderS** [comment]
:+1: Tested it, and can confirm that it is working. If you try to set an email address that is already taken by another user without this fix, the email is ignored without a message. With this patch the field show the error message "Email address must be unique".

**Review by AlexanderS — APPROVED** [review]
Tested it, and can confirm that it is working. If you try to set an email address that is already taken by another user without this fix, the email is ignored without a message. With this patch the field show the error message "Email address must be unique".

**Comment by terrywbrady** [comment]
+1, reviewed and tested

**Review by terrywbrady — APPROVED** [review]

**Pull request merged**
