### PR TITLE
Default submission forms per Entity type

### LINKED ISSUE #8633: New atribute in Item submission for name-mapping based on collection's entity type
**Is your feature request related to a problem? Please describe.**
For associating a specific submission form to an entity type, you are required to know the handle of the collection. That is how it worked in the past and currently works. But, if you load entities model, collections currently have a way to specify which Entity types it's related to ease and better suggest external services to use. But with item submission, that work isn't considered.

**Describe the solution you'd like**
We currently specify a submission form using the handle
```
<item-submission>
    <submission-map>
		<name-map collection-handle="12345/6789" submission-name="Person"/>

```
but I think this configuration can be extended to support a new parameter, like `collection-entity-type`:

```
<item-submission>
    <submission-map>
		<name-map collection-entity-type="Person" submission-name="Person"/>

```
An that will enable all configured collections with "Person"
image

to be associated with this `submission-name="Person"`.

**Describe alternatives or workarounds you've considered**
Not the best solution, but the most easiest to implement this is to change `getCollectionsBySubmissionConfig`, of `SubmissionConfigReader `class, and extend it in order to look for all collections that have that `entity-type` attribute and add those collections to the resulted List.

```java
    public List<Collection> getCollectionsBySubmissionConfig(Context context, String submitName)
        throws IllegalStateException, SQLException {
        List<Collection> results = new ArrayList<>();
        // get the submission-map keys
        for (String handle : collectionToSubmissionConfig.keySet()) {
            if (!DEFAULT_COLLECTION.equals(handle)) {
                if (collectionToSubmissionConfig.get(handle).equals(submitName)) {
                    DSpaceObject result = HandleServiceFactory.getInstance().getHandleService()
                                                              .resolveToObject(context, handle);
                    if (result != null) {
                        results.add((Collection) result);
                    }
                }
            }
        }
        return results;
    }
```

Also, processMap method should be changed in order to support `collection-entity-type` parameter. And item-submission.dtd should also accommodate this.

**Additional context**
There is an issue regarding the change of item-submission to Spring: https://github.com/DSpace/DSpace/issues/7985
There will be an issue when you have the same collection handle associated with different submission forms. I would suggest to give priority to the configuration that specified the handle and the that occurs first, discarding the rest.

### PR DESCRIPTION
**Pull request by paulo-graca**
## References
* Fixes #8633
* Related PR #8864

## Description
These new configurations will enable default submission forms per Entity type, you don't have to specify which collection handle to use for a particular form if you intend to use entities.
A new attribute `collection-entity-type` will have the entity type attribute associated with a collection (entities that are usually specified in relationship-types.xml file).
The default collection handle configuration will prevail over this new configuration. Meaning that if a collection-entity-type is defined and a collection-handle is also defined and if a collection handle overlaps in both configurations, then, the form to be considered it will be the one that is defined by collection-handle (it will prevail the one with more granularity).

## Instructions for Reviewers

This PR changes the way we read submission configurations. It will read the new `collection-entity-type` attribute and look for all collections that have that entity type associated. In order to look for those collections, for better performance, a discovery search is performed.

List of changes in this PR:
* index-submission.dtd is changed to support a new attribute - `collection-entity-type`
* default configurations are added as examples at index-submission.xml
* a new collection service - findAllCollectionsByEntityType - to retrieve all collections based on discovery for performance issues

To test it, you will need to change your `index-submission.xml` file:
```
<name-map collection-entity-type="Person" submission-name="Person"/>
```
firstly ensure you have loaded entities in your database ( please read this first: https://wiki.lyrasis.org/display/DSDOC7x/Configurable+Entities) and also ensure you have a collection with the Entity Type assigned for your test.

**Additional notes:**
Due to the way SubmissionConfigReader is loaded into memory (on a initialize process) currently there is no implemented way to reload submission forms (there is an available `reload` method but currently isn't in use). So, every time you assign an entity type to a collection **you will need to do a Tomcat restart** for that collection to be available at the item submission config.
I will address this issue in another PR (also partially addressing https://github.com/DSpace/DSpace/issues/7985) that will add a specific Event Consumer to be run on every Collection change (create, update, delete) to force item submission config to reloaded.

This PR opens a path to future work on removing our dependency on Handles in main core structure. That could be ensured by using the UUID in the item submission config hashmap instead of the collection's Handle.

### CODE REVIEW

**Review by atarix83 — COMMENTED** [review]
@paulo-graca @tdonohue 

On DSpace-CRIS we already have something similar made by using a collection metadata, like is done for the entity type, for choosing the submission name to use with the collection. 
It can be also added/modified  by means of the collection form

Schermata da 2023-06-01 18-58-33

We are wondering if we could move the same approach also to DSpace

**Comment by paulo-graca** [comment]
> @paulo-graca @tdonohue
> 
> On DSpace-CRIS we already have something similar made by using a collection metadata, like is done for the entity type, for choosing the submission name to use with the collection. It can be also added/modified by means of the collection form
> 
> Schermata da 2023-06-01 18-58-33
> 
> We are wondering if we could move the same approach also to DSpace

Thank you @atarix83, If 4Science already have a solution, that does the same, I think it can be reused. It's a matter of checking out the implementation. I don't know if you already have a PR for that.
Currently, this PR is very small and it will work as is. It raises an issue regarding new collections. I'm already addressing that issued in another PR that will introduce a new `consumer` that will be pre-configured (dspace.cfg) for collections creation, deletion events and it will refresh loaded item submission forms configs. But it needs some more code changes and that's why it's in another, much larger, PR.
As in entities approach, everything I'm doing is configurable. The sysadmin can enable this in the item submission xml to use this type binding and also can continue to use handles. This change doesn't alter how submission forms are associated (using handles). I imagine DSpace-CRIS does the same. My only point with what you shared is that you expose a new field to the Collection Admin User. And I'm certain, from my experience, that user will not know what to do with that field. That type of user doesn't understand what are submissions forms and will not know what value should be inserted. He will be kind of lost and he will look for support, unlike the SysAdmin that has access to all of this and should know what forms ids should be used.
@atarix83 Do you think this work is compatible with your approach?

**Review by atarix83 — APPROVED** [review]
thanks @paulo-graca 

i've tested it and it works properly.

i think this work is compatible with the change made on cris, that can be ported anyway afterward

**Review by tdonohue — APPROVED** [review]
@paulo-graca and @atarix83 :  Took a look at this today... I'm OK with the approach, though it's obviously frustrating that we have to **restart Tomcat** anytime a new Collection (with an Entity Type) is created.  That said, I understand why that is necessary, and it's good to hear that a fix will be coming in #7985 .  

Overall though, this looks good and it works for me.

I'll go ahead and merge it as it's a step in the right direction.  @paulo-graca : Could you add basic documentation for this new configuration to both https://wiki.lyrasis.org/display/DSDOC7x/Configurable+Entities and https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-AssigningacustomSubmissionProcesstoaCollection ?

**Pull request merged**
