### PR TITLE
Skip recording usage events if user is administrator

### LINKED ISSUE #9223: Usage statistics (views and downloads) being recorded for Administrators
**Describe the bug**
In DSpace 7.x now all item views and bitstream downloaded are being recorded, including for those logged in as administrators. This was not the case in previous versions of DSpace, and now it can be quite confusing for end users, especially in cases where items are embargoed and file downloads are being shown.

**To Reproduce**
1. Log in as an administrator
2. Visit an item page and download a file that is either restricted or under embargo
3. Visit the item's statistics page after a few minutes

**Expected behavior**
It would be good is usage events for admin users weren't logged in Solr but could be recorded in the DSpace log files for audit purposes
**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by amgciadev**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #9223 

## Description
This PR skips logging usage statistics events for Administrators. Instead records to DSpace log for information purposes

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [X] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
Thanks @amgciadev! I tested on DSpace 7.6.1, first confirming the bug and then confirming that this patch fixes it. :+1:

I only have two minor comments:

- Do we need to be logging to info? On a busy site like ours this would be hundreds or thousands of useless log entries per day.
- Can you rebase to squash the whitespace commit? It's a shame to keep commits like that in the git history forever. You should be able to use a command like `git rebase -i HEAD~2` and then mark the whitespace commit with `s` for squash (or I can do it for you when I merge)

**Comment by amgciadev** [comment]
Thanks @alanorth for the review and the feedback - now addressed. Initially I thought of including the logging for auditing purposes but you are right, it is not really adding any important / useful information so I have now removed it.
Ta!

**Comment by alanorth** [comment]
@tdonohue this is a pretty simple fix that I've tested. I think it can be `1 APPROVAL`.

@amgciadev I see there are some CAM comments in the first commit that are removed later. I'd prefer if we just squash this into one clean commit to keep the git history clean. Do you know how to do that, or shall I do it for you? Thank you!

**Comment by amgciadev** [comment]
@alanorth sorted now I hope, thanks for reviewing this!

**Review by nwoodward — APPROVED** [review]
👍 Deployed locally and confirmed admin usage events are no longer logged in the stats.

**Review by alanorth — APPROVED** [review]

**Pull request merged**
