### PR TITLE
Add missing wosPublisherContrib key-ref in wos-integration.xml (#9579)

### LINKED ISSUE #9579: Web of Science import missing entry key-ref wosPublisherContrib
**Describe the bug**
Version: DSpace 7.6.1
Missing entry key-ref wosPublisherContrib in DSpace 7.6.1 in /dspace/config/spring/api/**wos-integration.xml**

**<entry key-ref="wos.publisher" value-ref="wosPublisherContrib"/>**

### PR DESCRIPTION
**Pull request by schastlivcev**
## References
* Fixes #9579

## Description
Added missing *wosPublisherContrib* key-ref in `wos-integration.xml` file

## Instructions for Reviewers
*No specific instructions*

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies REST API endpoints, I've opened a separate [REST Contract](https://github.com/DSpace/RestContract/blob/main/README.md) PR related to this change.
- [ ] If my PR includes new configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by schastlivcev** [comment]
There are some problems with importing records from `wos-response.xml` in *WOSImportMetadataSourceServiceIT* tests, what should I do?

**Comment by tdonohue** [comment]
@schastlivcev : You would need to debug the errors in `WOSImportMetadataSourceServiceIT`.  It's possible those errors are signs that this PR is not correct. But, it's also possible that the tests in `WOSImportMetadataSourceServiceIT` need to be fixed/updated.

You can run these same tests locally (to help debug the problem) as documented at https://github.com/DSpace/DSpace/tree/main?tab=readme-ov-file#running-tests

I won't be able to help investigate this further until likely after the 8.0 release.  But, hopefully, that's enough information to help you get started.

**Comment by schastlivcev** [comment]
Added missing publisher metadatum to tests, so everything works now)

**Review by kshepherd — APPROVED** [review]
+1 by inspection and IT review. Thanks @schastlivcev !

**Comment by kshepherd** [comment]
I didn't realise this had port to 7.x tag - i have added 8.x now but i might have to make the port myself now as the bot probably won't trigger again

**Pull request merged**
