### PR TITLE
DS-3885. Minor fix on CommunityServiceImpl.java

### PR DESCRIPTION
**Pull request by mohideen**
Update methods should call clearModified.

### CODE REVIEW

**Comment by tdonohue** [comment]
@mohideen : could you add in more information about how to reproduce this bug?  Ideally, we prefer having a linked in JIRA ticket (per our [Code Contribution Guidelines](https://wiki.duraspace.org/display/DSPACE/Code+Contribution+Guidelines).  But, if you could minimally describe how to reproduce this bug, we could always create a ticket on your behalf.

Thanks!

**Comment by mohideen** [comment]
@tdonohue Created the JIRA ticket describing the issue: https://jira.duraspace.org/browse/DS-3885

**Comment by AlexanderS** [comment]
See also: https://jira.duraspace.org/browse/DS-3867

**Review by kshepherd — APPROVED** [review]
+1 by inspection, seems like an easy and obvious fix.
needs porting to dspace-6.x, hopefully we can get this into 6.3 with some more reviews

**Review by tdonohue — APPROVED** [review]
👍 Looks correct to me, but could use a tester/verifier, perhaps?

**Comment by tdonohue** [comment]
After further analysis, this is definitely a fix that was introduced in 6.0.  In 5.x, the code cleared this flag here:  https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace-api/src/main/java/org/dspace/content/Community.java#L565

Since this is already at +2, I'm merging and flagging to be ported to 6.x

**Pull request merged**
