### PR TITLE
Rest exception cause

### LINKED ISSUE #8358: More detail for REST exceptions
We have written our own front-end for submitting items to DSpace (using VueJS). This works well except when there are exceptions, in which case we only get an HTTP code or a generic message such as "Request is invalid or incorrect". This makes it difficult for us to debug the error. We have our server hosted externally so we do not have easy access to the logs - and the logs don't show us the cause of the error unless debug/stacktrace is enabled.

For example, a recent issue was that the metadata registry had not been updated, and we were trying to write to non-existent meta fields. The REST response just gave us 500, and it took a long time to track down the error. Recently we have been getting 422 exceptions for some items, and simply have no idea what the problem is.

**Describe the solution you'd like**
For REST requests, I would like the _cause_ exception message to be provided in the REST response. Often the message of the original exception is more than enough for us to fix the problem. (This message wouldn't be displayed to the user, but rather logged for us to investigate.)

**Describe alternatives or workarounds you've considered**
The only workaround we have currently is to ask our provider to scan the logs - in most cases this is also insufficient due to lack of detail in exceptions, especially 422 exceptions.

### PR DESCRIPTION
**Pull request by tlloydthwaites**
## References
* Fixes #8358 

## Description
* If X-DSPACE-REST-EXCEPTION-CAUSE header is present, append the root exception cause to the error message.

## Instructions for Reviewers
* Will have no effect unless the header is present in the request
* If header is present and matches String "true", the root cause of the exception will be added to the message.
* Exact message format is controlled with config property 'rest.exceptionCause.format', defaults to '%s [CAUSE: %s]'
* Example: An exception has occurred [CAUSE: bad_dublin_core schema=a.fake.key. Metadata field does not exist!]

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [ ] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by tlloydthwaites** [comment]
sorry about the .vscode stuff! :)

**Comment by tdonohue** [comment]
@tlloydthwaites : This PR is _unlikely to be accepted_ as it opens DSpace up to "information exposure" security issues. See this "Information exposure through a stack trace" note from LGTM (on this PR): https://lgtm.com/rules/6780073/

Essentially, error stack traces / caused by clauses can provide information about the underlying system's behavior to attackers, allowing them to gather information on which attacks may be possible on your system.   

Therefore, DSpace purposefully only provides generic error messages in responses, and never any information from the Java stacktrace itself. The full error stacktrace can always be found in the DSpace logs (dspace.log), and there's a configuration on the backend that allows you to optionally include the full stacktrace in REST responses (`server.error.include-stacktrace = always`) for debugging (or development) purposes.

If I'm misunderstanding this PR, let me know. But, I'd lean towards not merging this for the reasons given.

**Comment by tlloydthwaites** [comment]
Thanks Tim,

Understand about information leakage, and that this is a bit of a desperate measure! At the moment however, because our dspace is hosted elsewhere, we are stuck.

The issue is that we don't have access to the logs, and our provider will not enable debug mode for performance reasons. So as REST consumers we have no way of knowing what is happening when we get an error. For example, sometimes file uploads work, sometimes they don't. We need some way to diagnose this without enabling debug/trace logging. Even a logsnap solution wouldn't help as the error log also does not really show the root problem, just general advice that an error occurred. 

Another example: one time we updated our custom front-end tool and found that nothing was working - it took us a long time to determine that our metadata registry was missing a key. A cause message in the API response would have let us diagnose this straight away. (We would not display that cause to users, but store it in our own logs.)

Could it be managed with permissions? For example, only allow cause messages if the API consumer is logged in, and possibly check for a specific permission? (Either a user policy or a simple list of user ids in config). That way unauthenticated consumers will never see cause messages. I will mock that up and update the PR - just as a means of discussion. 

Appreciate you getting back to me so quickly Tim, thank you!

**Comment by tlloydthwaites** [comment]
Updated with some ideas on how to lock it down. A user must explicitly be allowed to receive cause messages, so this will have no effect unless explicitly enabled. Presumably, if a user is allowed to see the messages, then they are a known to the repo admins and it would be ok for them to see any potentially leaked information.

**Comment by tdonohue** [comment]
@tlloydthwaites : I'm having a hard time understanding the use case here (and whether it would apply to others in some manner). Currently, we definitely assume that if you are developing a frontend for the DSpace backend then you *must* have some access to the logs of the backend.  There are plenty of log sharing tools out there that can provide such access, even if your team cannot be given commandline access to the backend REST API.

Your configuration `rest.causeAdvice.allowedUsers` seems like it really wouldn't scale to more than a few users (I cannot imagine any site wanting to add 100s of users to this list), which begs the question why those few users cannot just be given log access.

Keep in mind, I'm not against a solution here that allows for some to see the errors via the REST API... but it'd have to be secure.  Your solution seems secure, but it really doesn't scale, which begs the question of whether DSpace should even offer this or simply point users to log analysis/sharing tools instead (which would provide you with more controls over logs and be non-DSpace specific).

The only other option I can think of would be to allow authenticated **Administrative Accounts** to retrieve caused by errors from the REST API (perhaps only when a configuration flag is enabled).  That's potentially more scalable, but again I'm not entirely convinced yet that this is a common need for other institutions.

**Comment by tlloydthwaites** [comment]
Hi @tdonohue, we are actually using an administrative account, so that solution would be perfect. Then we could have a simple flag to turn detailed messages on or off for admins.

Pulling up to a more philosophical level - if we step back from DSpace and consider REST APIs in general, then of the dozen or so APIs we interact with, DSpace is the only one that doesn't give some sort of error feedback. All of these APIs (Airtable, Jira, email, student management, etc.) will at least give us, eg: "Unknown field: X", or "Validation failed: required field 'email'". So as someone who uses a number of APIs, DSpace stuck out as an exception (pardon the pun!).

I wonder if other users of the REST API might also benefit from better feedback. My personal feeling is that requiring API consumers to go to the logs is a little bit onerous and not the workflow I would expect from a typical API. The logs often don't give enough information unless in debug mode, and to enable debug we have to get the server restarted, which annoys researchers - and our provider is unlikely to accomodate that request again, as it impacted server performance. So we are kind of stuck!

**Comment by tlloydthwaites** [comment]
Well it seems that I am a goose. I thought that server.error.include-stacktrace only affected what was sent to logs - I didn't twig that is also sent it to REST responses, and would not also be logged unless in debug mode.

Thanks for your patience everyone and sorry for wasting your time! :)

**Comment by tdonohue** [comment]
Flagging as "needs discussion".  I'm still not entirely sure I understand the use cases here beyond being helpful for development.  While we could give Administrators this capability, there are no tools in the UI to allow them to easily view the exception cause -- so it'd only make sense for Administrators who are also very technical (or developers themselves).

The core question is whether DSpace should solve this problem, or whether this is a use case that is very specific to a single institution.  If others are interested in this feature, please speak up or provide additional use cases.

**Comment by tlloydthwaites** [comment]
The main case for this is for REST consumers other than Angular UI. We use it as part of a microservice orchestration piece, eg to display items on a researcher's website page, and to allow researchers to add/edit their items from a web front end.

In the latter case, when the API returns errors, we have no way to help. Rebooting the server to enable debug mode and look through logs is infeasible for us. As noted, even if we had access to server logs, they don't print cause messages either (they probably should - we don't need a stack trace, just the message), and our provider is very reluctant to enable debug logging for performance reasons. 

So this is probably a fairly unusual scenario where we can't put the server in debug mode, but to me it seems a bit drastic having to do that to get an error message. If the REST API is mainly for serving Angular, then I can see that this change is not that useful.

**Comment by tlloydthwaites** [comment]
Thanks for your thoughts @tdonohue - I appreciate the consideration for the API in general. I agree, it is definitely a quick-fix and should probably not be a PR in its current form - more to stimulate discussion. We can apply this to a custom build but I would prefer to keep abreast with the main repo.

The general issue is that we need at least some feedback for errors to be sent in the REST response. In our case it doesn't matter if it's 4xx or 5xx. This is not so much for debugging dspace itself, but 'why did my item not submit'. I wouldn't display these messages to users, but some feedback is crucial for us to help diagnose issues such as why some attachments upload and some don't.

We don't technically need a cause message (which may be quite specific, such as JDBC problems), and we would never need a stack trace. A few examples that we have tracked down are that we have forgotten to migrate a meta key, or have sent an invalid owning collection for new items. The cause messages for those exceptions are very useful! However, other times we have some files that won't upload, and it is difficult to see why. Perhaps a specific exception type could be thrown that indicates it is intended/allowed to be reported. However, that would require a fair bit of work, which is why we reached for a quick-fix.

Regarding the logs, when I see errors in my local dev build, it is usually a WARN message with a 4xx HTTP code and 'An exception has occurred.' 5xx will include the stack trace, but it is the 4xx that are a mystery.

**Comment by tlloydthwaites** [comment]
To answer your points:

1. Agreed - logs don't need stack traces for 404s. However, just the cause message would probably be ok for all 4xx exceptions? It wouldn't fill the log and would be very useful. (Eg "An exception has occurred: <cause string>")

2. i) This is really the solution. Specific messages for known problems should be fed back to the REST response where possible. The problem is, we don't know what specific situations will throw an exception. The message we get, 'An exception has occurred', is not really useful.

2. i-sidenote: that is probably something I haven't looked into closely enough, however a message would still be nice. 

2. ii) I think the idea of returning causes arose because it was the easiest way to get _some_ feedback coming from the API. It is probably really a symptom of point 2.i. 

2. iii) that is a major weakness of the current PR - it requires admin privileges to see error messages. I think this stems from using a cannon to kill a mosquito - sending java-level cause messages in the absence of controlled, sanitised error feedback.

**Comment by mwoodiupui** [comment]
"An exception has occurred" is a useless and exasperating message.  One should *never* see such a message.  OTOH simply upchucking an exception's message or, worse, a stack trace, without interpretation, is often nearly as bad for the client.

I know that I struggle with the tendency to think of exception handling as a botheration rather than an opportunity to explain failure, but it is worth the struggle.  The caller knows what it *means* for the callee to have thrown an exception in this context, and the developer should attempt to interpret the exception in terms of the caller's own purpose.

Now, there may be cases where LGTM is worrying about nothing.  There is no point in trying to hide details of DSpace's methods, because the source is published.  What we need to protect is local secrets and users' secrets.  We should avoid returning stack traces to clients, not because they give away secrets, but because they are usually clutter.  What the client needs to know is what *it* did wrong, or that the service failed for reasons that are interesting only to the service's own admin.s.  "Internal error, please tell us what you did and when" is as helpful *to the client* as "you are not authorized for that operation", if it *is* an internal error (resource exhaustion, "impossible" internal state, etc).

Crafting a good error report is hard work that interrupts the flow of the developer's thoughts, but with practice it becomes an enjoyable skill as well as a valuable one.

**Comment by kshepherd** [comment]
Just a note that I have also found the vague 4xx/5xx "An exception has occurred" errors frustrating! In development enabling request stack traces helps, but I think it'd be great to get the REST API sending informative, internally-consistent error messages that explain a specific problem without disclosing sensitive information (and in logs, too) even if they're not intended to be displayed to a user in the Angular UI

**Comment by tlloydthwaites** [comment]
I'm closing this pull request, as even the root exception messages are not always helpful. As noted [here](https://github.com/DSpace/DSpace/issues/8358#issuecomment-1558360130), we are getting exceptions like this:

`org.springframework.web.util.NestedServletException: Request processing failed; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet`

This is no more illuminating than 'an exception has occurred.'

**Pull request closed without merging**
