### PR TITLE
Make DSpace 7.x compatible with Java 17 (without losing compatibility with Java 11)

### LINKED ISSUE #8190: Full support for Java 17
The DSpace codebase was made “build-compatible” with Java 17 in release 7.2, that is, it can now be built using a JDK 17. However, it must still be built towards Java 11, which is reflected by the `java.version` property and the maven-compiler-plugin `release` argument.

The project should be fully Java 17 compliant, which would result in being able to build it towards Java 17, which is the latest LTS Java version since September 2021. This would allow DSpace users/developers to write code using newer Java features (e.g., string blocks, switch expressions, records) for their own needs. Such code, however, should not become part of the DSpace codebase as long as DSpace is expected to support Java 11.

In a local copy of the version 7.2 codebase, I upgraded a few library versions (e.g., Spring, JSON-Path) and marked several injected dependencies with `@Lazy` to make the project buildable and runnable again. I consider the `@Lazy` annotations a temporary fix, as the involved classes and attributes should be refactored to eliminate all circular Spring bean dependencies.

The resulting code is still fully compatible with Java 11. It can be switched to any Java version between 11 and 17 (inclusive) by setting the `java.version` property and maven-compiler-plugin `release` argument mentioned above accordingly.

### PR DESCRIPTION
**Pull request by jeffmorin**
## References
* Fixes https://github.com/DSpace/DSpace/issues/8190

## Description
Makes the required updates to the code and dependencies to make DSpace fully compatible with Java 17. The project, however, remains compatible with and targeted towards Java 11.

## Instructions for Reviewers
To test building and running the project using Java 17, you'll have to set to 17 the values in lines 21 and 142 of the parent POM (`<java.version>` property and maven-compiler-plugin `<release>` argument, respectively). No other changes are required. The application should run as it already does, as there are no functional changes in this fix.

The changes included in this patch can be summarized as follows:

- The need to update some dependencies originates from Spring-ASM 5.2.5 being unable to handle Java 17 class files. Apart from Spring, I had to update versions of Spring Boot, Spring Security, JSON-Path, and the Spring HAL Browser/Explorer module.
- There are a lot of circular dependencies among the Spring beans, mainly around the `ConverterService` class and its subclasses in the `dspace-server-webapp` module. In order to keep code refactoring at a minimum in this fix, I introduced `@Lazy` annotations where necessary to make the application runnable again. **The related code should be refactored to avoid such circular dependencies**, and hopefully this will be addressed in a future PR.
- As a bonus, I added a fix to the `build.xml` Ant script to address a “classpath too long” error when building the project from a root directory not located at the root of a given disk (e.g., `c:/root/subdir1/subdir2/dspace-server` instead of `c:/dspace-server`).

## Checklist

Please see my comments in [_italics_] following each item, where applicable.

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide). [_A few lines may have been reformatted or reorganized when I saved the classes I changed. This results from automatic save actions I configured to optimize compliance with the DSpace Code Style Guide._]
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods. [_Only one method was added in compliance with its parent interface `CrudRepository` from Spring Data. I added succinct Javadoc as is done for the other inherited methods in the involved class._]
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation. [_No new libraries, just a few updates. I didn't see any change in the underlying licences._]
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change. [_Not applicable in this PR._]

### CODE REVIEW

**Comment by tdonohue** [comment]
@jeffmorin : Thanks for this PR.  However, I did want to note that I've realized this PR is *duplicative* of the work I've recently been doing to fix #3017 .  I see a lot of similar changes in my in progress (still local) code with what you've done here.... that's a great sign that we are working towards the same end/goal, even if for slightly different reasons.  

But, I wanted to call it out as I think the largest challenge in this/your PR is that you've swapped the Hal Browser for the Hal Explorer.  That, in itself, I've found is a massive change...as it causes old Hal Browser custom code to break/fail (and some of that old code needs to be replaced or removed).   This is exactly what I'm working on in my own PR (hopefully to be posted in the next week, but I'm still working on fixing broken Integration Tests -- many of the same ITs you can see failing in this PR, and I've found fixes for most but not all yet).

All in all, I think this work you've done is good overall...and I'll compare it with what I'm working on to see if I can borrow any of your ideas (at a glance a lot of what we've done looks the same though).  But, we may wish to merge this work into my upcoming PR (once that's ready), as I think it'll be easier to combine efforts here.

**Comment by jeffmorin** [comment]
@tdonohue: I think this is a good idea. Look out, however, as there are some classes that need reordering in their imports according to some Checkstyle rule. If there are fixes you want me to apply before you merge my code into your PR, just let me know.

**Comment by jeffmorin** [comment]
@tdonohue: I pushed in my fork (https://github.com/jeffmorin/DSpace) an update for classes that threw CheckStyle errors in my initial pull request, mainly in imports organization. I am just not sure about the best way to update the current pull request accordingly. Of course, the build will still not pass integration tests due to errors remaining in switching from Hal Browser to Hal Explorer, which you are already working on. But at least, my CheckStyle errors will be gone.

**Comment by jeffmorin** [comment]
@tdonohue: No problem, I didn't want to rush you, but only to fix errors that I let slip into my initial pull request. Please take your time and notify me when you are ready. Besides, I see that there are still plenty of Javadoc errors that make the build fail. I guess they shall be fixed prior to merging anything into the main branch.

**Comment by tdonohue** [comment]
@jeffmorin : Sorry for not being clear... I've decided it might be best to treat these PRs separately.  So, I'm working on getting reviewers for my PR #8215 to do the initial Spring updates & fix the broken tests. Once that is merged, you should be able to "rebase" this PR so that it only includes the minor additional fixes to bring us to Java 17 compatibility -- which I can then review & merge myself.

I think that'd be easier to manage review-wise than one massive combined PR. Per DSpace policies, every PR has to have at least 1-2 reviewers (from a separate institution from the developer), and it's easier to find reviewers for smaller PRs.

All that said, it's OK that you updated this PR with mine.  That likely will make it easier to rebase this PR on `main` after my PR is merged.

**Comment by tdonohue** [comment]
@jeffmorin : I wanted to note that (as of a moment ago), our `main` branch is now updated to the latest Spring versions via #8215 (which was just merged).

That means that, when you have the time, you could always rebase this PR against `main` (or optionally recreate it again `main`).  I *think* the `main` branch will now include the majority of the changes you had to make in this PR to make things more compatible with Java 17.  But, there still may be a few additional fixes that we should ensure get applied.

Once this PR (or a follow-up, if it is easier to start fresh) is ready for review, I'll gladly help review it and assign others as needed.  Thanks!

**Comment by jeffmorin** [comment]
I rebased my fork with the latest version of the main branch and made a few fixes as follows:
– Validated the code base against both Java 11 and Java 17. The parent POM is configured for Java 11, but it could be configured for Java 17 without changing anything other than the two occurrences of "11" referring to the Java version.
– Fixed a few errors: Log4J configuration file location in dspace-server-webapp web.xml, and checkstyle.xml
– Fixed a few CheckStyle errors (tabs in files). There are many more to come, but they could be part of a separate pull request.

**Comment by jeffmorin** [comment]
I rebased my fork and tested it against both Java 11 and Java 17 (by changing both occurrences of 11 to 17 in the parent POM) and it looks like that Tim's pull request for HAL Browser actually covered all necessary updates to make DSpace compatible with Java 17. This pull request is therefore obsolete, and I will open another one if I find issues elsewhere (e.g., CheckStyle).

About CheckStyle, the errors still appear in my IDE but are not blocking towards building and running the project. Therefore, I will open a new PR dedicated to CheckStyle only if I find blocking issues.

**Pull request closed without merging**
