### PR TITLE
Add Brazilian controlled vocabulary from CNPQ

### PR DESCRIPTION
**Pull request by samueloph**
Controlled vocabulary from the Brazilian National Counsel of Technological and Scientific Development (CNPQ), freely distributed at http://cnpq.br/dados_abertos and discussed at https://groups.google.com/forum/#!topic/dspace-tech/Q8GpYLVtqKY.

Also available at the oficial Brazilian Institute of Information in Science and Technology (IBICT) repository: https://github.com/ibict-br/TEDE/blob/dspace-4_x/dspace/config/controlled-vocabularies/cnpq.xml

Please consider backporting this to other releases of DSpace supported (5.x, 4.x, 3.x).

### CODE REVIEW

**Comment by samueloph** [comment]
Hi @tdonohue, could you have a look at this, please?

Thanks.

**Comment by helix84** [comment]
I don't see any statement of license on the site. If I missed it, can you please point it out? If it's not stated, we'll need an explicit license from the copyright holder of the vocabulary. Thank you.

**Comment by samueloph** [comment]
@helix84 I will talk to a person that works on IBICT next monday, i will ask for explicit licensing.

Is a license header at https://github.com/ibict-br/TEDE/blob/dspace-4_x/dspace/config/controlled-vocabularies/cnpq.xml enough or do i have to ask for one at http://estatico.cnpq.br/bi/CNPQ/DadosAbertos/Tabelas/AreaConhecimento/area_conhecimento.xml?

**Comment by tdonohue** [comment]
@samueloph : I'm not sure what "license header" you are referring to in those files. Perhaps I'm overlooking it?

Generally speaking, we cannot re-distribute a new controlled vocabulary without *explicit* rights from the group that created (or owns) the controlled vocabulary.  Otherwise, we could risk being sued if they later come to use and say we are not allowed to redistribute that controlled vocabulary to everyone who downloads DSpace.

Currently, we only redistribute two controlled vocabularies, and we have explicit licenses/agreements to redistribute them here: https://github.com/DSpace/DSpace/blob/master/dspace/config/controlled-vocabularies/LICENCES

So, we'd need to be either given rights to redistribute this vocabulary, or we'd need documentation that this vocabulary allows others to redistribute it (e.g. if it's released under a specific open source license or creative commons license, often those would detail whether DSpace can add this vocabulary).

**Comment by samueloph** [comment]
@tdonohue : By "license header" i mean to have a license declaration (gpl or cc) at the first lines of the file https://github.com/ibict-br/TEDE/blob/dspace-4_x/dspace/config/controlled-vocabularies/cnpq.xml, would that be enough?

The other URL i commented (http://estatico.cnpq.br/bi/CNPQ/DadosAbertos/Tabelas/AreaConhecimento/area_conhecimento.xml) comes from a section entitled "open data", that is, everything there should have open licenses, although they're not explicit.

Could you please confirm if the mentioned license header would be enough, or if not, what exactly i need to get to settle down the licenses problems?

**Comment by tdonohue** [comment]
Hi @samueloph : yes, adding a license header to those files would be enough.  We really just need some sort of "proof" that these are free to redistribute.  That "proof" can either be an explicit license from their website, a license header, or something similar.

**Comment by samueloph** [comment]
Unfortunately my contact at IBICT (the person who wrote the xml file) wasn't interested in declaring a license in the file, so I'm gonna close this PR.

**Pull request closed without merging**
