### PR TITLE
DS-4380 : Upgrading 7.x to JDK11.  Remove JMockit (replace with Mockito)

### PR DESCRIPTION
**Pull request by tdonohue**
This PR replaces / builds on #2611 (from @cwilper )

https://jira.lyrasis.org/browse/DS-4380

It upgrades DSpace 7.x to JDK11 (or above).  **JDK8 will no longer be supported once this is merged.**

This upgrade required the following:
* **JMockit is completely removed from all tests & replaced with _Mockito_.** (We already use Mockito heavily in the new REST API v7, as Spring integrates better with Mockito).  This removal was necessitated as I was never able to get JMockit to work properly on JDK11.  Additionally, all our old JMockit tests were invalid anyhow, as they used deprecated testing tools that were removed in recent versions of JMockit
    * Mockito is very *strict* about not having unused "mocks" in tests (it throws errors if it find them, failing the build). Therefore, after some tests were migrated from JMockit to Mockito, **some unused mocks were removed**.  You may notice in reviewing this PR that mocks are _not always identical_ between what was mocked in JMockit and what is mocked now in Mockito.
    * Mockito also does NOT allow for mocking/overriding any `static final` classes or variables.  Therefore, minor changes were made to `AuthorizeUtil` to allow it to be more easily mocked in tests.
* **Some old tests were removed.** As I migrated tests from JMockit to Mockito, I found some tests which were duplicative. Therefore a handful of tests were removed in this PR.
* Other dependencies were upgraded/added as necessary to support JDK11
    * During dependency upgrade, I made sure we were using latest version of Maven plugins as well to ensure JDK11 alignment.
* This PR also comments out the POM changes applied in #2642. It is no longer needed and appears to slow the build slightly.  Left the `<repository>` commented out in the POM in case it is ever needed again.
* Updates all Docker configurations to use JDK11
    * Docker images no longer include "jdk" in the name. Previously some were named "jdk8".
    * **NOTE: When this PR is merged, minor changes to Docker configs in DSpace/dspace-angular project will be necessary.**  The changes are extremely minor, just removing the "jdk8" in old image names.

As you'll see in reviewing this PR, it's rather large as it touches a LOT of tests (primarily in `dspace-api`, which used JMockit heavily). However, the changes to each test are similar in nature, which should make it easier to review.

Still left **TODO**:
- [x] Rebase this on latest master (wanted to first get tests working before doing that)
- [x] Upgrade Docker configs to also use JDK11
- [x] Coveralls appears to not be functioning with JDK11. Our code coverage percentage shows up as 0% in this PR.
- [x] After upgrading `errorprone`, there's a number of new code warnings that are thrown during the build.  Ideally those should be either cleaned up in this PR or a later PR. (WILL BE DONE IN A FOLLOWUP PR, as this PR is already rather large)
    - **FOLLOW PR TO FIX `errorprone` warnings**: #2669 
- [x] Some tests throw a warning that says `WARNING: An illegal reflective access operation has occurred`.  These do NOT fail the tests, but are notes of what is now deemed "misbehavior" as of JDK9.  These reference third party tools that may require upgrading (once they fix the misbehavior on their end).
    - I've cleaned up those that can be cleaned up. Others will still exist until third-party dependencies fix the issues on their end.
    - **NOTE: New version of XOAI will need to be released** to resolve some of the warnings thrown by its dependencies. See PR at https://github.com/DSpace/xoai/pull/74/

This is ready for more eyes/reviews/testing.  The code changes pass all tests.

### CODE REVIEW

**Comment by tdonohue** [comment]
I've taken WIP status off this PR, as it is now testable/mergeable.  The only remaining task is some minor cleanup of code reported by `errorprone`.  But, that could be done in a followup PR.

Unfortunately, at this time Travis builds are all being killed (after 50 minutes) because of this issue: https://jira.lyrasis.org/browse/DS-4425  However, locally all builds/tests pass.  Additionally, locally code coverage looks to go slightly *up*.

**Review by cwilper — APPROVED** [review]
@tdonohue I have reviewed the code changes and ran locally with the Coretto 11 jdk. Everything worked as expected. I also manually ran a couple of the ITs with no incident. From my perspective, this can be merged, my only concern would be making sure other developers are fully aware that we need Java 11 in development, and to deploy, when this makes it into master.

**Comment by victorwss** [comment]
Java 11 is already somewhat old. If I would run it in Java 13 or 14, will there be any showstopper?

**Comment by tdonohue** [comment]
@victorwss : We chose Java 11 because it is the latest LTS release of Java and it is under support until Sept 2023 (with extended support until 2026): https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

Java 13 is not-LTS and is considered "obsolete" as soon as Java 14 is released (March 2020).  Java 14 is not yet released, but is also not-LTS and is only supported until Java 15 is released (approximately Sept 2020).

Because of the very short support windows of non-LTS Java releases, we are recommending all DSpace production systems remain on LTS releases, the latest of which is Java 11.

For the above reasons, we haven't tested the DSpace 7 backend on Java 13 or 14 at this time. It might work OK, but it also may not -- it depends on if there are any breaking changes in those Java releases.

**Comment by victorwss** [comment]
Well, when the migration work for Java 11 is done, it might be worth to have an experimental branch working on whatever is the bleeding edge of Java to ensure that no bad surprises shows up and that they are quickly solved if they do. Also, if there are optimizations and improvements in the deep guts of the JDK and the JVM that people would desire to have, there should be no reason to not let them at least try.

**Comment by tdonohue** [comment]
Regarding questions about ongoing JDK support in DSpace 7, I've started some notes in the comments of the associated ticket: https://jira.lyrasis.org/browse/DS-4380

**Comment by tdonohue** [comment]
As discussed in today's DSpace 7 meeting, this will be merged shortly.  I've done a quick rebase on the latest `master` code just to ensure this JDK11 upgrade also works fine with all code from recently merged PRs.  Once Travis approves, this will be merged.

**Pull request merged**
