### PR TITLE
[DS-2713] Ensure that there can still be an xml workflow migration

### PR DESCRIPTION
**Pull request by KevinVdV**
In progress pull request in order to get the xml workflow migration operational again.

### CODE REVIEW

**Comment by KevinVdV** [comment]
Pull request has been updated to work for postgres and oracle in the following scenarios:

- DSpace 5 basic workflow enabled, migrate to DSpace 6 WITH xml workflow directly
- DSpace 5 basic workflow enabled, migrate to DSpace 6 with basic workflow & THEN enable xmworkflow
- DSpace 5 xmlworkflow enabled, migrate to DSpace 6
- DSpace 6 new setup with xml workflow
- DSpace 6 new setup basic workflow (& then migrate to XmlWorkflow)

**Comment by tdonohue** [comment]
The code looks reasonable here.

However, I'd prefer it if we changed the names of these Flyway migrations to include a reference to the ticket they refer to.

For example, changing
`V6_0_2015_08_31__Hibernate_Workflow_Migration.java`
to
`V6_0_2015_08_31__DS_2701_Hibernate_Workflow_Migration.java`

It's a minor name change, but it'd follow the conventions already begun in
https://github.com/DSpace/DSpace/tree/DS-2701-service-api/dspace-api/src/main/java/org/dspace/storage/rdbms/migration

Renaming the migration shouldn't change anything in your code, but it'll help us later if we forget what ticket the "Hibernate_Workflow_Migration" referred to.

**Comment by KevinVdV** [comment]
Will make this change if we accept: https://github.com/DSpace/DSpace/pull/1067, because I will need to rebase & retest this pull request after.

**Comment by KevinVdV** [comment]
Rebased due to the changes in #1067 + renamed the sql files to match DSpace conventions.

**Comment by tdonohue** [comment]
Reviewed and approved in today's DevMtg. Merging.

**Pull request merged**
