### PR TITLE
Metadata Import via Scopus API: improved handling of empty search results

### PR DESCRIPTION
**Pull request by saschaszott**
## Bug Description

An **empty search** result which is returned from the Elsevier Scopus REST API looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<search-results xmlns="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/"
                xmlns:prism="http://prismstandard.org/namespaces/basic/2.0/" xmlns:atom="http://www.w3.org/2005/Atom">
    <opensearch:totalResults>0</opensearch:totalResults>
    <opensearch:startIndex>0</opensearch:startIndex>
    <opensearch:itemsPerPage>0</opensearch:itemsPerPage>
    <opensearch:Query role="request" searchTerms="a-query-without-hits" startPage="0"/>
    <link ref="self"
          href="https://api.elsevier.com/content/search/scopus?start=0&amp;count=10&amp;query=a-query-without-hits&amp;httpAccept=application%2Fxml"
          type="application/xml"/>
    <entry>
        <error>Result set was empty</error>
    </entry>
</search-results>
```

The implementation in `ScopusImportMetadataSourceServiceImpl` considers this kind of result as a not-empty result.

In consequence, this leads to this unexpected state in the UI:

image

### CODE REVIEW

**Comment by saschaszott** [comment]
In DS-CRIS 7 the test class `ScopusImportMetadataSourceServiceIT` was extended: it contains a test (`scopusImportMetadataGetRecordsEmptyResponseTest`) which covers an empty search result. Is it ok to merge the changes in `ScopusImportMetadataSourceServiceIT` which were added by 4Science in the DS CRIS repo? In this case, the test case `scopusImportMetadataGetRecordsEmptyResponseTest` has to be adapted in this way: https://github.com/4Science/DSpace/pull/434/files#diff-12daf99ec2c1ccf4239c0b7fa4d21a2b0b81eb37ba36d1bfbbe79396d7658808

**Comment by tdonohue** [comment]
@saschaszott : My understanding from the 4Science team (pinging @abollini ) is that they welcome code being ported from DSpace-CRIS back to DSpace.  So, I think it's safe to port that test back to DSpace....provided it can be easily ported & works just as well on DSpace.

**Comment by tdonohue** [comment]
@saschaszott : Looking at the IT failures in this PR, it appears it may be failing its own tests?

**Review by tdonohue — CHANGES_REQUESTED** [review]
Flagging as `work in progress` until it passes it's own tests.  Currently failing 3 tests in `ScopusImportMetadataSourceServiceIT`

**Comment by tdonohue** [comment]
@saschaszott : Just a quick note.  This PR is still failing tests in `ScopusImportMetadataSourceServiceIT`.

**Comment by saschaszott** [comment]
> @saschaszott : Just a quick note. This PR is still failing tests in `ScopusImportMetadataSourceServiceIT`.

@tdonohue , I've tried to fix the failing tests but without success. I'm not sure why the tests are failing as they are copied from the 4Science repo without any modifications.

**Comment by tdonohue** [comment]
@saschaszott : Ok, I'll keep this flagged as a "work in progress" then.  Unfortunately we cannot merge anything with failing tests.  It sounds like someone will need to find time to dig into why they are failing.  My only guess would be that, assuming these tests are succeeding in DSpace-CRIS, that'd imply there's missing code or different test data in this PR which is causing them to fail.

**Comment by saschaszott** [comment]
@tdonohue , I will close this PR and create a new one that only contains the bugfix but not the 4Science changes. I have no clue why the 3 tests are failing.

**Pull request closed without merging**
