### PR TITLE
Solving the issue DS-3193

### PR DESCRIPTION
**Pull request by ghost**
As  I commented in the https://jira.duraspace.org/browse/DS-3193, I fixed the value of retrieveLink in the rest response instead of change the root of the rest application to the UI application.

### CODE REVIEW

**Comment by KevinVdV** [comment]
@LuizClaudioSantos Not sure if the best way forward would be to hardcode the "rest" parameter. If anybody would like to deploy their rest under a different contextPath this would break the code again.

Perhaps try using request.getContextPath(): http://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getContextPath--

**Comment by LuizClaudioSantos** [comment]
@KevinVdV I agree with you, but the HttpServletRequest is not available in Bitstream but in BitstreamResource instead, do you think that should I HttpServletRequest as a dependency of Bitstream?

**Comment by LuizClaudioSantos** [comment]
I add the suggest of @KevinVdV in the [https://github.com/DSpace/DSpace/pull/1460](url), please use that one instead.

**Comment by tdonohue** [comment]
Closing as requested. Replacement PR is at #1460

**Pull request closed without merging**
