### PR TITLE
Item/Collection admin can't create new version item

### PR DESCRIPTION
**Pull request by qzhao-ulb**
## References
_Add references/links to any related issues or PRs. These may include:_
* None

## Description
Collection admin should create a new version as well if the property "versioning.submitterCanCreateNewVersion" set to false. Therefore the authorization to create new version should be checked in the item level, instead of system site.

## How to test this PR:
User login with role of collection admin, open an item, can create a new version.

## Checklist
This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!

- [X]  My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [X] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [X] My PR includes Javadoc for all new (or modified) public methods and classes. It also includes Javadoc for large or complex private methods.
- [X] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new, third-party dependencies (in any pom.xml), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@qzhao-ulb : Tested this today & I've verified that this fix is correct & it works.  I can now create a version as a Collection Admin.

However, before we merge this, I'd appreciate it if we could add a new test to `VersionRestRepositoryIT` which *proves* that you can version an Item as a Collection Admin.  Having such a test in place would ensure that we don't accidentally break this feature in the future...as the test would fail if the feature was ever (accidentally) broken.

I suspect the new test method would be similar to [`createFirstVersionItemTest()`](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/VersionRestRepositoryIT.java#L287), but it would use a Collection Admin similar to this:
```
EPerson colAdmin = EPersonBuilder.createEPerson(context)
            .withCanLogin(true)
            .withEmail("coladmin@email.com")
            .withPassword(password)
            .withNameInMetadata("Collection", "Admin")
            .build();
Collection col = CollectionBuilder
            .createCollection(context, parentCommunity)
            .withName("Collection 1")
            .withAdminGroup(colAdmin)
            .build();
```

If you could add that test, then I'll quickly re-review this and merge it.   Thanks!

**Comment by tdonohue** [comment]
@qzhao-ulb : I wanted to see if you'll have a chance to add a few, small Integration Tests to this PR (as I requested above back in Oct)?  I think we'd want those in place... so if you won't have the opportunity to add them, I could do so instead.  But, this would likely require creating a new PR & copying your commit into it (and afterwards, closing this PR).  Let me know if you'll have time in the near future or not.

**Comment by qzhao-ulb** [comment]
@tdonohue  thanks a lot for the suggest and sorry for the late reply. I added a test method _createNewVersionItemByCollectionAdminTest_ in  the class VersionRestRepositoryIT.

**Comment by tdonohue** [comment]
@qzhao-ulb : Thanks for the added test!  I just made a minor change to your test to remove the `System.out` test statements (as those aren't needed anymore now that the test appears to be working).  Once the tests succeed again, I'll go ahead and merge this. Thanks again!

**Comment by qzhao-ulb** [comment]
@tdonohue thanks for review! I've forgot to delete System.out. The check of submitter after creation of new version is failed. I saw there is no submitter information in the response in the out file.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @qzhao-ulb !  This works for me and the test looks good to me.  It proves that a Collection Admin can now successfully create a new version

**Pull request merged**
