### PR TITLE
REST API changes to embed size

### PR DESCRIPTION
**Pull request by Raf-atmire**
## References
* Required for: https://github.com/DSpace/dspace-angular/issues/918  (However, a corresponding Angular PR is necessary)

## Description
This PR adds support for paging options in the embedded objects for the REST response. It'll now be possible to specify how large the list of returned embedded objects can be for a specific embed.
For example, it'll now be possible to limit the amount of returned subcommunities when retrieving a community through the DSpace 7 REST API

## Instructions for Reviewers
This PR adds support for paging options in the embeds. This can be done by adding the parameter `embed.size` with the value being `{rel}={size}`. If this is given with the request, it'll make sure that the returned list of embedded {rel} objects will not be larger than the size given.

List of changes in this PR:
* Build and deploy this PR
* Construct a community with more than 5 subcommunities
* perform a findOne on the community with `embed=subcommunities`. Also give it a parameter `embed.size` with value `subcommunities=5`.
* Verify that the list of embedded subcommunities is only 5 objects large and that the page for this embed shows how many there truly are

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [x] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by abollini** [comment]
@tdonohue @benbosman I remember that we have discussed that or something really close to that in a recent meeting but unfortunately I'm not able to find any note about the discussion maybe you have a better memory or know where to look...

in our discussion about how to name the parameters we end with the suggestion to look to how the solr community solve this kind of issue where there are parameters that are specific of one of the values send in another one.
This is the case of the facet parameters that can be specified with a general parameter but overridden for a specific facet, i.e. `embed.size` should apply to ALL the embed that don't have a personal settings  and `embed.subcommunities.size` should take the precedence for the size of the specific subcommunities embedding

**Comment by benbosman** [comment]
@abollini I remember there was a discussion about choosing the syntax `embed.size=collections:5` vs `embed.size=collections=5`, and it turned out both work well.
The estimate also wouldn't suffice for using `embed.subcommunities.size`

**Comment by tdonohue** [comment]
@abollini : This PR's design was discussed/documented in the ticket... discussion started in this comment, but see the following two comments as well: https://github.com/DSpace/dspace-angular/issues/918#issuecomment-728784746

**Review by tdonohue — APPROVED** [review]
👍 Thanks @Raf-atmire . This looks good to me overall.  I was able to successfully test it using a Community with many Collections and requests using `embed=collections&embed.size=collections=2` (and similar).   Just to be safe, I've also tested that syntax from several browsers & from `wget` on the commandline.  It seems perfectly valid to have an `=` within the value of the parameter.  I've also attempted encoding the equal symbol, e.g. `embed=collections&embed.size=collections%3D2` and that also works.

I only have two minor notes (neither of which block this PR):
* First, see below, I'd like some missing JavaDocs added
* Second, it appears that we need a corresponding Angular PR to fully solve DSpace/dspace-angular#918 , as this PR just provides the necessary REST embed feature to fix that ticket.  So, I've updated this PR to remove the `Fixes` note & unlink the Angular ticket.  We cannot close that Angular ticket without a corresponding Angular PR.

**Review by benbosman — COMMENTED** [review]
I've reviewed the code, but I'm missing one IT: multi-level embed sizes

If you're asking for an item's embed on bundles/bitstreams, can you verify the embed size of the bitstreams per bundle can also be adjusted?

I will also test the branch. This will help me verify whether this use case works, and is just missing tests. Or alternatively that this use case is not supported

**Review by benbosman — CHANGES_REQUESTED** [review]
I've tested this using `/server/api/core/items/5a3f7c7a-d3df-419c-b8a2-f00ede62c60a?embed=bundles/bitstreams&embed.size=bundles=3&embed.size=bundles/bitststreams=2` (which matches the agreed syntax from https://github.com/DSpace/dspace-angular/issues/918#issuecomment-728784746 `embed.size=subcommunities/collections=1`, but this didn't change the size of the bitstreams

This seems to be not supported either

**Review by benbosman — APPROVED** [review]
I've reviewed the code, and tested using /server/api/core/items/5a3f7c7a-d3df-419c-b8a2-f00ede62c60a?embed=bundles/bitstreams&embed.size=bundles=3&embed.size=bundles/bitstreams=2

This returned for the bundles:
```json
"page": {
    "number": 0,
    "size": 3,
    "totalPages": 1,
    "totalElements": 2
  }
```

This returned for the bitstreams:
```json
{
  "page": {
    "number": 0,
    "size": 2,
    "totalPages": 1,
    "totalElements": 1
  }
}
```

Everything looks good to me

**Comment by tdonohue** [comment]
New code looks good to me.. This is also at +2, so merging.  Thanks @Raf-atmire and @YanaDePauw  !

**Pull request merged**
