### PR TITLE
[DS-3170] Allow Password Auth to be enabled for Rest Reports

### PR DESCRIPTION
**Pull request by terrywbrady**
See https://jira.duraspace.org/browse/DS-3170

This change will create a configurable setting that can enable/disable password authentication from the  rest reports.

Note: incorporated comments from PR review at the 4/27 DSpace meeting.  Also normalized whitespace in the javascript files.

To activate the authentication code, see https://wiki.duraspace.org/display/DSDOC6x/REST+Based+Quality+Control+Reports#RESTBasedQualityControlReports-EnableUserAuthentication(PasswordAuthNonly)forRESTreports.

Note that the user is not logged in.
image

Click the not logged in link to open an authentication window.
image

Authenticate the user
image

Refresh the report, note the presence of restricted collections
image

### CODE REVIEW

**Comment by terrywbrady** [comment]
@mwoodiupui , @tdonohue , I applied the changes suggested in the DSpace meeting.  (I messed up my prior PR.  I need to remember to not mix GitHub client actions with command line actions).

**Comment by tdonohue** [comment]
+1 via code review (most of the changes look to be code realignment).  Needs a tester. Assigning to @hardyoyo as he expressed an interest in helping test today.

**Comment by hardyoyo** [comment]
I can't seem to find a way to configure this functionality, and the text "you are not logged in" does not appear to be a hyperlink in my testing of this PR in Vagrant-DSpace. I *can* confirm that going to the /rest/reports/authenticate.html URL *does* facilitate a log-in process, and that the reports seem to work well after logging in. It would be comforting to see a link to log-out, but, I'm a shibboleth user, and am accustomed to simply closing my browser to log out. Not everyone is so understanding about that kind of thing. :-) So, this is an improvement over the current situation, I'm casting a +1. I'd like to see that link added to log in (and maybe make it more explicit?) As well as a log out link. But this is good enough as-is.

**Comment by terrywbrady** [comment]
@hardyoyo , the instructions for configuring this feature are here: https://wiki.duraspace.org/display/DSDOC6x/REST+Based+Quality+Control+Reports#RESTBasedQualityControlReports-EnableUserAuthentication(PasswordAuthNonly)forRESTreports.

I will update the PR description as well.  Could you please try updating this setting and post your results?

**Comment by hardyoyo** [comment]
@terrywbrady If I'm reading the documentation correctly, and the comments in dspace/config/modules/rest.cfg:
```
#By default, the DSpace REST API will only return communities/collections/items that are accessible to a particular user.
# If the REST API has been deployed in a protected manner, the reporting tools can be configured to bypass authorization checks.
# This will allow all items/collections/communities to be returned to the report user.
# Set the rest-reporting-authenticate option to false to bypass authorization
# rest.reporting-authenticate = false
```

rest.reporting-authenticate = true _is_ the default? However, I've tried setting it explicitly to true, and have restarted Tomcat after deploying the new configuration file. Same results as before: "You are not logged in." is not a link, and there are no links to enable a user to login or log out. Navigating directly to the authenticate.html page does work as expected (though I did notice this time around that the "authenticate" button is not the default, so you have to actually click it, not just hit the return/enter key.

**Comment by terrywbrady** [comment]
@hardyoyo , please see the comment at https://wiki.duraspace.org/display/DSDOC6x/REST+Based+Quality+Control+Reports#RESTBasedQualityControlReports-EnableUserAuthentication(PasswordAuthNonly)forRESTreports

This is the section that you will need to change to turn on password authentication

    //disable this setting if Password Authentication is not supported
    this.makeAuthLink = function(){return true;};

**Comment by hardyoyo** [comment]
I see... modifying a JS file is not quite what we usual mean by "configuration" in DSpace.. but, I can confirm that the link appears, and there is a provision for logging out. The user experience is a bit clunky, but I can live with it. I'd prefer that the "authenticate" button be the default in that form. I'd also prefer that the authenticate form close after the login process is completed. And ideally there would be some feedback if the operation is a success. But, those are all things that can be improved later, and this entire UI is just a demo of the capabilities of the REST-API report functionality, and will likely get absorbed into the new UI project. So, not a big worry at this point. But, I figured I'd mention it anyway. I stand by my initial reaction: +1, good enough.

**Comment by hardyoyo** [comment]
This is at +2, I'm merging it.

**Comment by terrywbrady** [comment]
@hardyoyo , thanks for the review and test.  This is a temporary solution until the AuthN functions work properly with REST.

**Pull request merged**
