### PR TITLE
DSpace 7 backend as one webapp (REST, SWORD, OAI, RDF, etc)

### PR DESCRIPTION
**Pull request by tdonohue**
This is more of a proposal/brainstorm than a finished PR.  So, it's meant to start a discussion around whether this is a good idea or not.

In brainstorming ways to simplify the DSpace 7 installation process, I thought it might be nice to try and see if we could simplify the backend.  For a more detailed summary of the idea/proposal, see: https://wiki.duraspace.org/display/DSPACE/DSpace+Backend+as+One+Webapp

This PR is just an example of how we could start to achieve it.  Currently it only does the following:

 - [x] Updates all modules to use latest version of Servlet API (3.1.0)
 - [x] Turns the SWORDv1 webapp into a JAR, and includes it in the Spring Boot REST API (v7) webapp
 - [x] Updates the Spring Boot REST API to scan for `@Configuration` classes in `org.dspace.app.configuration`. This allows it to find/load the new SWORDv1 `SWORDWebConfig` class, which replaces the old SWORDv1 `web.xml`
 - [x] Updates the Spring Boot REST API to only use Spring Security on the `/api` path. This ensures other modules can use their existing authenticate/authorization without having to adopt Spring Security immediately.

I've lightly tested this, and SWORDv1 is now accessible in the "dspace-spring-rest" webapp on the `/sword/` path. 

If this seems like a good idea to others, I can work on similar merging in SWORDv2, OAI-PMH, and RDF.  NOTE: I'd explicitly exclude merging in Solr (cause it's not really our webapp) and the old REST API (as it's deprecated in 7.x)

(_UPDATE: Travis is currently reporting test build errors, but the code builds/works fine. I'll look into updating/correcting the tests._)

### CODE REVIEW

**Comment by pnbecker** [comment]
First I thought that is not a good idea at all. Most people use only some of these features but hardly all of them. So I tell everyone to only deploy the webapps they are really using and to avoid unnecessary overhead regarding RAM and startup time of the Servlet container. But then I saw that you started to include the modules directly into the REST API. I think that may actual help to reduce DSpace's footprint. Is that part of what you want to achieve?

Looking to your code changes: Your setting the part of sword to /sword. Will this be configurable again, when you finished it? It might be a problem for DSpace users to change the URL of an announced API-Point like SWORD. I also can imagine where people want to have dspace-swordv2 running under /sword while others want to have dspace-sword running there. With dspace-rdf some people will probably deploy it under /rdf, others under /data... So it would be great if this could still be configured.

Hope that helps as first feedback?

**Comment by tdonohue** [comment]
@pnbecker : Thanks, yes that's good feedback. In fact, your notes are exactly what I'm trying to achieve (but this PR is not fully there yet).

Yes, this should reduce DSpace's footprint, as all modules would be included as part of the REST API webapp.  In DSpace 6.x, all modules are separate webapps, and each one loads up the DSpace Services + Hibernate (separately).  In this proposal, there'd just be one webapp loading Services + Hibernate.

Yes, the goal would still be to make each module's endpoint configurable, and still allow users to enable/disable specific modules.  This is currently *not* in the PR, but it's the next thing I've been working on.  But, I fully agree that users need to be able to customize whether they want SWORDv1 or SWORDv2 enabled (or both), and which one responds on "/sword" (or another path).  

Additionally, they should still be allowed to decide not to even use SWORD at all (in which case the path should not even respond). This already works in the PR if you build DSpace excluding the SWORD module, e.g. `mvn package -P '!dspace-sword'`, but I'd like to make it more easily configurable still.

So, the goal of this rough PR is really just to see if others agree this sounds like a worthwhile direction.  In the meantime, I'm already looking into making the module paths configurable -- so, hopefully I'll get that fully figured out soon.

**Comment by mwoodiupui** [comment]
Yes, if services have to move within the namespace this will make some difficult work.  For example, we deploy OAI PMH at /pmh, though for reasons I don't understand many place it at /oai (the name of an organization, not a specific service over a specific protocol).

Maybe we should be working to establish some necessary /.well-known labels.  ("resourcesync" is already registered.)
https://tools.ietf.org/html/rfc5785
https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml

**Comment by tdonohue** [comment]
Just as a note here. This initial PR was really just a "sanity check" of the general idea of creating a single webapp.  I agree 100% that it's not a completely Production-ready unless we can:
1. Ensure all paths are still configurable (i.e. you should be able to change the path that OAI-PMH or SWORD or RDF responds on)
2. Ensure all modules can still be disabled (i.e. you should be able to choose to disable specific paths and/or build DSpace without them)

That said, at this time, I'm fairly confident both of the above can be achievable.  They are not fully in this PR, but I'm digging into them.

**Comment by tdonohue** [comment]
Based on feedback in today's DSpace 7 Sprint meeting, this needs more discussion (and may need to occur post-DSpace 7).  Several folks prefer the current multi-webapp deployment, as it provides more flexibility in how to resource DSpace *and* ensures that if one webapp is overwhelmed/crashes, it doesn't take down the entire system.

So, I'll put this "on hold" for now and flag as `needs discussion`.

For the time being, I'm going to keep this PR open, as we may still want to perform the minor upgrade of moving all webapps to Servlet API v3 (to ensure they are all using the same version of servlet spec).  I can look at breaking that out separately.

**Comment by tdonohue** [comment]
I'm revisiting this idea after discussions in [DSpace 7 meeting on Nov 15](https://wiki.duraspace.org/display/DSPACE/2018-11-15+DSpace+7+Working+Group+Meeting), looking specifically at ways to simplify the DSpace 7 backend installation/deployment process.

Additional feedback/discussion is more than welcome.  I may end up opening a new PR for ongoing work (as this one is now quite out-of-date). If so, I'll close this out and link up the new PR.

**Comment by tdonohue** [comment]
Closing in favor of new PR https://github.com/DSpace/DSpace/pull/2265

**Pull request closed without merging**
