### PR TITLE
DS-4135 prevent escaping for citation_ tags

### PR DESCRIPTION
**Pull request by bram-atmire**
https://jira.duraspace.org/browse/DS-4135

### CODE REVIEW

**Comment by tdonohue** [comment]
@bram-atmire : This looks like a good start, though I see the changes are only being applied to Mirage 2 XMLUI theme.  I'm assuming we'd need similar/identical changes to Mirage 1?  Also, have we verified this does *NOT* occur in the JSPUI?

**Comment by bram-atmire** [comment]
Hi @tdonohue - apologies for not catching your comments sooner.
1. Correct, I think Mirage 1 is also affected
2. Couldn't reproduce this on JSPUI: http://demo.dspace.org/jspui/handle/10673/142

**Comment by bram-atmire** [comment]
Just added the fix in for Mirage 1.

**Review by tdonohue — APPROVED** [review]
👍 Code looks good to me.  I haven't tested it though, so it may be good to do a quick sanity check test prior to merging.

**Comment by alanorth** [comment]
LGTM! Tested and confirmed working on 6.4-SNAPSHOT with an item using non-ASCII Vietnamese text.

Before:

```
<meta content="Thu hoạch v&agrave; bảo quản c&agrave; ph&ecirc; ch&egrave; đ&uacute;ng kỹ thuật (Harvesting and storing Arabica coffee)" name="citation_title">
```

After:

```
<meta name="citation_title" content="Thu hoạch và bảo quản cà phê chè đúng kỹ thuật (Harvesting and storing Arabica coffee)" />
```

**Comment by toniprieto** [comment]
I think it need some changes. The quote character ("), and others characters, should be escaped. 

Testing it with the title:

> Test "quoted text" example

Shows an incorrect output:

` <meta name="citation_title" content="Test "quoted text" example" />`

**Comment by alanorth** [comment]
@toniprieto perhaps we should recommend merging this, as it fixes the citation tags in some corner cases (ie Vietnamese text), and then open a new Jira issue for the incorrect quoting? At this rate I think we need to prioritize getting as many fixes into DSpace 6.4 as possible so we can release it ASAP.

The amount of energy going into preparing DSpace 7 is really killing the DSpace 6.x effort—to say nothing of DSpace 5.x—for several years now!

**Comment by J4bbi** [comment]
@alanorth , I think you are right, filing a separate issue seems like a good solution considering, ideally we would want to get 6.4 out this year 

@kshepherd , what do you think? I've not tested

**Comment by alanorth** [comment]
@J4bbi I just verified that the quotation bug is present in vanilla DSpace 6.3, so we should definitely merge this and open a new issue for that. This pull request correctly fixes non-ASCII text in the citation tags.

**Comment by J4bbi** [comment]
@alanorth , thanks

I'll merge this, would you mind opening an issue for the quotation bug?

**Comment by alanorth** [comment]
> @alanorth , thanks
> 
> I'll merge this, would you mind opening an issue for the quotation bug?

Thanks. No problem, I've opened [DS-4585: Incorrect escaping of citation_ meta tags when metadata contains quote characters](https://jira.lyrasis.org/browse/DS-4585).

BTW how do I get edit permissions on Jira? The formatting is messed up in my bug and I can't edit it.

**Comment by J4bbi** [comment]
thanks

> BTW how do I get edit permissions on Jira? The formatting is messed up in my bug and I can't edit it.

@alanorth, I think when you're logged in there should be an edit button => https://jira.lyrasis.org/secure/EditIssue!default.jspa?id=38071

**Comment by alanorth** [comment]
> thanks
> 
> > BTW how do I get edit permissions on Jira? The formatting is messed up in my bug and I can't edit it.
> 
> @alanorth, I think when you're logged in there should be an edit button => https://jira.lyrasis.org/secure/EditIssue!default.jspa?id=38071

I don't see a link. But when I use your link it says:

> You do not have permission to edit issues in this project.

**Comment by J4bbi** [comment]
@bram-atmire, thanks for this PR

**Pull request merged**
